### ISSUE TITLE
Let admin create a new version of a question while viewing it

### ISSUE THREAD

**Issue by neel-a-mehta** [civiform/civiform#1031]
From the Question Bank, a CiviForm admin can click on a question to view a preview of it. Add some call-to-action button  that the user can press; this button should take them to the screen where they can create a new version of the question. Right now, there's no such call-to-action on the question viewer page.

![image](https://user-images.githubusercontent.com/77128518/117342442-42c9f000-ae71-11eb-80f6-1ef88bb58cd7.png)

**Comment by goldblatt** [comment]
hey @shanemc-goog did your changes a while ago fix this?

**Comment by shanemc-goog** [comment]
@goldblatt No, the changes you might be thinking of are that in the normal edit flow you could accidentally overwrite an existing draft if you had old browser state.

**Comment by elisekalstad** [comment]
Done--able to view questions as we're building them.
