### ISSUE TITLE
Let CiviForm admin clone a question

### ISSUE THREAD

**Issue by neel-a-mehta** [civiform/civiform#1193]
In #1091, we discuss how it's often helpful to edit certain facets of a question (e.g. its name or enumeration status), yet that's not always easy to implement on the dev side. A nice workaround would be to let the admin clone a question and edit the copy while leaving the original one intact.

The "copying" screen should let CiviForm admins edit these hard-to-change fields, such as the name and enumeration status, before saving the new question.

**Comment by neel-a-mehta** [comment]
cc @kendrickt

**Comment by kristinyim** [comment]
other feedback was the ability to clone screens or use a template
