### ISSUE TITLE
Find more consistent wording for question bank

### ISSUE THREAD

**Issue by neel-a-mehta** [civiform/civiform#1202]
There are several different types of links available in the question bank. For questions that have *not* been edited since the most recent publication, there is:

- View
- New Version

For questions that *have* been edited since the most recent publishing, there is:

- Edit Draft
- Manage Translations

The divergence in wording seems confusing. It may be unclear to the CiviForm admin why the wording changes and how the sets of links correspond to each other (e.g. "New Version" does something similar to "Edit Draft", yet the names are very different; "Manage Translations" is also included in "New Version" but you wouldn't know that from the link). Can we find a unified, consistent set of names for the links?

![image](https://user-images.githubusercontent.com/77128518/118848223-2a57cd80-b894-11eb-8781-ec12d713dcae.png)

**Comment by neel-a-mehta** [comment]
Copying over some comments from @baipai: 

> And tried another time under "address", but why those two questions I have created show "edit draft" and "manage translations" but not "view" and "new version"
> So, when do the questions become published from the "edit draft"? is it based on if the program gets published or not?
> Is it possible to make the name"New Version" same as "Edit"? It seems there are all means to "edit" in some way? Or is it a totally different system on its own?
> Let me make an issue about this so we can store the conversation -- I'll draw in the technical writer who might be able to help us

**Comment by baipai** [comment]
My first thought is “View” can be “Preview”, “New Version” and “Edit Draft” can be just “Edit”.

**Comment by kencenerelli** [comment]
Thanks, Bai for kicking off the discussion.

So when I think "Preview", I think "preview the changes". If a user simply wants to look at a question, I suggest we stick with View or we go with "Review".

As for “New Version” and “Edit Draft”, I agree with Bai that we go to “Edit”. Once on the edit screen, we could alert the user with a banner they either just created a new version of the question or they are editing an unpublished question.

Side note: Why do we not have cancel buttons on the Create screens? To stop creating a new program or question, you have to navigate away.

**Comment by baipai** [comment]
Then I think View can stick on View, because right now, the questions part cannot let the user preview the changes.

Good question, about the cancel buttons, and I don’t think we don’t have something like a go back button either. I will be sure to put on the screen and talk about that during the office hour and with the engineer.

**Comment by baipai** [comment]
Any thoughts on the “View Published” button? I am thinking if it makes more sense to change it to “Previous View”? @kencenerelli

**Comment by baipai** [comment]
Some updated with wording, where I and @kencenerelli  work together for the civiform admin part.
https://docs.google.com/document/d/1QLL5ytDdpi24pk6H0IHdmWabZRsAQFmcpALtuj2OeGA/edit?usp=sharing

**Comment by reemaka** [comment]
Out of date as the UI has changed a lot since 2021.
