### ISSUE TITLE
In list of questions in form builder, surface the languages that each question is translated into

### ISSUE THREAD

**Issue by neel-a-mehta** [civiform/civiform#1239]
When I go to add questions in the CiviForm Admin's Form Builder UI, I can't see which languages the questions are translated into, which makes it hard for me to know the "quality" of each question / whether or not I need additional translation help to translate those questions.

![image](https://user-images.githubusercontent.com/77128518/119168923-0973b180-ba27-11eb-910b-44c5d710065f.png)

Perhaps add some chips or badges that show the languages that each question is translated into, such as `EN`, `ES`, `CN`, etc.

**Comment by mayamcgrory** [comment]
This issue is resolved through the question bank. Link to Figma file here. https://www.figma.com/file/0qsODjocwTF9bKuJn5THAA/Admin-CiviForm-Admin-Program-Admin-Screens?node-id=616%3A3447
