### ISSUE TITLE
Use sentence case throughout UI

### ISSUE THREAD

**Issue by neel-a-mehta** [civiform/civiform#1250]
We currently have an inconsistent mix of Title Case (This Is My Text) vs Sentence Case (This is my text). UX writing best practices say that we should use sentence case wherever possible, so go through the codebase to identify strings in Title Case that we can change to Sentence Case.

**Comment by cassandralfernandes** [comment]
@rahaghas this seems to be fixed to me - do you notice any issues with Title Case (This Is My Text) vs Sentence Case (This is my text) anywhere in the product? I could use another pair of eyes

**Comment by rahaghas** [comment]
agreed I think this is fixed
