### ISSUE TITLE
On Civiform admin's Questions page, separate archived and unarchived questions

### ISSUE THREAD

**Issue by neel-a-mehta** [civiform/civiform#1319]
In the Civiform admin's Questions page, they see the list of all questions in CiviForm. Archived and regular (non-archived) questions are intermingled here. To make the page easier to skim, we should either:

- Style archived questions differently so the admin can tell what's active or not; or, 
- Separate archived questions, perhaps by putting them at the very bottom of the screen in a separate section.

Here's how the page looks right now, btw:

![image](https://user-images.githubusercontent.com/77128518/121228801-31eb1080-c85b-11eb-9a80-ede31485319a.png)

**Comment by ndmckinley** [comment]
They're only mixed until the next version is published.  Once the next version is published the archived questions will be gone.

**Comment by neel-a-mehta** [comment]
Got it, good to know -- at some point down the road we'll want to add some UI affordances to explain this. Not now though.

**Comment by baipai** [comment]
This has already been done, the UX and UI already leave space for this part. When users click the different status on the top, they will be able to go to the different status.
