### ISSUE TITLE
Make UX of one- vs multi-line text inputs clearer in question builder

### ISSUE THREAD

**Issue by neel-a-mehta** [civiform/civiform#1364]
When creating new questions, the program admin has to enter several pieces of data. Some of those inputs are paragraph / `<textarea>` input, while others are one-line / `<input type="text">` input. But the UX doesn't differentiate between these, which can be confusing. See how the one-line Name input and the other multi-line inputs look the same: 

![image](https://user-images.githubusercontent.com/77128518/122104077-42fcca00-cde5-11eb-86c0-2ea896c383ad.png)

We should make the multi-line inputs look different, perhaps by making them taller or showing [a resizing widget](https://www.w3schools.com/cssref/tryit.asp?filename=trycss3_resize). 

I think this problem might be broader, too: see if other `<textarea>`s in the app have UX that makes them look different than one-line `<input>`s. If not, add that UX.

**Comment by lianne-oy** [comment]
(To clarify - this applies everywhere; not just date question type)
