### ISSUE TITLE
Question text and help text can be entered as multiline, but don't render as such

### ISSUE THREAD

**Issue by neel-a-mehta** [civiform/civiform#1374]
In the Question builder, you can enter multiple lines of text for the Question Text and Question Help Text (which are both shown to the applicant).

But the newlines get removed when the question gets rendered, both in the preview pane:

![image](https://user-images.githubusercontent.com/77128518/122302072-75c2c300-ceb6-11eb-93d4-e8cdba3f9b3b.png)

And in the actual applicant view:

![image](https://user-images.githubusercontent.com/77128518/122302119-86733900-ceb6-11eb-8dcb-ae302ca84d11.png)

To resolve this inconsistency, I propose:

- Make the Question Text field only accept one line of input. It shouldn't be too long in the first place.
- Let the Question Help Text field still accept multiple lines of input, but ensure that the renderers render the newlines so that line breaks actually show up. 

This builds off #1364 in terms of improving the UX of the question builder.

**Comment by neel-a-mehta** [comment]
In the Question builder, you can enter multiple lines of text for the Question Text and Question Help Text (which are both shown to the applicant).

But the newlines get removed when the question gets rendered, both in the preview pane:

![image](https://user-images.githubusercontent.com/77128518/122302072-75c2c300-ceb6-11eb-93d4-e8cdba3f9b3b.png)

And in the actual applicant view:

![image](https://user-images.githubusercontent.com/77128518/122302119-86733900-ceb6-11eb-8dcb-ae302ca84d11.png)

To resolve this inconsistency, I propose:

- Make the Question Text field only accept one line of input. It shouldn't be too long in the first place.
- Let the Question Help Text field still accept multiple lines of input, but ensure that the renderers render the newlines so that line breaks actually show up.

**Comment by reemaka** [comment]
You can't hit enter on these fields anymore, so this is outdated
