### ISSUE TITLE
Add markers to optional and required questions in applicant view

### ISSUE THREAD

**Issue by neel-a-mehta** [civiform/civiform#1423]
In #1404 we describe how questions should get markers representing whether they're optional or required. Check that issue for the latest in UX plans, but at least for now:

* Put an asterisk next to required questions
* Put (optional) next to optional questions

This might be a lot, but we should err on the side of overcommunicating for now.

**Comment by neel-a-mehta** [comment]
cc @kendrickt

**Comment by lianne-oy** [comment]
Moving to Q3

**Comment by elisekalstad** [comment]
Continues to be a BIG theme for the program admins in order to have a smooth flow.

**Comment by azizova-leyla** [comment]
Related: https://github.com/seattle-uat/civiform/issues/2629
