### ISSUE TITLE
Ask applicants/TIs for feedback after they apply

### ISSUE THREAD

**Issue by neel-a-mehta** [civiform/civiform#1454]
Just have a quick feedback form after someone applies. Ask applicants what part of the form was hard, for instance, or how long it took them to fill it out. Ask TIs what their client needed help with, why the applicant came to them, if the applicant knew about the program or if the TI told them about it. Ask for Net Promoter Score.

This is great qualitative / survey feedback to complement the quantitative / metrics data that we are gathering.

**Comment by elisekalstad** [comment]
Survey link: https://civiform.seattle.gov/programs/survey

**Comment by elisekalstad** [comment]
@msprenke  to start on PRD (consider universal ability to insert appropriate link)

**Comment by msprenke** [comment]
assigned to matt for PRD

**Comment by msprenke** [comment]
Tracking in backlog.  This can be solved by item https://github.com/civiform/civiform/issues/4354 as we will be able to post the surveys in the custom confirmation screen for each program

**Comment by msprenke** [comment]
@elisekalstad now that links are available in program confirmation screens, you have the ability to include links to surveys.  I'm going to mark this item as done and you can apply feedback surveys to all programs that wish it.

**Comment by elisekalstad** [comment]
@elisekalstad -- put in translations! Then publish.

**Comment by msprenke** [comment]
links added to program confirmations
