### ISSUE TITLE
Seattle logo obscures text in iOS iPhone 11 mobile view

### ISSUE THREAD

**Issue by gcapiel** [civiform/civiform#1462]
See screenshot
![Screenshot 2021-06-23 at 3 34 18 PM](https://user-images.githubusercontent.com/437060/123176748-e0d14400-d438-11eb-9394-05b1e0b8660c.png)

**Comment by azizova-leyla** [comment]
This is no longer the case, was fixed as part of other work. Closing the issue.


![Image](https://user-images.githubusercontent.com/1741747/201209526-e48916b9-5488-4b33-b9b8-33b3e68ab96a.png)
