### ISSUE TITLE
Uglify Tailwind CSS file

### ISSUE THREAD

**Issue by neel-a-mehta** [civiform/civiform#1480]
#1399 and #1419 strip away unnecessary classes from the tailwind.css file we use, getting it down to ~1.6 MB. But the file is normally-formatted CSS (i.e. not minified or uglified). Uglifying it (removing spaces, etc.), [by my estimate](https://www.uglifycss.com/), could cut it down to closer to 1.3 MB. Not a huge savings, but it helps on the margin, and helps load faster on slower internet connections.

**Comment by syntapy** [comment]
I'm going to work on this one

**Comment by gwendolyngoetz** [comment]
Trimmed, but not yet minified.

**Comment by melanie-exygy** [comment]
We're moving away from Tailwind and I just checked the stylesheet size when loaded into the browser and it was less than 1MB on initial load.  Given that it's cached after that, it isn't worth the effort to work on this.
