### ISSUE TITLE
Let TIs transfer data they've inputted for a client to the client's CiviForm account

### ISSUE THREAD

**Issue by neel-a-mehta** [civiform/civiform#1507]
This is the reverse of #1506. In that issue, we let applicants share their data and accounts with TIs so TIs can apply on their behalf and use the data that applicants have already put into CiviForm. In this issue, we let TIs give clients control over  applications and data that the TI has started filling in for them.

Imagine this workflow:

- A CBO staffer creates an "account" for client X.
- The staffer (a TI) fills in a few forms on behalf of client X.
- The TI wants to let client X start doing applications on their own, without the TI's help (see #1436).
- So the TI tells the client to make their own IDCS account.
- Then the TI transfers the data and applications they've created for client X to client X's shiny new account. (That's this feature.)
- The accounts are now "merged", in a sense, since both TI and applicant can apply independently. But either side can sever the connection, such as if the applicant wants to start working on their own.

**Comment by elisekalstad** [comment]
This is completed. But we don't inform clients/TIs that this is possible. Should consider messaging around it. Closing for now. Need to create a new feature request.
