### ISSUE TITLE
Login access as CiviForm Admin AND Program Admin

### ISSUE THREAD

**Issue by elisekalstad** [civiform/civiform#1593]
**Describe the bug**
I'm not sure if this is actually a bug--I would also understand if this is how the tool is intended to be in order to preserve additional layers of privacy. BUT

I'm looking for a good way to be able to see how many applications were submitted. As CiviForm Admin, I have no way (currently) of knowing if it is a test application or a real application. My work-around is to assign myself as a Program Administrator to get access to the applications as they come in. 

But I cannot login as a Program Administrator--my CiviForm Admin role takes precedence.

**To Reproduce**
1. Go to "Civiform.Seattle.gov"
2. Click on Admin Login'
3. Only able to view the CiviForm Admin view

Alternatively:
1. Open email when a new applicant submits an application
2. Click on the link to view the application
3. Get an error message, attached

**Expected behavior**
If the CiviForm Admin role is deliberately separate from the Program Admin role (which is very well might be!), then it's functioning as expected. It would be great to have a way to see how many applications were received that are REAL applications and not just test ones :)

**Screenshots**
[Program Admin vs. CiviForm Admin.docx](https://github.com/seattle-uat/civiform/files/7018387/Program.Admin.vs.CiviForm.Admin.docx)

**Comment by elisekalstad** [comment]
I am unable to act as both a CiviForm Administrator AND Program Administrator. Without this access, I have a hard time troubleshooting issues that Program Admins face. I often cannot replicant their issue in Staging. It would also help to respond to resident questions about the status of their application, if I'm able to look them up in CiviForm. Is it possible to re-open this request? I'd like to better understand what it will take to grant CiviForm Admins (Matt and I) access as Program Admin)

**Comment by azizova-leyla** [comment]
@cassandralfernandes need your input. 

It was an explicit decision to not give Civiform Admin access to Program Applications, to have better privacy model and limit number of people accessing PII. @elisekalstad if that's not a concern for you - we can change it.

Currently we have an explicit check to not allow Civiform Admin assign themselves as Program Admin. We can add a server config variable that will disable that check. So it will be up to civic entity to enable that or not.

That would behave similarly to demo server when using "Program and Civiform Admin" button. Applications will be under 3 dot menu: 
![image](https://user-images.githubusercontent.com/1741747/191316501-2e65b82f-adfc-410e-9dd1-d95264ca0068.png)

There two options for the user flow:
1. When the flag is on - Civiform Admin has access to all applications for all programs without additional actions. If the flag is later turned off - they lose program access.

2. When the flag is on - Civiform Admin can add themselves as a Program Admin. If the flag is later turned off - they will not automatically lose access, they will need to be manually removed from that program.

**Comment by elisekalstad** [comment]
Hi @azizova-leyla -- It's not a concern to have CiviForm Admins access PII (approved by Seattle's Privacy Team, common practice with other applications used in the City). It allows us to triage issues program admins encounter much quicker. And can help when residents reach out directly to us about an issue with their application. 

My recommendation would be Option 1--access for all application for all programs. I know this is a deviation from the original setup of CiviForm, but this will help us provide better support to users! Thank you!!

**Comment by azizova-leyla** [comment]
Assigning to Gwen to enable this in the next release.

**Comment by gwendolyngoetz** [comment]
I enabled the feature flag. It will be enabled after next prod deploy.
