### ISSUE TITLE
Need translations for applicant-facing app strings

### ISSUE THREAD

**Issue by leonwong** [civiform/civiform#1629]
Some applicant facing strings are compiled into civiform (and not authored by program admins). We currently have incomplete Spanish translations (`messages.es-US`) and we are missing translations for the following languages (located in [universal-application-tool-0.0.1/conf](https://github.com/seattle-uat/civiform/tree/main/universal-application-tool-0.0.1/conf)):

```
messages.am
messages.ko
messages.so
messages.tl
messages.vi
messages.zh-TW
```

The master `messages` file has helpful comments describing how these strings are used.

In addition to getting missing strings translated, we should ideally have a repeatable process for detecting if strings have changed in `messages` and getting translations updated.

**Comment by elisekalstad** [comment]
Added Tier 2 languages, still need translation from me.

**Comment by elisekalstad** [comment]
Elise to add "save and next"

**Comment by elisekalstad** [comment]
Feedback from CBOs: Enumerator "Nickname" reads "Name". So it looks like "Name of Name". Check enumerator questions support text. @elisekalstad

**Comment by elisekalstad** [comment]
Done--may need to periodically update UI translation.
