### ISSUE TITLE
Ability to segment application downloads

### ISSUE THREAD

**Issue by lindsayzad** [civiform/civiform#1671]
**Is your feature request related to a problem? Please describe.**
Currently, program admins are processing civiform applications by downloading the csv of all applications.  As more and more applications come in over time, this may be confusing for them, as the admins have to go through the apps to figure out which ones are new and need attention.  It is also not very readable to have such a huge download.  This will also help if a program is ever at the scale where the number of applications cannot reasonably all be downloaded at once, and must be separated as a technical limitation.

**Describe the solution you'd like**
Some partners at Seattle have floated the idea of being able to set a date start and end time for the download.  They would only get applications that had been submitted in that window.  This allows them to potentially do a new download every week, and simplify their processing.  Overall, admins want a more usable, readable way to download the application data so that they can process it.  Currently, they tend to put the csv in a spreadsheet and do their processing outside of civiform

**Additional context**
This needs UX consideration on what the best path forward should be before Eng moves forward

**Done when**
Program Admins have a usable experience when downloading applications for processing

**Comment by gwendolyngoetz** [comment]
Date range filter was added a long while ago. Closing.
