### ISSUE TITLE
Error message: Not fully translated into English

### ISSUE THREAD

**Issue by elisekalstad** [civiform/civiform#1712]
**Describe the bug**
When logging into CiviForm as a resident, there is an error flag at the top. "This program is not fully translated to English". 

**To Reproduce**
1. Login to CiviForm using Username and Password
2. Click on a program (I selected "UDP"
3. See the alert on the top of the all form pages

**Expected behavior**

**Screenshots**
Attached
![English Translation Error](https://user-images.githubusercontent.com/86082659/142952637-ba54a6ec-425a-4d63-9e60-60642615fed6.JPG)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by bion** [comment]
Is it possible that one of the questions for this program is missing an english translation?

**Comment by elisekalstad** [comment]
@bion -- I don't think so. All of the questions start out in English. I just tried it again and the error flag is no longer there.

**Comment by kristinyim** [comment]
If the error flag is gone, can we close this?

**Comment by elisekalstad** [comment]
Nope, it’s still there! Let’s keep this open for now. It might be an issue on my side, I just saw a flag from Bion that I might be missing some UI text :/

[Title: City of Seattle logo]Elise Kalstad
She/Her/Hers
City of Seattle, Innovation & Performance
206-256-5515 | ***@***.******@***.***>
Learn more about Innovation & Performance: seattle.gov/innovation-performance<https://www.seattle.gov/innovation-performance>

**Comment by nb1701** [comment]
Closing as this is an old issue and it seems the program no longer exists, but please reopen if that's not the case.
