### ISSUE TITLE
Applicants are screened for income eligibility before submitting application

### ISSUE THREAD

**Issue by elisekalstad** [civiform/civiform#1738]
Include eligibility requirements early on in the application process so that residents are only applying to programs for which they are qualified. This would save residents and program staff time currently spent evaluating applications that don't qualify.

This could be a part of the Affordable Seattle portal (eligibility calculator). Or initial CiviForm page.

**Comment by elisekalstad** [comment]
This is the #1 priority for the FreshBucks team. Relates to #2407 --Validate that address is within City limits.

**Comment by msprenke** [comment]
User Stories: 
1. Applicant enters number of people living in household and household income Applicant enters number of people living in household and household income 
2. Applicant receives a message informing them that they do not qualify if income and household size exceeds income/household size qualifiers if set by program (Relates to #973 )
