### ISSUE TITLE
Program Admin Dashboard

### ISSUE THREAD

**Issue by elisekalstad** [civiform/civiform#1745]
Create dashboard for transparency of summary metrics (# of applications, by status, time to complete, other programs applicants applied to)

**Comment by melanie-exygy** [comment]
Closing since we are covering this in our current metrics work:  see this [PRD](https://docs.google.com/document/d/18G6Iujj-YZADFZ3SSBjInGA4gux8Mi5LTnq9LLCWpzE/edit?usp=sharing)
