### ISSUE TITLE
Call to IDCS logout endpoint

### ISSUE THREAD

**Issue by elisekalstad** [civiform/civiform#1770]
**Describe the bug**
Selecting "logout" does not trigger an endpoint logout in IDCS. For example, if I log in to CiviForm and then click "logout", I am redirected back to the CiviForm login homepage. But if I then click "login", I am not asked for my username or password. It automatically takes me to my account. 

The IDCS team recommends calling the IDCS logout endpoint to make sure we have a clean logout ending application session and IDCS session as well.

**To Reproduce**
1. Go to https://civiform.seattle.gov
2. Click on 'Login"
3. Enter Username and Password
4. Selected 'Logout'
5. Return to home login page
6. Selected 'Login'
7. See that CiviForm does not ask for username or password; user is still logged in.

**Expected behavior**
Clicking logout would force a user to enter their username and password when trying to log back in.

**Comment by bion** [comment]
Fixing this involves redirecting to IDCS logout URL after the user has visited the CiviForm logout controller.

Info IDCS logout endpoint (confirm with Vinay): https://docs.oracle.com/en/cloud/paas/identity-cloud/rest-api/logoutopenidconnect.html

Docs on customizing pac4j logout controller behavior:
https://github.com/pac4j/play-pac4j/wiki/Logout-configuration
http://www.pac4j.org/docs/logout-endpoint.html
