### ISSUE TITLE
GCP Terraform: Configure VPC and access Postgres with Private IP

### ISSUE THREAD

**Issue by shubha-rajan** [civiform/civiform#1812]
The Could SQL Postgres instance should only be accessible through its private IP address, so we need to configure a VPC network, a serverless VPC connector for Cloud Run, and enable only private IP connections on the Cloud SQL instance.

**Comment by nbeloglazov** [comment]
Closed it as we are not planning to support GCP in short-term. And when we do - likely we'll file new issues based on AWS configuration.
