### ISSUE TITLE
Runtime error when creating question

### ISSUE THREAD

**Issue by shubha-rajan** [civiform/civiform#1884]
**Describe the bug**
For certain question types, including Address, Currency, Date, Name, Enumerator, and File Upload, a runtime error is thrown after trying to save a new question:

**To Reproduce**
1. Start Civiform dev server
2. Attempt to create a new FileUpload question

**Expected behavior**
Creating a new question shouldn't cause the program to crash.

**Screenshots**
<img alt="Screen Shot 2022-02-07 at 1 14 11 AM" src="https://user-images.githubusercontent.com/19631367/152761801-5061a169-9024-490e-b821-e3f4a91c09dc.png">

**Desktop (please complete the following information):**
 - OS: Mac OS Monterrey (12.1)
 - Browser: chrome
 - Version: Version 97.0.4692.99 (Official Build) (x86_64)

**Additional context**
Adding the following annotation to the inner ValidationPredicates classes of the affected question types seems to fix the problem:
```java
@JsonAutoDetect(fieldVisibility = JsonAutoDetect.Visibility.ANY)
```

**Comment by syntapy** [comment]
Hey I'd like to try working on this one if no one else is

**Comment by shubha-rajan** [comment]
> Edit: Nevermind, I can't reproduce the bug, maybe because I'm not on a Mac?

Yeah, the weird thing about this error is that it only happens on some computers. I'm not sure why I'm running into it and others aren't.

**Comment by syntapy** [comment]
Weird...

When I do `run-dev` I get a few errors scattered about but otherwise it can run.

Are different people are getting different sets of errors?

**Comment by shubha-rajan** [comment]
> Edit: No idea if that would have anything to do with anything, but if you want I can show the ones I have

Yeah, what errors are you getting?

**Comment by syntapy** [comment]
Ok ok, maybe I should actually click the submit button when trying to reproduce the error, do you think? Lol

Now, with localstack emulator, after I hit submit it tries to redirect to url `http://localstack:4566/civiform-local-s3` and I get the error page "This site can't be reached". 

Do you think the redirecting to `localstack` instead of `localhost` is related to this problem?

With azurite emulator I am getting this error
![azurite_error](https://user-images.githubusercontent.com/7295000/152892226-029daded-91df-42a2-a0e1-31bbdef69f8e.png)

**Comment by shubha-rajan** [comment]
> Do you think the redirecting to `localstack` instead of `localhost` is related to this problem?

Yeah this is a known issue. The same thing happens with azurite. To get it to work, you'll need to add a line to your `/etc/hosts` file that maps 127.0.0.1 to `localstack` so that your browser knows how to resolve the host.

> With azurite emulator I am getting this error as soon I start the application (file upload question is 1st question) ![azurite_error](https://user-images.githubusercontent.com/7295000/152892226-029daded-91df-42a2-a0e1-31bbdef69f8e.png)

are you using the --azure flag when starting the application?

**Comment by syntapy** [comment]
Ok, thank you for the tip

> are you using the --azure flag when starting the application?
Yes, and no args I think for the localstack

I was just about to post errors I was seeing in `run-dev` which I mentioned earlier, but I guess you all must have fixed whatever was causing them

**Comment by kristinyim** [comment]
If this bug is unable to be replicated, can we close it?
