### ISSUE TITLE
Add more information about program visibility options

### ISSUE THREAD

**Issue by glorialiou** [civiform/civiform#1910]
We received feedback that it would be helpful to add a header/description to program visibility options (Public or Hidden in Index) for clarity on what they mean.

**Comment by cassandralfernandes** [comment]
Initial mock [here](https://docs.google.com/presentation/d/15fcq3dYFgy1Dfy2UjZybmHD9KIW5cz8Q1BjwgOpLJ7g/edit#slide=id.g13ec4604693_0_19)

Needs UXR

**Comment by cassandralfernandes** [comment]
On [this page](https://screenshot.googleplex.com/7LvjHedHNgqP3zU) under program visibility, 

Change hidden in index to: Hide from applicants. Only individuals with the unique program link can access this program

Change public to: Shown publicly

**Comment by clouser2** [comment]
That text is pretty long but still fits on the screen in the existing layout:
![Image](https://user-images.githubusercontent.com/1870301/189768002-b508f934-22e5-4e10-a602-7ab2aa0ea742.png)
