### ISSUE TITLE
Change button copies on applicant experience preview page

### ISSUE THREAD

**Issue by glorialiou** [civiform/civiform#1919]
In the preview page of the applicant experience, change the button copies for "Start here" and "Continue." See screenshot here: https://docs.google.com/presentation/d/1goxiepPXPrW3wK8wUSNoCpcf7iXIohXfj96iTYiQxo0/edit#slide=id.gfa7bf315fa_0_741

Currently, "Start here" and "Continue" bring the user to different places, which may not be intuitive.
"Start here" jumps the applicant to that (first) question, and then the applicant is ONLY shown questions that aren't auto-filled.
"Continue" on the other hand, takes the applicant through the full application from the beginning to the end (all questions + different UI/UX than "Start here").

Instead of "Continue," perhaps "Review all answers" or something like that.
Please consult with UX (UXR/D/W) when we get to this.

**Comment by kristinyim** [comment]
Closing in favor of #1920
