### ISSUE TITLE
Update the names of the links (View, New Version, Archive) and replace arrows

### ISSUE THREAD

**Issue by glorialiou** [civiform/civiform#1931]
For both questions and programs, there was feedback (both from admins and from UX audit) around the naming of the links being unclear. No proposed solution, but something we should run by UXR/D/W when we get to this issue.

There was also feedback about the arrows being poor UI/UX (I also really don't like the arrows). Maybe a pipe instead? (View | Edit)

Relevant slide in UX audit: https://docs.google.com/presentation/d/1goxiepPXPrW3wK8wUSNoCpcf7iXIohXfj96iTYiQxo0/edit#slide=id.gefcb4c94df_0_252

**Comment by baipai** [comment]
Hi, @glorialiou 
About the text name and flow, we’ve found the same issue, here is the design we did back in 2021 Q2 with ux designer, ux writer, design lead, product manager and engineer together. I think you may find some text names have been updated, some are not, so causing the question and the program name didn't match. 

Hope the information will be helpful.

Here is the doc with changed text and design: [https://docs.google.com/document/d/1QLL5ytDdpi24pk6H0IHdmWabZRsAQFmcpALtuj2OeGA/edit?usp=sharing](https://docs.google.com/document/d/1QLL5ytDdpi24pk6H0IHdmWabZRsAQFmcpALtuj2OeGA/edit?usp=sharing)

Here is the program part:
<img width="1280" alt="214Programs" src="https://user-images.githubusercontent.com/11348330/153830304-106b7894-6eba-4b88-8f57-36c0dd3f216d.png">

Here is the question part:
<img width="1284" alt="Questions -_ Manage Translations" src="https://user-images.githubusercontent.com/11348330/153831482-254985e1-5223-46c3-9bf7-9338dbfb2f5d.png">

**Comment by cassandralfernandes** [comment]
Closing this issue in favor of duplicate #3033
