### ISSUE TITLE
CiviForm client-side scripts in need of refactoring

### ISSUE THREAD

**Issue by cassandralfernandes** [civiform/civiform#1932]
CiviForm is predominantly server-side rendered but makes use of TypeScript for some features. It is currently a fairly hodgepodge approach that includes a variety of files, some of which have very poor separation of concerns. Improving the CiviForm UI would be much easier with a more consistent and well organized JavaScript situation.

Bare minimum improvements:

- factor out individual concerns from main.ts
- factor out individual concerns from validation.ts
- add unit tests for all JS behaviors
- remove all uses of the any type in favor of more specific typings

Additional improvements:

- introduce a JS build system (such as webpack or similar) rather than individual Play views including injecting script tags at runtime
- enable TS files to import shared code
- enable TS files to import library code and types from npm

**Comment by goldblatt** [comment]
@clouser2 this might be in relation to what you were thinking about with the client side rendering!

**Comment by nbeloglazov** [comment]
The second part (about introducing a JS build system) is covered here: #3864
