### ISSUE TITLE
Unable to exercise file upload code in dev

### ISSUE THREAD

**Issue by cassandralfernandes** [civiform/civiform#1939]
We use emulators to simulate cloud services in dev and test (Localstack for AWS and Azurite for Azure), but they only actually work for file uploads in the test environment. This means that it's not possible to use the file upload feature when running the app in dev mode.

We should

1. fix file uploads with the emulators in dev mode
2. create a means of connecting to a real cloud storage backend in dev mode to exercise the real integration

**Comment by bion** [comment]
Done
