### ISSUE TITLE
CiviForm lacks a feature flag or experimentation system

### ISSUE THREAD

**Issue by cassandralfernandes** [civiform/civiform#1943]
When new code is introduced to CiviForm, there is no way to enable or disable it, only deploy or rollback.

We should implement release decoupling for CiviForm using either an open source or custom-made feature flag or experiments system.

- [x] Feature Flag
- [ ] Set feature flags via url (ease of testing in staging etc.)
- [ ] Experiment System

**Comment by shanemc-goog** [comment]
I'm going to work on a Feature Flag design as ambiguity in the Status Tracking work will necessitate having checked in but turned off code paths.

**Comment by bion** [comment]
Done

**Comment by shanemc-goog** [comment]
This was updated to allow browser overrides in #3115, and revamped in #3134
