### ISSUE TITLE
Visibility condition on multiple question responses

### ISSUE THREAD

**Issue by kristinyim** [civiform/civiform#1958]
Right now, visibility condition is based on one question but would like it to be based on multiple question responses.

**Comment by elisekalstad** [comment]
This is a sticking point right now--for example, we only need income documents from residents who aren't already on SNAP Food Benefits AND who are older than 18. I can only pick one of those qualifiers currently. It would be helpful if the visibility feature had the ability to do:

IF (Question 1) = (Answer) AND (Question 2) = (Answer) THEN show Screen A.

**Comment by elisekalstad** [comment]
Sounds like this is already in the works. Also related to eligibility feature **https://github.com/civiform/civiform/issues/3744**

**Comment by shanemc-goog** [comment]
It's related but not a main use case for the FreshBucks Eligibility work, so it'd only be covered unintentionally

It's a good blanket feature request for both Visibility and Eligibility so I'd run this through the feature request process.

It has been something that has been in mind with improvements to the blanket Condition specification UI for Eligibility though (which would then come for free with Visibility).


@bion While the "logic builder" that we've talked about could end up meeting this need, there's likely a larger feature of having multiple first-order predicate conditions that aren't inherently tied to each other here.

**Comment by bion** [comment]
Design doc: https://docs.google.com/document/d/1keRHFKgwNDTyqf0f1sNR63UvxvPl2yDJWe2VYC0NIyY/edit#

**Comment by bion** [comment]
Done
