### ISSUE TITLE
Increase Observability Capabilities (Phase 2)

### ISSUE THREAD

**Issue by bion** [civiform/civiform#1974]
### Epic Overview
CiviForm lacks observability. The goal of this epic is to provide CiviForm deployments with a low-cost, non-proprietary monitoring solution to improve system reliability in terms of uptime, latency, and incident resolution speed.

### Problem Statements(s)
CiviForm is missing the kind of instrumentation and data presentation that makes maintaining and operating a web service less risky (i.e. observability or o11y). Both Seattle and Rochester have little more than server logs with the basic cloud-provider provided tools for searching through them. In both cases looking through logs is onerous, and looking into critical metrics such as QPS, request latency, error ratios, etc is impossible.

Improving this circumstance is made more complicated since we cannot mandate a specific paid tool for civic entities to use for o11y. There are however open-source instrumentation tools that allow the implementer to choose their own paid data ingestion and presentation service. https://micrometer.io/ is one such example.

From @shanemc-goog:

Likewise the ability to launch new features an observe they're working as intended is missing.

We currently launch features with code pushes, so the lack of observability makes it hard to do this safely, or know if a rollback is needed.

### Product Requirements

For Q4:

- document usage of the monitoring system in the docs website

### Design & Eng Requirements
[CiviForm Monitoring Design](https://docs.google.com/document/d/1thjkRcDc925VDdMTJ8h4CAPZK0CA5nx2Vw-RMwQzGDk/edit?resourcekey=0-5JpjYZsFpFRvg1c3yaUX8Q#heading=h.iopf4bmhbkhg)

**Comment by rasmi** [comment]
Related to #1816 and #2606?

**Comment by shanemc-goog** [comment]
@rasmi Those issue look at to about setting up logging, but this Issue is that logs are insufficient for most meaningful system monitoring needs.

**Comment by bion** [comment]
Draft design for monitoring system (request access if unable to view): https://docs.google.com/document/d/1thjkRcDc925VDdMTJ8h4CAPZK0CA5nx2Vw-RMwQzGDk/edit?usp=sharing&resourcekey=0-5JpjYZsFpFRvg1c3yaUX8Q

**Comment by bion** [comment]
Done: https://github.com/civiform/docs/pull/154
