### ISSUE TITLE
TIs can view additional client information within TI dashboard.

### ISSUE THREAD

**Issue by elisekalstad** [civiform/civiform#2009]
Trusted Intermediaries would like to be able to view additional client information within the TI dashboard. They would like to be able to view **client's name,** **date of birth,** and **address** (WHOOPS! I MEANT EMAIL ADDRESS!) within the TI dashboard. They would like to be able to **view the application status** for each client's application within the client card.

Will need mock-ups for TI view.

**Comment by rahaghas** [comment]
Here's a mock of my thinking for this experience:


<img width="1280" alt="V2" src="https://user-images.githubusercontent.com/103459221/169105476-60139ddd-b102-4546-8c18-11ebcffa7662.png">

The overflow menu houses the actions to manage each client's info, such as editing details or deleting. 

To view application status, the TI would click "Go to programs" and land on this page:
<img width="1280" alt="V2" src="https://user-images.githubusercontent.com/103459221/169106520-4565bc59-743f-4e45-9722-9aa53896b0fd.png">

**Comment by swatkat1** [comment]
Thank you Raha!

**Comment by bion** [comment]
@swatkat1 in standup today we discussed application status with respect to this feature. After seeing the mockups here I think our discussion today wasn't correctly understanding what this design is calling for. We *do* have the ability to display to the TI/Applicant whether an application for a given program is unstarted, started but not submitted (and % complete, though that number can be misleading), or submitted. Starting and submitting an application updates its [lifecycle stage](https://github.com/seattle-uat/civiform/blob/main/server/app/models/Application.java#L90)
