### ISSUE TITLE
TI's can search client list

### ISSUE THREAD

**Issue by elisekalstad** [civiform/civiform#2010]
TIs would like to be able to search for clients by name and date of birth within the TI dashboard.

Mock-ups needed.

**Comment by swatkat1** [comment]
Hi @rahaghas I have a question for you- 
When you recommended the Search by DOB in a separate search box, did the text and the date search have a OR functionality or an AND functionality? 
Between the two searches should I add -AND it or 
OR it?

![Image](https://user-images.githubusercontent.com/101214724/176748517-2fc3f859-e0e2-420a-9042-be340fbfcd40.png)

**Comment by rahaghas** [comment]
Would prefer an OR functionality, meaning the Search button would only apply to the Search by name field and date of birth would need it's own action

**Comment by swatkat1** [comment]
Awesome Thank you @rahaghas
