### ISSUE TITLE
Add a Visible Version Number to the Application

### ISSUE THREAD

**Issue by gwendolyngoetz** [civiform/civiform#2022]
Currently there is no way to determine the version of the deployed application without going to look in the AWS console.

It would be useful to put the version number on the app. This would make it easier to verify during/after deployment as well as when communicating with each other on bugs and items in new releases.

We want to use the docker image tag which would be the same value of the running container.

[Example from DockerHub](https://hub.docker.com/layers/civiform/civiform/SNAPSHOT-de47160-1646344687/images/sha256-877cfcdaecb3949878fa4851223120b80bf4e323ceb4d8fb3f66eddc200ec95d?context=explore)

![Tag Info](https://user-images.githubusercontent.com/195162/156813164-2aef7446-c6ac-47be-8428-4f6cf0edc3db.png)

Mock up of the version shown on the page

![Login Form](https://user-images.githubusercontent.com/195162/156813176-70ac62cf-3a5c-464b-93ce-fd604066c548.png)

**Comment by nbeloglazov** [comment]
You can get current version from `<head>` tag:
```html
<head>
  <title>Get benefits — CiviForm</title>
  <link rel="icon" href="https://civiform.us/favicon.png">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="civiform-build-tag" content="SNAPSHOT-e29fbd9-1664481688">
  <link href="/assets/stylesheets/c037e0af10c7ef8cb187e5aa10f06e84-tailwind.css" rel="stylesheet">
</head>
```
Though having it at the bottom would be nicer indeed.
