### ISSUE TITLE
Cleanup for post seattle migration of all Accounts to authority_id

### ISSUE THREAD

**Issue by shanemc-goog** [civiform/civiform#2059]
With the migration from email to authority_id as the Account ID, we need to account for the fact that the Seattle deployment has accounts keyed ONLY with email.

Parts of the code allow for that, even though it should indicate a data error for all subsequent deployments.

This is a tracker bug to be referenced in those code locations that can be cleaned up if/once seattle migrates all it's accounts to have an authority_id

**Comment by goldblatt** [comment]
@gwendolyngoetz or @swatkat1 just adding y'all as FYI maybe worth a convo on this

**Comment by swatkat1** [comment]
According to Shane the possible fixes could be- 
1. Migrate the email only users to use an authority idea (may be trying to build one based on what we know)
2. Delete the accounts that are more than year old and which do not have an authority id.

**Comment by shanemc-goog** [comment]
For #2 we don't need to delete the accounts.

What we'd remove is [this code](https://sourcegraph.com/github.com/civiform/civiform/-/blob/server/app/auth/oidc/OidcProfileAdapter.java?L187&subtree=true) that allows accounts to be keyed off of only email as a last resort. Removing this would effectively orphan the accounts that don't have an authority_id. These would be users that haven't logged in in a year.  When those users log in they would be treated like a new account.

**Comment by elisekalstad** [comment]
@shanemc-goog How many accounts do you estimate it would impact?

**Comment by shanemc-goog** [comment]
I'm not sure, but @gwendolyngoetz or @swatkat1 could look at how many Accounts have a null [authority_id](https://docs.civiform.us/contributor-guide/developer-guide/database/db-schema) value.

Also the change was 8 months ago, so it'd indicate those users who haven't logged in in 8 months (not a year as I previously stated)

**Comment by shanemc-goog** [comment]
For #1

Someone would have to look at examples of authority_ids, but for non-admins as I recall it was something like

iss: ORACLE_SERVER_URL sub: email


if that holds you could set all missing authority IDS to that pattern, using the email that is present.

An issue there may be around the casing of emails.   IIRC for the accounts in question their email may depend on the casing they logged in with, which means if they login with different casing they may have multiple accounts too.   This is something that a sql query could likely determine too.

A caveat on setting the authority_id is that Admins will have a different iss value since they use a different login, so if there's an admin that hasn't logged in in 8 month, this would likely orphan that account as we'd associate it as an applicant login

**Comment by elisekalstad** [comment]
@gwendolyngoetz --How many people have the authority_id value of null?

**Comment by gwendolyngoetz** [comment]
```
 4004   authority_id is null and email is not null        likely old accounts
74457   authority_id is null and email is null            likely guest accounts
 8237   authority_id is not null and email is not null    likely correct accounts
----------------------------------------------------------------------------------
86699 total count
```
