### ISSUE TITLE
Unable to modify default state in Address question type

### ISSUE THREAD

**Issue by carchy-1** [civiform/civiform#2102]
**Describe the bug**
Unable to modify "Default State" value in Address question type. Currently, it only shows Washington (which will not be useful for other civic entities with residents outside of Washington state) or --Leave-- Blank option.

**To Reproduce**
1. Go to 'Questions'
2. Click on 'Create New Question' and select 'Address' question type
3. In the Question settings section, select 'Default State'
4. Washington and Leave Blank are the only options in the drop-down

**Expected behavior**
A listing of all the 50 states and territories to let the Civiform Admin to choose from.

**Screenshots**
![image](https://user-images.githubusercontent.com/98119305/159504413-ca7c021a-6e4d-430c-a233-42ca5302837f.png)
![image](https://user-images.githubusercontent.com/98119305/159504215-ebd716a4-cefb-41b1-a7c5-5053cf653689.png)

**Desktop (please complete the following information):**
 - OS: [ChromeOS]
 - Browser [Chrome]
 - Version [beta]

**Smartphone (please complete the following information):**
N/A

**Additional context**
It should be consistent with the values that get developed for the State field in https://github.com/seattle-uat/civiform/issues/1485

**Comment by bion** [comment]
Should be done at the same time as #1485

**Comment by reemaka** [comment]
It looks like this just doesn't work at all currently. The defaultState field isn't read anywhere. We could fix it or just remove the option completely
