### ISSUE TITLE
Lack of navigation bar when reviewing applications

### ISSUE THREAD

**Issue by carchy-1** [civiform/civiform#2103]
**Describe the bug**
There is no navigation bar when viewing applications. I was unable to navigate to a different program without clicking the 'back' browser button.

**To Reproduce**
1. Login as "Of All Active Programs'  
2. This will take you to the 'Your Programs' screen
3. Click on a program that has Applications
4. Once you are in the 'All Applications" screen for that program, there is no way to navigate back to the 'Your Programs" screen to select a different program, other than to use the browser's 'back' button'
5. Tried clicking on the CiviForm logo but it didn't redirect me away from that page.
6. Similar experience when you login as a "Program and Civiform Admin"

**Expected behavior**
To be able to click on a navigation bar to get back me back to the 'Your Programs' screen (via Programs) or to navigate to a different part of the system. The browser back button should not be the navigation mechanism. 

**Screenshots**
![image](https://user-images.githubusercontent.com/98119305/159510430-1518d933-4daa-45c3-8337-70ff7fe81ef4.png)

**Desktop (please complete the following information):**
 - OS: [ChromeOS]
 - Browser [chrome]
 - Version [beta]

**Smartphone (please complete the following information):**
-N/A

**Additional context**
https://github.com/seattle-uat/civiform/pull/1175 is closed but doesn't seem to be working
Navigation bar proposed in https://github.com/seattle-uat/civiform/issues/1906 should apply throughout.

**Comment by reemaka** [comment]
Not sure when it changed but I can't reproduce this anymore
