### ISSUE TITLE
Add confirmation before discarding question drafts

### ISSUE THREAD

**Issue by kmcnellis** [civiform/civiform#2105]
**Is your feature request related to a problem? Please describe.**
When editing questions, the "discard draft" button is very close to edit.  If you click it by accident, your question might get deleted unexpectadly.

**Describe the solution you'd like**
Prompt for confirmation before deleting.

**Comment by kmcnellis** [comment]
![image](https://user-images.githubusercontent.com/5566205/159567932-384879e3-87d0-4710-9785-0a704ce44913.png)

**Comment by MichaelZetune** [comment]
![Screenshot 2023-02-03 at 12 07 30 PM](https://user-images.githubusercontent.com/30369272/216699575-e31d7a7a-a4bc-4ed6-a08c-dcbe5addf4c3.png)

The original screenshot from this issue is outdated; the new one still has a "Discard Draft" button we should add a confirmation to.
