### ISSUE TITLE
Github status checks we would like

### ISSUE THREAD

**Issue by bion** [civiform/civiform#2184]
This is a meta issue for tracking [Github status checks](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/collaborating-on-repositories-with-code-quality-features/about-status-checks) the dev team would like to implement to improve reliability.

- [x] check that typescript formatting is correct
- [x] check that terraform formatting is correct
- [x] check that python formatting is correct
- [x] check that bash formatting is correct
- [ ] check that style changes (tailwindcss class usages) are correct

**Comment by nbeloglazov** [comment]
@bion what kind of style checks do you have in mind for tailwind?

**Comment by bion** [comment]
@nbeloglazov hard to say, I'm inclined to close this and hold off. Mostly I was thinking that any tailwind classes found in the rendering code refer to actual classes, but I don't think it's realistic.
