### ISSUE TITLE
How do I add shared inbox as program admins?

### ISSUE THREAD

**Issue by elisekalstad** [civiform/civiform#2238]
There are a number of programs that would like to receive email alerts and access applications via a shared inbox. This allows multiple staff to manage applications from the same place. I was able to successfully add 1 shared inbox as a Program Administrator about a year ago (sppapplication@seattle.gov). I am unable to add 2 more shared inboxes now. I tried all different kinds of upper case/lower case scenarios, still now luck. 

Seattle IT took a look at the configuration of the accounts, and they are set up exactly the same way. Is it possible to add shared inboxes as CiviForm Program Admins? 

WORKS:
sppapplication@seattle.gov

DOESN'T WORK:
SCL_InfoEBA@seattle.gov
ridenow@seattle.gov

**Comment by elisekalstad** [comment]
Elise to flag with Kristen/Bion to see how to set up permissions.

**Comment by goldblatt** [comment]
this is like have to have an account to add an admin

**Comment by kristinyim** [comment]
Any help needed on this?

**Comment by elisekalstad** [comment]
I have a pretty chunky work-around for this one (created an outlook rule to forward all CiviForm email alerts to a shared inbox. Specific program staff with admin rights can then open the application link within the email alerts). I talked with Susan about it a few weeks ago. Sounds like early on in CiviForm's life, there was probably a way to sneak in a shared inbox as an admin. Things are tighter now and we cannot add shared accounts/emails as program admins. 

Most city programs already have shared email addresses that are monitored by multiple staff. Is there a way to send the alerts for new applications to a shared inbox? And then access can still be granted via an individual's account?

**Comment by kristinyim** [comment]
Talked to Bion and Susan and based on what the goal is here, we have two options for solutions: 1) If the goal is just for an email to be sent, we can add a feature so that the admin specifies custom email addresses to be notified for a program. 2) If the goal is to grant access to a shared email, we have to allow shared emails that don't have passwords to be added as accounts which is a bit hard. We can chat more about this at our sync today.

**Comment by elisekalstad** [comment]
> Talked to Bion and Susan and based on what the goal is here, we have two options for solutions: 1) If the goal is just for an email to be sent, we can add a feature so that the admin specifies custom email addresses to be notified for a program. 2) If the goal is to grant access to a shared email, we have to allow shared emails that don't have passwords to be added as accounts which is a bit hard. We can chat more about this at our sync today.

Option 1 would satisfy the need perfectly!

**Comment by kristinyim** [comment]
Amazing! This isn't highly prioritized for other cities so its probably best if Seattle engineers take this on if this is high priority for you. Susan said she's happy to consult and point in the right direction.

**Comment by elisekalstad** [comment]
The root of this issue is solved by making it possible for a Program Admin to search within CiviForm for applications by name, email, application ID even if the applicant came in as a guest. See the guest account background: https://github.com/civiform/civiform/issues/4094#issuecomment-1428394537

**Comment by elisekalstad** [comment]
Closing this request since Program Admins can now search within CiviForm for applications (and don't need to rely on emails for managing the application process).
