### ISSUE TITLE
Way to "Off-ramp" residents based on response

### ISSUE THREAD

**Issue by elisekalstad** [civiform/civiform#2264]
There are programs on CiviForm that take in only NEW applicants. If an applicant has already applied, the programs would like a gentle way to re-direct them so that they don't submit another application. 

**Describe the solution you'd like**
The ideal solution would be a way to add a question validation that would route users to an end page that doesn't have the "submit" button, but where the applicant could still find and apply to other programs

**Additional context**
Current flow attached with proposal
[CiviForm_Off Ramp Option.pdf](https://github.com/seattle-uat/civiform/files/8444560/CiviForm_Off.Ramp.Option.pdf)

**Done when**
What conditions need to be met before this issue can be closed?

**Comment by msprenke** [comment]
Deployed with eligability
