### ISSUE TITLE
Gateway timeout for exporting demographic data

### ISSUE THREAD

**Issue by elisekalstad** [civiform/civiform#2267]
**Describe the bug**
I'm logged in as the CiviForm Administrator. I'd like to download an export of all demographic information. I get a "504 gateway timeout" error.

**To Reproduce**
1. Go to CiviForm.seattle.gov
2. Click on Log in as Admin
3. Scroll down to Download Export to CSV

**Screenshots**
Attached
![504 gateway time-out](https://user-images.githubusercontent.com/86082659/162277854-8ba38787-1f3b-4334-9625-d0dfefb1dcfe.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by shanemc-goog** [comment]
Likely similar to #1730, where the data collation is taking too long.

For that I had to optimize the export by removing a redundant lookup done on every row.

**Comment by shanemc-goog** [comment]
@elisekalstad is the action and data you're working with the same as in #1730?

**Comment by elisekalstad** [comment]
@shanemc-goog - Yeah, it's the exact same issue and action and data and everything. Just figure our data is growing :)

**Comment by bion** [comment]
It may be time to make this an asynchronous interaction. There's a couple way that could be presented in the UI, but on the backend this will require us to configure some manner of job runner. Play has a few options for this, there are also open source libraries that could help.

**Comment by bion** [comment]
After a quick look, I think we may be able to improve performance enough here to avoid the background job solution for a while longer.

**Comment by bion** [comment]
@gwendolyngoetz the PR for reducing N+1 queries is out on staging now. It's possible getting it to production will be an adequate fix for the short term. After it's deployed and @elisekalstad has attempted another export please update here with whether this is still an immediate issue.

**Comment by gwendolyngoetz** [comment]
@bion I was able to export the demographics data on 2/3 attempts. The first attempt was the same 504 error.

**Comment by bion** [comment]
@gwendolyngoetz sounds like the performance improvement may have bought us a *little* time. Hopefully this will be enough to get the export done for May 1. If not are you able to temporarily increase the timeout?

**Comment by gwendolyngoetz** [comment]
@bion I should have access, might need to be pointed at the right place though

**Comment by bion** [comment]
@gwendolyngoetz this should do it https://docs.aws.amazon.com/elasticloadbalancing/latest/application/application-load-balancers.html#connection-idle-timeout

**Comment by gwendolyngoetz** [comment]
Not seeing any further errors right now so we will leave the timeout as is unless it becomes a problem.

**Comment by gwendolyngoetz** [comment]
Getting 504's again. @bion  I raised the timeout as outlined in that above aws link, but that resulted in 502's. There's probably something else that needs longer timeout, but I'm not sure what.

**Comment by bion** [comment]
@gwendolyngoetz have you checked the server logs to see if the 502s are coming from the application? If they're not there then it'll be something on the AWS side that needs adjusting.

**Comment by bion** [comment]
This has mostly been resolved by the feature to specify a time range for the export. Closing for now.
