### ISSUE TITLE
Handle azure-storage blob updates to v12

### ISSUE THREAD

**Issue by goldblatt** [civiform/civiform#2290]
Renovate bot has let us know that azure__storage-blob needs to be updated to v12. This is a breaking change and needs to be refactored.

Closed PRs with comments and versions to update:
https://github.com/seattle-uat/civiform/pull/2216
https://github.com/seattle-uat/civiform/pull/2160

**Comment by nbeloglazov** [comment]
Closing this as we are using azure__storage-blob 12.19 now with latest update happend on Sep 19. Seems no longer breaking.

**Comment by melanie-exygy** [comment]
Per @nbeloglazov's comment on Sept. 30, 2022, this issue can be closed.
