### ISSUE TITLE
Page contains more than one h1 tag

### ISSUE THREAD

**Issue by gwendolyngoetz** [civiform/civiform#2325]
This started showing up in the logs after deploying the current docker container to Seattle prod. I'll see if I can track  down if there is a specific page tomorrow

`[[31merror [0m] v.a.ApplicantLayout - Page contains more than one <h1>, which is detrimental to screen readers.`

**Comment by bion** [comment]
@gwendolyngoetz if there's more context for this (i.e. list of pages where it's happening) please add. If it's resolved please close.

**Comment by gwendolyngoetz** [comment]
This isn't showing in the logs for the last two months. Probably was fixed with the A11y work Jeannie did.
