### ISSUE TITLE
Admins can preview program forms in sandbox

### ISSUE THREAD

**Issue by neel-a-mehta** [civiform/civiform#240]
Can "fill in" a program form and "submit it" without anything going to the database. Instead, they can see CSVs/PDFs of what they _would_ have generated.

**Comment by glorialiou** [comment]
Support a “Preview” mode (like Google Forms) for admins for quick validation that content looks as expected.

Currently, there is no quick way to review the user-facing program application before/without publishing. This has led to many versions of CiviForm forms being published during the testing and review process between CF Admin and Program admins, even for minor updates. Frustrating admin experience.

**Comment by kristinyim** [comment]
want a link to preview that admins can send to co-workers for feedback

**Comment by seanmalbert** [comment]
@isabelcshaw and @cassandralfernandes,

This request came from Arkansas recently:
> Is it possible to add a “Preview Form” capability within the CiviForm Admin which allows paging through the screens to review what a form will look like in its entirety. The preview state would not allow any answers to be submitted and would only be used to review each screen for accuracy and useability.

**Comment by nbeloglazov** [comment]
We also have #3080 which I think is talking about the same thing (preview how question/screen looks during building it). Maybe merge them?

**Comment by reemaka** [comment]
Design doc here: https://docs.google.com/document/d/1ACKnO4Z3dU9mAPEx5BnflKqcJ9IeZbbCFCGz2TMVyhE/edit#heading=h.bknox3ib8wpb
