### ISSUE TITLE
Address validation to check that resident lives within City

### ISSUE THREAD

**Issue by elisekalstad** [civiform/civiform#2407]
**Is your feature request related to a problem? Please describe.**
The Fresh Bucks team receives 12,000 applications a year. They are not able to manually verify all 12,000 applicants reside in the City of Seattle, but they can only accept City residents. Is it possible to use the City's GIS webserver to validate current City addresses? 

**Describe the solution you'd like**
If a resident enters a City of Seattle address, they would be able to proceed with the application. If a resident enters a non-City address, they would receive an alert "The address provided is not within City of Seattle limits. You must reside at a City of Seattle address to qualify for this program?" and it would off ramp the applicant so they cannot submit the application. 

**Additional context**
The GIS team provided instructions when the Fresh Bucks team was getting their platform up and running. I included those instructions attached.

**Done when**
A resident receives a notice if they are not eligible based on address. Program staff do not receive applications from people outside the City of Seattle limits.

**Comment by shanemc-goog** [comment]
@elisekalstad for the GIS instructs you say " I included those instructions attached.". I'm not seeing them, can you point out what you mean?

**Comment by elisekalstad** [comment]
@shanemc-goog --Yeah, we deleted it from the attachments since there is City-specific server and database information, just to be careful. I know @gwendolyngoetz is working on this one, I'll check with her to see what can be shared over github.

**Comment by gwendolyngoetz** [comment]
Closing this since it's redundant with the PRD and the tracking issue for the work at #4051
