### ISSUE TITLE
Upgrade Jest monorepo

### ISSUE THREAD

**Issue by bion** [civiform/civiform#2431]
Renovate bot has created an immortal PR to update jest monorepo along with TS-jest. The PR is immortal because it involves two dependencies. It's a major version upgrade so will require making some changes to our Jest (browser test) code.

Since we cannot close the PR without it being reopened, I have marked it as a draft for now.

https://github.com/seattle-uat/civiform/pull/2428

**Comment by gwendolyngoetz** [comment]
Additionally, as of today, the Jest-Playwright module isn't yet compatible with v28

https://github.com/seattle-uat/civiform/pull/2680

**Comment by shanemc-goog** [comment]
Non blocking warnings when running bin/run-browser-tests

```
warning " > jest-playwright-preset@1.7.2" has unmet peer dependency "jest-circus@^26.6.3 || ^27.0.0".
warning " > jest-playwright-preset@1.7.2" has unmet peer dependency "jest-environment-node@^26.6.2 || ^27.0.0".
warning " > jest-playwright-preset@1.7.2" has unmet peer dependency "jest-runner@^26.6.3 || ^27.0.0".
```

**Comment by gwendolyngoetz** [comment]
Jest-playwright now supports Jest v28. We should try upgrading again.

**Comment by kmcnellis** [comment]
Looks like the PR is merged
