### ISSUE TITLE
Design Doc & Scoping for Status Tracking 

### ISSUE THREAD

**Issue by goldblatt** [civiform/civiform#2453]
We need a design doc and scoping work done for the status tracking feature

**Comment by shanemc-goog** [comment]
Waiting on a PRD :D

**Comment by cassandralfernandes** [comment]
Here is the [PRD](https://docs.google.com/document/d/1TbG2rGD2sI5EpaEKH4rYD2okpJOO5EKZEYlPZ62jOns/edit?resourcekey=0-MC8VRf_JN0BpjwQiBIJqlQ#heading=h.wm8dmtm3jyp0) and [design doc](https://docs.google.com/document/d/1qOMs9x3yfUFCHirwseWiY9Iu-W1utn-hDdXpXJowtNk/edit?resourcekey=0-t-MYyT9nYHZ54HjMad2jzA#heading=h.xc9pjhpu4y1q)
