### ISSUE TITLE
(azure) Consider writing a script to make key vault tear down faster

### ISSUE THREAD

**Issue by jeanniefu** [civiform/civiform#2500]
When running the terraform destroy command ([doc](https://docs.civiform.us/contributor-guide/developer-guide/dev-azure#tearing-down)), it takes a while to destroy the key vault. We should evaluate whether we want to write a script to do it smarter/faster.

**Comment by jeanniefu** [comment]
Probably not worth the effort yet since we are planning on only using AWS for now

**Comment by cassandralfernandes** [comment]
Closing this issue as we don't have plans to use azure in the near future
