### ISSUE TITLE
AWS Terraform Deploy

### ISSUE THREAD

**Issue by goldblatt** [civiform/civiform#2511]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional context**

**Done when**
What conditions need to be met before this issue can be closed?

**Comment by azizova-leyla** [comment]
Plan of action:
1. Write terraform to bring staging env on aws. Similar to azure staging.
2. Write necessary scripts to automate parts that are not in terraform
3. Copy&adapt tests from https://github.com/civiform/staging-azure-deploy
4. Make a version with Bloomington setup (auth providers) to mirror as closely as possible their prod setup.
5. ...
6. Success!

**Comment by azizova-leyla** [comment]
Marking this is done. It works =) future improvements are tracked separately.
