### ISSUE TITLE
Admin program list view has N+1 behavior for checking program admin authorization

### ISSUE THREAD

**Issue by clouser2** [civiform/civiform#2582]
**Describe the bug**
PR feedback from #2568. We loop through each program and check user authorization for each program, which may result in N+1 queries ([code](https://github.com/seattle-uat/civiform/blob/b64946155fd3a72db1d76471ebe01283762fabb6/server/app/views/admin/programs/ProgramIndexView.java#L302)). This bug tracks confirming that the N+1 query behavior does in fact exist (i.e. confirm that EBean isn't caching the results from the previous query) and fixing it if necessary.

**Comment by shanemc-goog** [comment]
Just a note, be careful about the distinction between the CiviForm/Global Admin who has access to everything and Program Admins who have access to specific programs.

**Comment by clouser2** [comment]
Good point. Ideally any of that distinction would be wrapped up in `CiviFormProfile.checkProgramAuthorization`. That's something to confirm as part of this workstream as well.

**Comment by bion** [comment]
wontfix, not causing a problem currently
