### ISSUE TITLE
Remove Seattle-specific applicant support page

### ISSUE THREAD

**Issue by gwendolyngoetz** [civiform/civiform#2586]
~~I came across the [UnconfirmedIdcsEmailBugView.java](https://github.com/seattle-uat/civiform/blob/main/server/app/views/support/UnconfirmedIdcsEmailBugView.java) file and it's got hard coded text for people to contact Seattle with phone and email address. We probably want to make this configurable so it can be customized for other cities.~~

We should investigate to see if this can/should be generalized.

**Comment by shanemc-goog** [comment]
The file you found is a pretty Seattle specific issue that we may want to generalize as part of this bug.

It can only be triggered by Seattle users due how Seattle login team manages unconfirmed users.  So those specifics wouldn't translate to another deployment.

**Comment by gwendolyngoetz** [comment]
Oh that interesting. I'll leave this open so it can be investigated further.

**Comment by kristinyim** [comment]
Going to leave this for Seattle to clean up, changing the label to seattle-backlog

**Comment by shanemc-goog** [comment]
Here's the original [Issue](https://github.com/seattle-uat/civiform/issues/1824#issuecomment-1016940563), the [PR](https://github.com/seattle-uat/civiform/pull/1771) that added this, and the [call site](https://github.com/seattle-uat/civiform/blob/1fa37bbf7cb5425f7157256778c902a9cbb1675b/server/app/filters/ValidAccountFilter.java#L40) that triggers it.

**Comment by msprenke** [comment]
@gwendolyngoetz to pull stats for review on those who would be affected

**Comment by elisekalstad** [comment]
@gwendolyngoetz -- Are you working on this? Should we move this to "In Progress"? "Ready for Dev"? Still necessary?

**Comment by gwendolyngoetz** [comment]
@elisekalstad I added logging to monitor if tit was ever actually being called. Then I forgot about it. I need to review the logs to see if I can remove this.
