### ISSUE TITLE
Enumerator remove button aria-label should include which item it is removing

### ISSUE THREAD

**Issue by jeanniefu** [civiform/civiform#2625]
Feedback from a11y experts during an a11y audit.

Severity (Critical/Serious/Moderate/Good to have): Good to have

In the below screenshot, we should add an aria-label to associate the "Remove child" button with which child it is removing. 
<img width="1270" alt="Screen Shot 2022-06-01 at 6 20 13 PM" src="https://user-images.githubusercontent.com/9094240/171527760-66709e2d-b469-4c79-ae13-fbbd7a433d9e.png">

Note that since the html is created serverside, we may not be able to easily grab the actual value (e.g. `aria-label="Remove child, Jeannie"`). There is a related issue for adding an index to the enumerator label: https://github.com/seattle-uat/civiform/issues/2624. If that issue is fixed, we can do something like `aria-label="Remove child, child #1"`.

See the application review page for an example. We have an aria-label for the edit buttons to associate the button and question:
<img width="1454" alt="Screen Shot 2022-06-01 at 6 30 14 PM" src="https://user-images.githubusercontent.com/9094240/171528184-8bc091c6-994e-49f2-ba76-496624e4983f.png">

**Comment by caitlinshk** [comment]
It looks like the remove buttons now have #1, #2, etc in them thanks to the fixes in https://github.com/civiform/civiform/issues/2624. So, maybe this can be marked as fixed?

![8f3XmmQFEfvibEL](https://github.com/civiform/civiform/assets/147177873/751aaa37-f3ea-4f6d-b057-4be37bda97d7)
