### ISSUE TITLE
Buttons collide with text on application review page at 400%

### ISSUE THREAD

**Issue by jeanniefu** [civiform/civiform#2626]
Feedback from a11y experts during an a11y audit.

Severity (Critical/Serious/Moderate/Good to have): Serious

At 400% page the page should allow for reflow. See below resource link for more information on reflow. 
<img width="716" alt="Screen Shot 2022-06-01 at 6 42 51 PM" src="https://user-images.githubusercontent.com/9094240/171529350-2d56fdea-5c6b-46ad-a04f-3187689e94d3.png">

How to reproduce (chrome):
* Right click > Inspect
* Toggle device toolbar
* Create custom of 320 x 700
  * Dimensions > Edit > Add custom device...
  * Choose width 320, height 700
  * Choose user agent string "Desktop"
* Select your new custom device dimensions

Note that because of variations in resolution, default settings, etc. the recommended way to simulate 400% zoom is to set the width to 320 pixels, instead of actually zooming in to 400%. From the below link, "320 CSS pixels is equivalent to a starting viewport width of 1280 CSS pixels wide at 400% zoom."

Resources: 
* https://www.w3.org/WAI/WCAG21/Understanding/reflow.html

Related issue: #2627

**Comment by nbeloglazov** [comment]
Fixed in https://github.com/civiform/civiform/pull/2874
