### ISSUE TITLE
Change "Upload" to " Save and Next" in Bloomington CiviForm

### ISSUE THREAD

**Issue by jessborland** [civiform/civiform#2645]
Pages in CiviForm: 
1) Proof of Household Income 
2) Proof of Monroe County Residency 

Issue:
Participants were confused about "Choose File" versus "Upload".

Recommendation: 
Change "Upload" to "Save and Next" to match the rest of the application. Leave "Choose File" as is.

**Comment by jeanniefu** [comment]
+1 - We received this same feedback from a UXR with a screenreader user.
