### ISSUE TITLE
Change Format for Uploaded File 

### ISSUE THREAD

**Issue by jessborland** [civiform/civiform#2646]
Pages on Bloomington CiviForm: 
1) Proof of Household Income 
2) Proof of Monroe County Residency 

Issue: 
It was also hard for participants to see when their file was uploaded.

Recommendation: 
When the file is uploaded, make the font bigger, bolder, or a different color so that the user can identify it quickly.

**Comment by goldblatt** [comment]
assigning to @rahaghas to think about what this would look like; also would note might want to look at what the a11y audit @jeanniefu said about this page to see if we can consolidate any efforts there!

**Comment by goldblatt** [comment]
might want to consider taking a deeper look at file upload experience & @bion has some context on file upload

**Comment by jeanniefu** [comment]
Re: a11y, we actually did not get any specific feedback for the file upload page

**Comment by melanie-exygy** [comment]
The file upload styles have been updated as part of the North Star.
