### ISSUE TITLE
Allow questions to NOT share data across programs

### ISSUE THREAD

**Issue by jessborland** [civiform/civiform#2649]
Issue: When the participant reviewed their second application, their consent was automatically approved based on previous application. 

Recommendation: Remove automatic consent approval and ask the user to give consent for each individual application.

**Comment by azizova-leyla** [comment]
This is a more generic issue of us always sharing the data. In some cases it would make sense to ask the question again in a new program. Consent is one example, re-application is another - applicants might need to re-verify their status if they are applying yearly.

**Comment by cassandralfernandes** [comment]
Duplicate, closing in favor of #1575

**Comment by nbeloglazov** [comment]
Closing as dup as per [#issuecomment-1223392370](https://github.com/civiform/civiform/issues/2649#issuecomment-1223392370)
