### ISSUE TITLE
Update Admin navbar UI

### ISSUE THREAD

**Issue by clouser2** [civiform/civiform#2651]
As part of ongoing UI work with the Program Admin UI, we'll want to update the navbar consistently based on the mocks from https://github.com/seattle-uat/civiform/issues/1906#issuecomment-1106881407.

#1906 addressed the usability issue of highlighting the active nav tab.

**Comment by Lz-01** [comment]
assign this issue to me.

**Comment by nbeloglazov** [comment]
Hi @Lz-01 

Feel free to join our [slack channel](https://docs.civiform.us/governance-and-management/governance/communication#slack-channels) where we discuss project-related things and generally sync. Also it's a good place to ask questions if you have some issues with development setup. If you feel like it - please introduce yourself on #introductions channel.

As for working on this issue - sure, assigning it to you.

**Comment by dkatzz** [comment]
This seems to have been completed, so closing.
