### ISSUE TITLE
Log email content in dev mode

### ISSUE THREAD

**Issue by shanemc-goog** [civiform/civiform#2716]
Email is not testable outside of prod instances.  It _should_ be working in staging, but practically doesn't seem to be, and there's no mechanism for local dev.

We should at least log the email in dev mode for easy of local development.

**Comment by goldblatt** [comment]
if this happens with a higher prio issue seems good, on it's own we marked as p2

**Comment by shanemc-goog** [comment]
It'll be necessary for Status Tracking as that will send emails, so I plan on doing it to support that

**Comment by nbeloglazov** [comment]
@shanemc-goog this issue should have been closed by #3330?

**Comment by shanemc-goog** [comment]
Emails can be dev tested via https://docs.civiform.us/contributor-guide/developer-guide/dev-testing#email
