### ISSUE TITLE
Status Tracking: Create CiviForm Admin configuration update handler

### ISSUE THREAD

**Issue by shanemc-goog** [civiform/civiform#2751]
Create a handler that takes the status configuration specified by the CiviForm Admin in the UI and saves it to the current Program Draft revision.

Note:

Statuses don't have a first-order representation, they're effectively just a "bag of strings".  Whatever the Admin enters is the configuration, including manually moving content around.

However, given we need to support translations of this content (#2754) we could be a little clever in not losing translations after the fact.  This could be done by, for instance trying to fuzzy match new statuses against the "about to be overwritten" ones and preserving the translation for any matches.  A normalization system could be the sluggifier we use for program names etc.

**Comment by shanemc-goog** [comment]
This is done right? can you link the PR?

**Comment by clouser2** [comment]
Fixed with #2938.
