### ISSUE TITLE
Status Tracking: Create Program status configuration UI

### ISSUE THREAD

**Issue by shanemc-goog** [civiform/civiform#2752]
- [x] Somewhere in the Program editor, provide an area to add/remove/edit statuses. Mocks TBD
- [ ] Upon clicking a Submit button send the configuration to the handler in #2751 

Note: This should be gated on the Status Tracking Feature Flag.  All other status tracking features will trigger based on their being status configuration and not on the feature flag also; so this will serve as the main control for enabling statuses.

**Comment by clouser2** [comment]
The main work here is complete with assorted TODOs to clean up.
