### ISSUE TITLE
Refactor to better handle lists of FieldWithLabel instances in newer j2html 1.5.0

### ISSUE THREAD

**Issue by syntapy** [civiform/civiform#2764]
**Describe the change needed**

FieldWithLabel can be used to create multiple types of html tags. There are lists of FieldWithLabel types in 
- [QuestionTranslationView](https://github.com/seattle-uat/civiform/blob/main/server/app/views/admin/questions/QuestionTranslationView.java)
- [ProgramTranslationView](https://github.com/seattle-uat/civiform/blob/main/server/app/views/admin/programs/ProgramTranslationView.java)
- [TranslationFormView](https://github.com/seattle-uat/civiform/blob/main/server/app/views/admin/TranslationFormView.java) 

In [one place](https://github.com/seattle-uat/civiform/blob/3b1df04afabcd3807af08f15655b5efc00a16d7d/server/app/views/admin/TranslationFormView.java#L88) these are iterated through to create a list of tags

Using the old j2html 1.4.0 all types of html tags have the same java type (Tag or ContainerTag), but in the [new version](https://github.com/seattle-uat/civiform/pull/2281) there will be a unique java type for each html tag type

This means the `FieldWithLabel` can have multiple final tag getters (`getInputTag()`, `getRadioTag()`, `getCheckboxTag()` etc...) as opposed to the one `getContainer` method in the old version, and hence can return multiple java types

As such this [line](https://github.com/seattle-uat/civiform/blob/3b1df04afabcd3807af08f15655b5efc00a16d7d/server/app/views/admin/TranslationFormView.java#L88) mentioned above can be potentially problematic since that method does not have any knowledge of whether each element in the list is e.g. to be generating an `input` or `radio` or `textarea` tag type etc...

Granted, at the time of this report, only `input` types were being generated by elements in lists of FieldWithLabel, so just using `.getInputTag()` for now will suffice

**Comment by nb1701** [comment]
If this becomes a problem in the future, we'll address it then.  Working on cleaning up our tech debt, so closing this issue for now.
