### ISSUE TITLE
Update URL when applicant selects create account

### ISSUE THREAD

**Issue by elisekalstad** [civiform/civiform#2864]
**Describe the bug**
There is an unnecessary step for residents when they try to create an account. It would remove confusion (and an extra step!) to update the link for "Create account" to go directly to https://login.seattle.gov/#/registration?appName=CIVIFORM

**To Reproduce**

1. Go to 'Create Account'
2. Click on 'Don't have a profile? Register
3. Complete registration

**Expected behavior**
Residents should be able to:
1. Go to 'Create Account'
2. Complete registration (they should not need to click "Don't have a profile? Register" we already know they need to create an account)

**Screenshots**
Attached
[Create Account_extra step.pdf](https://github.com/seattle-uat/civiform/files/9074640/Create.Account_extra.step.pdf)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kmcnellis** [comment]
I think this is just a configuration change

**Comment by kmcnellis** [comment]
I think this is just a configuration change @gwendolyngoetz or @swatkat1 is this something you have the ability to change?

**Comment by msprenke** [comment]
This appears to be the same as #3790 and is a part of release 1.8.3
