### ISSUE TITLE
Reset database between browser tests in a single run

### ISSUE THREAD

**Issue by jeanniefu** [civiform/civiform#2891]
Some browser tests call `dropTable()` before each test case: [code](https://github.com/seattle-uat/civiform/blob/9a42804c84531f87117f7cb12b7fde211f1a8fe2/browser-test/src/application_download.test.ts#L19-L23)

We also globally delete the database before an entire test run using globalSetup: [code](https://github.com/seattle-uat/civiform/blob/9a42804c84531f87117f7cb12b7fde211f1a8fe2/browser-test/jest.config.js#L7). (Can consider changing this to [setupFiles](https://jestjs.io/docs/configuration#setupfiles-array) if we want to clear between runs)

In an ideal state, each test case should be hermetic (database updates in one test should not be able to affect the state of another test), so we should clear the database between each test case. In a less than ideal but better than what we have state, we could clear the database between each test suite.

We should evaluate the performance of now vs. clearing DB between test suites vs. clearing DB between test cases. Unknown how much time clearing DB takes.

**Comment by nbeloglazov** [comment]
While migrating tests to TestContext became a bit more familiar with existing tests. Some tests fill db with some data (questions, applications) and `beforeAll` and then each test case relies on that data being available. Migrating those tests to do it in `beforeEach` has pretty bad performance hit. For example some tests go from 20s to 100s. So we need to come up with an efficient way to prepare and share DB state between test cases.

As I see we have 2 separate but somewhat related problems:
1. Quickly seed DB with data for a test. Currently we do it by clicking through UI and it's kinda slow.
2. Share seeded DB between test cases.

For (1) we could do something like sending JSON with data and saving it to DB. But I don't think we can fully get rid of manually clicking through UI to prepare the desired initial DB state for a test. 

For (2) we could do something along `dev-dump`, `dev-restore-db` scripts: introduce a new TS function `prepareDB` that users can call and pass callback that builds necessary DB state. This callback will be ran once, in `beforeAll` and DB state is saved somewhere. Then in `beforeEach` that state will be restored. That way we can be sure that test cases don't affect each other as each test cases gets a new DB state. So test fill look something like:

```ts
describe('some test', () => {
  const ctx = createTestContext()
  
  describe('some specific scenario', () => {
    prepareDb(async () => {
      const {adminQuestions, adminPrograms} = ctx
      adminQuestions.createQuestion(...)
      adminQuestions.createQuestion(...)
      adminPrograms.createProgram(...)
    })

    it('check question', async () => {
      // verify that applicant can fill question
    })
    
    it('check invalid values', async () => {
      // verify that applicant can't submit invalid values
    })
  })
})
```

**Comment by gwendolyngoetz** [comment]
Done a while ago
