### ISSUE TITLE
Failure to upload code coverage report shouldn't mark the "run unit tests" action as failed

### ISSUE THREAD

**Issue by clouser2** [civiform/civiform#2901]
Perhaps we want this behavior, but I've empirically seen transient failures uploading code coverage even when all of the unit tests passed (https://github.com/seattle-uat/civiform/runs/7344962435?check_suite_focus=true).

Could we either 1) make this failure still consider the overall action as successful or 2) add retries?

Initially assigning to @swatkat1 for triage / determining if either option is feasible or worth prioritizing.

**Comment by clouser2** [comment]
Additional note: Retrying the failed task typically succeeds, but adds a few minutes of latency to the overall process.

**Comment by elisekalstad** [comment]
@swatkat1 --Is this still open?

**Comment by swatkat1** [comment]
@elisekalstad - This is no longer an issue. It was an issue with the previous version of Codecov. Also I have made ccodecov as informational only so it shouldn't break the build. This item can be closed.
