### ISSUE TITLE
Allow Specified User To Be In Multiple Roles

### ISSUE THREAD

**Issue by gwendolyngoetz** [civiform/civiform#2904]
**Is your feature request related to a problem? Please describe.**
CiviForm admins are unable to access all the same resources as a Program Admin. If you are a CiviForm admin you can't be added as a Program Admin at the same time. This is by design. 

There is a case when some people (such as selected developers) might need access to both.

One example of a difference
![image](https://user-images.githubusercontent.com/195162/179088868-ea7b3889-569f-42b7-9930-441be8a48440.png)

**Describe the solution you'd like**
Provide a way to specify that a user can be both a CiviForm Admin and Program Admin

**Additional context**
Further discussion is needed on the best solution. Adding a token to ADFS/IDCS was mentioned, but may need more research

**Comment by nbeloglazov** [comment]
@gwendolyngoetz this is done since CiviForm admins can now be also have Program admin rights?

**Comment by gwendolyngoetz** [comment]
Yes
