### ISSUE TITLE
Handle RDS password secretly

### ISSUE THREAD

**Issue by azizova-leyla** [civiform/civiform#2918]
Terraform doesn't allow to connect to secret manager directly.
One option: create instance with a temp password, switch it manually to use secrets manager (aws has native support for it)

**Comment by azizova-leyla** [comment]
There's a way to create db password via [aws cli](https://docs.aws.amazon.com/secretsmanager/latest/userguide/reference_secret_json_structure.html), explore if we can chain it in our scripts:
1. [terraform] Create DB with temp password
2. [aws cli] Create DB secret with a new password (
3. [terraform] Use data to import DB secret and pass it to Fargate

**Comment by nbeloglazov** [comment]
Spent few hours reading about. You are talking about rotating database password, right? It seems quite complicated. Essentially we need to create and manage a lambda function which will do the rotation of the password (generating new password and updating it in secret manager) and then logging in postgres and changing passwords there. And it requires a bit convoluted VPC settings. I actually hasn't been able to fully make it work even from AWS web console (lambda function is timing out). Here is the terraform-specific tutorial that matches my understanding of how to do it as well: https://advancedweb.hu/how-to-set-up-amazon-rds-password-rotation-with-terraform/ 

Also we wouldn't need to generate new password. We generate DB credential once, with a temp password and then enable rotation. Once rotation is enabled - it will update the password for us. And maybe it will run rotation immediately as well, upon applying terraform changes.
