### ISSUE TITLE
Format emails in static text properly

### ISSUE THREAD

**Issue by azizova-leyla** [civiform/civiform#2929]
Currently [TextFormatter](https://github.com/seattle-uat/civiform/blob/main/server/app/views/components/TextFormatter.java) recognizes something@email.com as a URL.
Resulting href is https://something@email.com.
We want it to me mailto:something@email.com.

**Comment by reemaka** [comment]
Emails are now formatted as plain text after https://github.com/civiform/civiform/pull/4117. We can consider further updating it to mailto in the future.

**Comment by dkatzz** [comment]
Closing, since the initial issue was resolved. If we want to add a mailto link, we can open a separate issue.
