### ISSUE TITLE
TextFormatter treats anything with a dot as url

### ISSUE THREAD

**Issue by azizova-leyla** [civiform/civiform#2930]
https://github.com/seattle-uat/civiform/blob/main/server/app/views/components/TextFormatter.java 
We use this in static questions and it would create a link for anything "something.something".
This is especially bad for emails with a dot like "name.last@email.com" because it would generate two links for two parts of the email.

**Comment by cassandralfernandes** [comment]
Leyla to spend a bit of time investigating. Potential workaround by linking to contact us page instead of including an email
