### ISSUE TITLE
Cloud SQL DB should force SSL

### ISSUE THREAD

**Issue by bion** [civiform/civiform#2936]
- [ ] The Cloud SQL [database instance](https://github.com/seattle-uat/civiform/blob/main/cloud/gcp/modules/database/main.tf#L28-L39) should require all connections to use SSL (require_ssl attribute).

**Comment by nbeloglazov** [comment]
Closed it as we are not planning to support GCP in short-term. And when we do - likely we'll file new issues based on AWS configuration.
