### ISSUE TITLE
CiviForm Admin UX: Remove "What is the purpose of this screen..."

### ISSUE THREAD

**Issue by cassandralfernandes** [civiform/civiform#3025]
**Is your feature request related to a problem? Please describe.**

"What is the purpose of this screen? Add a description that summarizes the information collected" should not be visible in the sample question preview when the user leaves that part blank

**Describe the solution you'd like**
Remove "What is the purpose of this screen? Add a description that summarizes the information collected." when the field is blank.

**Additional context**
From Admin UXR feedback sheet 

**Screenshot**
<img width="1615" alt="Screen Shot 2022-08-02 at 3 46 11 PM" src="https://user-images.githubusercontent.com/99513234/182486261-95d6b053-563f-4050-82ce-d409bf084493.png">

**Comment by clouser2** [comment]
The default screen shown when creating a new program uses "Screen 1 description" when it renders the screen builder. When a new screen is added (using the "Add Screen") button, the text shown above renders, which is definitely surprising.

I believe that text was intended to draw the admin in to edit the existing text, but there's no real need for them to.

At the very least, we should be consistent. Based on this issue, I propose we:
  * Set the description to "Screen XY description" upon adding a new screen, consistent with what we do for the first screen
  * Change the button to "Edit screen name and description"

If we find discoverability to be an issue in the future, we can look into different ways to tackle that.
