### ISSUE TITLE
CiviForm Admin UX: Update the question options in the question preview as a user adds them

### ISSUE THREAD

**Issue by cassandralfernandes** [civiform/civiform#3026]
**Is your feature request related to a problem? Please describe.**
When creating a question, the preview on the side shows "sample question option" even thought user has typed in "yes"

**Describe the solution you'd like**
Update the question options in the question preview as a user adds them (see screenshot)

**Additional context**
From admin uxr sheet 

**Screenshot**

<img width="1615" alt="Screen Shot 2022-08-02 at 3 49 24 PM" src="https://user-images.githubusercontent.com/99513234/182486594-5aaedae9-8133-461f-9c7f-beb94b4d954a.png">

**Comment by clouser2** [comment]
I'll take a look. I also noticed that the enumerator question's "Add" button throws an error in the console when clicked. We should probably fix that up as well so that the applicant experience can be better previewed in this case.
