### ISSUE TITLE
CiviForm admin UX: hide question bank and add "add question" button 

### ISSUE THREAD

**Issue by cassandralfernandes** [civiform/civiform#3030]
**Is your feature request related to a problem? Please describe.**
When creating a program, the CiviForm admin is confused/overwhelmed by the long list of questions in the question bank 

**Describe the solution you'd like**
Do not show the question bank on the "manage questions" page when a user first lands on the page. Instead, add a button that says "add question" to each page. When a user clicks the button, then the question bank appears 

**Additional context**
From admin UXR feedback sheet

**Screenshot**
(ignore the "allow user to reorder question" text on the screenshot. That's github issue #1928 )
<img width="1662" alt="Screen Shot 2022-08-02 at 3 59 06 PM" src="https://user-images.githubusercontent.com/99513234/182487638-9b3464cf-94b0-463d-8a46-2c8563f62e79.png">

**Comment by cassandralfernandes** [comment]
mock [here](https://docs.google.com/presentation/d/15fcq3dYFgy1Dfy2UjZybmHD9KIW5cz8Q1BjwgOpLJ7g/edit#slide=id.g13ec4604693_0_42)

**Comment by nbeloglazov** [comment]
@cassandralfernandes did you come up with some mocks for this issue?

**Comment by rahaghas** [comment]
So the linked mock from a few comments ago still works, just in terms of interaction, every time a new question is added, the side panel should stay open and allow for multiple questions to be added at a time until the panel is dismissed. Every time "Add" is selected, the button would change to say "Added" and look like this:
<img width="611" alt="Screen Shot 2022-10-03 at 4 27 38 PM" src="https://user-images.githubusercontent.com/103459221/193675887-bbd0761b-1dd2-4d37-b3b6-68b658fa7e16.png">
