### ISSUE TITLE
CiviForm admin UX: update layout of questions tab

### ISSUE THREAD

**Issue by cassandralfernandes** [civiform/civiform#3033]
**Is your feature request related to a problem? Please describe.**
The question list on the questions tab does not have the same layout as the programs tab and it is confusing 

**Describe the solution you'd like**
Update question list to be consistent with the program list UI. Draft and active should be two separate list items within the card

**Additional context**
From admin UX feedback sheet

<img width="1659" alt="Screen Shot 2022-08-02 at 4 11 01 PM" src="https://user-images.githubusercontent.com/99513234/182490894-f32fb9c3-5318-4faf-9bae-8349afeacfb5.png">

[Mock](https://docs.google.com/presentation/d/15fcq3dYFgy1Dfy2UjZybmHD9KIW5cz8Q1BjwgOpLJ7g/edit#slide=id.g13ec4604693_0_182)

**Comment by cassandralfernandes** [comment]
mock [here](https://docs.google.com/presentation/d/15fcq3dYFgy1Dfy2UjZybmHD9KIW5cz8Q1BjwgOpLJ7g/edit#slide=id.g13ec4604693_0_182)

**Comment by nbeloglazov** [comment]
@cassandralfernandes so this bug is no longer about just updating text, but rather redoing question layout to have 2 items as in the mock, right?

**Comment by cassandralfernandes** [comment]
Yes, that's correct

**Comment by cassandralfernandes** [comment]
@nbeloglazov I took another look at this issue and realized the screenshot in the original issue is confusing. I wanted to confirm the changes are: 
-Change new version to edit 
-Add 3 dot menu with the other options 
-Add labels for active or draft 

Am I missing anything else?  

![Image](https://user-images.githubusercontent.com/99513234/186044036-4a3863fb-3ea9-484d-b905-d48e916c2a9f.png)

**Comment by nbeloglazov** [comment]
Do we still need "view" button? With the proposed change the "View" button will go under 3-dot menu. At which point it's somewhat hidden and "Edit" remains the main action. Users can use "Edit" to view the question as well, just no save it or click "back" to exit.

**Comment by cassandralfernandes** [comment]
I think we can remove the view button. Gut check @rahaghas - what do you think? 'View' gives the same view as edit

**Comment by rahaghas** [comment]
We don't need to view button, but I would make the whole row clickable as a way to "view" the question and that can also just go to the edit page. People who want to view the question won't expect to have to click on "edit" to do so, but clicking the list item is intuitive.

**Comment by nbeloglazov** [comment]
Accidentally closed it.

**Comment by nbeloglazov** [comment]
@rahaghas @cassandralfernandes 
One case that, I think, should be exposed in UI is question deletion. Today you can mark a draft question that's not used in any program as "to be archived". And then, when you publish all programs and questions, that "to be archived" question becomes fully archived and disappears from the list of questions.

Should we indicate draft questions that are in status "to be archived" in UI somehow? Currently you can see it only by clicking on triple-dot menu and there you see either "Archive" or "Restore archived" buttons that indicate current question status.

**Comment by nbeloglazov** [comment]
And another question about what fields do we show in the question tab. Today we show 4 different fields: question name, admin note, question text and question help text:

<img width="1433" alt="image" src="https://user-images.githubusercontent.com/252053/188753890-5a7e6e8d-793e-4b26-90f2-08b5bb8651c3.png">

In the mock I see only 3 fields: question text, question help text and admin note. The fourth field, question name, is missing from mocks. Should it be hidden? I'm guessing rationale here is that "quesiton name" and "question text" are often/always duplicate each other semantically. 

@rahaghas @cassandralfernandes

**Comment by rahaghas** [comment]
It should be hidden because we are consolidating it into admin note

**Comment by nbeloglazov** [comment]
@rahaghas  Sorry, I didn't fully understand it. We are planning to remove "question name" field fully in future leaving only "question text" and telling admins to put any info into "question description" which is admin notes?

**Comment by rahaghas** [comment]
**Ideal interaction:** I think all questions should offer the ability to archive. If the question is used in a program, it should pop up a confirmation dialog explaining that archiving this question will result in it being removed from the programs it's used in. Any programs that are archived can then be accessed by creating a filter at the top of the page that allows you to see all active/draft questions only in the default, or select to only see archived questions.

Let me know if this seems infeasible.

**Comment by rahaghas** [comment]
The admin-specific inputs which today are under "info" are to be consolidated into one input called admin note, making the second column now the first.

**Comment by nbeloglazov** [comment]
Hm. Replacing "question name" and "question description" with a new "admin note" field is a bigger task as it requires redoing database schema as today we use "question name" a lot throughout the app. What do you think if we keep displaying both fields for now and add draft/active rows? Doing it step by step.

Though it might be annoying to users if we gradually change UI rather than in one release.

**Comment by clouser2** [comment]
FYI, the workstream to try and reduce the number of "names" a user is editing is tracked here: https://github.com/civiform/civiform/issues/3075

**Comment by rahaghas** [comment]
I think for now we can keep the two inputs while still visually showing them close to how we have it in the mock, right?Admin note would just be everything under "info" for the time being until we consolidate

**Comment by nbeloglazov** [comment]
@rahaghas if we add "question name" to admin note then it will look something like that: 
![image](https://user-images.githubusercontent.com/252053/189221982-9ca9aa9d-0521-4b09-8331-7288aeed6418.png)

Does that look reasonable?

**Comment by rahaghas** [comment]
Yes!  any chance that for the scenario where there is both active and draft states that the note come below active instead of next to it?

**Comment by rahaghas** [comment]
Still keeping it fully left-aligned

**Comment by nbeloglazov** [comment]
Fixed in https://github.com/civiform/civiform/pull/3449
