### ISSUE TITLE
Docs: Debugging local browser tests is rough 

### ISSUE THREAD

**Issue by shanemc-goog** [civiform/civiform#3058]
https://docs.civiform.us/contributor-guide/developer-guide/testing#debugging-browser-tests

These steps aren't sufficient, perhaps based on changes since they ran.

1. Installing node.js / npm isn't documented (Can just do it from the node site
1. You have to run run-browser-tests-local from browser-tests which ends up looking like `../bin/run-browser-tests-local`, further that script wants to be run from the root and gives an error `line 5: bin/lib.sh: No such file or directory` though it keeps working.
1. There's no general usage steps in the debugger such as how to set breakpoints, or if that's even possible, navigating the code run, etc

**Comment by nbeloglazov** [comment]
The step 2 should have been fixed by the PR where Timmy added screenshots.

**Comment by nb1701** [comment]
Look into playwright docs for debugging, see if we need to mess with timeouts, more docs around setting up things for playwright.
