### ISSUE TITLE
Old versions of program forms should not be available to "continue" when logged in

### ISSUE THREAD

**Issue by elisekalstad** [civiform/civiform#3067]
**Describe the bug**
When I log into CiviForm, I am able to continue completing old versions of forms. For example, the Utility Discount Program form shows up 3 times under my "Continue" list. 2 of those forms are outdated versions. It could cause an applicant to submit an application that is no longer valid.

**To Reproduce**

1. Login to CiviForm
2. View programs under the "Continue" list
3. See duplicate and out-dated versions of the forms

**Expected behavior**
I would expect a resident to be able to continue working on only the most recent version of a program form.

**Screenshots**
attached--showing the "logged in" view and the correct view as a guest.
[Old versions available to continue if logged in.pdf](https://github.com/civiform/civiform/files/9270505/Old.versions.available.to.continue.if.logged.in.pdf)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by cassandralfernandes** [comment]
@gwendolyngoetz The line about the Utility Discount Program form showing up 3 times under the "Continue" list -- is that related to #2969? 

@elisekalstad Let's talk more about this issue in our meeting later today

**Comment by gwendolyngoetz** [comment]
Yes, the reason there were three showing up was because there were multiple active drafts for that program. Should be fixed now.
