### ISSUE TITLE
Translate "1 of 5" text

### ISSUE THREAD

**Issue by jeanniefu** [civiform/civiform#3068]
We use this text to indicate which screen number out of the total number of screens the applicant is on. This text is used in at least two places and is hardcoded. We should move it into the messages API and get it translated.

In the UI here:
![Screen Shot 2022-08-05 at 10 49 36 AM](https://user-images.githubusercontent.com/9094240/183132912-4d79cd86-1d56-4ba1-95a4-c78f47feab0c.png)

And in the page title: https://github.com/civiform/civiform/pull/3050

Note that "1/5" also is not universally understood, so if we use this format we also would need to localize/translate.

**Comment by cassandralfernandes** [comment]
On hold until @bion has more info from the localization team

**Comment by clouser2** [comment]
From #3578, we'll also want to localize the titles shown on the application preview, application review, and block editing pages.
