### ISSUE TITLE
Resident UX: Make it clear what the resident will get BEFORE the log in screen

### ISSUE THREAD

**Issue by elisekalstad** [civiform/civiform#3072]
**Is your feature request related to a problem? Please describe.**
Residents currently must log in or create an account and select desired language before they even see the menu of programs available. In order to encourage a resident to create a login, it would be helpful if they know what was available to warrant them taking the time to create an account.

**Describe the solution you'd like**
1) Reordering of the initial pages on civiform.seattle.gov
2) Clear benefits for why a resident should create a login

**Additional context**
Screenshots of current and proposed flow attached 
[Log in flow revised.pdf](https://github.com/civiform/civiform/files/9271590/Log.in.flow.revised.pdf)

**Done when**
What conditions need to be met before this issue can be closed?

**Comment by msprenke** [comment]
Assigning to Joe while PRD is under way

**Comment by elisekalstad** [comment]
Review for duplicate feature requests--michael currently working on this.

**Comment by elisekalstad** [comment]
Done!
