### ISSUE TITLE
CiviForm admin UX: allow user to navigate directly to add a question from the main program page

### ISSUE THREAD

**Issue by cassandralfernandes** [civiform/civiform#3073]
**Is your feature request related to a problem? Please describe.**
The CiviForm admin wants the ability to navigate directly to add a question from the program row on the main programs page

**Describe the solution you'd like**
When a user clicks the entire program row on the main program page, it take the user directly to the page to add screens and questions to their program. Clicking a draft program takes the user to where they left off

Clicking the edit button also directly takes the user to the page to add screens and questions to their program

**Additional context**
From admin UXR feedback sheet

**screenshot**
<img width="1731" alt="Screen Shot 2022-08-05 at 1 44 31 PM" src="https://user-images.githubusercontent.com/99513234/183159910-e5fc4fac-3ca5-4b0c-b9b1-2f6bf68dd8a8.png">

**Comment by cassandralfernandes** [comment]
mock: https://docs.google.com/presentation/d/15fcq3dYFgy1Dfy2UjZybmHD9KIW5cz8Q1BjwgOpLJ7g/edit#slide=id.g13ec4604693_0_8

**Comment by rahaghas** [comment]
Sorry I misread what this one was about, unassigning myself, it's good to go from a UX perspective and would actually consider it a high priority change

**Comment by nbeloglazov** [comment]
I think this one is blocked on https://github.com/civiform/civiform/issues/3074. Because if we change "edit" button to go directly to "edit screens and questions" view then user won't be able to access program details.

**Comment by nbeloglazov** [comment]
Sorry, I referenced wrong issue in my PR. Reopening this issue.
