### ISSUE TITLE
CiviForm Admin UX: Switch the order of the columns on the question page 

### ISSUE THREAD

**Issue by cassandralfernandes** [civiform/civiform#3076]
Note: this issue is dependent on issue #3075 

**Is your feature request related to a problem? Please describe.**
The user is confused about the order of the questions on the question tab. Users expressed that they would find it more intuitive if questions appear on the furthest left, then description 

**Describe the solution you'd like**
Change "Info" to "Admin note" 

Change "Question text" to "question". Truncate if question is too long.

Swap columns of admin note and question so that the question is the column on the furthest left 

**Additional context**
From admin UXR feedback sheet 

**Screenshot**
<img width="1589" alt="Screen Shot 2022-08-05 at 2 18 36 PM" src="https://user-images.githubusercontent.com/99513234/183201220-ab8c7818-23ed-4fb9-8f2a-d7c36c2bcdfd.png">

[mock here](https://docs.google.com/presentation/d/15fcq3dYFgy1Dfy2UjZybmHD9KIW5cz8Q1BjwgOpLJ7g/edit#slide=id.g13ec4604693_0_182)

**Comment by nbeloglazov** [comment]
I think this issue is obsolete due to #3033 where we remove these columns altogether and replace with single "info" section that includes question text, help text and admin note.

**Comment by clouser2** [comment]
Agreed. @cassandralfernandes , I'm closing this since the new UI seems like it hopefully reduces this confusion:
![Screen Shot 2022-09-19 at 2 35 38 PM](https://user-images.githubusercontent.com/1870301/191123930-361ff74a-1a9e-491b-8080-db04ea2e90c8.png)
