### ISSUE TITLE
CiviForm admin UX: allow admin to leave the program description field blank 

### ISSUE THREAD

**Issue by cassandralfernandes** [civiform/civiform#3077]
**Is your feature request related to a problem? Please describe.**
A CiviForm admin cannot leave the admin program description field blank 

**Describe the solution you'd like**
Make the admin program description field optional

**Additional context**
From Admin UX feedback sheet

**Screenshot**

<img width="1481" alt="Screen Shot 2022-08-05 at 2 20 34 PM" src="https://user-images.githubusercontent.com/99513234/183202879-30165acc-ba7b-4f39-bc71-3ffefdc34896.png">

**Comment by bion** [comment]
Assigning to @azhangggggg

**Comment by azhangggggg** [comment]
I think this interface has gone outdated and my guess is it's pointing to `Program note for administrative use`. Please correct me if it's not the case.
![Screenshot 2023-12-08 at 1 53 48 PM](https://github.com/civiform/civiform/assets/149536150/de806a25-5e7a-4dd5-b9e5-ae4d57b4a725)
