### ISSUE TITLE
Date validation error messages suggests using an incorrect date format

### ISSUE THREAD

**Issue by jeanniefu** [civiform/civiform#3078]
**Describe the bug**
After entering an invalid date and clicking next, the error message that pops up suggests using "YYYY/MM/DD", but the input field expects mm/dd/yyyy.

A few nuances to consider when solving this bug:
* I believe the placeholder text in `<input type="date">` is dependent on the language the user sets their browser to. (Based on this [stackoverflow](https://stackoverflow.com/questions/61186908/how-to-change-input-type-date-calender-language-localization) and linked [docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input#localization)). So this is not always going to be mm/dd/yyyy as shown in my screenshot.
* We can set the `lang` attribute for the input tag to force a certain language (e.g. the one selected by the user within CiviForm).
  
My proposed solution (open to alternatives):
* Set `lang="en"` to ensure the format displayed to the user is always mm/dd/yyyy.
* Update all [message translations](https://github.com/civiform/civiform/blob/c337065f5e9cb0945f81e3b5ca9c952c05e05aca/server/conf/messages#L258) to use "MM/DD/YYYY".

I feel like this is the easiest solution to ensure the error message matches the input field format. 

Alternatively, we could try to fully localize by setting `lang` to the CiviForm selected language, but this introduces room for bugs where the translation we have may not match the input date format. Also, I think applicants are used to and expect the mm/dd/yyyy format, since they are US based.

**To Reproduce**

1. Answer a date question with invalid date 05/05/999999
2. Click "Save and Next"
3. Look at the error text!

**Screenshots**
![Screen Shot 2022-08-05 at 2 04 29 PM](https://user-images.githubusercontent.com/9094240/183177567-4e61defd-8fe1-4ffc-a492-dcd07bd37c33.png)

**Comment by jeanniefu** [comment]
Actually based on some quick manual testing, I'm not sure if setting lang changes the date formatting. It may only be based on the user's browser's locale. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date#value

**Comment by nb1701** [comment]
I'm going to assume it's probably fine to leave the placeholder text for this kind of field (relating to https://github.com/civiform/civiform/pull/4099) since it actually helps the user input the value, unlike other placeholder text we had.

**Comment by nb1701** [comment]
It seems that even changing the browser's locale still makes the input format MM/DD/YYYY, so I think we should just update all the messages.

**Comment by nb1701** [comment]
Rather than trying to wrestle with this (because it all gets converted to a common format in the backend, this is all just UI differences), we could just say "Please enter a date in the correct format" instead?

**Comment by mferhut** [comment]
Agree let's update the help text date format to: MM/DD/YYYY in the meantime and then update to: "Please enter a date in the correct format."

**Comment by lftaylor2023** [comment]
We (Arkansas) noticed this problem with date validation and the red text date format not being correct today. We'd sure like to bump this one up on the priority list since it's been hanging around for a while now.
