### ISSUE TITLE
CiviForm admin UX: When the admin adds a question to their program, show the full question

### ISSUE THREAD

**Issue by cassandralfernandes** [civiform/civiform#3080]
**Is your feature request related to a problem? Please describe.**
When a CiviForm admin is adding questions to a program, they are not able to see the true format of the question they have added

**Describe the solution you'd like**
Options:
1) (Recommended) When an admin adds a question to their program, show the full question as it will appear to the resident 

2) (Other option if above is not feasible) Link to a preview of the question in a new tab

**Additional context**
From Admin UX feedback sheet 
[mock here](https://docs.google.com/presentation/d/15fcq3dYFgy1Dfy2UjZybmHD9KIW5cz8Q1BjwgOpLJ7g/edit#slide=id.g13ec4604693_0_52)

<img width="1716" alt="Screen Shot 2022-08-05 at 2 25 16 PM" src="https://user-images.githubusercontent.com/99513234/183205409-21d186b2-21f6-4c85-b455-e83e8d9653a3.png">

**Comment by nbeloglazov** [comment]
This has been brought up by Arkansas in the most recent feedback.

**Comment by melanie-exygy** [comment]
The admin preview solves this problem.
