### ISSUE TITLE
CiviForm admin UX: make adding questions from the question bank more clear

### ISSUE THREAD

**Issue by cassandralfernandes** [civiform/civiform#3081]
**Is your feature request related to a problem? Please describe.**
In UXR, the CiviForm admin did not know how to add a question from the question bank.

**Describe the solution you'd like**
On the manage questions and screens page: 
Change "+" to "add" 
Move "add" to the right of the question
Add a divider between the question and "add" button 

**Additional context**
From Admin UX feedback sheet
[Mock here](https://docs.google.com/presentation/d/15fcq3dYFgy1Dfy2UjZybmHD9KIW5cz8Q1BjwgOpLJ7g/edit#slide=id.g13ec4604693_0_76)

**Screenshot**
<img width="1709" alt="Screen Shot 2022-08-05 at 2 29 35 PM" src="https://user-images.githubusercontent.com/99513234/183208422-a8416a35-0a11-41b6-b0fa-81eccb27d513.png">

**Comment by jessbumblebee** [comment]
Hi Cassandra

As a newby to the system there were a few other bits about the wording that made this unclear to me.
I've got a couple of small suggestions. How about we:

Rename "Question bank" to something like "Your predefined questions" or "Predefined questions"
Add a short text below that along the lines of "You can add a predefined questions to the form by clicking on "add" button next to it"
Plus what you suggested already

**Comment by nbeloglazov** [comment]
Actually I started working on that as part of bigger question bank redesign: https://github.com/civiform/civiform/pull/3701
Both of your proposals, I think, are incorporated in Raha's design. Here is how my implementation looks:
https://drive.google.com/file/d/1xERLRLzJ32ky0eALqlZAP5XWHGaZ5cyw/view?usp=sharing

**Comment by nbeloglazov** [comment]
Done in https://github.com/civiform/civiform/pull/3701
