### ISSUE TITLE
CiviForm Admin UX: Change "Edit" to "Add" on the TI tab

### ISSUE THREAD

**Issue by cassandralfernandes** [civiform/civiform#3083]
**Is your feature request related to a problem? Please describe.**
When a CiviForm adds a TI on the TI tab, the user's action (to add) does not match the button's name that allows them to perform that action.

**Describe the solution you'd like**
Change "Edit" to "Add" on the TI tab

**Additional context**
<img width="1729" alt="Screen Shot 2022-08-05 at 3 07 24 PM" src="https://user-images.githubusercontent.com/99513234/183217749-b7617c5b-c5a2-4721-9c9f-06ce431347df.png">

**Comment by azizova-leyla** [comment]
@cassandralfernandes Add looks confusing here. Is it "Add members"? maybe something a bit more descriptive?

**Comment by cassandralfernandes** [comment]
Looking at this again, the edit button actually takes you to a place where you can add or delete members. So let's label the button "Edit members" (not add). The delete button next to edit is confusing, because that deletes the whole group. I suggest we add the word group there so it says "Delete group". WDYT?
