### ISSUE TITLE
SVG icons don't have consistent pixel sizing

### ISSUE THREAD

**Issue by clouser2** [civiform/civiform#3148]
Throughout the codebase, we set explicit width / height on SVGs. Each of the paths that's already present doesn't contain the original "size" represented by the SVG. This means that if two paths were copied based on a different pixel size, we'll get inconsistent clipping / centering when trying to render them at different sizes (see TODO referencing this bug).

We should do a pass through the codebase and import SVGs based on a consistent size (and include it in the HTML we output in order to make it easier to scale the icons). See https://css-tricks.com/scale-svg/.

**Comment by nbeloglazov** [comment]
Adjusted slightly script that calculates inferred size of the icons and most of them are 20 and 24px. So should be pretty safe to bake-in sizes of each svg into its enum value.

![image](https://user-images.githubusercontent.com/252053/185500320-cad20802-08ff-4dd7-af9b-1bc05cc804fe.png)
