### ISSUE TITLE
Allow CiviForm admins to see a published program / question's configuration

### ISSUE THREAD

**Issue by clouser2** [civiform/civiform#3162]
Presently, we only show this information for draft programs / questions. Surfacing a read-only view will allow admins to more easily see what has changed between the published content and the draft content.

**Comment by jessbumblebee** [comment]
This issue refers to Phase 2 of this Mini [prd](https://docs.google.com/document/d/1oD8EaFejs6L7_I-LKxt5ixQRFi5gtcTeL6NOwPMahf0/edit?resourcekey=0-76DVYMd4iDDbpA243q6l_Q#heading=h.atpwj1mzv74n)
I discussed some open questions with Cassandra and will pick this up next.
Some personal notes are [here](https://docs.google.com/document/d/10YjZvROqCgt4UZiwFtI6C6qAX-XpHEBfm62E_HLzlTY/edit?resourcekey=0-XiFHZHU8vfcxPqjgz1UP9w#heading=h.6c74rjtnc77s)
