### ISSUE TITLE
Program App List Display Error If Submit Time is Unset

### ISSUE THREAD

**Issue by gwendolyngoetz** [civiform/civiform#3227]
I've been seeing the error "Application ### submitted without submission time marked" getting logged. See [code](https://github.com/civiform/civiform/blob/ccf88d6a9284c8eafd06c3d825078727f7244551/server/app/views/admin/programs/ProgramApplicationListView.java#L281-L288)

This looks to be happening on the Admin Program Application List (/admin/programs/41814/applications) when an Application has this state:
* lifecycle_stage = 'obsolete'
* submit_time = null

We either need to filter the list to active applications only (which I believe is not the desired solution) or not log this as an error.

**Comment by cassandralfernandes** [comment]
To confirm: Does this bug impact users, or is it just in logs?

**Comment by gwendolyngoetz** [comment]
This would affect admin users

**Comment by nb1701** [comment]
Needs some investigation as to how to submit_time is being set to null.  Is it because the application was never submitted? Or was the value cleared out at some point incorrectly?

**Comment by bion** [comment]
@gwendolyngoetz it'd be helpful to know the submission time of the most recent application that is either `ACTIVE` or `OBSOLETE` that does not have a submission time.
