### ISSUE TITLE
Enable User to Reapply for Programs

### ISSUE THREAD

**Issue by cassandralfernandes** [civiform/civiform#3245]
### Introduction
Enable Applicants to Reapply for Programs (e.g. annual renewals)
### Problem Statements(s)
Many programs require regular renewals. Applicants are not always aware of these requirements, and they do not have an easy way to reapply on CiviForm at the moment 
### Product Requirements
PRD to come

### Design & Eng Requirements
Design doc and mocks to come

**Comment by msprenke** [comment]
This should be linked to https://github.com/civiform/civiform/issues/1497 which is the item for notifying the applicant that it is time to reapply

Assigning this item to myself to write the PRD for Seattle's requirements that we can then allow others to review/add to

**Comment by elisekalstad** [comment]
@shreyachatterjee00 -- You're working on the PRD for this one? Mind if I assign the feature to you for now?

**Comment by elisekalstad** [comment]
https://docs.google.com/document/d/1pYfhQjF6GAJlhuqueScdQeoYSasryQCk4pR01R7lwWA/edit?usp=drive_link&resourcekey=0-AYixBXEmt3wdybccQwjwpA
