### ISSUE TITLE
Enhance Applicant UX (Phase 1: Refined Application Review Page)

### ISSUE THREAD

**Issue by cassandralfernandes** [civiform/civiform#3248]
### Epic Overview

Improve critical user journeys for applicants on CiviForm. This includes look/feel and usability improvements to the application review page
  
### Product Requirements
PRD link + any important details

### Design Requirements
Mocks link + any important details

**Comment by melanie-exygy** [comment]
This is the focus of the North Star UX redesign and is being tracked elsewhere.
