### ISSUE TITLE
Kill the versions tab 

### ISSUE THREAD

**Issue by cassandralfernandes** [civiform/civiform#3256]
**Describe the bug**

After connecting with Seattle, I confirmed that we can and should remove the versions tab from CiviForm. In the future, a nice to have would be a revert/undo button after publishing programs, but for now CiviForm admin can manually make changes to programs post publishing as needed. 

**Screenshots**

<img width="1494" alt="Screen Shot 2022-08-25 at 1 37 29 PM" src="https://user-images.githubusercontent.com/99513234/186764141-7f7714f9-55d7-4e57-89d1-76bd6971abbe.png">

**Comment by cassandralfernandes** [comment]
@bion @azizova-leyla FYI I confirmed with Seattle and they do not use the versions tab. Let's remove it

**Comment by bion** [comment]
great, thanks @cassandralfernandes !
