### ISSUE TITLE
Applicant UX: Start Here and Continue confusing for users

### ISSUE THREAD

**Issue by elisekalstad** [civiform/civiform#3261]
**Is your feature request related to a problem? Please describe.**
Users and testers of CiviForm find it confusing to have "Start here" and "Continue" on the initial application screen. They don't understand what the difference is between the two buttons and often have difficulty finding the "start here" button, if there's a lot of text.

**Describe the solution you'd like**
Re-name both **"start here"** and **"continue"** to **"Complete Application".** IF a resident is new to CiviForm, they would be directed to the beginning of the form. IF the resident is returning and has data already stored, move the applicant to the final "Review" page to see questions they still need to answer.

**Additional context**
Open to any other possible UX flows. The goal should be that it's obvious that the user is selecting the right button from the beginning--regardless if they're coming to CiviForm for the first time OR if they're a returning applicant.

**Done when**
Button text, shape, and function are all updated. (Text = "Complete Application", Shape = should look like the current "continue" button, Function = should take first-time users to the beginning of the form and returning users to the "review" page.
[Start here vs. continue.pdf](https://github.com/civiform/civiform/files/9419914/Start.here.vs.continue.pdf)

**Comment by cassandralfernandes** [comment]
Smiliar to #1920

**Comment by elisekalstad** [comment]
Closed: 

![Image](https://user-images.githubusercontent.com/86082659/212968815-b23ccc79-21b4-4bc9-84bc-c6e5707b1474.png)
