### ISSUE TITLE
Update jest monorepo (major) 

### ISSUE THREAD

**Issue by azizova-leyla** [civiform/civiform#3302]
**Notes on the dependency**

- Make sure to include a link to the RenovateBot pull request
- https://github.com/civiform/civiform/pull/3266
- Add comments on why the original PR was not merged
- Tests are failing. Possibly undefined variables detected.

**Comment by syntapy** [comment]
version `29.0.1` of jest has not been tested with `ts-jest` so probably best to wait for a supported version 

` jest --testTimeout=180000 --forceExit --maxConcurrency=1 --runInBand error_pages.test.ts
ts-jest[versions] (WARN) Version 29.0.1 of jest installed has not been tested with ts-jest. If you're experiencing issues, consider using a supported version (>=28.0.0 <29.0.0-0). Please do not report issues in ts-jest if you are using unsupported versions.`

**Comment by clouser2** [comment]
Looking at the failing browser tests from that PR, it looks like there are two warnings and an error:

```
ts-jest[ts-jest-transformer] (WARN) Define `ts-jest` config under `globals` is deprecated. Please do
transform: {
    <transform_regex>: ['ts-jest', { /* ts-jest config goes here in Jest */ }],
},
ts-jest[config] (WARN) message TS[15](https://github.com/civiform/civiform/actions/runs/3118214310/jobs/5057348520#step:9:16)1001: If you have issues related to imports, you should consider setting `esModuleInterop` to `true` in your TypeScript configuration file (usually `tsconfig.json`). See https://blogs.msdn.microsoft.com/typescript/2018/01/31/announcing-typescript-2-7/#easier-ecmascript-module-interoperability for more information.
Error: Jest: Got error running globalSetup - /usr/src/***-browser-tests/src/delete_database.ts, reason: [TSError: src/support/index.ts:70:45 - error TS2550: Property 'replaceAll' does not exist on type 'string'. Do you need to change your target library? Try changing the 'lib' compiler option to 'es2021' or later.

70           expect.getState().currentTestName.replaceAll(/[:"<>|*?]/g, ''),
                                               ~~~~~~~~~~]
```

### Warning 1: Defining ts-jest config under globals is deprecated

This came from a recent release ([link](https://github.com/kulshekhar/ts-jest/blob/main/CHANGELOG.md#features-1)). Presumably this will eventually become an issue. Once finished with updating the monorepo, I'll send out a separate PR to fix this.

### Warning 2: Set esModuleInterop to true

We already use the @typescript/recommended config in our server-side TS ([code](https://github.com/civiform/civiform/blob/bc75839355e5625df3ae3b12d18efaf9e2faa533/server/tsconfig.json#L2)), which sets this property to true. I see no reason we couldn't extend this to the tsconfig we use for browser tests ([code](https://github.com/civiform/civiform/blob/bc75839355e5625df3ae3b12d18efaf9e2faa533/browser-test/src/tsconfig.json)).

### Error: string.replaceAll can't be found

I'm not sure what about the Jest upgraded caused this to start failing, but it's a pretty simple fix. `String.replaceAll` is defined in the ES2021 config, which we currently don't include in our `libs` section of our tsconfig ([code](https://github.com/civiform/civiform/blob/bc75839355e5625df3ae3b12d18efaf9e2faa533/browser-test/src/tsconfig.json#L4)).

We can add `ES2021` or `ES2021.String` to that list and it should resolve itself.

## Rollout plan:

I'll start by updating the browser-test's `tsconfig.json` to 1) extend the recommended config and 2) include the `ES2021` lib.

After that, I'll rebase the renovate bot PR and see if it passes. If all goes well, we'll submit that, then I'll send out a follow-on PR to no longer specify `jest-config` in the globals section.

**Comment by clouser2** [comment]
> version `29.0.1` of jest has not been tested with `ts-jest` so probably best to wait for a supported version
> 
> ` jest --testTimeout=180000 --forceExit --maxConcurrency=1 --runInBand error_pages.test.ts ts-jest[versions] (WARN) Version 29.0.1 of jest installed has not been tested with ts-jest. If you're experiencing issues, consider using a supported version (>=28.0.0 <29.0.0-0). Please do not report issues in ts-jest if you are using unsupported versions.`

I think this may have now resolved itself and might have been Renovate Bot originally seeing a dependency update for one of the libraries before the new version of its dependent library had been published.

**Comment by clouser2** [comment]
While going down this road, I ran into several problems where I couldn't actually do most of what I wanted.

### Warning 2: Set esModuleInterop to true

I attempted to add @tsconfig/recommended to package.json. However, when I did that, I think setting the `esModuleInterop` flag caused a whole new set of warnings around how we're performing our import statements. I'm abandoning fixing that right now.

### Error: string.replaceAll can't be found

No matter what combination of `ES2021` / `es2021` / `ES2021.String`, I still got a similar compiler error. One thing that was mentioned is that as long as the regex has a `/g` in it (which ours does), a call to `replace` is equivalent to `replaceAll`. We can sidestep this by updating that call.

### New errors:

After doing the above and simulating the Jest upgrade on a local client, I saw several new warnings while running the upgrade command:

```
warning " > jest-image-snapshot@5.1.1" has incorrect peer dependency "jest@>=20 <=28".
warning " > jest-playwright-preset@1.7.2" has incorrect peer dependency "jest@^26.6.3 || ^27.0.0".
warning " > jest-playwright-preset@1.7.2" has unmet peer dependency "jest-circus@^26.6.3 || ^27.0.0".
warning " > jest-playwright-preset@1.7.2" has unmet peer dependency "jest-environment-node@^26.6.2 || ^27.0.0".
warning " > jest-playwright-preset@1.7.2" has unmet peer dependency "jest-runner@^26.6.3 || ^27.0.0".
```

Attempting to run tests after this fails spectacularly:

```
Ran all test suites matching /address.test.ts/i.
TypeError: Cannot read properties of undefined (reading 'serial')
    at PlaywrightRunner.runTests (/usr/src/civiform-browser-tests/node_modules/jest-playwright-preset/lib/PlaywrightRunner.js:128:28)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async TestScheduler.scheduleTests (/usr/src/civiform-browser-tests/node_modules/@jest/core/build/TestScheduler.js:319:15)
    at async runJest (/usr/src/civiform-browser-tests/node_modules/@jest/core/build/runJest.js:405:19)
    at async _run10000 (/usr/src/civiform-browser-tests/node_modules/@jest/core/build/cli/index.js:386:7)
    at async runCLI (/usr/src/civiform-browser-tests/node_modules/@jest/core/build/cli/index.js:237:3)
    at async Object.run (/usr/src/civiform-browser-tests/node_modules/jest-cli/build/cli/index.js:155:37)
error Command failed with exit code 1.
```

I believe this comes from the unmet dependencies for jest-playwright-preset. We might want to investigate migrating away from this.

For `jest-image-snapshot`, it appears that we'll need to wait for a PR to land before that works: https://github.com/americanexpress/jest-image-snapshot/pull/309

**Comment by clouser2** [comment]
Discussed today and we're going to wait and see if `jest-playwright-preset` and `jest-image-snapshot` update in the next month or so.

I filed https://github.com/civiform/civiform/issues/3513 to track whether we should move away from `jest-playwright-preset` entirely.

For now, reassigning to @bion to reinvestigate in a month to see if the dependencies have been updated.

**Comment by clouser2** [comment]
#3513 has been fixed and PR https://github.com/civiform/civiform/pull/3266 now passes. I believe we can merge this :D.
