### ISSUE TITLE
Standardize browser handling in browser tests

### ISSUE THREAD

**Issue by nbeloglazov** [civiform/civiform#3323]
At the moment there are 2 different styles of working with browser: launch new instance of browser on each test case and destroy it afterwards or launch browser once and reuse its context between test cases, resetting civiform play session. Both approaches have downsides: launching browser each time slows down tests and reusing same context breaks video recording: we get single video for multiple test cases. Additionally it requires extra work from eng to remember destroy browser or reset session.

We should centralize browser handling and update existing tests to follow the new pattern. Proposed pattern is to create a new function `createTestContext` that returns an object containing `page`, helper objects like `adminPrograms`. That function will register appropriate `before/afterAll`, `before/afterEach` handlers to ensure that browser context is reset correctly between tests. Additionally it will ensure that db is reset between tests. 

Example usage: 

```js
describe('some test', () => {
  const ctx = createTestContext()

  it('should do foo', async () => {
    await ctx.page.click('#some-button')
  })
})
```

**Comment by nbeloglazov** [comment]
Here is more detailed description on how browser context/session is reset between tests. 

First, we need to close browser context after each test case so that its video is saved as a separate file. If we reuse browser context between multiple test cases we end up with longer videos that span multiple test cases and hard to understand (can't see at which point next test starts).

Second, we need to make sure that browser is initialized and ready to use during all `beforeAll/afterAll` invocations. 

Resetting session/context means that users shouldn't expect that `ctx.page` will be on certain page or logged in when they implement `afterAll`. It's important to note as it's reasonable to expect that when you logged in in `beforeAll` - then you'll be logged in during the test and in `afterAll`. In fact each test will get fresh session and need to log in in `beforeEach`. 

Here is example of how sessions reset between tests (different numbers mean different sessions). The example assumes that there can be multiple before/afterAll and nested describes.

```
describe()
    [1] beforeAll()
    describe()
        [1] beforeAll()
        // first test
        [2] beforeEach()
        [2] beforeEach()
        [2] it()
        [2] afterEach()
        [2] afterEach()
        // second test
        [3] beforeEach()
        [3] beforeEach()
        [3] it()
        [3] afterEach()
        [3] afterEach()
        [4] afterAll()
    describe()
        [4] beforeAll()
        // third test
        [5] beforeEach()
        [5] it()
        [5] afterEach()
        [6] afterAll()
    [6] afterAll()
```

@jeanniefu this should answer the question why we have fresh objects. 
@clouser2 do you see this approach conflicting with your login test proposal?

**Comment by clouser2** [comment]
I don't think this approach would interfere. The majority of the changes are going to be in the `loginAsTestUser` code, which should be resilient to being called from multiple browser sessions.

**Comment by jeanniefu** [comment]
Ah thanks, I didn't realize that an outermost `beforeEach` still applies to each nested `it()`.

Actually for #3324, if we are calling reset for `beforeAll`, `beforeEach`, `afterEach`, aren't we calling it more than needed? e.g. would look like:

```
describe()
    [1] beforeAll()  - reset

    describe()
        [1] beforeAll()

        // first test
        [2] beforeEach()  - reset
        [2] beforeEach()
        [2] it()
        [2] afterEach()
        [2] afterEach()  - reset

        // second test
        [3] beforeEach()  - reset
        [3] beforeEach()
        [3] it()
        [3] afterEach()
        [3] afterEach()  - reset

        [4] afterAll()

    describe()
        [4] beforeAll()

        // third test
        [5] beforeEach() - reset
        [5] it()
        [5] afterEach() - reset

        [6] afterAll()

    [6] afterAll()
```

Isn't calling it in `beforeAll`, `beforeEach` sufficient? Or do we also want to call it in `afterEach` out of principle because we feel like it is a test's responsibility to clean up and reset the state?

**Comment by nbeloglazov** [comment]
I want call it in `afterEach` as well to get clean test videos that end after all `afterEach` is called. If we don't it then video will contain parts of the next `beforeAll` and can be confusing. Calling reset both in `beforeEach` and `afterEach` gives us cleanest separation. 

And I agree that calling `afterEach` is not strictly necessary. If calling reset too many times ends up being a problem we can get rid of it.
