### ISSUE TITLE
Increase automation and ease of deployment

### ISSUE THREAD

**Issue by cassandralfernandes** [civiform/civiform#3342]
### Epic Overview

To facilitate CiviForm deployment and alleviate the burden on IT staff, Civiform team is developing a set of scripts to create all necessary infrastructure to run Civiform on their preferred cloud provider. 

This work includes: 
- Dockerize cloud deployment scripts 
- Switch config to YAML. 
- Setup e2e tests for both AWS and Azure that run from scratch and do full setup/teardown

 See technical deployment docs below for full details.  

### Design & Eng Requirements
[CiviForm Deployment Infrastructure Roadmap](https://docs.google.com/document/d/1Sj0uw0aZuVhBStrny0fVtqoTDgsjHamxATfMIadndns/edit#)

**Comment by rasmi** [comment]
Closed as duplicate of #4760
