### ISSUE TITLE
Change applicant question div IDs to use a string that does not contain square brackets and periods

### ISSUE THREAD

**Issue by jeanniefu** [civiform/civiform#3356]
Currently, the HTML id for applicant question divs use the contextualized path as a string, which could contain square brackets and periods: [code link](https://github.com/civiform/civiform/blob/main/server/app/views/questiontypes/ApplicantQuestionRendererImpl.java#L137).

According to the note [here](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/id) it is a best practice for IDs to only use letters, numbers, -, and _.

**Comment by clouser2** [comment]
If we don't have a need to do any JS / browser test queries based on the IDs themselves, I'd vote for either 1) not setting an ID at all or 2) setting a random ID.

**Comment by jeanniefu** [comment]
Random ID SGTM! I do need it to associate aria labels correctly.
