### ISSUE TITLE
Scroll bar missing from application view

### ISSUE THREAD

**Issue by elisekalstad** [civiform/civiform#3362]
**Describe the bug**
Program admins are unable to view the entirety of an application within CiviForm. Previously there was a scroll bar for them to scroll and view the entire resident's application. That scroll bar is no longer there and program admins are unable to view the application beyond the first few questions.

**To Reproduce**

1. Log in as a Program Admin
2. Click on 'Applications'
3. Click to view 1 application
4. See that only the first part of the application shows and you cannot scroll to see the rest

**Expected behavior**
Program admins should be able to scroll to see the entire application

**Screenshots**
Attached

[Issue_No scroll.pdf](https://github.com/civiform/civiform/files/9509114/Issue_No.scroll.pdf)

**Comment by shanemc-goog** [comment]
@swatkat1 as oncall this seems like a good thing to repro and access the impact of.

**Comment by clouser2** [comment]
This is a regression from https://github.com/civiform/civiform/pull/3191 where we incorrectly added the `overflow-hidden` class to the application content (thus disabling scrolling). I can put together a fix for this.

**Comment by clouser2** [comment]
@elisekalstad Sorry about the breakage :(.

**Comment by elisekalstad** [comment]
All good! No worries!

[Title: City of Seattle logo]Elise Kalstad
She/Her/Hers
City of Seattle, Innovation & Performance
206-256-5515 | ***@***.******@***.***>
In office: TH  | Remote: M, T, W, F
Learn more about Innovation & Performance: seattle.gov/innovation-performance<https://www.seattle.gov/innovation-performance>
