### ISSUE TITLE
Admin preview of static text questions do not show formatting

### ISSUE THREAD

**Issue by jeanniefu** [civiform/civiform#3373]
Admin view (prints as plain text):
<img width="905" alt="Screen Shot 2022-09-08 at 3 04 41 PM" src="https://user-images.githubusercontent.com/9094240/189235068-11c3eafc-2f6a-4e67-bc03-710c21c64682.png">

Applicant view (uses formatting):
<img width="901" alt="Screen Shot 2022-09-08 at 3 10 29 PM" src="https://user-images.githubusercontent.com/9094240/189235080-d8a38a8e-47f1-4308-80f6-891271a66edf.png">

**Comment by shanemc-goog** [comment]
Just discovered this myself, there's a related bug around this #3933 for radio buttons so seems likely there may be others too
