### ISSUE TITLE
"Previously answered on YYYY-MM-DD" text on application summary page has wrong date

### ISSUE THREAD

**Issue by jeanniefu** [civiform/civiform#3379]
I answered this question on 2022-09-08, but the text displays the wrong day("09" instead of "08"). My guess is that we are not using the correct timezone (but I haven't dug into this yet).

<img width="1757" alt="Screen Shot 2022-09-08 at 5 50 55 PM" src="https://user-images.githubusercontent.com/9094240/189249970-4a1b11c4-9640-4107-ac57-06cb2ed8d0c6.png">

**Comment by shanemc-goog** [comment]
Note: until recently we stored pre-submit data in the application but largely read it from the applicant stored data too.  It seems likely that is having an effect here.
