### ISSUE TITLE
"Previously answered on YYYY-MM-DD" text is missing from some prefilled answers

### ISSUE THREAD

**Issue by jeanniefu** [civiform/civiform#3380]
**Describe the bug**
"Previously answered on YYYY-MM-DD" text is missing from some prefilled answers

**To Reproduce**

1. Apply to a program and submit
2. Reapply to program, all answers should be prefilled
3. Notice that only some of those prefilled answers have the "previously answered on <date>" text.

**Expected behavior**
All prefilled answers should have the "Previously answered on YYYY-MM-DD" text

**Screenshots**
<img width="1757" alt="Screen Shot 2022-09-08 at 5 50 55 PM" src="https://user-images.githubusercontent.com/9094240/189250192-d65e7f58-7bd5-43ac-843a-6d405f779622.png">

**Comment by shanemc-goog** [comment]
Note: until recently we stored pre-submit data in the application but largely read it from the applicant stored data too. It seems likely that is having an effect here.

**Comment by dkatzz** [comment]
I tested this out and I'm seeing that the "previously answered on" text will show if I answered those questions in a different program. If I answered the questions in the current program, they won't show up.

So for example:
1) I apply for Accessibility Primary
2) I reapply to Accessibility Primary and see my answers but no "previously answered" text
3) I apply to Accessibility Secondary and see "previously answered" for all answers that I filled out in Accessibility Primary
4) I change some answers in Accessibility Secondary
5) I go back to Accessibility Primary and see "previously answered" for all answers that I changed in Accessibility Secondary (or on the same page as other answers I changed)

@jeanniefu, I just want to check what the intended behavior should be? This seems to be working as intended if we want to only show the "previously answered on" for questions answered in a different program, but if we want it to show for questions answered previously in the same program, this would be a bug. Let me know what you think - thanks!

**Comment by jeanniefu** [comment]
Thanks @dkatzz for investigating! Sounds like the feature is working as intended as originally designed.

However, I personally think the current UI confusing. What do you think about just marking all of them as "previously answered"? So we don't have a filter for whether it was used in this program vs a different program.

@bion - Do we have a UX person who could help make a decision?

**Comment by shanemc-goog** [comment]
@mferhut for UX

**Comment by mferhut** [comment]
We can include ‘Previously answered on…’ for all questions regardless if it was answered on another program or the one the applicant is currently on. The date will help distinguish the exact timing of it to the applicant.
