### ISSUE TITLE
Applicant-facing program list cards overlap on smaller screen sizes

### ISSUE THREAD

**Issue by clouser2** [civiform/civiform#3492]
**Describe the bug**
![Screen Shot 2022-09-22 at 1 13 59 PM](https://user-images.githubusercontent.com/1870301/191842327-b65d2d07-0ae7-4fa0-b108-e202dfab1618.png)

This is fallout from #3447, where the program card was resized from `w-72` to `w-96`. The previous hard-coded value was closely tied to the grid layout we set for each card that renders. We should revert back to `w-72`, since the increase in size wasn't strictly necessary.

**Comment by clouser2** [comment]
I'll fix the immediate problem by reverting back to `w-72`, then I'll see if there's a browser regression test we can add for rendering with lots of programs. This might require me to resize the browser to create the issue, so unclear how much value we'll get out of it.

**Comment by bion** [comment]
Fixed
