### ISSUE TITLE
Setup e2e testing for AWS deploy scripts

### ISSUE THREAD

**Issue by azizova-leyla** [civiform/civiform#3510]
We want to test deploying from scratch and validate correctness if possible.

**Comment by avrittrohwer** [comment]
General plan:

1. Create a new `e2e-tests` AWS account under the root organization for the existing `Google.org Works` account.
2. Configure a `e2e-test-bot` IAM account with proper permission bindings to run the deploy scipts.
3. Update the `destroy` deployment command to run [aws-nuke](https://github.com/rebuy-de/aws-nuke), needed to fully clean the AWS account.
4. Add a new `e2e-deploy` github action that runs the full deployment flow.
5. Action passes if deployment flow encounters no errors and the civiform server is accessible through AWS load-balancer public DNS name.

Known unknowns:

1. How to handle multiple e2e tests running at the same time.  Likely need multiple `e2e-tests` AWS accounts with a centralized way to acquire a lock to one.
2. How to catch things that are not cleaned up by aws-nuke and file a bug to add support in aws-nuke.
