### ISSUE TITLE
Consider moving away from jest-playwright-preset in favor of Playwright's builtin runner

### ISSUE THREAD

**Issue by clouser2** [civiform/civiform#3513]
Playwright is a library that allows interacting with a webpage through a headless browser. Jest is a test runner. `jest-playwright-preset` is a library that makes it possible to use the Jest test runner and interact with the browser using Playwright.

The jest-playwright-preset docs now suggest using Playwright's builtin test runner (https://www.npmjs.com/package/jest-playwright-preset), which presumably was recently built.

As part of https://github.com/civiform/civiform/issues/3302, we ran into issues where Jest 29 was updated, but `jest-playwright-preset` wasn't compatible with it immediately. It's unclear whether this will be resolved at some point. Either way, carrying this forward will always be a source of potential time sink. Given the warning on the `jest-playwright-preset`, it might make sense to try and use Playwright's native library instead.

I'll fill out a pointers as to what this migration might look like in future comments.

**Comment by nbeloglazov** [comment]
One thing I don't fully understand yet is what exactly `jest-playwright-preset` does. Reading our code - we write regular jest tests, using `describe`/`it`/`expect`/etc. We create new instances of browser manually using `chromium.launch()` using playwright API directly.  For example we are not using their helper functions like these: https://github.com/playwright-community/jest-playwright#reset-helper-functions

So I'm curious what will happen if we just remove jest-playwright-preset. What will break, if anything?

**Comment by clouser2** [comment]
> One thing I don't fully understand yet is what exactly `jest-playwright-preset` does. Reading our code - we write regular jest tests, using `describe`/`it`/`expect`/etc. We create new instances of browser manually using `chromium.launch()` using playwright API directly. For example we are not using their helper functions like these: https://github.com/playwright-community/jest-playwright#reset-helper-functions
> 
> So I'm curious what will happen if we just remove jest-playwright-preset. What will break, if anything?

Agreed. I removed `jest-playwright-preset`, rebuilt the browser env, and `address.test.ts` still continued to pass. That said, I have no idea if there's something subtle about the underlying library that we were relying on or depending on. Here's the custom runner that's used when the preset is enabled: https://github.com/playwright-community/jest-playwright/blob/main/src/PlaywrightRunner.ts.

I don't feel confident to say if anything will break or what the behavior change will be :/.

**Comment by clouser2** [comment]
> > One thing I don't fully understand yet is what exactly `jest-playwright-preset` does. Reading our code - we write regular jest tests, using `describe`/`it`/`expect`/etc. We create new instances of browser manually using `chromium.launch()` using playwright API directly. For example we are not using their helper functions like these: https://github.com/playwright-community/jest-playwright#reset-helper-functions
> > So I'm curious what will happen if we just remove jest-playwright-preset. What will break, if anything?
> 
> Agreed. I removed `jest-playwright-preset`, rebuilt the browser env, and `address.test.ts` still continued to pass. That said, I have no idea if there's something subtle about the underlying library that we were relying on or depending on. Here's the custom runner that's used when the preset is enabled: https://github.com/playwright-community/jest-playwright/blob/main/src/PlaywrightRunner.ts.
> 
> I don't feel confident to say if anything will break or what the behavior change will be :/.

I did an experiment for the jest-monorepo upgrade: https://github.com/civiform/civiform/pull/3518.

In this PR, we:
  * Remove `jest-playwright-preset` entirely
  * Update the Jest monorepo with the same changes as #3302. There's still a warning about image snapshot being incompatible. That said, the tests currently pass, so we don't necessarily have to wait. 

Given this, it might make sense to remove our dependency on `jest-playwright-preset`. Thanks to @nbeloglazov for pushing on this. I'm going to do a bit more scanning of the jest-playwright-preset codebase ([code](https://github.com/playwright-community/jest-playwright)) to see if there's anything subtle I can see that we might be losing out on.

**Comment by clouser2** [comment]
Things provided by the preset:
  * Hooks for setting up a development server and tearing it down as part of tests. We spawn our dev server using `bin/run-browser-test-env` presumably due to it running in a distinct container - I don't think this is useful ([code](https://github.com/playwright-community/jest-playwright/blob/95b83774be71e3859875ccdcc27e0e5aef28c3ff/src/global.ts#L41)).
  * Supporting a distinct config for how browsers are launched ([docs](https://github.com/playwright-community/jest-playwright#options)). We in fact have a `jest-playwright-config.js` file ([code](https://github.com/civiform/civiform/blob/2fd76f8d9b89e4bea896834f6e60521596df04fe/browser-test/jest-playwright.config.js)) which specifies some options. That said, since we don't use any of the playwright context hooks ([code](https://github.com/civiform/civiform/blob/2fd76f8d9b89e4bea896834f6e60521596df04fe/browser-test/src/support/index.ts#L94)), this is effectively ignored. I think this file can be removed to reduce confusion. It's entirely an unnecessary browser process is started as part of Playwright's setup ([code](https://github.com/playwright-community/jest-playwright/blob/95b83774be71e3859875ccdcc27e0e5aef28c3ff/src/PlaywrightEnvironment.ts#L222)). However, our call to `chromium.launch` would bypass all of this infrastructure.
  * The preset supports reading a list of browsers / devices from the configuration and generating distinct test targets for each combination ([code](https://github.com/playwright-community/jest-playwright/blob/95b83774be71e3859875ccdcc27e0e5aef28c3ff/src/PlaywrightRunner.ts#L140-L172)). We only test in Chromium and don't make use of this feature
  * Overriding the test timeout from the Playwright default ([code](https://github.com/playwright-community/jest-playwright/blob/95b83774be71e3859875ccdcc27e0e5aef28c3ff/src/PlaywrightRunner.ts#L98-L103)). We already do this as part of invoking the Jest process ([code](https://github.com/civiform/civiform/blob/2fd76f8d9b89e4bea896834f6e60521596df04fe/browser-test/package.json#L6-L7)).
  * Looks like the `jest-playwright-preset` ends up including the `ts-jest` preset to add TypeScript support ([code](https://github.com/playwright-community/jest-playwright/blob/95b83774be71e3859875ccdcc27e0e5aef28c3ff/jest.config.js#L2)). We can replace our preset entry with this.

I'll update my PR to 1) remove `jest-playwright-config.js` since it's unused and 2) Update our preset to `ts-jest`.

If that all passes cleanly, I'll send the PR out for review without the Jest monorepo update. Once that's submitted, we can resync the RenovateBot PR and proceed.

**Comment by clouser2** [comment]
Test run was successful: https://github.com/civiform/civiform/actions/runs/3137537237/jobs/5095817477.

I'll send out a PR with those changes sans the Jest monorepo update.

**Comment by nbeloglazov** [comment]
I can see needing to have 2 variations of screenshots, one for desktop and one for mobile. In which case jest-playwright-preset might have simplified things a little. But we might come up with our own enhancements to support that use case. Other than that I don't think we'd use their features.
