### ISSUE TITLE
Update pac4j dependencies to v5.5.0

### ISSUE THREAD

**Issue by gwendolyngoetz** [civiform/civiform#3547]
**Notes on the dependency**

[Source PR #3527](https://github.com/civiform/civiform/pull/3527) 

The dependency bump to v5.5.0 is now unable to find a JSONArray object for some reason.

```
#22 69.03 [error] /usr/src/server/app/auth/oidc/admin/AdfsProfileAdapter.java:8:1: package com.nimbusds.jose.shaded.json does not exist
#22 69.03 [error] com.nimbusds.jose.shaded.json.JSONArray
```

**Comment by nbeloglazov** [comment]
I believe @azizova-leyla dealt with that issue during on of previous releases. Weird to see it again.

**Comment by azizova-leyla** [comment]
I never bumped the version because it was breaking logback. Jsonarray can be directly replaced with List<String>, but I didn't have time to figure out how to bump logback version. 

See https://github.com/civiform/civiform/issues/3260

**Comment by nbeloglazov** [comment]
Going to close is as dup of #3260
