### ISSUE TITLE
Title for login page is not localized

### ISSUE THREAD

**Issue by clouser2** [civiform/civiform#3548]
**Describe the bug**
We hardcode a value of "Login" for the page title [here](https://github.com/civiform/civiform/blob/d818b469c9030f1a63a03f640c672a8e0337ad26/server/app/views/LoginForm.java#L73).

The assumption may have been that this page would only be shown prior to language selection. However, an applicant can:
 1) Continue as guest
 2) Choose another language
 3) Navigate back to the front page (maybe by logging out).
 4) The login page is rendered with localized text

We should likely localize this text, similar to the other applicant-facing page titles.

Noticed as part of #3545.

**Comment by jeanniefu** [comment]
Currently the front page is translated, and the language selection page is not.

Should we even translate the front page? In my opinion, it makes sense for the front page + language selection page to both be in English. My expectation is that when I click logout, the website is returned to its default state (English).

**Comment by nbeloglazov** [comment]
It think we can best-guess user language even before they select language based on `accept-language` header. It provides languages user likely uses. For example here mine: `accept-language: be,en-GB;q=0.9,en;q=0.8,en-US;q=0.7,ru;q=0.6,la;q=0.5` Which states that my 2 preferred languages are Belarusian and English GB (no idea why GB over US but ok). If do that than localizing first screen makes more sense.

**Comment by MichaelZetune** [comment]
https://user-images.githubusercontent.com/30369272/220974946-f3a5d781-cd58-41c4-b559-6968c318d7e9.mp4

It looks like we already pre-select the correct language for the user based on the `accept-language` header. This video demonstrates that with the ModHeader chrome extension.

Changing the content of the log in and language page based on this header (even before the language is confirmed) seems reasonable to me. Will have to check with PMs on whether we should proceed. #4269 just adds the log in title translation for now.
