### ISSUE TITLE
(WCAG 2.1) Add either sr-only or visual text to progress bar indicating status

### ISSUE THREAD

**Issue by jeanniefu** [civiform/civiform#3570]
Required to meet WCAG 2.1 guidelines. Identified during an accessibility audit against WCAG 2.1.

**WCAG SC**: [4.1.2. Name, Role, Value](https://www.w3.org/TR/WCAG21/#name-role-value)

**Observed results**: Progress bars on the Program application review page do not provide accessible name or label.

**How to fix**:
From a11y team:
"Unlike in the application forms where the progress bars have adjacent textual information displayed (e.g. 1 of 5), the Program application review page can actually display different progress bars for the specific application and therefore it must convey some kind of alternative text or accessible label.

Consider adding textual information on top of the bar such as In progress, Completed, Not started; otherwise, provide role and label to the progress bars for screen readers to convey (see: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/progressbar_role)."

From me:
Should check with UX whether we want to add additional visual text. Otherwise, add alt text.

![image](https://user-images.githubusercontent.com/9094240/192913498-566a5164-ae3d-4d84-82f9-b7841c5cf1b6.png)
![image](https://user-images.githubusercontent.com/9094240/192913512-56d28682-e1a0-4368-b5e0-c0f6c47f5c48.png)
![image](https://user-images.githubusercontent.com/9094240/192913527-9e13a3cc-0be2-453b-aef0-478fdc7c2881.png)

**Comment by clouser2** [comment]
Adding new text seems reasonable. Another alternative would be to try and make these fully consistent with the block editing page and show the "2 of 5" text to the right of the program name. For not started, it'd say "0 of 5" and for completed it'd say "5 of 5".

An advantage of this approach would be that we could fully reuse the existing localized content.

**Comment by bion** [comment]
Done
