### ISSUE TITLE
(WCAG 2.1) Set focus to specific input field after user clicks Q from application summary page.

### ISSUE THREAD

**Issue by jeanniefu** [civiform/civiform#3571]
Required to meet WCAG 2.1 guidelines. Identified during an accessibility audit against WCAG 2.1.

**WCAG SC**: [2.4.3. Focus Order](https://www.w3.org/TR/WCAG21/#focus-order)

**Observed results**: Focus is not set explicitly to the correct form field when "Start here" was activated for that particular application question (in this case - What is your favorite color?)

**How to fix**: After the user clicks on a specific link from the preview page, we should set focus to that particular input field in the application block. (e.g. "What is your favorite color?" input field).

![image](https://user-images.githubusercontent.com/9094240/192914038-f0b81250-827e-4612-a765-03fb4d9af522.png)

**Comment by rockycodes** [comment]
Completed by: https://github.com/civiform/civiform/pull/5409
