### ISSUE TITLE
New batch of translations

### ISSUE THREAD

**Issue by clouser2** [civiform/civiform#3577]
As part of some A11y issues, we're adding new strings in need of translating. This issue tracks doing a new batch of translations and updating the TODOs associated with this issue once translations are available.

**Comment by clouser2** [comment]
I'll continue editing this comment as new translated strings are added.

The translations we're looking for are:
  * button.editSr - from #3562
  * button.continueSr - from #3562
  * link.externalLinkOpensInNewTab - from #3564

**Comment by jeanniefu** [comment]
More translations:
- validation.errorAnnouncementSr from #3706
- ariaLabel.begin from #3709
- ariaLabel.continue from #3709
