### ISSUE TITLE
A11y UXR feedback: Improve preview page experience for screenreader users

### ISSUE THREAD

**Issue by jeanniefu** [civiform/civiform#3600]
During a UXR with a Googler who uses a screenreader, they mentioned the preview page was confusing. When they clicked the first link ("Start here"), they were surprised they were brought to a new page instead of being able to just fill out the answer right away. The user said that it seems like from the preview page, it's asking you to fill out fields already (and it's not clear it's just a preview).

They said the presence of both the "Start here" and "Continue" buttons was confusing.

Note that at the time of the UXR, we had bug #3559 where the screenreader reads "Edit What is your name?" instead of "Start here What is your name?".

![image](https://user-images.githubusercontent.com/9094240/193362565-76c2d281-9d8b-4a96-b570-dc63529ec86f.png)

UXR notes: https://docs.google.com/document/d/1LNsgNZMFo9tAzaAcKXgI_wobXSA4CPg21gImtXwoKHU/edit?usp=sharing&resourcekey=0-7iPvDr7I8Yk8i4Ti2pj3gA

**Comment by bion** [comment]
Closing this since the associated bug is fixed and experience is improved
