### ISSUE TITLE
Admin Programs List Page Loading Slow

### ISSUE THREAD

**Issue by gwendolyngoetz** [civiform/civiform#3609]
**Describe the bug**
The admin program list page `/admin/programs` is beginning to load slow. We have 20 programs in prod and it's taking about 2-2.5 seconds to load the html page. Other files (js/css) load in parallel under 100ms, so they are fine.

![image](https://user-images.githubusercontent.com/195162/193694388-dd6677da-487f-407c-ba70-cc2f0b7f94c1.png)

**To Reproduce**
Create a number of programs with questions. At least 20. Load the `/admin/programs` page; check the load time.

**Expected behavior**
Load quicker

**Comment by nbeloglazov** [comment]
staging-azure.civiform.dev has ~20 programs and it takes 5-6s to load: https://staging-azure.civiform.dev/admin/programs

**Comment by gwendolyngoetz** [comment]
Seattle Prod has 27 programs and is now taking 5-6 seconds to load

**Comment by isabelcshaw** [comment]
@gwendolyngoetz - @nb1701 is gonna jump in and do some investigating here. Pls let us know if you have any insights from when you first encountered the issue. Thanks!

**Comment by gwendolyngoetz** [comment]
I'm pretty sure it's related to the ORM and how the "queries" are written for the database. It probably needs to more eagerly load the data for this page. I'd also check that it's filtering out `obsolete` programs/questions on the database and not pulling it all and filtering it in the web server.
