### ISSUE TITLE
Enable OIDC logout during user logout

### ISSUE THREAD

**Issue by nbeloglazov** [civiform/civiform#3621]
Currently applicant logs out from CiviForm - we only log them out from CiviForm session. They are still logged in on the corresponding auth provider. Kiana implemented this functionality in https://github.com/civiform/civiform/pull/3171 but it's not enabled by default. And not enabled in any of the deployments. We should enable it by default and work with existing deployments to make sure it works there.

**Comment by nbeloglazov** [comment]
@mferhut this is mostly tracking bug. There is not much context on it.

**Comment by nbeloglazov** [comment]
Met with @gwendolyngoetz and Vinay from Seattle. Enabling standard logout OIDC flow through their IDCS is not working. Here is the logout url that CiviForm creates and redirects user to during logout:

https://idcs-f582fefb879b4db5a88a370e8f2f6013.identity.oraclecloud.com/oauth2/v1/userlogout?post_logout_redirect_uri=https%3A%2F%2Fstaging.seattle.civiform.com%2F&client_id=bc51d5ddae25436c89db4b57a86ce5b1

But it says "Invalid logout request.". We thought that the problem was that `post_logout_redirect_uri` wasn't registered in IDCS and that's why it rejected request. Vinay added that url and it still didn't work. Instead Vinay suggested to use custom logout url: https://qalogin.seattle.gov:12443/#/logout?appName=CIVIFORM_STAGE. Basically this ignores OIDC spec and works around it. From brief testing it seemed to work: after logout I was redirected to the civiform site.

Agreed that Vinay is going to contact Oracle regarding why standard logout flow is not working. Meanwhile I'll look into adding support for custom logout url that will be used by Seattle.

**Comment by mferhut** [comment]
@nbeloglazov Was there a log out issue that required confirmation messaging to the admin that they're logging out of the identify provider for all applications? I believe we chatted with @bion regarding this. Can you tag me on that and let me know the ux priority.

**Comment by nbeloglazov** [comment]
@mferhut I created 2 videos demonstrating how login/logout work on login.gov (Arkansas) and Access Indiana (Bloomington). It also shows an issue with Access Indiana.

login.gov: https://drive.google.com/file/d/1A6pkQkhwE5W4HzJyF9o3pEjVmt5MGViA/view?usp=share_link

Access Indiana: https://drive.google.com/file/d/1OiUZu4YQHQA4kzW0HoqqyWoNZKB863ec/view?usp=share_link

On CiviForm side we don't control what auth provider is showing to the user. In fact each provider is doing it slightly differently: 

* login.gov: show confirmaion "do you want to logout" and then redirects back to the CiviForm
* Access Indian: shows "you successfully logged out" message and doesn't redirect the user back to the CiviForm
* auth0: logs out user without confirmation and redirects the user back to the CiviForm

I don't think we can do much here given that we don't control auth provider's logic. But we'll need to look into Access Indiana and see if we can improve it on their side.

@bion were you thinking of some UX changes on CiviForm side?

**Comment by inghamn** [comment]
I've been digging deeper into OpenID sign out, and this *may* be a case if Access Indiana implementing the spec correctly.

https://openid.net/specs/openid-connect-frontchannel-1_0.html

The spec for this says to use an iframe on the Identity Provider's sign out page to load the logout URL of the client application (in this case CiviForm).  Browsers that block thirdy-party content (which I have enabled in all my browsers) block this capabilllity.

I think what might be happening when the browser loads the CiviForm logout URL as an iframe on a third-party website (aka Access Indiana), there is no session cookie information available in the iframe load.  It is blocked by the browser (and rightfully so).  

So, users are, in fact logged out of Access Indiana; however, they still have the CiviForm session cookie alive in their browser.  The only way to purge that is to get the user to follow a link back to the CiviForm logout URL.

**Comment by inghamn** [comment]
It turns out the Access Indiana developers expect the id_token_hint paramter to be included when sending a user back to AI to sign out.  They use this to determine which session to invalidate.

https://openid.net/specs/openid-connect-rpinitiated-1_0.html

Access Indiana does not redirect back to CiviForm, but instead provides a link the user must follow.

All of the parameters are optional; the id_token_hint is the only recommended one.
