### ISSUE TITLE
Default address does not display

### ISSUE THREAD

**Issue by elisekalstad** [civiform/civiform#3630]
**Describe the bug**
As a CiviForm Admin, I'd like to be able to set "Washington" as the default state for all address questions. This would prevent erroneous address entries (WA, Wash, Washington, Wa$hingt0n) and ensure a consistent address export. The default, however, does not display within the forms. It also appears the Address question type does not save any changes to the default state.

**To Reproduce**

_As a CiviForm Admin_
1. Go to an address question type (i.e. Mailing Address)
2. Click on 'Default State'
3. Select 'Washington'
4. Save
5. Republish

_As a resident_
6. Try to complete the form as a Resident and see that the default state does not show.

_As CiviForm Admin_
7. See that the address question type did not save the selected default state.

**Expected behavior**
I would expect the selected default state to show on any forms that use an address question type. I would expect that the selected default state would save on the question.
[Default Address not visible.pdf](https://github.com/civiform/civiform/files/9758806/Default.Address.not.visible.pdf)

**Screenshots**
Attached

**Additional context**
The Default State would only show for future forms. For example, we won't be back and fix any inconsistent data prior to the default state being set. But any forms published or republished with a default state address question component should show going forward.

**Comment by nbeloglazov** [comment]
@elisekalstad question that came up from reviewing Swathi's fix for this issue. Should applicant be able to override "State" from default to something else? If not - we should rename "Default state" to something else as it's not longer "default" but rather "forced" or "hardcoded" (probably there is a better word for that).

**Comment by elisekalstad** [comment]
@nbeloglazov Good question! The applicant should not be able to override it; it should be hard coded. (Sorry for the slow response!)

**Comment by nbeloglazov** [comment]
@elisekalstad do you have an idea of how to call that field? I just don't like "forced state" or "hardcoded state". They might not be clear.

**Comment by elisekalstad** [comment]
@nbeloglazov How about "persistent"? or "constant"?

**Comment by nbeloglazov** [comment]
I like "persistent". And we can add a note underneath saying that "user can't override state". @swatkat1 WDYT?

**Comment by swatkat1** [comment]
Thank you @nbeloglazov. I think 'fixed' sounds better to be. As it is fixed, it can't be overridden.

**Comment by msprenke** [comment]
Closed, no longer relevant
