### ISSUE TITLE
Question that asks for date is followed by address fields instead of date fields in Arkansas staging

### ISSUE THREAD

**Issue by jessbumblebee** [civiform/civiform#3645]
**Describe the bug**
The Arkansas staging environment  asks the question "what was your end date at <company name>"
However the fields following that are address fields rather than date fields
See attached screenshot.
I suspect that it's not a software bug and can be fixed by a CiviForm admin for Arkansas

**To Reproduce**
Go to the staging environment 
https://dev-adjusted-rattler.azurewebsites.net/loginForm?message=login
Fill in the form until you reach the step in the attached screenshot
Look for the question "what was your end date at <company name>"

**Expected behavior**
Question should be a followed by a date selector

**Actual behavior**
There are address fields

**Screenshots**
![Screenshot 2022-10-13 at 16 46 04](https://user-images.githubusercontent.com/26064282/195669668-14feffac-6327-4425-a86f-f3281b582249.png)

**Comment by bion** [comment]
@cassandralfernandes do you know if this is still a concern? Would be nice to close this issue since it's not a development-related task

**Comment by nb1701** [comment]
This does still appear to be an issue in staging.

**Comment by gwendolyngoetz** [comment]
@dkatzz Do you know if this is still a problem?

**Comment by dkatzz** [comment]
Adding @avaleske who has been attending the Arkansas meetings, but I think this is fine to close. As far as I know they've been testing their programs in production and it doesn't look like they have any questions like this there.

**Comment by avaleske** [comment]
> Adding @avaleske who has been attending the Arkansas meetings, but I think this is fine to close. As far as I know they've been testing their programs in production and it doesn't look like they have any questions like this there.

Closing this out. They've just finished user testing with their prod instance, so anything like this still around would've been caught.

Also removed the bug label, since this isn't a software issue.
