### ISSUE TITLE
Missing ability to change status for existing programs

### ISSUE THREAD

**Issue by elisekalstad** [civiform/civiform#3646]
**Describe the bug**
As a Program Admin for an existing program, I would like to be able to update an applicant's status. For any existing programs (ones that were created more than a few weeks ago) I do not see the button to change an applicant's status. I can set statuses, enter status translations, but I cannot then update the status for an application.

**To Reproduce**

1. Login as a Program Staff for an existing program (such as Gold Card)
2. Click on "View" next to one application
3. See that the button to update an applicant's status is missing

**Expected behavior**
I would expect that all programs, even existing ones, would have the ability to change application status within the Application Review page.

**Screenshots**
Attached
![Mising Status Feature on Existing Programs](https://user-images.githubusercontent.com/86082659/195718306-97134864-9da7-4d8c-bba5-670c92815f21.jpg)

**Additional context**

**Comment by shanemc-goog** [comment]
The available statuses are versioned to a program the same way Questions are, and similarly Applications are tied to a specific Program version.

So if an applicant applies to a program version that doesn't have statuses, a Program Admin can't apply a status to it.  Similar to if the Program version didn't have a Question the Application won't contain the answer to that question.

In this manner the possible Statuses can evolve as the Program evolves too without impacting previous versions.

We could make bootstrapping allowances such as Applications on Program versions without statuses use the first statuses set on the Program.  That would require prioritization.

**Comment by shanemc-goog** [comment]
FYI @cassandralfernandes

**Comment by elisekalstad** [comment]
I think this is actually just fine, I'm going to close the bug for now. Program staff can continue with the manual status update (i.e. an email) until they have their statuses and messages ready to go. And any new applications that come in will have that feature. thanks for the quick response and explanation, @shanemc-goog !

**Comment by elisekalstad** [comment]
Functioning as expected
