### ISSUE TITLE
Standardize button UI across all pages

### ISSUE THREAD

**Issue by nbeloglazov** [civiform/civiform#3659]
CiviForm has 2 types of buttons. Old rectangular ones and new rounded buttons. The new buttons were added after the recent admin UX redesign. Still there is a number of places where the old-style buttons are used. We should revisit them and update. It's mostly mechanical work of finding calls of `BaseHtmlView.submitButton` and updating them to use `BaseHtmlView.makeSvgTextButton` where appropriate (where we can add an icon) or just add `AdminStyles.PRIMARY_BUTTON_STYLES` or `AdminStyles.SECONDARY_BUTTON_STYLES`. 

It would be great if we had utility functions like `createPrimaryButton` and `createSecondaryButton` but it's challenging to do with j2html as the library prevents adding extra classes to the already created element. 

Example of old buttons:
![image](https://user-images.githubusercontent.com/252053/196308760-54b42dea-76e1-46ed-802e-cc18810ad6f2.png)

Example of new buttons:  
![image](https://user-images.githubusercontent.com/252053/196308777-23ce2537-2895-4cf5-830b-cf3cc5721217.png)

**Comment by lwsm99** [comment]
I would like to work on this issue

**Comment by nbeloglazov** [comment]
Hi @lwsm99. 

Feel free to join our [slack channel](https://docs.civiform.us/governance-and-management/governance/communication#slack-channels) where we discuss project-related things and generally sync. Also it's a good place to ask questions if you have some issues with development setup. If you feel like it - please introduce yourself on #introductions channel. 

As for working on this issue - feel free to open PRs. Currently no one is working on it and there is a bunch of place where we use old-style buttons. So it's quite easy to parallelize.
