### ISSUE TITLE
OpenJDK Vulnerability Advisory: 2022/10/18

### ISSUE THREAD

**Issue by shanemc-goog** [civiform/civiform#3674]
https://openjdk.org/groups/vulnerability/advisories/2022-10-18

We're on 11.0.16_8

Need a new image to be available I believe at
-  https://hub.docker.com/r/amd64/eclipse-temurin/
- https://hub.docker.com/r/bellsoft/liberica-openjdk-alpine

**Comment by nbeloglazov** [comment]
eclipse-temurin still haven't released updated version. Looking at the vulnerabilities it seems like they affect java running on client-side and untrusted code. Java running server-side is not affected.

**Comment by gwendolyngoetz** [comment]
Still no new release yet.
