### ISSUE TITLE
Route TI directly to TI Dashboard upon initial login

### ISSUE THREAD

**Issue by elisekalstad** [civiform/civiform#3696]
**Is your feature request related to a problem? Please describe.**
I need a way to prevent TIs from going directly to the Program Card Page when helping a client apply to a program because they miss out on the benefits of the “Add a Client” flow and are stuck with one client’s data hogging the form. 

**Describe the solution you'd like**
I believe that by routing TIs directly to the TI Dashboard upon login they will use the “Add a Client” feature and not experience the confusion they currently experience because they are essentially using CiviForm as a Resident. I also believe that renaming the TI Dashboard to something more actionable, such as **“View and add clients”** will help Tis to continue to return to the dashboard to add and edit applications across multiple applicants, see feature request https://github.com/civiform/civiform/issues/3695. 

**Additional context**
Feedback was received with El Centro staff.

**Current User Flow:**
- Login to CiviForm
- See Program Card page
- Select program and enter data for 1st client
- Submit application
- Select program for 2nd client
- See that CiviForm stored information from their 1st client

**Proposed User Flow:**
- Login to CiviForm
- Routed directly to the TI Dashboard (now called “View and Add Clients”
- Add a client
- Complete a program application
- Select “View and add clients” to add 2nd client
- See that program application is blank and ready for the 2nd client

**Screenshots**
[IT Dashboard Flow_Proposal.pdf](https://github.com/civiform/civiform/files/9834271/IT.Dashboard.Flow_Proposal.pdf)

Translations: TI Experience does not include translated UI text. Are TI expected to navigate CiviForm in English or in-language?

**Done when**
A TI logs into CiviForm and is routed directly to the TI Dashboard (now called "View and Add Clients")

**Comment by swatkat1** [comment]
@bion -  I was working on it but not right now. draft PR - https://github.com/civiform/civiform/pull/3752
