### ISSUE TITLE
Set up initial TypeScript unit test

### ISSUE THREAD

**Issue by natsid** [civiform/civiform#37]
Once we decide on a unit test framework (probably either Jest or Jasmine), we should write a test as an example, both to encourage writing tests with code from the start, and to get TS tests set up with our CI.

Done when we have a passing TypeScript unit test that runs as part of our CI.

**Comment by natsid** [comment]
Taking this out of milestone for now. We don't need this now, and it remains to be seen if/when we will need this.

**Comment by natsid** [comment]
We still don't have any unit tests for the TypeScript code. May still be a good idea to implement unit tests at some point as the TS codebase grows.

**Comment by shanemc-goog** [comment]
Bion: We have brower-test, do you know if this was referring to those before they existed or is this discussing function level testing of typescript?

**Comment by bion** [comment]
@shanemc-goog yeah this is referring to unit/function-level typescript tests
