### ISSUE TITLE
Add confirmation prompt when deleting a screen

### ISSUE THREAD

**Issue by gwendolyngoetz** [civiform/civiform#3766]
We should consider adding a confirmation prompt when a program admin clicks the 'delete screen' button on the edit program page. Since there is no undo option they could lose a lot of work if the button is accidentally clicked.

I don't see the same need for the delete button for individual questions since those can be re-added easily from the question bank.

**Comment by cassandralfernandes** [comment]
When this issue is picked up, reach out to @mferhut for thoughts on the UX/UI

**Comment by michaela559** [comment]
hello, can i try?
