### ISSUE TITLE
Error during account sign up

### ISSUE THREAD

**Issue by inghamn** [civiform/civiform#3768]
When coming to CiviForm for the first time, a citizen must sign up for the identity provider.  This sign up process can take a while. By the time the citizen finishes the account creation with the identity provider, the session is usually invallid and the site errors out when they return.

In my case, signing up for Access Indiana took me 15-20 minutes.  When I finally logged into Access Indiana, the Civiform session was no longer valid and shows a nasty error message.  Closing my browser completely (to kill cookies) and going back to CiviForm, I was able to successfully log in.

I suspect most of our citizens will take a similar amount of time to work through creating their account with the identity provider.  If possible, it might be good to delay the session instantiation until login completes, rather than at the home screen.

**Comment by rasmi** [comment]
@nbeloglazov FYI!

**Comment by rasmi** [comment]
Another alternative is to clear the session and redirect to the login page if there is a timeout.

**Comment by nbeloglazov** [comment]
Avritt and I looked into it today. I started a chat on slack about that issue.

**Comment by inghamn** [comment]
What is happening is that even though the login was initiated from CiviForm, users have to create their account in Access Indiana first.  Access Indiana has a whole process for people to go through to create their account.

Once a person finally has an Access Indiana account, they initiate a brand new login attempt initated from Access Indiana.  This flow is not supported in CiviForm, so it errors out.

I have initiated a service configuration change with Access Indiana to just send users to the home page of civiform.  Users will need to click on the login link again, be redirected back to Access Indiana, and then be redirected back to CiviForm again.

**Comment by inghamn** [comment]
Access Indiana now sends users to the CiviForm homepage when they have a user already logged in to Access Indiana.  I think we're all set here.

**Comment by rasmi** [comment]
@nbeloglazov Is there some sort of login timeout in place that closes/clears the session and redirects CiviForm users to the login screen to prevent the "nasty error message" Cliff saw? Any way to fail gracefully here?

**Comment by inghamn** [comment]
I should rename this ticket to better reflect the real problem we discovered.  The problem was not a timeout thing.  Instead, it was that CiviForm did not support authentication intiated from Access Indiana.

We told Access Indiana to just send citizens to the CiviForm home page and have citizens click the CiviForm login link to start the process again.

**Comment by nbeloglazov** [comment]
Also to answer @rasmi questoin, there is no timeout on CiviForm session. Once created it stays active until user logs out or "ends session" which usually means closes browser. Play uses [session cookies](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#define_the_lifetime_of_a_cookie) for that. Play seems to have an option to set TTL for cookies but we are not using it.

**Comment by nbeloglazov** [comment]
I'm going to close this issue. Cliff resolved it on Access Indiana side.
