### ISSUE TITLE
Image in Program Card

### ISSUE THREAD

**Issue by elisekalstad** [civiform/civiform#3783]
**Is your feature request related to a problem? Please describe.**
Residents, CBOs, and City Staff have all mentioned that having images in the program card would help to know who the program serves. It's quicker to digest images than text. Would it be possible to add an image to the program card?

**Describe the solution you'd like**
As the CiviForm Admin, I would like to be able to upload an image that displays on the program card.

**Additional context**
Screenshots below and attached:
![image](https://user-images.githubusercontent.com/86082659/200976304-8205b696-789b-44c4-93ec-ac1e5e215462.png)

![image](https://user-images.githubusercontent.com/86082659/200976337-253afd5f-9509-4573-96b3-156d4fd4d383.png)

**Done when**
There is an upload box on the main program edit page. Uploaded photo shows on the program card. Supports JPEG, PNG, GIF images at a minimum.
[Image in Program Card.pdf](https://github.com/civiform/civiform/files/9976380/Image.in.Program.Card.pdf)

**Comment by bion** [comment]
I thought there may be a way to do this using existing functionality, but I'm afraid not.

This will likely require creating a way for admins to upload images to the file storage backend (S3) and then reference those images somehow in the question definition. Recommend collaborating with @mferhut on what admin and applicant UI for this could look like.

**Comment by mferhut** [comment]
@cassandralfernandes Let me know the priority on this on when to pick this up.

**Comment by rasmi** [comment]
See #979 (closed as duplicate) for more discussion.

**Comment by elisekalstad** [comment]
Behavioral economics research: https://docs.google.com/presentation/d/1q7atQDjFbaBeP2QbHt32PyijOtFVV_KCvoR7xBPfFd0/edit#slide=id.g24d728ee21f_0_0

**Comment by msprenke** [comment]
This is being worked under https://github.com/civiform/civiform/issues/5676. Closing this item
