### ISSUE TITLE
Allow Address Correction in CiviForm (Phase 1)

### ISSUE THREAD

**Issue by cassandralfernandes** [civiform/civiform#3835]
### Epic Overview
There is a need for CiviForm to ensure that addresses are formatted consistently, are valid addresses, and to autosuggest address corrections. Address correction functionality, along with ensuring addresses fall within a specified geographic area, are key to enabling eligibility verification 

### Problem Statements(s)
To qualify for many civic programs, a resident must live within a given geographic area (e.g within state, city, or more specific regional boundaries). In the current experience, an admin can add address-type questions to programs in CiviForm, but manual address entry leads to typos, formatting errors, missing information, and wrong addresses being entered. Additionally, there is greater friction for the applicant if they need to type their entire address and do so without mistake. Program administrators also experience significant friction and wasted time connecting with applicants to manually correct and validate addresses. Goals:

- Reduce the number of invalid addresses that are submitted in CiviForm applications 
- Reduce the friction (typos, mistakes, and time) for applicants to enter their full and correct address.
- Reduce the time Program Administrators take to manually fix applicants' incorrect addresses.

### Product Requirements
[Address Correction PRD](https://docs.google.com/document/d/1qF_6I_gLgsQLpClnkeAf6HL1h-US9V2VWAnl1KysGAc/edit?resourcekey=0-7baAK4hMbE7MOVz6daJGHQ)

### Design & Eng Requirements
Mocks & design doc to come

**Comment by gwendolyngoetz** [comment]
Been done for a long time.
