### ISSUE TITLE
Logout does not logout from Access Indiana

### ISSUE THREAD

**Issue by nbeloglazov** [civiform/civiform#3863]
**Describe the bug**
When I click "log out" it takes to Access Indiana page that says that I was sussesfully logged out. But when I try to log in again through civiform - it doesn't ask for my login and password. Instead it logs me in immediately indicating that on Access Indiana I am still logged in to CiviForm.

**To Reproduce**

1. Go to https://civiform.bloomington.in.gov/loginForm
2. Click "log in" and log in through Access Indiana.
3. Click "log out"
4. See "Access Indiana" page with "you have successfully signed out" message.
5. Go back to https://civiform.bloomington.in.gov/loginForm and try log in again.
6. You are immediately logged in without entering login/password.

**Expected behavior**
Login attempts after log out should ask the user for login/password.

**Screenshots**
Here is the screenshot of Access Indiana logout page:
![image](https://user-images.githubusercontent.com/252053/204832316-12813b84-9ec9-4bd6-a894-046d471c63c0.png)

**Comment by nbeloglazov** [comment]
@inghamn can you take a look at the bug and see if it makes sense to you? Or maybe current logout behavior working the way you expect?

**Comment by inghamn** [comment]
It is working as Access Indiana expects it to.  Going to the logout screen in Access Indiana gives you a list of the websites that you have used AI to authenticate.  On the logout screen, they are prompting users to choose which applications to log out of.

On the right, where it lists "Your Recent Apps", it has a button to actually log out of the websites listed (that's where CiviForm is listed).  Until you click the "Sign out of all my recent apps" button, you're still considered logged in to those web sites listed.

**Comment by nbeloglazov** [comment]
I see, thanks for checking! So "you have successfully signed out" means that I successfully signed out from CiviForm but not from "CiviForm on Access Indiana". Personally I find it a bit confusing. But looks like it works as intended form Access Indiana point of view. 

Going to close this issue.

**Comment by inghamn** [comment]
I have sent an email to the Access Indiana developers asking for clarification on the expected sign out process.  I'll post any updates here.

**Comment by inghamn** [comment]
I received the answer from Access Indiana developers. ...

Access Indiana is expecting the id_token_hint parameter in order to know which client is signing out.

https://openid.net/specs/openid-connect-rpinitiated-1_0.html

**Comment by nbeloglazov** [comment]
Thanks Cliff! That's useful info. I'll look into how to add id_token_hint and see if it helps.

**Comment by nbeloglazov** [comment]
I tested with adding `id_token_hint` to the logout request. It seems to be working as in it logs me out from AccessIndiana account. The problem is though the wording says that it logged me out from the AccessIndiana and all its applications: 

![image](https://user-images.githubusercontent.com/252053/209246284-ff39250a-acd1-4c05-bcf7-c0dff8ef8a50.png)

This is what Cliff was mentioning previously and behavior he and Greg didn't want. I hoped that it would log me out *only* from CiviForm part of AccessIndiana, but the wording says otherwise. So I'm not sure whether we should go ahead and enable it. It's up to Cliff/Greg.

For posterity I'll give some details on my hacky local implementation. The idea is that we want to store `id_token` JWT string that we get during login in session and then pass it as `id_token_hint` to the logout request. 

1. Original id_token can be retrieved from within `OidcProfileAdapter.create` method, from Credentials object: `((OidcCredentials) cred).getIdToken()` 
2. I couldn't figure how to attach id token to session. Cookie-based sessions have limit of 4k size and also seems we shouldn't be storing id token in cookie as it might be exposed to end user (and also push cookie over 4k limit as id toke is 1.2k). For local testing I just stored id token in a public static variable.
3. To pass id token to logout request in `CiviformOidcLogoutActionBuilder.getLogoutAction` it can be added to `extraParams` map that is passed to the `CustomOidcLogoutRequest` constructor.

**Comment by bion** [comment]
@inghamn is there still an issue that needs resolving on the CiviForm side of things for this?

**Comment by inghamn** [comment]
The only thing that would be CiviForm's responsibility would be sending the `id_token_hint` parameter in the logout request when sending a user back to the OIDC Provider (AccessIndiana) to log out.

At that point it's up to the OIDC Provider ( AccessIndiana) to decide whether they log users out of everything or not.  AccessIndiana uses the `id_token_hint` to know which which session the user is wanting to log out of when the user arrives back at the OIDC Provider's logout url.

**Comment by bion** [comment]
@seanmalbert FYI

**Comment by MichaelZetune** [comment]
https://user-images.githubusercontent.com/30369272/219420201-6b43d979-81e8-4fdf-9be0-0145d6f23ce8.mp4

Made a screen recording of the issue for posterity, above.

**Comment by MichaelZetune** [comment]
I've been working on this for a little while now. Still haven't figured out how to resolve this, but I'll note a few updates here:

* As noted above, we need to pass the `id_token_hint` parameter to the logout URL action. Normally, this is done automatically for us by Play  in the `getLogoutAction` method of [`OidcLogoutActionBuilder`](https://github.com/pac4j/pac4j/blob/master/pac4j-oidc/src/main/java/org/pac4j/oidc/logout/OidcLogoutActionBuilder.java), by using the `OidcProfile`'s ID token.
* We override this class with [`CiviformOidcLogoutActionBuilder`](https://github.com/civiform/civiform/blob/main/server/app/auth/oidc/CiviformOidcLogoutActionBuilder.java), which overrides `getLogoutAction`, and does not account for the ID token we need to pass. It's not entirely clear why we need to do this - it's not clearly documented. The only obvious reason is that `getLogoutAction` expects a `UserProfile` (a base class) as the third param, which is usually an `instanceof` `OidcProfile` but for some reason in our codebase it ends up being an `instanceof` `CiviformProfileData`, and `CiviformProfileData` does not contain an id token
* Adding an ID token member to `CiviFormProfileData` is tempting, but it isn't clear where to add it, where to get it from, or where the pac4j framework is getting the exact `CiviFormProfileData` instance from when it internally calls (our implementation of) `getLogoutAction` in `CiviformOidcLogoutActionBuilder`.

Many attempts at getting and passing the ID token are [here](https://github.com/civiform/civiform/commit/1f05c1d94dc43ae3c94c8d5562afa1cad596c214) for posterity.

My main point of confusion is why we need to do this at all; given that the Play framework has code to handle this with `OidcProfile` objects, why are we overriding so many of their methods in ways that preclude us from using their default code? What does `CiviFormProfileData` give us that `OidcProfile` can't do? Can't we just add more attributes to the `OidcProfile` and avoid having a custom class?

**Comment by MichaelZetune** [comment]
As referenced above, I believe #4359 will resolve this issue. It's a more significant refactor, but I believe it will be worth waiting it out instead of tackling this issue on its own.

**Comment by yotommy** [comment]
Closing this since #4359 is complete.
