### ISSUE TITLE
Hitting "return" should not trigger form submission

### ISSUE THREAD

**Issue by nbeloglazov** [civiform/civiform#3872]
**Describe the bug**
When admin creates a question and fills question data - they might hit "return" button, for example when creating a dropdown question and adding options for the dropdown. "return" is expected to add a new option. Currently "return" triggers form submission which seems to be default form behavior in html. We should disable it. 

**To Reproduce**

1. Go to https://staging-aws.civiform.dev/
2. Login as CiviForm adming and go to Questions tab.
3. Create new dropdown question. 
4. Scroll to "Question settings" and click "Add answer optino".
5. Add value and click "return"
6. Page is refreshsed with error message saying that question can't be created.

**Expected behavior**
Page should not be refrehsed/form submitted.

**Comment by cassandralfernandes** [comment]
@mferhut  for visibility

**Comment by nbeloglazov** [comment]
Found this somewhat article about that issue. And comments are interesting to read: https://www.tjvantoll.com/2013/01/01/enter-should-submit-forms-stop-messing-with-that/

**Comment by nbeloglazov** [comment]
Personally I didn't even know that hitting "enter" on any form field triggers submission. I think it's reasonable to disable this behavior for forms on admin side (e.g. new question page). 

But not so sure about applicant pages. There we need to consider accessibility more. I don't know whether from accessibility point of view forcing user to navigate to "submit" button and click it is bad. Compared to submitting form from any field by hitting enter. To me navigating to "submit" button and clicking it seems reasonable, but I'm not using screen reader. 

@mferhut @jeanniefu do you know if "submit on enter" behavior is important to screen readers? Or maybe everyone expects that they need to click on a some button anyway.

**Comment by jeanniefu** [comment]
I'm not sure - I'm checking with our a11y contacts (cc'ed you @nbeloglazov @mferhut). I can update here once I hear back.

For this admin bug, could we just change the behavior of the return button for that particular use case you described? For example, I notice that on the enumerator applicant page, hitting "return" adds another enumerator instead of submitting. On other pages, it submits.

**Comment by nbeloglazov** [comment]
This was a complaint from admin that question was submitted unexpectedly when they hit enter while adding dropdown options for a dropdown question. Of course we could disable it only for question creation page, but same issue might happen on other pages as well. I'd rather do app-wide default behavior if it doesn't violate any requirements.

**Comment by jeanniefu** [comment]
To recap the offline discussion with our a11y contact, @nbeloglazov's proposed solution to disable submission on hitting "enter"/"return" key sounds good.
