### ISSUE TITLE
Error when editing a program

### ISSUE THREAD

**Issue by elisekalstad** [civiform/civiform#3887]
**Describe the bug**
As a CiviForm Admin, I'd like to edit a program. When I select "Edit" on a specific program, I see an error page with this text: "_services.program.ProgramBlockDefinitionNotFoundException: Block not found in Program (ID 1079) for block definition ID 1_" and this URL: **https://civiform.seattle.gov/admin/programs/1079/blocks/1/edit**.

I have a work-around: I just remove a section of the URL: **/blocks/1**

**To Reproduce**

1. Login as a CiviForm Admini
2. Navigate to the Program Dashboard
3. Select "Edit" next to one program

**Expected behavior**
Would expect to be routed to the "Edit" page for the program.

**Screenshots**
![image](https://user-images.githubusercontent.com/86082659/206028522-005a314f-82b5-4233-a14b-0775238594cd.png)

Attached

![Error in program edit](https://user-images.githubusercontent.com/86082659/206028513-4cdf3d54-d412-44af-9ce7-86f4477bb789.jpg)

**Comment by shanemc-goog** [comment]
The Issue appears to be a recent change to take the user directly into the block editor rather than through the Description editor.

The change loads `/blocks/1/edit` however the number is a unique block ID (Block ID 1) and not a positional value (1st block)

If you add a second block then delete the default original block, then block ID 1 will never be a valid block.

The Manage Questions button on the Description Editor links to `/blocks` which appears to find the correct first block to go do.

**Comment by seanmalbert** [comment]
@shanemc-goog ,
Before I get the fix up, `/blocks` redirects to the last block. You can see that it gets the last block [here](https://sourcegraph.com/search?q=context:global+long+blockId+%3D+program.getLastBlockDefinition%28%29.id%28%29%3B+repo:civiform/civiform%24+rev:refs/heads/main&patternType=standard&sm=0) and passes to `edit`. Do you know why we would want the last block vs the first block?

I see three options:
1. update ProgramView.renderEditLink to link to `/blocks` as is which will cause it to link to the last block
2. do step one and update AdminProgramBlocksController.index to get the first block
3. create a new method AdminProgramBlocksController.redirectToFirstBlock and corresponding route and use that

**Comment by shanemc-goog** [comment]
Only thing I can think of is that it's trying to help the CiviForm Admin "pick up where you left off" with the assumption that is the end of the Blocks.

I believe the intent of the previous change was to achieve parity with the existing behavior (just remove the extra step) so I see no problem with #1

**Comment by nb1701** [comment]
@elisekalstad @msprenke Is this happening on the latest version?  I don't seem to be able to reproduce it locally.

**Comment by elisekalstad** [comment]
I haven't had this issue for months. Good to close!
