### ISSUE TITLE
Use of @Transactional without ebean enhancement

### ISSUE THREAD

**Issue by bion** [civiform/civiform#3979]
[ProgramServiceImpl](https://github.com/civiform/civiform/blob/main/server/app/services/program/ProgramServiceImpl.java) makes heavy use of the `@Transactional` annotation. The intention is to associate all database interaction within the scope of a given ProgramService public method with a single transaction.

However `@Transaction` depends on [EBean enhancement](https://ebean.io/docs/enhancement/) to actually have any effect, and CiviForm is not currently using EBean enhancement. The result is that the actual transaction semantics of ProgramService methods is different from what developers expect based on the annotation.

## Option A: remove the annotations and use explicit transactions
- [ ] remove the annotations
- [ ] audit all code paths in the service and add explicit transactions where needed

## Option B: enable EBean enhancements

> [!NOTE]
> The Play EBean Enhancement has been removed. The EBean enhancer is still a possibility, but they recommend using both an IDE plugin and a build or runtime tool.

- [ ] enable for prod build in sbt
- [ ] test integration with IntelliJ to ensure dev workflows are usable
- [ ] update CiviForm developer docs

**Comment by melanie-exygy** [comment]
Closing this because we are no longer using the @Transactional annotation in the `ProgramService`.
