### ISSUE TITLE
Docker issues: ApplyLayer exit status 1 stdout:  stderr: lchow.... invalid argument

### ISSUE THREAD

**Issue by jessbumblebee** [civiform/civiform#4014]
Since mid December the below and similar error messages have been observed when we build civiform, first on Swathi’s machine and lately also on Gwen’s and Jess’ machine. They occur under slightly different circumstances on the three Linux machines. Shane is not seeing the same problems on his Linux machine.

failed to register layer: ApplyLayer exit status 1 stdout:  stderr: lchown /code/server/[node_modules](https://sourcegraph.com/github.com/civiform/civiform/-/blob/formatter/formatter.Dockerfile?L56:29&subtree=true)/escodegen/node_modules/optionator/CHANGELOG.md: invalid argument".

Please find a full description in the doc below and update the "things we tried" section in the doc if you try out additional things to keep them all in one place.

https://docs.google.com/document/d/1DFLH-y0Sxh2cdlmk1IoY-FNEws8Lj6bVTm5ROeCEmFA/edit#

**Comment by gwendolyngoetz** [comment]
@nb1701 Didn't we fix this?

**Comment by gwendolyngoetz** [comment]
I'm going to close cause I haven't seen any complaints about it for ages either.
