### ISSUE TITLE
Edit link for an active program without drafts causes error every time after the first ever created screen is removed from the program

### ISSUE THREAD

**Issue by jessbumblebee** [civiform/civiform#4029]
**Describe the bug**
When you edit a program, remove the screen that was created first, publish all programs and then edit the program again, an error message is shown complaining that the first screen does not exist. 

I investigated and this is caused bye the value "1" being hardcoded AdminProgramController.newVersionFrom()

https://github.com/civiform/civiform/blob/1dd788827166557ab4c87d2786976617ce6ea06c/server/app/controllers/admin/AdminProgramController.java#L144

**To Reproduce**

1. Log into civiform as a program admin
2. On the program dashboard, choose any program and click edit (either on the draft or the active version)
3. On the left hand side you can see all screens of the program, choose the one that was created first. You can find it by clicking on each of them on the left until you find the one where the url reads something like https://staging-azure.civiform.dev/admin/programs/22/blocks/1/edit. The "1" tells you that this is the oldest screen
4. Delete the screen by clicking "delete screen"
5. Click back
6. On the program Dashboard click "publish all programs", you should see only active programs now, no drafts
7. Next to the program you just edited, click Edit

**Expected behavior**
The edit view should open

**Actual behavior**
An error is shown:
services.program.ProgramBlockDefinitionNotFoundException: Block not found in Program (ID 22) for block definition ID 1

Severity:
Not a total show stopper, but we should fix this fairly soon. While it won't happen all the time, once a program has been affected by it, the bug occurs after each program publishing for as long as the program exists.

**Comment by nb1701** [comment]
Look up the program, find the first block ID, use that instead of 1.
