### ISSUE TITLE
Eliminate unedited submissions of applications - perceived duplicates

### ISSUE THREAD

**Issue by elisekalstad** [civiform/civiform#4033]
**Is your feature request related to a problem? Please describe.**
Program Admins receive duplicate applications (we're not sure why residents submit multiple applications, but it's a big slow down across all programs). It would help if there was a way to reconcile the applications; i.e. decide which one to keep and which to archive/delete so that Admins and Residents are only communicating around 1 application.

**Describe the solution you'd like**
A way for Program Admins to select the duplicate applications and then identify which one to keep and which to archive/delete.

**Additional context**
Consider a way to use the status feature to send the applicant an email that an application appears to be a duplicate and was archived.

**Done when**
What conditions need to be met before this issue can be closed?

**Comment by msprenke** [comment]
Setting this as a P3.  We have initiatives to prevent duplicates which may be where we need to focus our efforts.  Reconciling duplicates may be a task best left to the CRM software (or spreadsheet) used by the receiving department.

**Comment by msprenke** [comment]
This part of https://github.com/civiform/civiform/issues/4022

Duplicates are a result of CiviForm allowing an applicant or TI the ability to start an edit and submit it without changes causing what appears to be a duplicate.  Proposed in PRD that this no longer be allowed to occur or not display these type of edits to be displayed to the program admin.  https://docs.google.com/document/d/1WgrjiPNc27ZcimyqGeCjaFCeScaPnx-e7rEIYk9GylY/edit?usp=drive_link

@sijiayam is working on mocks for a redesign of the application display for Program admins and this should be included in that redesign effor.

**Comment by msprenke** [comment]
As a part of this work is a requirement from Freshbucks to be able to not allow application edits of any kind and to direct the applicant to contact program staff.

**Comment by msprenke** [comment]
Closing to be tracked with https://github.com/civiform/civiform/issues/4869 where a duplicate issue was captured and work is in progress
