### ISSUE TITLE
Transfer name field from Trusted Intermediary Client into forms

### ISSUE THREAD

**Issue by melissakessler** [civiform/civiform#4035]
**Is your feature request related to a problem? Please describe.** 
When working as a trusted intermediary, adding a Client requires that you input a First and Last Name.  However, when you go to apply to a program for that Client, often times the program has a name field required and what has been entered in the Client profile does not auto populate.

**Describe the solution you'd like**
It would be great if the Name entered from the client profile auto populated any name based fields in programs.

**Done when**
Association of Client Name fields to question type "name."

**Comment by isabelcshaw** [comment]
This could be a bug or it could be added training needed. @isabelcshaw to follow up

**Comment by isabelcshaw** [comment]
Closing this issue because @rockycodes system actions work resolves this
