### ISSUE TITLE
Clean up question text for document uploads

### ISSUE THREAD

**Issue by elisekalstad** [civiform/civiform#4060]
**Describe the bug**
Document upload questions now have hard-coded text to give phone users instructions. Prior to that enhancement, I added support text to the document upload questions with the same instructions. It's now redundant and question text needs to be cleaned up.

**Screenshots**
![image](https://user-images.githubusercontent.com/86082659/212378118-123e380b-f295-4a59-aee2-844706e28ccf.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by elisekalstad** [comment]
@msprenke -- I believe this is done. Good to close?

**Comment by msprenke** [comment]
Yes, Completed!
