### ISSUE TITLE
Bug when editing screen visibility

### ISSUE THREAD

**Issue by elisekalstad** [civiform/civiform#4090]
**Describe the bug**
As a CiviForm Administrator, I'd like to update the visibility of a screen on the test form, "Discounts on Parks and Recreation Programs; Upcoming Cycle open Summer 2023 - Spring 2024".  I'd like to make one of the screens only visibility IF the applicant is interested in Preschool Summer Camps. I received a few different odd outcomes:
1) The question that determines visibility doesn't show up in the list of options
2) I get an error message when I try to edit the visibility condition, attached

**To Reproduce**

1. Login as a CiviForm Administrator
2. Go to the testing form "Discounts on Parks and Recreation Programs; Upcoming Cycle open Summer 2023 - Spring 2024"
3. Open the screen for "Preschool Summer Camps"
4. Try to set the visibility to show "Preschool Summer Camps" ONLY if "Interested in programs 20232024" = "Preschool Summer Camps"
5. See error OR see that there is no option to set the visibility condition to "Interested in programs 20232024"

**Expected behavior**
I would expect to be able to select "Interested in programs 20232024" as an option for a visibility statement

**Screenshots**
![image](https://user-images.githubusercontent.com/86082659/214140719-f3c6f96b-f19c-41ff-a411-83b07c9a9c05.png)
**Desktop (please complete the following information):**

Windows 10

Chrome

**Comment by bion** [comment]
@elisekalstad did you end up checking in with @gwendolyngoetz about this?

Are you still able to reproduce it?

**Comment by elisekalstad** [comment]
I'm rebuilding the form now, I'll test it and get back to you, @bion And loop in @gwendolyngoetz , if it's still giving an error. Thanks for checking in!

**Comment by elisekalstad** [comment]
Rebuilt the parks form and it works great! Guessing there was too much editing back and forth on questions, visibility conditions, and re-order of screens. I'll re-open, if there are future issues.
