### ISSUE TITLE
'Assign Issue to Project' Action Runs as Specific User

### ISSUE THREAD

**Issue by gwendolyngoetz** [civiform/civiform#4112]
Leyla's account is being used by the [assign issues to project action](https://github.com/civiform/civiform/blob/main/.github/workflows/assign_issues_to_project.yaml). Probably best to have this be a bot or someone actively on the project be the one this runs as.

Example
![image](https://user-images.githubusercontent.com/195162/214941473-91d5a624-90df-4dbd-a642-20fcb09b4c09.png)

**Comment by reemaka** [comment]
The PAT also expires in September so this would have to be replaced eventually.

**Comment by reemaka** [comment]
I was originally thinking we could use GITHUB_TOKEN for this, but it looks like that's not supported by the Action.
