### ISSUE TITLE
Add Renovatebot To Other Repositories in Org

### ISSUE THREAD

**Issue by gwendolyngoetz** [civiform/civiform#4129]
We should have rennovatebot configured for all the other repositories that have code or github actions in them to make sure everything is staying up to date.

**Comment by nb1701** [comment]
Already on cloud-deploy-infra, don't need it on docs or the template repos.

**Comment by gwendolyngoetz** [comment]
Renovatebot will also pickup updates for Github actions. The docs and civiform-staging-deploy should get them.

**Comment by gwendolyngoetz** [comment]
Done
