### ISSUE TITLE
Enable integration testing of ESRI functionality

### ISSUE THREAD

**Issue by bion** [civiform/civiform#4167]
ESRI integration (for address correction and service area validation) is currently not tested either with a fake service in the hermetic test environment or a real service with staging probers. This increases the risk of releasing a version of CiviForm with broken address correction and service area validation.

**At minimum**
The hermetic environment (i.e. running browser tests locally or in CI) should use a fake ESRI server provided via Docker, similar to the fake OIDC server.

**Best effort**
The prober environments should integrate with an actual ESRI server, if possible.

**Comment by gwendolyngoetz** [comment]
This was done a long time ago
