### ISSUE TITLE
Allow an admin to set a default application status for a program 

### ISSUE THREAD

**Issue by isabelcshaw** [civiform/civiform#4174]
**Is your feature request related to a problem? Please describe.**
This feature request aims to address the following problems: 
- Reduce the number of emails and calls to program admins asking about application status by improving communication (both content and speed) with applicants around the status of their applications 
- Reduce the time Program Administrators take to manually update application status - with the number of applications expected for Fresh Bucks, the time required will be not feasible 

[More detailed description can be found in the [**Application Status Management PRD**](https://docs.google.com/document/d/1EbWixfzrWdgDvCBBFW_Mw3KKm8JfXVNg6JlYKGrhMic/edit#)]

**Describe the solution you'd like**
- Using the existing application status feature, the admin can add a new status or select an existing status 
- The admin can set that status as a default 
- The admin can see which status is set to default when they look at their list of statuses 
- (A program is NOT required to have a default application status) 
- When a program has a “default status” added, all new applications to that program are automatically assigned the custom “default status” and the Program’s “custom email” is sent
- Programs with default statuses do not send out the standard “application received” email
- CiviForm applicants with accounts will see the “default status” on their programs view if they have applied (existing behavior) 

**Additional context**
[Detailed mocks](https://www.figma.com/file/4MirFQhWIUeeqkCWkQdjfk/CiviForm---Status-management-features---Public-file?node-id=404%3A27316)

This feature is needed in order to launch Fresh Bucks in Seattle.

**Comment by seanmalbert** [comment]
@isabelcshaw ,

To clarify this point:
> Programs with default statuses do not send out the standard “application received” email

The email sent should use the `Email the applicant about the status change` text instead?
