### ISSUE TITLE
Toggles in questions cause page to reload from the top

### ISSUE THREAD

**Issue by nb1701** [civiform/civiform#4182]
When an admin is creating a screen and toggles something in one of the questions, like "optional" or "address correction", we reload the whole page and the user ends up at the top of the page.  This is a bit annoying from a UX perspective.  Ideally, it would toggle and leave them right where they are in the page.

**Comment by nb1701** [comment]
Actually an issue for more things than just toggles, since we use redirects a lot.

**Comment by nb1701** [comment]
@bion has thoughts about how to make this better.

**Comment by reemaka** [comment]
I used [htmx](https://htmx.org/) to fix this for the [ProgramSettingsEditView](https://sourcegraph.com/github.com/civiform/civiform/-/blob/server/app/views/admin/programs/ProgramSettingsEditView.java?L53), we can do the same here
