### ISSUE TITLE
Program Details link appends as relative path without http(s):// protocol

### ISSUE THREAD

**Issue by seanmalbert** [civiform/civiform#4188]
**Describe the bug**
If a user fills out the `Link to program website` field in program details and doesn't include http:// or https://, then the link is appended to the URL (e.g. https://civiformstage.seattle.gov/applicants/229840/www.seattle.gov).

**To Reproduce**

1. Go to [Seattle staging](https://civiformstage.seattle.gov/loginForm)
2. Click on Program and CiviForm Admin
3. Click to edit a program and edit program details
4. Add www.seattle.gov to the link to program site field
5. publish the program
6. logout and continue as guest to the program cards and click on the program details link

**Expected behavior**
Program details should link out to the URL provided

**Additional context**
Validation should be added to the field to enforce a properly formed URL.

**Comment by isabelcshaw** [comment]
https://github.com/civiform/civiform/pull/4120

**Comment by MichaelZetune** [comment]
During eng meeting we decided the following:

* Adding an interface to force absolute links on hrefs isn't a great abstraction - instead we should ensure that the links are absolute in the database
* We'll add link validation at program creation time to ensure that they are full, absolute links that start with `http://` or `https://`.

**Comment by MichaelZetune** [comment]
The PR above is out for review. I'll check with Matthew after approval, before merging.

**Comment by gwendolyngoetz** [comment]
The program details link no longer allows me to leave it blank. When blank [it is supposed](https://github.com/civiform/civiform/blob/b6d14d681052a2fabd5d8aeba8f40675bd3fd0ea/server/app/views/applicant/ProgramIndexView.java#L314-L320) to default to the program details page. If this is no longer the case we can close again, but should add an issue to an asterisk to the question if it is now required.

**Comment by MichaelZetune** [comment]
Thanks @gwendolyngoetz. I'll fix this before closing the issue; it was not intentional.
