### ISSUE TITLE
Error on website

### ISSUE THREAD

**Issue by elisekalstad** [civiform/civiform#4198]
**Describe the bug**
I tried to open civiform.seattle.gov and received the below error message.

**To Reproduce**

1. Go to https://civiform.seattle.gov/

**Screenshots**
![image](https://user-images.githubusercontent.com/86082659/218143989-fe2234b9-e9e6-4635-8a13-cb926e64e3b9.png)

**Desktop (please complete the following information):**

- windows 10
- chrome
- tried clearing my history

**Additional context**

**Comment by elisekalstad** [comment]
CiviForm now working while on VPN or off VPN.

**Comment by elisekalstad** [comment]
Issue appears to persist if inside the City network, while on VPN, for example. Users outside the City network do not experience the issue.

**Comment by gwendolyngoetz** [comment]
Updated internal DNS and loads again.
