### ISSUE TITLE
Browser tests are flaky

### ISSUE THREAD

**Issue by nb1701** [civiform/civiform#4217]
Ideas:

- [ ] run the find flaky test script on a cron, report results
- [x] look at Brett's browser test PR: https://github.com/civiform/civiform/pull/3389
- [x] figure out what's taking the popup so long

Flaky tests:

- [x] [src/application_navigation.test.ts:149-150](https://github.com/civiform/civiform/actions/runs/4557075631/jobs/8038245538)
   - Fixed in #4539
- [ ] [src/admin_predicates.test.ts:270](https://github.com/civiform/civiform/actions/runs/4547433374/jobs/8017303164)
   - Maybe fixed in #4550. Hard to tell as local runs have been consistently passing.
- [ ] [src/support/admin_programs.ts:774](https://github.com/civiform/civiform/actions/runs/4558582078/jobs/8041625390)
   - May be related to #2018
   - Cannot reproduce flakiness with `bin/find-flakey-browser-tests -n 5 -t application_review.test.ts` and `fit()` on the affected test (`src/application_review.test.ts` uses `admin_programs.ts`)
 - [x] [src/file.test.ts](https://github.com/civiform/civiform/actions/runs/4852129375/jobs/8646731307)
    - `net::ERR_ABORTED` error appears
    - Bion suggests swallowing the error when it happens as it wouldn't interfere with the test's assertions
    - Implemented in #4873

**Comment by nb1701** [comment]
From @gwendolyngoetz : This should help diagnose flaky tests https://github.com/civiform/civiform/blob/main/bin/find-flakey-browser-tests

**Comment by shanemc-goog** [comment]
Fyi: for interacting with the question bank I reduced the animation wait from 1s to 250ms, which saves at least 4 minutes in the test runs. #4131 

If flakyness is around the question bank then that might need upping again, or for the QB interaction detection to be better

**Comment by nb1701** [comment]
Investigate if https://github.com/civiform/civiform/pull/3389 makes the tests less flaky.

**Comment by MichaelZetune** [comment]
Idea from Gwen: consider lowering hardware specs on Docker container to see if that makes the flakiness more apparent locally. See if we can match the GitHub actions specs.

**Comment by gwendolyngoetz** [comment]
Related #4111

**Comment by michaelzetune** [comment]
Closing as lately we haven't been seeing much flakiness in browser tests.
