### ISSUE TITLE
Guest Accounts: Improved Program Admin Search Functionality

### ISSUE THREAD

**Issue by msprenke** [civiform/civiform#4238]
Applications from guests do not show the applicant’s name in the summary list and can not be searched for using the name or email when the applicant calls to check on status. All applications contain a name question type. Allow program admins to search guest account applications by name in the provided search field.

**Comment by msprenke** [comment]
also email and phone number

**Comment by isabelcshaw** [comment]
We've confirmed that if applications use the "pre-seeded" questions for name, then it does show up on the summary list and can be searched for. 

Next steps are to ensure the same is true for email and phone number. 

Meanwhile, we have a larger item open for investigating if this is the long-term implementation we want to pursue.

**Comment by rockycodes** [comment]
Will be done as a part of this work: https://docs.google.com/document/d/10coGz5wuCGyulfM4y7J5vXaKpoH8hAulqVJcevYGpnc/edit#heading=h.efagci2pksiz
