### ISSUE TITLE
Program Details in Not Eligible Message not linked to program website

### ISSUE THREAD

**Issue by msprenke** [civiform/civiform#4240]
Program cards were updated to remove External Website reference and change Program Details to link to the program website configured in the program details. However, the message that applicants receive if they do not qualify includes a Program Details link  that still links to the description.  This needs to be updated to send the applicant to the Program Website.

**Comment by msprenke** [comment]
@swatkat1 what would it take to update this?

**Comment by swatkat1** [comment]
@msprenke  - Will look into this.
