### ISSUE TITLE
Launch Office of Housing (Weatherization)

### ISSUE THREAD

**Issue by elisekalstad** [civiform/civiform#4253]
**Tentative Launch Date**
TBD

**Required features ahead of go-live**
- [ ] Custom eligibility messaging: https://github.com/civiform/civiform/issues/6913
- [ ] Approval from MOS on changes to MOA

**NOT REQUIRED but would make experience better than paper process**
- [ ] Address correction for any address (i.e. those outside Seattle: (add feature request for this one) 
- [ ] Show if outside City but within SCL service area: https://github.com/civiform/civiform/issues/6228

**Staff work-arounds required**

- [ ] IF applicant lives outside Seattle AND SCL service area, staff will need to check the address and then inform the applicant that they do not qualify. There is no way to handle this type of eligibility currently in CiviForm.

**Comment by gwendolyngoetz** [comment]
@Miguel-314 This one is done right? Please close if it is.
