### ISSUE TITLE
Specific CiviForm version number not shown on login page when using 'latest' version

### ISSUE THREAD

**Issue by rasmi** [civiform/civiform#4270]
#4171 enables showing the active CiviForm version on the login page. When deploying with tag `'latest'` and `SHOW_CIVIFORM_IMAGE_TAG_ON_LANDING_PAGE=true`, CiviForm displays the verstion as "latest" rathter than the version number. 

![Screenshot 2023-02-22 16 59 07](https://user-images.githubusercontent.com/2267370/220769951-fc9225a8-d507-49e5-b842-df53cf26d1a7.png)

**Comment by avrittrohwer** [comment]
@rasmi what is the desired behavior?  When CIVIFORM_VERSION is set to 'latest', the docker image tagged 'latest' is pulled.  https://hub.docker.com/layers/civiform/civiform/latest/images/sha256-180920fd9e59644bf81817ae8fcb75d35ff79e21054382cef50aa51be76f4c6b?context=explore for example.  Is having "CiviForm version: SNAPSHOT-fd0aaa0-1677605688" the desired behavior?

**Comment by rasmi** [comment]
I see, I did not realize every commit is pushed to docker and that `latest` pointed to non-release version. 

I think if the code coincides with a release/version number, that version number should be shown. Otherwise, commit tag (if there is no clear release/version number) would be helpful. Ideally this happens even if someone uses `latest` in the deployment script. 

Maybe a longer-term improvement is to change how we use tags in Docker so that `latest` always pulls the most recent release version, and we use some other tag for 'give me the most recent snapshot of `main`'. For me, it is convenient to always use 'latest' because I can ideally just re-run the script with no changes to update my release -- but with the expectation that I'm getting the latest official release.

This is not important right now IMO, we should just re-emphasize with users that the recommended way to deploy is by specifying a specific version number (and maybe warn/ ask for confirmation if they don't use a specific version).

**Comment by avrittrohwer** [comment]
Implementing the above comment is a small change, got it working in my dev deployment: 
![image](https://user-images.githubusercontent.com/17995083/225446998-c7966fbf-3b9b-42d1-aa38-887174453797.png)

**Comment by rasmi** [comment]
That looks great! My impression is that no one except developers/IT staff will want to see the snapshot on the login page, so maybe we can only display that on admin page footers instead. WDYT? 

One more tweak could be to only display the numeric version (and not the snapshot) if the numeric version is available, otherwise just display the snapshot. I'm not sure that 'latest' is ever useful to display since it quickly becomes outdated. I don't feel strongly about any of this and I imagine it's low priority relative to everything else, so it's up to you all!

**Comment by avrittrohwer** [comment]
> One more tweak could be to only display the numeric version (and not the snapshot) if the numeric version is available, otherwise just display the snapshot

I like this idea.  I will update the code so that that snapshot version shown instead of "latest" when CIVIFORM_VERSION="latest" is set in the config file.  Otherwise, if a release version is set in the config file, only the release version is shown and the snapshot is not.

> My impression is that no one except developers/IT staff will want to see the snapshot on the login page

Leslie requested the version being shown on the login page to make it easy to tell what version staging and prod are at
