### ISSUE TITLE
Tracking: Refactor auth package

### ISSUE THREAD

**Issue by michaelzetune** [civiform/civiform#4280]
General tracking issue for refactoring the `app/auth` package. Improvements include but are not limited to:

* Renaming classes and other symbols to better represent their use case
* Restructuring the inheritance hierarchy and using other architectural constructs to more clearly represent the relationships and reuse of logic between classes.
* Factoring out common, redundant, or misplaced logic across files.

**Comment by MichaelZetune** [comment]
Added back the tech-debt tag because I think the current state of the auth package is convoluted and hard to understand, which is something I consider to be tech debt. Nick, feel free to reply if you disagree.

**Comment by michaelzetune** [comment]
Closing this as the issue is relatively subjective, several PRs have been put out for it, and it's been a while since it's been touched.
