### ISSUE TITLE
Sometimes multiple draft programs are created, leading to invalid state

### ISSUE THREAD

**Issue by reemaka** [civiform/civiform#4282]
My local db has gotten into an illegal state a couple of times where I get a `java.lang.IllegalArgumentException: Multiple entries with same key`  at `services.program.ActiveAndDraftPrograms.buildFromCurrentVersions(ActiveAndDraftPrograms.java:35)` . This happened just now when I was on the admin program index page, clicked edit on a draft -> edit program details and then hit the back button twice to go back to the index view.

After examining the db, I see two instances of the program with the same creation timestamp. So I think there might be a race condition occurring. We check if there's an existing draft before creating a new one, but the check isn't included in the Transaction: https://sourcegraph.com/github.com/civiform/civiform@07b99d45996be3dde8c60b4d9167ca953bb7e64c/-/blob/server/app/repository/ProgramRepository.java?L96. One fix might be to wrap the check into the Transaction.

**Comment by nb1701** [comment]
@reemaka Can you confirm exact repro steps?  Possibly working on https://github.com/civiform/civiform/issues/3979 would fix this.

**Comment by reemaka** [comment]
Hasn't happened to me in a while but I think these were the steps:
1. Go to Programs page when logged in as a Program and CiviForm admin
2. Find an active program that has no existing draft.
3. Click edit on that program.
4. Go back to the Programs page
5. Sometimes you'll get the IllegalArgumentException at this point citing multiple programs with the same key, but it's nondeterministic.
6. If you do get the error, examine the db and observe that there were two drafts created for the program with the same create timestamp.

(So actually I think the description I had written originally was slightly incorrect in that you need to edit an active program, not a draft)

**Comment by bion** [comment]
https://github.com/civiform/civiform/pull/5314
