### ISSUE TITLE
Changes to Address not Triggering Correction a Second Time

### ISSUE THREAD

**Issue by gwendolyngoetz** [civiform/civiform#4310]

**Comment by seanmalbert** [comment]
@gwendolyngoetz , one way we could solve this for addresses that have been corrected, is by checking if the address question on app/controllers/applicant/ApplicantProgramBlocksController.java LN 490 is in the address JSON stored in session. It looks like updating the singleLineAddress set in EsriClient to match the format of AddressQuestion.getAnswerString() to make the checking easier.
