### ISSUE TITLE
Allow links to be clickable in custom program confirmation message

### ISSUE THREAD

**Issue by msprenke** [civiform/civiform#4354]
The custom application confirmation message configured in the program details page does not make https link clickable.  It would be helpful if urls could be clickable to help redirect applicants to additional program information without copy/paste

**Comment by msprenke** [comment]
any possibility of allowing line breaks as well?

**Comment by gwendolyngoetz** [comment]
> any possibility of allowing line breaks as well?

Yes.

![image](https://github.com/civiform/civiform/assets/195162/10e7e43c-9a63-4c80-92e8-bc0514c17241)
