### ISSUE TITLE
Tracking: Login, Language, Landing Improvements

### ISSUE THREAD

**Issue by michaelzetune** [civiform/civiform#4360]
Login, Language, and Landing improvements cover many aspects of the appearance and flow of CiviForm. They are separated into two phases listed in the Roadmap section.

# Resources
* [Figma](https://www.figma.com/file/tUV2i9QdFU2zQqZWg7Xl5g/CiviForm---Login%2C-Language-and-Landing-page-improvements-(public-link)?node-id=0%3A1&t=9tp2Cwid20GSgSfx-0)
* [Login, Landing, Language PRD](https://docs.google.com/document/d/1FuUapOmoaJNFkRtiCdOL8jSL5jUHuwr-VB0mP3kVgM8/edit?resourcekey=0-NggpmrHtGAmjetAhQy3s4g#heading=h.7yz7m0ei3bzh)
* [Easier Login PRD](https://docs.google.com/document/d/1S9rPRo8kobrmqNd8pRx3UM4-Wj7sgDitPYwknf0PAPU/edit#heading=h.en2991pfhoac)
* [CiviForm Guest Account Analysis](https://docs.google.com/document/d/1Ye2YsSPyHdN6WFvkYqp2pYPdW7M-xG0HS8tZAN21SEQ/edit)
* [CiviForm Login & Guest Account Messaging PRD](https://docs.google.com/document/d/1jpH9bjUuNIwQFKTtUgZtADtVEeQkt7x1P4NiIKjzQP4/edit)

# Roadmap
All changes include accompanying mobile changes on Figma.

1. #4364
2. #4365
3. #4705
4. #4367

## Archive
* #4366
* #4369

**Comment by mferhut** [comment]
Regarding the login prompt for users, there are two options: v1 which is showing the login UI in a dialog is ideal however I imagine there's a heavier lift for this. If that's the case using v2 is okay, which is using our simple dialog and including copy.

Regarding using the tooltip on the login page, it may make sense to just include all copy vs some in a tooltip. However, I reached out to Seattle team for preference and waiting to hear back.

**Comment by MichaelZetune** [comment]
Thanks! Will watch out for your update about the tooltip.
