### ISSUE TITLE
Investigate Translations for Civic Entity-specific UI Components

### ISSUE THREAD

**Issue by MichaelZetune** [civiform/civiform#4408]
There are some new mocks that call for civic entities to be able to customize the text onscreen outside of questions or programs (which have an admin "Manage Translations" interface).

The copy in question is the line "This is the same account as your utility bill" below:

![224736376-2028f2af-ed5c-4016-9ecd-582e5a3b664b](https://user-images.githubusercontent.com/30369272/225651654-e09d76fa-b2d6-4202-ba18-d080e402ab08.png)

Since this line is specific to Seattle, it must be either an environment variable or otherwise customizable from the admin's perspective (not every civic entity will have their logins inline with utility bill accounts). However, we cannot take language for Seattle and check it into the repo with translations.

There are a few potential next steps here:

1. Add environment variables for all languages (`LOGIN_HINT_TOOLTIP_EN_US`, etc.) and allow those in charge of deployment to fill them out. 
   * **This is not ideal** - it adds language complexity to the environment variables in a way that it isn't designed for.
 2. Add an environment variable **only for English**. When using CiviForm in other languages the text would not appear. 
    * This would cut down on the technical debt this introduces. 
    * Seattle has expressed equity concerns with only showing a message for English-speaking users, so this solution is at most a stop-gap.
 3. Extend the admin translations UI to allow for frontend text to be translated by the admin. Similar to [`QuestionTranslationView`](https://github.com/civiform/civiform/blob/6ddda40f0682e83f07e7cb784e058bc34e1038b7/server/app/views/admin/questions/QuestionTranslationView.java#L31) and [`ProgramTranslationView`](https://github.com/civiform/civiform/blob/6ddda40f0682e83f07e7cb784e058bc34e1038b7/server/app/views/admin/programs/ProgramTranslationView.java#L34), this would give admins the ability to localize strings for the frontend.
    * This is a significant design change, but could be worth it as future opportunities to allow entities to change frontend text appear.
    * This would require database schema changes in order to persist the translations, just like we persist program and question translations.
 4. Create a list of "login hints" that includes "This is the same account as your utility bill", with regular translations in `messages` files. Create an environment variable that shows 0 or 1 of these hints, which could include other strings (i.e. "this is the account you use to pay your state taxes" in the future). If the set of strings are generic enough, maybe it isn't a problem to support them like this.
 5. Reject this copy from appearing in CiviForm.

**Comment by MichaelZetune** [comment]
cc @bion - interested in your thoughts from an architectural perspective.

**Comment by avaleske** [comment]
We're probably going to need a place for additional admin-configured strings, such as the link out to the state of Arkansas site here:
https://docs.google.com/presentation/d/1rNP7cQPRRnnGk-pAYYTQWjLknObZvYNZrApRbHQnfso/edit?resourcekey=0-I-ivd7Qp2M5yIYW4ESPY9g#slide=id.g1f449759d58_0_388

**Comment by bion** [comment]
For option 2: isn't this view only shown before the applicant has indicated a language preference so we'd be unable to show anything other than english anyway?

**Comment by MichaelZetune** [comment]
Not quite. In my testing if we change the `Accept-Language` header, it shows the login screen in that language. Example:

<img width="1468" alt="image" src="https://user-images.githubusercontent.com/30369272/226684993-4671d3d0-b932-4353-9245-31291d91edf5.png">

**Comment by MichaelZetune** [comment]
Bion pointed out we can use a singleton (single row) database with a Json object serialized similar to [`BlockDefinition.java`](https://github.com/civiform/civiform/blob/predicate-age/server/app/services/program/BlockDefinition.java) and make a new admin UI to handle these admin-defined settings. I'll look into this and update this issue soon.

**Comment by MichaelZetune** [comment]
From product sync meeting:

* We want to put in more thought into the admin UI translations page, including design and a PRD that clearly states how we are going to approach this.
* Since that will take time, the **tooltip with login hint will be the last piece I implement on this project**.
   * If the PRD is finished by the time I get to that piece, then I will design it as the document specifies
   * If not, I will use environment variables to specify all languages for this tooltip (in a new `.conf` file). This will be technical debt we will address after the admin strings UI is finished.

**Comment by MichaelZetune** [comment]
Since this issue is for investigation and we have chosen a path, I've made #4483 and will close this one out.
