### ISSUE TITLE
Show eligibility status on the question level of admin application PDF export

### ISSUE THREAD

**Issue by dkatzz** [civiform/civiform#4455]
**Describe the solution you'd like**
This is a follow-up to adding this information to the [applications view](https://github.com/civiform/civiform/issues/4446). We should also show question level eligibility on the PDF export.

**Comment by nb1701** [comment]
@elisekalstad @swatkat1 How important is this for Seattle?

**Comment by elisekalstad** [comment]
> @elisekalstad @swatkat1 How important is this for Seattle?

P2--It would make things more efficient for program admins but it doesn't stop them from reviewing and processing applications. If it becomes a larger burden, we'll be sure to communicate a change in priority.
