### ISSUE TITLE
Enable applicants to download and print completed applications

### ISSUE THREAD

**Issue by elisekalstad** [civiform/civiform#4506]
**Is your feature request related to a problem? Please describe.**
A group of Trusted Intermediaries mentioned that it's helpful to print the completed program application for a resident/client to take with them. Residents often want the physical form to take with them. They mentioned it can be helpful if the residents seeks services from multiple CBOs, they can take their application to the next TI.

**Describe the solution you'd like**
An option on the application confirmation page that allows the applicant (TI or resident) to download then print the completed application.

**Additional context**
It would be helpful if it included all completed questions as well as a printout of any uploaded documents. There may be data privacy concerns with the email option, would want to check with Privacy on this. 

**Done when**
Resident or TI can completed application. 

![image](https://user-images.githubusercontent.com/86082659/228313499-ea679225-ddc7-430d-8b61-7a61accbd1ad.png)

**Comment by elisekalstad** [comment]
@swatkat1 is considering this feature as a good project for summer intern.

**Comment by elisekalstad** [comment]
This was a feature requested during listening sessions with community-based orgs (digital navigators) on April 25th.

**Comment by msprenke** [comment]
Possibly change to just download as PDF.  Adobe can print from there and possibly open users email application.

**Comment by elisekalstad** [comment]
![image](https://github.com/civiform/civiform/assets/86082659/30db3094-1625-4284-9864-d8c76108d9cb)

**Comment by sijiayam** [comment]
For responsiveness, I recommend laying out the information side by side, so on mobile buttons can stack. Here's a mockup!

<img width="575" alt="image" src="https://github.com/civiform/civiform/assets/116591382/c9247b5e-81a8-48f8-9975-9eb9914cdc94">
