### ISSUE TITLE
"Phone number" question type: implement bare-bones

### ISSUE THREAD

**Issue by neel-a-mehta** [civiform/civiform#452]
This question is a variant of the Text question type that creates a special phone number entry widget.

![image (10)](https://user-images.githubusercontent.com/77128518/110846546-e3d56980-8279-11eb-946e-ab7e32582a8e.png)

This graphic shows a useful design pattern for making phone number input fields:

![image](https://user-images.githubusercontent.com/77128518/110846537-e041e280-8279-11eb-8195-a4191928811c.jpg)

Crucially, only numbers can be inputted; all the other formatting (parentheses, dashes,e tc.) is automatically applied. This minimizes the amount of user confusion and potential validation errors.

Make it possible for UAT admins to create, and for applicants to fill out, questions of this type. Answers should be saved to a database. Configuration options and validation criteria aren't necessary yet.

See context for question types at https://github.com/seattle-uat/universal-application-tool/wiki/Question-type-requirements-notes

**Comment by neel-a-mehta** [comment]
[See this wiki page](https://github.com/seattle-uat/civiform/wiki/Adding-a-new-question-type) to learn how to add a new question type to the codebase!

**Comment by neel-a-mehta** [comment]
Heads up: the CiviForm admin we're working with at the City of Seattle (Elise) has requested phone numbers as the next question type we add support for. I'm bumping its priority up a little as a result.

**Comment by neel-a-mehta** [comment]
You may want to use the `<input type="tel">` HTML tag when showing this to the user -- it pops open the familiar "number pad" keyboard on phones.

![image](https://user-images.githubusercontent.com/77128518/118327481-b4d6b080-b4d3-11eb-934c-8087793a5118.png)

**Comment by neel-a-mehta** [comment]
You may want to use the `<input type="tel">` HTML tag when showing this to the user -- it pops open the familiar "number pad" keyboard on phones.

![image](https://user-images.githubusercontent.com/77128518/118327481-b4d6b080-b4d3-11eb-934c-8087793a5118.png)

You can also get access to the [`pattern` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attr-pattern).

**Comment by thomasphung** [comment]
I can see if I can tackle this issue

**Comment by elisekalstad** [comment]
Continues to be an issue for the programs onboarded to CiviForm.

**Comment by elisekalstad** [comment]
@thomasphung Are you still working on this feature? Not to worry, if not! This is a priority feature for the Seattle programs, just want to see how we can support the work.

**Comment by nbeloglazov** [comment]
I don't think anyone is working on that. We got this request while working with Arkansas on a demo program. Phone is a common question in forms and we should support it. 

@cassandralfernandes let's add it to the "admin UX" epic for Q4?

**Comment by bion** [comment]
Discussed implementation with @nbeloglazov, the likeliest path for getting a good UX for this is to use an existing open source JS library for phone number inputs. If we can find a stable library it's ok to vendor (i.e. copy the distribution code) into our repo, unless a suitable webjar is available.

**Comment by elisekalstad** [comment]
Fresh Bucks asked if it's possible to have the formatting auto populate.
