### ISSUE TITLE
Fix flaky tests

### ISSUE THREAD

**Issue by MichaelZetune** [civiform/civiform#4536]
TODO(@MichaelZetune): elaborate on this issue

- run the find flaky test script on a cron, report results
- look at Brett's browser test PR: https://github.com/civiform/civiform/pull/3389
- figure out what's taking the popup so long

**Comment by bion** [comment]
Flaky tests:

- [src/application_navigation.test.ts:149-150](https://github.com/civiform/civiform/actions/runs/4557075631/jobs/8038245538)
- [src/support/admin_programs.ts:774](https://github.com/civiform/civiform/actions/runs/4558582078/jobs/8041625390)
- [src/admin_predicates.test.ts:270](https://github.com/civiform/civiform/actions/runs/4547433374/jobs/8017303164)

**Comment by bion** [comment]
duplicate of https://github.com/civiform/civiform/issues/4536

**Comment by MichaelZetune** [comment]
> duplicate of #4536

Think you meant #4217. Thanks!
