### ISSUE TITLE
TiDashboard view is broken in STAGING

### ISSUE THREAD

**Issue by swatkat1** [civiform/civiform#4577]
**Describe the bug**
TiDashboard view is broken.

**To Reproduce**

1. Login as a TI
2. View is broken.

**Expected behavior**
UI components needs to be aligned.

**Screenshots**
https://civiformstage.seattle.gov/admin/tiDash?page=1
![image](https://user-images.githubusercontent.com/101214724/229940283-e4aa8ba8-0390-4345-a767-4630c005528d.png)

**Desktop (please complete the following information):**

- Observed in chrome and Bing.
- Unable to see it in Firefox

**Smartphone (please complete the following information):**

**Additional context**

**Comment by msprenke** [comment]
This appears to be in STAGING only.

**Comment by bion** [comment]
Part of fixing this should include adding a screenshot validation in the browser test for it to ensure it doesn't happen again

**Comment by swatkat1** [comment]
This is a weird issue. I see it in Chrome and Bing and not in Firefox. The snapshots looks fine in the code- https://github.com/civiform/civiform/blob/main/browser-test/image_snapshots/trusted_intermediary_test/dashboard-with-one-client.png
