### ISSUE TITLE
Replace Arkansas Specific Value in Config

### ISSUE THREAD

**Issue by gwendolyngoetz** [civiform/civiform#4677]
Some Arkansas specific strings are set in the main config file. Need to make sure their deployment is updated with correct values and replace these with non-civic entity specific value. 

https://github.com/civiform/civiform/blob/0ed40707f7e79645c1cea546ebf5463f57e15940/server/conf/application.conf#L86-L93

**Comment by gwendolyngoetz** [comment]
@reemaka FYI. Tracking bug

**Comment by reemaka** [comment]
Confirmed with Arkansas that they've set the values in their config so we're good to change these whenever.
