### ISSUE TITLE
Highlighted item in drop down has rounded edges

### ISSUE THREAD

**Issue by reemaka** [civiform/civiform#4688]
**Describe the bug**
Hovering over a drop down item in the admin UI shows it with rounded edges rather than non-rounded edges as expected.
![Screenshot 2023-04-25 at 4 01 28 PM](https://user-images.githubusercontent.com/7339672/234389960-9b54a49f-5918-4140-b84c-e235c7691362.png)

**Comment by reemaka** [comment]
@MichaelZetune FYI

**Comment by MichaelZetune** [comment]
Sigh, didn't realize those were buttons too...will fix and add a screenshot test.

**Comment by MichaelZetune** [comment]
Fixed in #4689
