### ISSUE TITLE
Add a tool for removing the "-recevied" suffix from updated snapshots

### ISSUE THREAD

**Issue by reemaka** [civiform/civiform#4695]
In #4685 I updated the browser test snapshot validation to store the updated snapshots instead of just the diff. This allows you to copy the update snapshots without re-running the browser tests. However, the snapshots are saved with a "-received" suffix due to a limitation of the library, so you have to manually remove the suffix to update the snapshots. It would be useful to have some sort of tool that makes this easier, e.g. a script that removes the suffix and maybe copies it into the appropriate directory.

**Comment by gwendolyngoetz** [comment]
Here's a starting point for a full script. This works on Ubuntu, but I'm not in front of my Mac to try it there.

`find . -type f -name "*-received.png" -exec bash -c 'mv "$0" "${0/-received.png/.png}"' {} \;`
