### ISSUE TITLE
Create a job that cleans out empty guest accounts

### ISSUE THREAD

**Issue by michaelzetune** [civiform/civiform#4719]
**NOTE:** this is deprioritized until it is actually necessary due to database storage issues.

#4704 will make CiviForm create a new Applicant record every time someone visits the landing page for the first time. This is because we no longer have a login page where users click "Continue as Guest" - instead, they are a guest the moment they open the programs index page.

Because of this, it's possible that there will be many empty records in the database for these guests that are not used. We can create a job that automatically purges these from the database to save space.

However, we'll wait until this becomes a problem before taking it on. This bug just tracks that future effort if it is required.

**Comment by MichaelZetune** [comment]
cc @bion @gwendolyngoetz

**Comment by bion** [comment]
fixed by https://github.com/civiform/civiform/pull/5742
