### ISSUE TITLE
TI Client's Email missing in forms

### ISSUE THREAD

**Issue by elisekalstad** [civiform/civiform#4723]
**Describe the bug**
Tis add basic information on each client to the client roster. The client’s name and date of birth populate on any applications. The email address does not.

**To Reproduce**

1. Log in as a TI
2. Add a new client (name, email, dob)
3. Apply to a program with question types: Name, Email, Date of Birth
4. See that the Name and Date of Birth are already populated but the Email is missing

**Expected behavior**
The email address entered on the initial client contact form carries forward to any programs that ask for email question type

**Screenshots**
![image](https://user-images.githubusercontent.com/86082659/235732807-15628746-3860-419f-b0cf-4e39e74cc3f0.png)

**Comment by msprenke** [comment]
Email doesn't appear to populate for direct applicant submissions as well.  Can we look into making the standard email question a seeded question tied to applicant email and client email in their profile?

**Comment by swatkat1** [comment]
The email question is not part of the seed question. Though it can be! (Today we have only two questions- Name and Dob). If Email should be part of the seeded question, I think we should look up the Client's/Profile email address. Let me if this is a feature request.

**Comment by gwendolyngoetz** [comment]
@melanie-exygy / @swatkat1  This was fixed right?

**Comment by swatkat1** [comment]
yes fixed!
