### ISSUE TITLE
Set up custom 404 page

### ISSUE THREAD

**Issue by neel-a-mehta** [civiform/civiform#474]
**Describe the solution you'd like**
This page should ideally show some clever message and point users back to the homepage. [See this article](https://designshack.net/articles/inspiration/what-makes-a-great-404-error-page/) for 404 page best practices.

**Done when**
Any mistyped URL takes users to a 404 page, which redirects them to the homepage or other important pages. Don't worry about trying to fix typos in the URL or anything.

**Comment by ScotttP** [comment]
First time open source contributor here.

I would like to have this assigned to me.

Are there any style guides to follow?

**Comment by carolinedanzi** [comment]
Hey Scott, welcome! Let me check on style guides - anything you create will be better than the current default

**Comment by carolinedanzi** [comment]
Our PM recommended looking into Tailwind (https://tailwindcss.com/) components related to 404 - might be a good starting place if you'd like!

**Comment by ScotttP** [comment]
Sounds good, thank you for the information!

**Comment by syntapy** [comment]
I'll do this one
