### ISSUE TITLE
Enable editing configuration settings in CiviForm Admin UI

### ISSUE THREAD

**Issue by reemaka** [civiform/civiform#4762]
**Is your feature request related to a problem? Please describe.**
Add a UI for CiviForm admins to update configuration variables

**Describe the solution you'd like**
[PRD](https://docs.google.com/document/d/1QV0hT6yi4D6DQkkVniMo6aqT4aqVIfopvhI8rn9yFZI/edit#heading=h.x9snb54sjlu9)

**Comment by rasmi** [comment]
Related to #4948

**Comment by reemaka** [comment]
Duplicate of #4948
