### ISSUE TITLE
Use X-Forwarded-For for IP checking on AWS deployments

### ISSUE THREAD

**Issue by bion** [civiform/civiform#4775]
We currently use [`WebContext.getRemoteAddr`](https://github.com/civiform/civiform/blob/main/server/app/auth/ApiAuthenticator.java#L117) to determine the remote IP address when authenticating API requests. When CiviForm is deployed on AWS, this value will refer to internal AWS resources (such as load balancers) rather than the actual API client IP address.

When CiviForm is deployed in AWS it should instead refer to the [`X-Forwarded-For`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For) header for retrieving the client's IP address.

**Comment by avaleske** [comment]
We need to split `X-Forwarded-For` on `,` and take the first one:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For#syntax

```
X-Forwarded-For: <client>, <proxy1>, <proxy2>
```

**Comment by avaleske** [comment]
Confirming that this fix works against staging!

Repro:
- Fetch your IP with `curl ifconfig.me`
- Use that IP to generate an API key
- Use that API key to curl against https://staging-aws.civiform.dev/api/v1/checkAuth
- See a 200!
