### ISSUE TITLE
Allow configurable number of trusted reverse-proxies

### ISSUE THREAD

**Issue by avaleske** [civiform/civiform#4795]
Currently we assume there's only one reverse-proxy between CiviForm and the public internet, so we take the rightmost IP from `X-Forwaded-For` when the `CLIENT_IP_TYPE` is `FORWARDED`.

Per the [MDN docs](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For#selecting_an_ip_address) we should take the rightmost IP that isn't a trusted proxy:
>The count of reverse proxies between the internet and the server is configured. The X-Forwarded-For IP list is searched from the rightmost by that count minus one. (For example, if there is only one reverse proxy, that proxy will add the client's IP address, so the rightmost address should be used. If there are three reverse proxies, the last two IP addresses will be internal.)

This is fixed when there's a `NUM_TRUSTED_PROXIES` flag that's used when selecting a client IP address.

**Comment by yotommy** [comment]
Config updated in [Add NUM_TRUSTED_PROXIES to example config file](https://github.com/civiform/civiform-deploy/pull/59)
