### ISSUE TITLE
Civic Entity Logo in Header Stretches on Mobile Screen Widths

### ISSUE THREAD

**Issue by gwendolyngoetz** [civiform/civiform#4796]
**Describe the bug**
On mobile (or narrow browser windows) civic entity logo becomes stretched.

**To Reproduce**

- Log in as a guest
- View browser in a very small width or on a smart phone.

**Expected behavior**

Logo does not stretch

**Screenshots**

![image](https://user-images.githubusercontent.com/195162/236593226-a0a88696-db78-44cd-a349-25fc2b9992a2.png)

**Smartphone (please complete the following information):**

- Device: LG V60
- OS: Android 13
- Browser Firefox
- Version 111.1.0

**Comment by michaelzetune** [comment]
cc @elisekalstad
