### ISSUE TITLE
TI flow incorrect

### ISSUE THREAD

**Issue by elisekalstad** [civiform/civiform#4816]
**Describe the bug**
As a Trusted Intermediary, the current flow is:
1. Login in as a TI
2. Land on the Program Cards page
3. Click on "Add a Client" 
4. Land on Client Roster page

Landing directly on the Program Cards page is confusing and has led to TIs applying for programs for themselves (not on behalf of clients). To avoid confusion, TIs should land directly on the Client Roster page.

**Screenshots**
Current State
![image](https://github.com/civiform/civiform/assets/86082659/ee152f81-6a4f-4a03-ad46-8a8307e3b618)

Desired Flow (TIs should land on the Client Roster directly after logging in)
![image](https://github.com/civiform/civiform/assets/86082659/47f1e580-a46c-4e1d-9d4e-61f8e21814af)

**Comment by michaelzetune** [comment]
Fixed in #4821
