### ISSUE TITLE
Logging in as FakeAdmin Trusted Intermediary shows "You're a guest user"

### ISSUE THREAD

**Issue by michaelzetune** [civiform/civiform#4825]
**Describe the bug**

Our auth display section on the top right corner either shows "Logged in as yourName" or "You're a guest user". In producation deployments this is fine, but when we log in using `FakeAdminClient` as a trusted intermediary in dev, we get this text that doesn't quite make sense and might confuse engineers.

**To Reproduce**

1. Open CiviForm dev
2. Click DevTools and Trusted Intermediary

**Expected behavior**
We should show something like "Logged in as FakeAdmin TI" or similar to be clear what the auth status is.

**Screenshots**
<img width="1708" alt="image" src="https://github.com/civiform/civiform/assets/30369272/d6f20f88-1bae-4cd8-9ac3-b0de21b8abe7">

**Desktop (please complete the following information):**

- OS: Mac
- Browser Chrome
- Version 112.0.5615.137

**Comment by bion** [comment]
fixed
