### ISSUE TITLE
Deployment system should not allow merging prs if checks fail

### ISSUE THREAD

**Issue by rockycodes** [civiform/civiform#4828]
Example: https://github.com/civiform/cloud-deploy-infra/pull/174#event-9214330146

Fix action so that PRs are only merged once all tests have passed.

**Comment by dkatzz** [comment]
Added branch protection rules for all of these, so now PR's shouldn't be able to be merged without those checks passing

<img width="764" alt="Screenshot 2024-05-15 at 12 22 52 PM" src="https://github.com/civiform/civiform/assets/86739416/e21c5af4-b8a8-4128-9d56-e282e1eab65d">
