### ISSUE TITLE
Translated program names are not displaying

### ISSUE THREAD

**Issue by msprenke** [civiform/civiform#4830]
**Describe the bug**
We are finding that translated program names are not being displayed on the program card or within the application.  The translation is added but not being displayed.

**To Reproduce**

1. go to civiform 
2. login or choose guest
3. change language
4. titles are still in english

**Expected behavior**
program names should be displayed in language of choice when a translation is available for that language.

**Screenshots**
![image](https://github.com/civiform/civiform/assets/106765777/0dfb1467-f17b-409c-adf3-5bb145cdc51e)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by gwendolyngoetz** [comment]
@msprenke I checked the 'All City of Seattle Programs' and 'Gold Card' and they aren't translating the program name. I'm going to close for now, but re-open if this is still a problem after translating them.
