### ISSUE TITLE
Warn applicants before resubmitting application if answers haven't changed

### ISSUE THREAD

**Issue by michaelzetune** [civiform/civiform#4869]
**Is your feature request related to a problem? Please describe.**
Right now, resubmitting an application without changing any answers is possible. AR is concerned that this leads to people resubmitting applications and creating unnecessary duplicates.

**Describe the solution you'd like**
Present a Modal that states that "none of your answers have changed" and confirms the user intends resubmit the application.

Highlight the answers that changed on the review screen.

**Additional context**
AR requests this feature.,

**Done when**
Above.

**Comment by bion** [comment]
FYI @yotommy

**Comment by isabelcshaw** [comment]
@sijiayam to add mocks of modal

**Comment by sijiayam** [comment]
<img width="568" alt="Screenshot 2023-09-18 at 9 34 43 AM" src="https://github.com/civiform/civiform/assets/116591382/da3d2deb-9f87-429b-907c-836e08027ab2">

**Comment by rockycodes** [comment]
Work to detect duplicate applications was done in this PR: https://github.com/civiform/civiform/pull/5292

**Comment by rockycodes** [comment]
Update from conversation with @sijiayam on 10/4:

The design to have a modal popup without a refresh isn't technically possible at this time. We opted instead to show a separate screen with the copy updated to "There are no changes to save for the {Program Name}"

The two sentences in the middle should be one paragraph

"Exit application" should be a button tag with link type styling

**Comment by rockycodes** [comment]
10/6 - a draft of this is ready for review but I'm waiting on translations to come through

**Comment by msprenke** [comment]
This was also captured under #4033 .  I'm closing that ticket to be tracked here.
