### ISSUE TITLE
Manage Admins UI doesn't make it clear what info is needed

### ISSUE THREAD

**Issue by reemaka** [civiform/civiform#4876]
**Is your feature request related to a problem? Please describe.**
The "Manage Admins" UI doesn't make it clear that the text field is for email addresses. We should improve this UX:

<img width="927" alt="Screenshot 2023-05-16 at 9 27 04 PM" src="https://github.com/civiform/civiform/assets/7339672/59ce51ab-da5c-4d05-8abd-16d9aa32c94f">

**Describe the solution you'd like**

**Additional context**

**Done when**
What conditions need to be met before this issue can be closed?

**Comment by yotommy** [comment]
The input box is currently used for two purposes:

- Displaying existing admins
  - The input box is non-editable.
  - The delete button removes this admin.
- Add new admin
  - The input box is editable.
  - The delete button removes the input box.

![image](https://github.com/civiform/civiform/assets/1391583/0683ba34-40dd-43e0-b19e-2f4978b19d33)

It would be cleaner to have separate sections for displaying/managing existing admins vs adding a new one.

**Comment by yotommy** [comment]
The current handling in `ManageProgramAdminsView` allows the user to accumulate multiple addition/deletion actions and then requires the user to press Save to apply them.

It seems like the handling would be simpler if each action resulted in a `POST` with no extra Save step.
