### ISSUE TITLE
[Placeholder] add Google Analytics support to civiform.us

### ISSUE THREAD

**Issue by bpq-g** [civiform/civiform#4951]
Things we should track:
* page hits on all paths
* consistent analytics on cross-site journeys when users navigate from civiform.us to docs.civiform.us subdomain
* form submissions
* outbound link clicks
* search usage
* FAQ clicks (note we should refactor FAQ page so all Qs start collapsed. This requires user to indicate which questions they care about with a 'click' we can measure)

**Comment by rasmi** [comment]
This was completed in: https://github.com/civiform/docs/pull/316
