### ISSUE TITLE
Give TI ability to update user details

### ISSUE THREAD

**Issue by msprenke** [civiform/civiform#4956]
**Is your feature request related to a problem? Please describe.**
If a trusted intermediary misspells a client name during setup there is no way to correct this.  Same if they get a new email address. The only edit function if for Date of Birth.

**Describe the solution you'd like**
The ability for a TI to edit user data including name and email

**Mockups**
<img width="631" alt="image" src="https://github.com/civiform/civiform/assets/116591382/7233c5d2-83d7-4471-94da-3bbc3b515237">

**Notes**
The mockups show updated visual styles with USWDS fields. We are okay to use current form input styles and update the USWDS in a separate issue. 

**Done when**
- There is a back button on the edit page that takes a user to the client list when they click on it
- The page has a h2 page title that says "Edit client information"
- The page has a h1 page title that says the organization name
- There is a dedicated page for users to edit 
- There is a phone number field for users to add or edit information
- Clicking the "Save" button saves the new updated information
- Clicking the "Cancel" button takes a user back to the client list

**Comment by msprenke** [comment]
PRD https://docs.google.com/document/d/14etX_bl3-71o6TdcSSNeYrorJxtgCD5jEayCOBZppdQ/edit?usp=drive_link&resourcekey=0-ACUKnQEe4jT-PCR7V1pFUw

**Comment by elisekalstad** [comment]
Could be a good second project for Zarif

**Comment by msprenke** [comment]
I have updated the design to include a stop if the TI attempts to add an existing email address and the ablility to archive a client if they enter a duplicate.
@sijiayam I would love your input on the mock up in the design

**Comment by msprenke** [comment]
combining with item https://github.com/civiform/civiform/issues/1448 to add notes to client profile. Same functionality that is used by program admins to add notes to an application.

**Comment by msprenke** [comment]
Moving back to scoping due to discussion next week with team on best course

**Comment by msprenke** [comment]
Updated design to include feedback from weekly planning meeting with Exygy on 8/28/23.  Edit design updated to change Update DOB button to and Edit button that introduces a pop up modal where all information can be changed.  Updated design mocks including input from Sijia.  Ready for development with approval in planning meeting.

**Comment by elisekalstad** [comment]
There could be a way to add an "archive" stamp to the account database.

**Comment by sijiayam** [comment]
@swatkat1 I have updated the issue details with a mockup screenshot and some requirements. Please let me know if you have more questions!
