### ISSUE TITLE
Research API Connection to Dynamics 365

### ISSUE THREAD

**Issue by Miguel-314** [civiform/civiform#4974]
DEEL does not do any manual data entry into Dynmics. They are currently using Portal as their digital application tool. Portal automatically creates new user profiles in Dynamics when an applications is submitted through portal. CiviForm will need an API connection to Dynamics. 

Actual requirements for CiviForm will be added as other issues.

**Comment by gwendolyngoetz** [comment]
Swagger schema can be used to create a connect for the power platform if the integration is simple enough for power automate. Other options (custom code or SSIS) can also use the Swagger file to generate code or build their own manually.
