### ISSUE TITLE
Long program screen names or screen descriptions cause formatting issues

### ISSUE THREAD

**Issue by melanie-exygy** [civiform/civiform#5001]
**Describe the bug**
Long screen names cause text to be cut off on the right side of the page and the "Delete screen" button to be out of view. 

**To Reproduce**

1. As a CiviForm admin, go to the Program Dashboard.
2. Select a draft program (or create one) and click on "Edit".  
3. Click the "Add Screen" button on the left.
4. Click "Edit screen name and description".
5. In the "Screen name" text box, type a very long name and/or a very long description. 
6. Click the "Save" button.
7. Notice that the screen name is cut off and you must scroll to the right to see the "Delete screen" button.  Also, notice how the text and "Delete" button are outside of the white container element.

**Expected behavior**
I expect all the text and buttons to stay within the view, without having to scroll to the right.  See below for more technical suggestions.

**Screenshots**
<img width="1440" alt="image" src="https://github.com/civiform/civiform/assets/134556723/ca062d18-d534-438b-9a44-50405f01138f">

**Desktop (please complete the following information):**

- OS: iOS
- Browser Chrome
- Version 113.0.5672.126

**Smartphone (please complete the following information):**

Did not verify on mobile.

**Additional context**
As a technical note, I would suggest adding input field length limitations.  This will also prevent other bugs.  I would also suggest that long descriptions wrap rather than continuing off the page.

**Comment by mepps** [comment]
Hi! I'm new to CiviForm and just set up my local environment. My latest commit locally is from Friday May 26th. I'm on a mac in Chrome version 113.0.5672.126. Interestingly, the screen title displayed with text wrapped rather than scrolling right. I agree a character length limit would be a good idea for this field.
<img width="1245" alt="Screenshot 2023-06-02 at 9 31 46 AM" src="https://github.com/civiform/civiform/assets/4406809/5ac44314-50e3-484f-afa0-6b43f0b2d584">

**Comment by mepps** [comment]
Oh! I realized why I couldn't reproduce this. It's because the text wrap doesn't kick in when it's a single word. If I type an unbroken string of characters, I see the same thing as the screen shot above.

**Comment by melanie-exygy** [comment]
Good catch Maggie!  It does seem unlikely that someone would create a long screen name without spaces, which would lower the urgency of this bug, in my opinion.
Still seems like good practice to have a character limit, though.
