### ISSUE TITLE
Allow Trusted Intermediaries to authenticate with either applicant or staff identity backend

### ISSUE THREAD

**Issue by bion** [civiform/civiform#5017]
# Overview

Trusted Intermediaries currently can only authenticate with the [applicant identity provider](https://github.com/civiform/civiform/blob/bionj-admins-can-see-settings/server/conf/helper/auth.conf#L3). This prevents civic entity staff from assuming the Trusted Intermediary role using their staff accounts.

A workaround is for staff to create TI accounts using the applicant identity provider, but this is not acceptable for civic entities that want the security guarantees of their staff authentication backend.

# UX considerations

Currently, when any staff-authenticated account logs in they are presented with the program index view in the admin layout. If they have the OIDC claim for CiviForm Admin, they are presented with the CiviForm Admin layout. Otherwise they are assumed to be a Program Admin and are shown a list of whatever programs they have been assigned as a Program Admin.

When a staff account logs that is designated as a TI, what should they see? What if they are designated as both a TI and a Program Admin? Also a CiviForm Admin?

# Relevant code paths

- Determining landing page based on user role: https://github.com/civiform/civiform/blob/main/server/app/controllers/HomeController.java#L59-L72
- Adding a new TI (creates a user account with the provided email if one doesn't exist): https://github.com/civiform/civiform/blob/main/server/app/repository/UserRepository.java#L172-L194
- Role creation for ADFS (staff/admin) profiles: https://github.com/civiform/civiform/blob/main/server/app/auth/oidc/admin/AdfsProfileCreator.java#L40-L47
- Role creation for non-staff profiles:
https://github.com/civiform/civiform/blob/main/server/app/auth/oidc/applicant/ApplicantProfileCreator.java#L85-L91

# Updates

* Based on conversation with Arkansas ([notes](https://docs.google.com/document/d/1gBsLGLlskSoAuMaFWLnDL0SyxPX_JLNx-Fw6unZY6ys/edit?resourcekey=0-v__fP947SnRcAsatHfo3eQ#bookmark=id.m7ieta7hoi3h)), we can assume that users will continue to be in exactly one role. This significantly reduces the implementation complexity since we don't need to address the case where a user logs in and needs to make a decision between going to the TI portal or [program|CiviForm] admin portal.

**Comment by michaelzetune** [comment]
From Bion:

> fortunately it doesn't look like too big of an effort, afaict it may only be a matter of adding ROLE_TI in the AdfsProfileCreator and updating the logic for where they get redirected after logging in
worth checking in with PM and UXD on the UX for them though
