### ISSUE TITLE
API response should include all questions that have been in a program

### ISSUE THREAD

**Issue by avaleske** [civiform/civiform#5018]
Consolidating this with #6285 and #5363.

The API currently uses the most recent program version when building the response for all applications, not the program version associated with the application. It also doesn't include questions that are skipped due to visibility conditions.

Instead
- The API response for a program should include all questions that have ever been part of the program
- It should include questions that are skipped due to visibility conditions
- We may need to add a field clarifying why an answer is null, similar to what CSVs show for each option in a multi-option question (see [MultiOptionSelectionExportType.java](https://github.com/civiform/civiform/blob/8d3f882a7bffd4e178a898285b2f9bc3be081882/server/app/services/export/enums/MultiOptionSelectionExportType.java))

**Comment by isabelcshaw** [comment]
@avaleske doing a review and noting this is a P0 bug added several months ago - should we find some time to discuss or is this now obsolete?

**Comment by avaleske** [comment]
This is next on my plate but could probably be labeled a P1 vs a P0. Changing that now.
