### ISSUE TITLE
Check box Questions: Each answer shows in separate column

### ISSUE THREAD

**Issue by msprenke** [civiform/civiform#5020]
**Is your feature request related to a problem? Please describe.**
When a check box button question has multi select answers, all answers show up in one field separated by commas in the CSV which is a problem for reporting.

![image](https://github.com/civiform/civiform/assets/106765777/4de50d84-7d7f-40af-b708-f23e20c5ad09)

**Describe the solution you'd like**
Have multi select answers show each answer in a separate column of the CSV for each possible answer.

**Additional context**

**Done when**
What conditions need to be met before this issue can be closed?

**Comment by msprenke** [comment]
This is a simple design and should not require a PRD.

Example: Question with 3 radio button answers
Question
Answer1
Answer2
Answer3

Display in CSV as:


![Image](https://github.com/civiform/civiform/assets/106765777/de7c396d-d542-44d4-9c3e-086e77cbb219)

**Comment by msprenke** [comment]
Moving to ready to get developer's input on LoE.  Possibly a feature to be turned on/off depending on municipality.

**Comment by elisekalstad** [comment]
(Swathi's comment): consider using a semi-colon to separate values.

**Comment by swatkat1** [comment]
@elisekalstad - just to confirm- for a check box type question (Not Radio question) if there are three answers selected like : 
![image](https://github.com/civiform/civiform/assets/101214724/6142689a-58b5-4c36-b816-4676fdb5f398)
You want the CSV to look like this: 
![image](https://github.com/civiform/civiform/assets/101214724/5b2f1037-9890-4bd9-ba1e-51521d887207)

**Comment by elisekalstad** [comment]
Yes! That looks great!

**Comment by swatkat1** [comment]
Sorry @elisekalstad , This will be a problem. This solution of adding all options will be better. So for a question which contains 5 options like: 
![image](https://github.com/civiform/civiform/assets/101214724/34d23510-c99f-4add-b541-9710bafa5963)
The Export will look like (All 5 columns and only the values picked will have non-empty)- 
![image](https://github.com/civiform/civiform/assets/101214724/663d4933-6218-41d3-a799-f8a4c9fb2293)

**Comment by elisekalstad** [comment]
@swatkat1 --That's perfect!

**Comment by elisekalstad** [comment]
To review with Product Design Committee on 9/6 for approval across jurisdictions.

**Comment by elisekalstad** [comment]
Reviewed with Product Design Committee on 10/11. Preference for more detailed table, added to the PRD: https://docs.google.com/document/d/148WiVgQ-m9vj3fy1HO4cgh-w4BrvZjDaO-B17EMImtA/edit#heading=h.bknox3ib8wpb
