### ISSUE TITLE
Add application lifecycle stage to the API

### ISSUE THREAD

**Issue by avaleske** [civiform/civiform#5029]
This will need a small design doc to ensure we're on the same page about how to expose enums via the API

**Comment by yotommy** [comment]
I see that we already have a method called [`Application.getLatestStatus()`](https://github.com/civiform/civiform/blob/e43afdc8ea74829629ae18185bd6e4c670b5e76e/server/app/models/Application.java#L165-L167). Is this related to application lifecycle? I checked my dev db and see a sample value of `"Pending Review"` (though I think that value was set by the [seeding process](https://github.com/civiform/civiform/blob/e43afdc8ea74829629ae18185bd6e4c670b5e76e/server/app/controllers/dev/seeding/DevDatabaseSeedTask.java#L219)).
