### ISSUE TITLE
Adding "Program Disabled" as part of the program visibility conditions

### ISSUE THREAD

**Issue by swatkat1** [civiform/civiform#5065]
**Is your feature request related to a problem? Please describe.**
Civiform admins have no way to disable a program from public access. Though they have the option to choose, "Hidden from public" as part of the visibility conditions, the public can still access it using a deep link. 

**Describe the solution you'd like**
Civiform admins should have an easy way to disable a program from public access. Even access to it using a deep link shouldn't be allowed.

**Additional context**
For a program admin, the experience will be normal. They will see the submitted applications to the program. 
For a CiviForm admin, the experience will be normal. They can set the visibility to "Disable from public access". This will also stop the program's deep link to be accessed. 
An applicant's experience will be like other visibility conditions. A disabled program will not appear in their home page nor can be accessed via deep link.
A TI's experience will be similar to an applicant experience. They will not see it and cannot access it through the deep link.

**Done when**
The above conditions are met.
Also, a UI indication on the visibility of the programs in the Program's list page will be useful to the CiviForm Admins.

**Comment by elisekalstad** [comment]
@isabelcshaw  to connect with @reemaka and @nb1701 and @swatkat1 via slack -- need alignment on preferred methodology (could be located within "Program Edit" page OR "Visibility")

**Comment by elisekalstad** [comment]
similar to #1375

**Comment by swatkat1** [comment]
PR followup- 

Comments from Danielle - 
Adding that we got this to work, but it isn't a very helpful error message. We'll show the error for now without an attached page and will follow up with an update to do one of the following based on the opinion of Elise and UX:

    Redirect to home page with a toast error explaining that the program was disabled
    Show generic error message (not found page)
    Add specific error message as a specific input to not found page

**Comment by msprenke** [comment]
I pulled the specific requirements for this into a seperate design document https://docs.google.com/document/d/1q7WJqDNhxtAnJ1UkuqIBAnVdZEmg-VatxKKxCftvGNQ/edit?usp=sharing&resourcekey=0-_lahZySh34RQpheoa8kKmg

**Comment by elisekalstad** [comment]
similar to #5806

**Comment by avaleske** [comment]
@azhangggggg did your work close this out?

**Comment by azhangggggg** [comment]
> @azhangggggg did your work close this out?

Yes it does. Good catch! Closing this for now but feel free to reopen it if there are any questions on it.
