### ISSUE TITLE
Using someone else's link to a program throws a 500

### ISSUE THREAD

**Issue by avaleske** [civiform/civiform#5067]
**Describe the bug**
If someone send you a link to a program, it will throw a 500 error.

**To Reproduce**
- From the programs index view, click into a program's application. This will be the program overview page ending in /review
- Copy and paste the URL into an incognito tab and load the page
- CiviForm returns a 500 error

**Expected behavior**
I'm unsure exactly what the expected behavior is, but it seems like it should probably behave the same way a deep link to a program does.

**Comment by reemaka** [comment]
The link includes the applicant's ID so the 500 is because the receiver doesn't have permission to access the sender's applicant data.

**Comment by reemaka** [comment]
> Try redirecting to the link with the user's current ID if permission is denied and the URL doesn't match the URL for the current ID?

One caveat is that we wouldn't want to redirect to the user's current ID if they're a TI

**Comment by melanie-exygy** [comment]
This is no longer reproducible.  Unsure of which commit fixed this, but when following the reproduction steps above, the user is redirected to the landing page rather than getting a 500 error.
