### ISSUE TITLE
Show users they are eligible for programs that don't have eligibility criteria as the default

### ISSUE THREAD

**Issue by Miguel-314** [civiform/civiform#5085]
Two programs don't have eligibility criteria embedded in the form, SPR Childcare scholarships and DEEL preschool program. If an applicant fills out another application and then goes back to the program card screen, they are not alerted that they might also be eligible for these programs. I believe this is a default setting.

**Comment by dkatzz** [comment]
Currently, the behavior is to only show the "may be eligible" tag when:
1) programs have eligibility conditions applied and 
2) the applicant has answered questions in a way that meets the eligibility criteria
so that is why the tag isn't showing in this case. 

If we want to show the may be eligible tag when there is no eligibility conditions applied, we can consider doing that, but this maybe should be implemented as a setting, in case there are sometimes when we don't want to show that tag.

**Comment by elisekalstad** [comment]
One work around is to set eligibility conditions for those programs, but make the criteria VERY generous! For example, Parks doesn't have eligibility criteria, but we could set the income threshold to be $20,000,000 per month, that way it would at least show as "May be eligible" for everyone coming through CiviForm.

**Comment by dkatzz** [comment]
> One work around is to set eligibility conditions for those programs, but make the criteria VERY generous! For example, Parks doesn't have eligibility criteria, but we could set the income threshold to be $20,000,000 per month, that way it would at least show as "May be eligible" for everyone coming through CiviForm.

Yes that's a good point! Just a note though that it would only show once the applicant answered that question. But if its in every program, then once they fill out one application those other programs would show as maybe eligible. Another idea could be using a birth date field and checking if the applicant's age is greater than 1 or something.

**Comment by msprenke** [comment]
@Miguel-314 you noted that SPR Childcare scholarships and DEEL preschool program don't have eligibility criteria in the application.  Does that mean that literally anyone can sign up for these programs or can this be resolved by applying necessary eligibility criteria to the existing programs?

**Comment by Miguel-314** [comment]
This is an intentional choice from the program staff. They want applicants to be able to submit ineligible applications so they can follow up to direct applicants to the right programs. I think there are two opposing goals. Goal 1) properly direct potential applicants to the programs they are most likely to qualify for. The problem is when an applicant reaches an "ineligible screen" there is no opportunity for a warm hand off to the program they are eligible for even though this information can general be know based on the information the applicant has already provided. Goal 2) Allowing all applicants to submit gives program staff more control over the ability to provide those warm hand offs when an ineligible application is received.

**Comment by elisekalstad** [comment]
@gwendolyngoetz -- It looks like the work with the fast-forward feature will satisfied this one. Mind taking a look though?

**Comment by gwendolyngoetz** [comment]
#5541 
#7965
