### ISSUE TITLE
Enhance error pages to be more user-friendly

### ISSUE THREAD

**Issue by melanie-exygy** [civiform/civiform#5097]
**Description**

Currently our generic error page for any type of server error looks like this:  

![image](https://github.com/civiform/civiform/assets/134556723/a5a4112a-7748-4a1c-8cc3-7c0d9d697522)

**Suggested Enhancements**

It would be good to follow a couple of the best practices for error pages.  
- Notifying user of what type of error occured.
- Giving the user a redirect.  Right now, when an error occurs, the only way to get back to the homepage would be through browser navigation arrows or modifying the URL.  It would be helpful to provide a link back to the homepage.  
- Offering next steps.  Can we help users quickly "copy" the error code? Should they refresh the page and check back later?

**Comment by melanie-exygy** [comment]
@sijiayam I created this enhancement issue per our conversation this morning about the error pages.

**Comment by melanie-exygy** [comment]
@rockycodes Do you think your recent work on the error page addresses everything in this issue?

**Comment by rockycodes** [comment]
Yep! Clicking the email address to send an email automatically includes the error code (this was the existing behavior which is nice) and I added a button to redirect to home. Good find!
