### ISSUE TITLE
Admin cannot access programs without going through preview

### ISSUE THREAD

**Issue by rockycodes** [civiform/civiform#5167]
**Describe the bug**
When I login as a program admin via dev tools I cannot see the full list of programs until I complete the program I landed on.

**To Reproduce**

1. Load the homepage
2. Click the dev tools and login as a CiviForm admin
3. See program page with no way to get to the list of programs

Note: This bug seems inconsistent so you might need to load up a specific program page first (eg https://staging-aws.civiform.dev/programs/test), then go to the home page, then login as an admin via dev tools.

**Expected behavior**
When logging in as an admin I expect to see the page with the list of programs.

**Screenshots**
Video: https://github.com/civiform/civiform/assets/24319951/e1cb5e08-98e1-4afe-919a-31c4fc896b29

**Desktop (please complete the following information):**

- OS: iOS
- Browser: seeing this in both Chrome and Firefox

**Comment by reemaka** [comment]
This is very odd. Looking into it now. There's no feature flag

**Comment by reemaka** [comment]
I think the issue might be with the REDIRECT_TO_SESSION_KEY value getting set when the program is loaded. programBySlug() sets the redirect value to itself and then it's still set when logging in as an admin and it gets read in the CallbackController which sees that the value is set and redirects to the programBySlug page. I'm not sure why we didn't have this problem before though.

**Comment by reemaka** [comment]
I checked out an old commit (c0212a457ec2c38c660cbe9f8e199fd6f2b2175f from June 22) and confirmed this was a problem before any of the program preview changes. I'll work on a patch.

**Comment by reemaka** [comment]
Generally, REDIRECT_TO_SESSION_KEY is set very optimistically and is only ever cleared if the user goes through the expected path of signing in after loading a program by the slug. It's set even if the program can't be found and isn't cleared if the user goes to the home page or to another program's page by ID instead of by slug. We should revisit this logic.
