### ISSUE TITLE
TI’s can edit clients

### ISSUE THREAD

**Issue by melanie-exygy** [civiform/civiform#5199]
**Is your feature request related to a problem? Please describe.**
TI's can only edit client DOB.

**Describe the solution you'd like**
User flow: TI’s can edit a client, update Last Name, First Name, Email or DOB, then press save to update information. 

**Additional context**
This is new functionality that @sijiayam and I discussed.

**Comment by elisekalstad** [comment]
This has come up multiple times during user research in past few weeks. For example social worker from a community-based org. last week was worried before the client's name on the client card was misspelled. But it was accurate on the actual program application. The social worker wanted to be able to go back and edit.

**Comment by elisekalstad** [comment]
This is a duplicate to #4956

**Comment by elisekalstad** [comment]
This is a duplicate to https://github.com/civiform/civiform/issues/4956
