### ISSUE TITLE
Canonical question for DOB doesn't populate the dob value directly.

### ISSUE THREAD

**Issue by swatkat1** [civiform/civiform#5231]
**Describe the bug**
Date of Birth value entered as part of TI Client creation, should directly be populating the canonical DOB question.

**To Reproduce**

1. Create a TI client with DOB say '06/25/2020'
2. Create a program referencing the canonical questions - name and Date of Birth. Publish it.
3. Login as a TI and apply to the program on behalf the Client.
4. The name is getting populated but not the Date of birth.

**Expected behavior**
Both name and Date of birth must be populated as they are using the WellKnown Path.

**Comment by rockycodes** [comment]
fixed by https://github.com/civiform/civiform/pull/5956 and https://github.com/civiform/civiform/pull/6073
