### ISSUE TITLE
Address Standarization does not correct for State

### ISSUE THREAD

**Issue by Miguel-314** [civiform/civiform#5291]
**Describe the bug**

Addresses that are entered with the wrong state are not corrected during the address standardization window. 

1. Enter a correct Address in WA. Enter any other state than WA. 
2. When the standardization page asks you to select a correct address, you can select an address with the original incorrect state. 

**Expected behavior**

All Seattle addresses should at least correct to WA for the state. 

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Miguel-314** [comment]
![Image](https://github.com/civiform/civiform/assets/126286905/ff2e554c-9e4c-4383-a7d9-096f93c9657e)
![Image](https://github.com/civiform/civiform/assets/126286905/40360e4e-2aea-4e8d-826a-ec83912d7d27)

**Comment by gwendolyngoetz** [comment]
It's actually more nuanced than it doesn't. The issue is that Seattle's endpoint is returning the state abbreviation under a different field. >_<
