### ISSUE TITLE
Allow deployments to pass in a custom registry for Docker image

### ISSUE THREAD

**Issue by rockycodes** [civiform/civiform#5300]
When debugging deployments, we sometimes hit a rate limiting issue with Docker from pulling the image too many times. To get around this, it would be nice to be able to load a Docker image into ECR in AWS and then fetch it from there, rather than from docker. 

Work entailed:
Add a config var that gets passed through to [here](https://github.com/civiform/cloud-deploy-infra/blob/ae5b08d58c9cd0aef2037c1d71906501d5c87409/cloud/aws/templates/aws_oidc/app.tf#L37)

**Comment by gwendolyngoetz** [comment]
If it's the automated deployments in GitHub actions we can probably use the GitHub Container Registry ([ghcr.io](http://ghcr.io/)) in lieu of separate AWS ECR instances.

**Comment by rockycodes** [comment]
Closing as a duplicate of https://github.com/civiform/civiform/issues/5993
