### ISSUE TITLE
Disable "Update DOB" button in TI clients list until user selects a new date and maintain focus on client row

### ISSUE THREAD

**Issue by melanie-exygy** [civiform/civiform#5303]
**Describe the bug**
The "Update DOB" button is always enabled, whether or not the user has selected a new date.  This means the user might click the button, without any effect.  Also, clicking the button redirects focus to the top of the page rather than maintaining focus on the client row.

**To Reproduce**

1. Log in as a TI.
2. If there are no clients in the list, create a new one.
3. Click the "Update DOB" button.
4. Note that clicking the button didn't change the client data and that it redirects focus to the top of the page.

**Expected behavior**
The "Update DOB" button is disabled until the TI selects a new date from the date picker.  Also, the focus stays on the client row after "Update DOB" has been clicked.

**Screenshots**
![image](https://github.com/civiform/civiform/assets/134556723/0752c2ac-d892-4152-952e-027efeb8cfa8)

**Comment by sijiayam** [comment]
@melanie-exygy Just a heads up this edit [Client Info PRD](https://docs.google.com/document/d/14etX_bl3-71o6TdcSSNeYrorJxtgCD5jEayCOBZppdQ/edit?resourcekey=0-ACUKnQEe4jT-PCR7V1pFUw) is currently being written. It may end up tackling/replacing the update DOB feature.
