### ISSUE TITLE
Update DOB Button in TI Add Client screens does nothing

### ISSUE THREAD

**Issue by Miguel-314** [civiform/civiform#5318]
After a TI has added a client the client name and DOB shows up in the Client list. There is a blue button that allows you to "update DOB". 

![Image](https://github.com/civiform/civiform/assets/126286905/79dca8a8-2721-4e4f-a7f0-2fc375000e95)

When you click this button it takes you to the top of the client management screen and does not prompt you to update the DOB. 

![Image](https://github.com/civiform/civiform/assets/126286905/b2e13ec9-5450-4e8a-86fb-6d6e80160744)

you can click the grey x next to the DOB. This will clear the DOB. 

![Image](https://github.com/civiform/civiform/assets/126286905/43914457-56de-421b-9d87-75cdbdd3fbb9)

If you click the update DOB button now intending to correct the recently cleared DOB you are sent to the top of the page again and shown an error message. 

![Image](https://github.com/civiform/civiform/assets/126286905/e55e4256-cd80-4522-b6bf-6be1366b1443)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by melanie-exygy** [comment]
This seems closely related to this issue:  https://github.com/civiform/civiform/issues/5303

**Comment by msprenke** [comment]
This is a training issue but also a good user feedback issue for the usability of the current DOB update feature.  Being handled as a part of https://github.com/civiform/civiform/issues/4956
