### ISSUE TITLE
Filtering admin applications view by applicant email filters by TI email instead

### ISSUE THREAD

**Issue by avaleske** [civiform/civiform#5324]
**Describe the bug**
The `ProgramRepository.getApplicationsForAllProgramVersions()` method searches by the email of the TI that submitted the application, not the applicant's email.

The field `submitter_email` in https://github.com/civiform/civiform/blob/2c0526aea1c5ce3c79cc2ff4762b3b0fc1590b32/server/app/repository/ProgramRepository.java#L254 is the email of the TI.

**To Reproduce**

1. Submit an application with a known email
2. In /admin/programs/{program id}/applications, search for the application by email address
3. See that there are no results.

**Additional context**
The tests didn't catch this cause they're manually setting the `submitter_email` on the application to the applicant's email, which is incorrect:
https://github.com/civiform/civiform/blob/2c0526aea1c5ce3c79cc2ff4762b3b0fc1590b32/server/test/repository/ProgramRepositoryTest.java#L358

Changing this map:
https://github.com/civiform/civiform/blob/2c0526aea1c5ce3c79cc2ff4762b3b0fc1590b32/server/test/repository/ProgramRepositoryTest.java#L345
to 
```java
.map(a -> a.getApplicant().getAccount().getEmailAddress())
```
works for most of the tests, except for the test cases on line 299 and 304 (test cases 6 and 9, zero-indexed) from
https://github.com/civiform/civiform/blob/2c0526aea1c5ce3c79cc2ff4762b3b0fc1590b32/server/test/repository/ProgramRepositoryTest.java#L292-L314
because they're searching by email address and looking for a match in the `submitter_email` field, which is no longer set.

**Comment by rockycodes** [comment]
@avaleske I'm starting work on https://github.com/civiform/civiform/issues/4238 and will likely fix this in the process!

**Comment by avaleske** [comment]
Great, assigning to you for now but feel free to unassign it if you don't end up doing it.

**Comment by avaleske** [comment]
In case it's helpful, this commit was the start of me trying to debug this

https://github.com/civiform/civiform/commit/b6620bfbda1509cc5e91106dd88b6c37f93e1dc0
