### ISSUE TITLE
Fix direct links to Generated API Docs page

### ISSUE THREAD

**Issue by avaleske** [civiform/civiform#5353]
Support opening the API docs link in a new browser (i.e. incognito mode).

Currently, opening the CiviForm home page in incognito, unauthenticated, followed by opening the API docs page (without logging in as an admin) works, but opening the API docs page in incognito mode directly causes you to get a sign-in prompt.

**Comment by yotommy** [comment]
It looks like `/api/` routes are [configured](https://sourcegraph.com/github.com/civiform/civiform@9358f1b66ff84c74f953246520cf86544568dcb9/-/blob/server/conf/application.conf?L278-285) to require basic authentication.

I don't understand why visiting the home page first would get around this. That being said, we should be able to work around this by excluding the '/api/docs/' routes from the config.
