### ISSUE TITLE
Figure out how to unlock TF state when errors occur during setup/deploy

### ISSUE THREAD

**Issue by nb1701** [civiform/civiform#5381]
Sometimes, if something goes wrong during a setup/deploy, or you Ctrl+C out of a TF apply, you can be left in a place where a lock has not been released in the Terraform state, or the S3 bucket it needs for TF state management isn't there when it expects it to be, and you are unable to do any more TF applies.  Need to figure out how to unwind these states.  It may be a matter of forcing the lock to be released, or reapplying the TF state resources.

**Comment by dkatzz** [comment]
I seem to be able to reproduce this when I deploy then change the cloud-deploy-infra branch I'm pointing to in the civiform-deploy config.sh file and run the deployment again.
