### ISSUE TITLE
Ensure that all client data is used to populate program applications

### ISSUE THREAD

**Issue by isabelcshaw** [civiform/civiform#5430]
Right now, when TIs add clients and then apply to a program on their behalf, only client name is auto-populating in the application. In order to reduce duplicative efforts, we need to ensure at all information (such as email) that a TI adds in creating a client is brought over to the applications they fill out. 

This was reported via user testing, so the first step here is to confirm the underlying behavior. Then to ensure that we are able to reuse all client data in applications. 

This issue is complete when we confirm that a TI user can add a new client and then, when applying to a program on their behalf, see First Name, Middle Name, Last Name, DOB, and email auto-populate the application.

**Comment by isabelcshaw** [comment]
https://github.com/orgs/civiform/projects/1/views/59?pane=issue&itemId=27162500

**Comment by rockycodes** [comment]
This will be addressed with this work: https://docs.google.com/document/d/10coGz5wuCGyulfM4y7J5vXaKpoH8hAulqVJcevYGpnc/edit
