### ISSUE TITLE
Clarify for TIs who they are logged in as vs who they are applying on behalf of

### ISSUE THREAD

**Issue by isabelcshaw** [civiform/civiform#5431]
When a TI goes to apply on behalf of a client, CiviForm shows at the top of the screen "Apply as: Jenny Lee" and also "Logged in as: Jenny Lee." This copy is confusing for TIs. 

@sijiayam I'd suggest implementing the sub banner you created in the header and footer exploration unless you'd like to head another direction? https://www.figma.com/file/RmhVJCLgAKWGENJLWWAtNS/CiviForm%3A-Components%2C-Styles?type=design&node-id=1014%3A3542&mode=design&t=oYxUgVr20cUbNupL-1

**Comment by isabelcshaw** [comment]
Wondering if the "guest" version of this banner could also be used for the TI in the scenario where they decide to apply on behalf of someone without making a client first. 

In that case, the CTA would be "add this client" and it would take them to the client creation view AND ideally, use the info already entered in the application.

**Comment by isabelcshaw** [comment]
![Image](https://github.com/civiform/civiform/assets/12836913/b30604d5-1925-4b94-93a0-c7ce1927d569)

**Comment by melanie-exygy** [comment]
> Should solve issue: https://github.com/orgs/civiform/projects/1/views/59?pane=issue&itemId=30602588

@isabelcshaw Could you help me understand how adding the sub-header will solve the issue of what user is displayed as logged in?  The header mocks only show "Applying for..."  I suggest that we keep the other bug separate from the work of adding the new header.

**Comment by melanie-exygy** [comment]
> Wondering if the "guest" version of this banner could also be used for the TI in the scenario where they decide to apply on behalf of someone without making a client first.

@isabelcshaw does the functionality of a TI applying for someone who is not a client already exist?  If not, I propose that this work be separated from that of creating the new header.  It could be fairly complex and require a PRD and TDD.  I also don't see a "guest" version of this banner.  Where can I find that?

**Comment by isabelcshaw** [comment]
@melanie-exygy these are great callouts! 

Some preliminary thoughts before our sync later: 
1. You're right - the ability to view/browse programs without selecting a client first is a future looking workflow that we currently don't support, so any type of "guest" workflow is not a part of this issue

**Comment by isabelcshaw** [comment]
<img width="1052" alt="Screenshot 2023-09-28 at 10 39 57 AM" src="https://github.com/civiform/civiform/assets/12836913/70880827-6d62-4b97-a351-5d03c51ed0b1">

To complete: 
- Remove 1
- Add banner at 3
- Update 2 to reflect the TI --> this to be pulled out into a separate issue

**Comment by melanie-exygy** [comment]
Perfect.  That completely answers my questions.  Thank you!

**Comment by melanie-exygy** [comment]
@sijiayam In the mock, I see "You are applying for First Name, Last Name".  Do we want a comma between the first and last name or should this be "Last Name, First Name" the way we have now?

**Comment by sijiayam** [comment]
@melanie-exygy LEts go with "First Name Last Name" ex. "Jenny Lee" like we currently have. Apologies for the mistake!

**Comment by melanie-exygy** [comment]
@sijiayam For the name format, we actually currently have "Last Name, First Name".  It would be easier to keep the format the way it is.  Would that be okay?

**Comment by sijiayam** [comment]
@melanie-exygy I think its fine to keep the current name format.

As for isabels question above, lets keep the big blue button for now. I think without the header update its not clear a quick path back to the client dashboard.
