### ISSUE TITLE
Allow for additional customization on the confirmation screen at application submission 

### ISSUE THREAD

**Issue by isabelcshaw** [civiform/civiform#5434]
Right now, when a CiviForm admin makes a program, they can add a custom message that will be shown on the confirmation page after an application has been submitted. The goal is to use this message to explain next steps of the application process and/or highlight other programs to apply for. 

Given the importance of this handoff and the feedback we have received that it is not as clear as expected, we'd like to expand the functionality of this space to allow for linking out to other pages outside of CiviForm and the text in the submission view to be easier to read. 

This issue is complete with the admin can:  

1. Add links to text that allow for navigation to sites outside of CiviForm 
2. Add custom formatting of the text in the form of bold, underlined, and text size

**Comment by rockycodes** [comment]
Requirement 1 was covered by this PR: https://github.com/civiform/civiform/issues/4354#event-9999013429

Requirement 2 might also work just by passing it through the formatter, but we'll need to test that.
