### ISSUE TITLE
Icon and Text Issue on App Preview Page

### ISSUE THREAD

**Issue by gwendolyngoetz** [civiform/civiform#5494]
On the admin's Applications view there are icons that are not sized correctly and text that doesn't fit with the rest of the system theme.

See attached screenshot for example. 

Issue is on this page:
https://hostname/admin/programs/{}/applications/{}

That page is rendered as an iframe on this page:
https://hostname/admin/programs/{}/applications

![image](https://github.com/civiform/civiform/assets/195162/d155ad9b-4eb2-4c70-985a-f43e576c7be8)

**Comment by Ashermuzic** [comment]
so you just need help with the design??
