### ISSUE TITLE
(WCAG 2.1) No Warning for Links open in a new tab or window

### ISSUE THREAD

**Issue by dkatzz** [civiform/civiform#5534]
OBSERVED RESULTS:

- The links open in a new tab as indicated by the icon but this is not conveyed programmatically to screen reader users.
- ![Screenshot](https://github.com/civiform/civiform/assets/86739416/d6232c07-a3e9-4ffb-b624-5bea5831819a)

EXPECTED RESULTS:

- Provide the additional context through the control's accessible label, e.g. aria-label="<link text>, opens in a new tab" or using an off-screen text.

STEPS TO REPRODUCE:

- Enable screen reader.
- Navigate to [URL](https://demo.civiform.dev/)
- Navigate to the ‘Program Details’ link.
- Observe that the links open in new tabs, however there is no warning provided to screen reader users.

ADDITIONAL INFORMATION:

- [ W3org Reference - G201: Giving users advanced warning when opening a new window](https://www.w3.org/TR/WCAG20-TECHS/G201.html)

ENVIRONMENT DETAILS:

- Device(s) (brand, OS version, test key or release key): Windows 10 Enterprise (64-bit),MacOS Ventura Version 13.4
- Screen reader name and version: JAWS 2022.2211.7, NVDA 2022.3, VoiceOver
- Browser name and version: Chrome Version 113.0.5672.93

**Comment by rockycodes** [comment]
Started work on this branch https://github.com/civiform/civiform/compare/rockycodes/a11y-link-out
