### ISSUE TITLE
Localize the TI dashboard

### ISSUE THREAD

**Issue by melanie-exygy** [civiform/civiform#5535]
**Is your feature request related to a problem? Please describe.**
It would be nice to make the TI dashboard more accessible to non-English speakers.

**Describe the solution you'd like**
We could offer translations for the text on the TI dashboard.

**Done when**
- All text on the TI Dashboard is translated into the languages that we support.

**Comment by elisekalstad** [comment]
![image](https://github.com/civiform/civiform/assets/86082659/c7492f08-3e8e-4d53-80eb-288057b54141)

**Comment by azhangggggg** [comment]
We're adding all the strings from https://www.figma.com/file/yfhnUmE2FsonLtAqfeEfoo/TI-Edit?type=design&node-id=1-19&mode=design&t=xRBY2FLTgjtD2WDt-0 instead of the screenshot above after discussion.

**Comment by melanie-exygy** [comment]
@azhangggggg I reopened this because there is more work for the translated strings to show up on the TI dashboard.  The main piece I'm thinking of is setting up the scaffolding to use messages from the TI view.  A first goal would be to make sure that existing strings show up on the page as translated.
