### ISSUE TITLE
Required fields indicator text is not localized in application summary view

### ISSUE THREAD

**Issue by melanie-exygy** [civiform/civiform#5536]
**Describe the bug**
The required fields explanation text ("Note: Fields marked with a * are required.") is not localized on the application summary page:

Also, the asterisk in the explanation text is not red in the application block view.  See the TI dashboard for the desired output.  

**To Reproduce**

1. From the landing page, select a program and click "Apply"
2. Select a language other than English from the language dropdown.
3. Note that "Note: Fields marked with a * are required." is not translated.

**Expected behavior**
The required fields indicator text should be localized on the application summary page.
The asterisk in the required fields text should be red in the application blocks view.

**Screenshots**
![image](https://github.com/civiform/civiform/assets/134556723/d96e1b37-54be-471c-beb8-9a2d631d462e)

![image](https://github.com/civiform/civiform/assets/134556723/cf486d32-e4c6-470b-b31f-ce12ca5551c8)

**Additional context**
The text has been localized in preparation for this work as `content.requiredFieldsAnnotationFirstHalf` and `content.requiredFieldsAnnotationSecondHalf` as part of this [PR](https://github.com/civiform/civiform/pull/5496)

**Comment by isabelcshaw** [comment]
Waiting on translations via Google

**Comment by bion** [comment]
Are translations still needed for this?

**Comment by dkatzz** [comment]
> Are translations still needed for this?

This should have been resolved with https://github.com/civiform/civiform/issues/5658
