### ISSUE TITLE
Fast forward to the latest program version

### ISSUE THREAD

**Issue by elisekalstad** [civiform/civiform#5541]
**Describe the bug**
As an applicant, I can start a program application but not submit it. 

A CiviForm Admin can make changes to the program application (add eligibility conditions, translations, or additional questions) 

Those changes will not show when the applicant returns to complete their application. 

This causes problems for applicants and Program Admins because the correct version of the program application was not submitted. For an applicant, they may have been able to bypass newly added eligibility criteria or required questions. For Program Admins, they must reach out to the applicant to ask for additional information to complete the application.

**To Reproduce**

As a Program Admin:
1. Create a new program
2. Publish it

As a Resident:
1. Log in
2. Complete the program application but DO NOT submit it

As a Program Admin:
1. Publish changes to the existing program by adding eligibility conditions, new questions, new translations

As a Resident:
1. Log back in
2. See the draft application
3. See that the draft application does not include the recent changes to the eligibility conditions, new questions, new translations
4. Submit the draft application

As a Program Admin:
1. See that the submitted application does not include answers to the new questions and bypassed the eligibility conditions

**Expected behavior**
Expect that a returning applicant would have their draft application upgraded to the most recent version of the program. Already completed questions would display, and any new questions/eligiblity conditions/translations would also show.

**Screenshots**
_Need to add screenshots for the workflow_

**Comment by elisekalstad** [comment]
@swatkat1 Did I capture this accurately? Anything else to add?

**Comment by elisekalstad** [comment]
@msprenke  For awareness

**Comment by bion** [comment]
@elisekalstad this is working as intended. If we want to change the behavior it'll require a fairly involved discussion and deep engineering work.

The reasoning is that if someone is in the middle of an application and the admin publishes changes to that program, the new changes will not cause an unexpected experience e.g. if they are about to submit their application but the admin adds new required questions or different eligibility or visibility conditions.

Another example:
- applicant is viewing screen A
- admin publishes a new version
- new version makes screen A no longer visible given applicant's previous answers
- applicant submits screen A, but there are validation errors, however the screen is no longer visible

**Comment by bion** [comment]
@elisekalstad we could maybe give admin the option to override this behavior and force all in-progress applications to update to the new version, but we'd need to think through the UX and application-logic consequences of that.

**Comment by msprenke** [comment]
@elisekalstad @bion I've seen other sites give a warning when you return to an application that a new version is available with an ok box that resets the form and starts a new application.  Essentially beginning a new edit and therefore carry over the previous answers

**Comment by swatkat1** [comment]
There is an existing bug- for an applicant who was never shown the Eligibility question, Program admins sees "Meets Eligibility" tag.
 Example: After adding the condition: 
![image](https://github.com/civiform/civiform/assets/101214724/8b779f83-7b66-4bd9-81f8-36b9b10c703b) and submitting it: 
![image](https://github.com/civiform/civiform/assets/101214724/1d717a6b-e783-4947-855c-9b3dbebf421f)
The Program admin sees this: 
![image](https://github.com/civiform/civiform/assets/101214724/81f1ec50-2d8a-4641-ac7e-78419039b0d1)

**Comment by swatkat1** [comment]
@nb1701 -  new issue: https://github.com/civiform/civiform/issues/5614

**Comment by msprenke** [comment]
https://docs.google.com/document/d/1hzeCBh37w3f94VNRscCJnImTCxLd3zGS696Uqsi-COY/edit?usp=sharing

**Comment by elisekalstad** [comment]
@gwendolyngoetz -- Does XL sound right for this one?

**Comment by gwendolyngoetz** [comment]
Yes
