### ISSUE TITLE
Update design of "Admin Name" input field for question options

### ISSUE THREAD

**Issue by sijiayam** [civiform/civiform#5612]
Context:
As part of [#4862](https://github.com/civiform/civiform/issues/4862) we add the concept of an immutable "Admin Name" for each option for Checkbox, Dropdown, and Radio Button questions. This admin name is what is exposed via the API. Since it's separate from the current user-facing text the admin sets, the admin can change the user-facing text without potentially breaking API consumers.

We put together a UI quickly to meet a deadline for AR, but it would be nice to update this with something more user friendly.

Done when:
- UI reflects the ability to input a text field for "admin name" for each option
- UI shows use cases for different screen breakpoints, mobile, table, desktop

## The current UI
<img width="616" alt="image" src="https://user-images.githubusercontent.com/1295824/268379514-74ab2747-84f4-46d9-844e-e6b5933b0a65.png">

## The desired UI
Option A from https://www.figma.com/file/7vmCisHc9GS0VTsQmJQvox/Admin-Name-input-field-layout-improvement?type=design&node-id=1%3A4&mode=design&t=mc9EU9rNoH7PUtbK-1

![image](https://github.com/civiform/civiform/assets/1295824/7925f4d0-7278-40ab-a37d-86ff043936e6)

**Comment by RonotronG** [comment]
Hi all, this is Ron, I was able to setup my account. Feel free to assign this to me.

**Comment by RonotronG** [comment]
Here's the design proposals to improve the current UI layout: https://www.figma.com/file/7vmCisHc9GS0VTsQmJQvox/Admin-Name-input-field-layout-improvement?type=design&node-id=1%3A4&mode=design&t=mc9EU9rNoH7PUtbK-1

**Comment by RonotronG** [comment]
For the buttons, feel free to keep them the same, except for the delete button - I recommend to remove the text labels. I used the CiviForm buttons components because I couldn't find the current button styles anywhere.

**Comment by avaleske** [comment]
Thanks @RonotronG!

@sijiayam, is there an approval process for designs before I start implementing?

**Comment by sijiayam** [comment]
@avaleske We will have a chance to review today during our design sync and then will ping/update status to Ready for Dev!

cc  @RonotronG

**Comment by RonotronG** [comment]
@avaleske Based on the team's feedback today, the UX team recommends Option A for the low-effort change. Option B is more forward-thinking, but it is also more complex to build a card system and it will take up more vertical screen space. Mobile views are out of scope for this design improvement, as the current Admin page does not support mobile views + use cases. Please let us know if it is okay to implement Option A.

**Comment by RonotronG** [comment]
@sijiayam Let me know if UX team's review today - leaning toward Option A equals to a thumbs-up on implementation. Thanks!

**Comment by sijiayam** [comment]
@RonotronG Yes thumbs up on  proceeding with option A.

**Comment by avaleske** [comment]
Great! switching this status to Ready for Development

**Comment by tinkelperson** [comment]
@isabelcshaw Thoughts on how to prioritize/assign this?

**Comment by avaleske** [comment]
> @isabelcshaw Thoughts on how to prioritize/assign this?

I promised an improved UI as a fast-follow to my admin name changes, so I've included it in Delivery Phase 2 of the API work, which should be done by the end of the year.
