### ISSUE TITLE
Warn users of max file upload size

### ISSUE THREAD

**Issue by melanie-exygy** [civiform/civiform#5675]
**Describe the bug**
There is no indication of the document upload file size limit (which is currently 100MB).  The user also does not see a validation error message.  If they try to upload a document that is too large, they will see a generic error message.

**To Reproduce**

1. In Staging, from the landing page, select a program that has a file upload question and click "Apply".
2. Click on 'Choose File' and select a file that is larger than 100MB.
3. Notice the generic error page.

**Expected behavior**
Either there is text under the question label that tells the user what the file size limit is or we show a validation error if the limit is reached.  

**Additional context**
- The limit may be different based on the cloud provider settings, so the code will need to account for that.  
- This is a follow-up to #2979 .

**Comment by caitlinshk** [comment]
+1 to this. On staging what I'm seeing is that I'm taken away from the CiviForm site entirely. The URL I'm redirected to is https://exygy-civiform-files-s3.s3.us-east-1.amazonaws.com/ and this is the page that I see:

![image](https://github.com/civiform/civiform/assets/147177873/6bdd4a78-3330-4e00-8f6f-269284a662e6)

I agree we should have some warning text, and it would also be great to not take users away from CiviForm if they do still upload a file that's too large.

I may look into this for program images. I can try and design something that would also work for the file upload question.

**Comment by caitlinshk** [comment]
See https://github.com/civiform/civiform/issues/6658 for the issue tracking improving this for program images.
