### ISSUE TITLE
[Epic] Add images to program cards

### ISSUE THREAD

**Issue by melanie-exygy** [civiform/civiform#5676]
### Epic Overview

Residents, CBOs, and City Staff have all mentioned that having images in the program card would help to know who the program serves. It's quicker to digest images than text.  We would like admins to be able to upload an image that displays on the program card.  See #3783.  

### Goal

Feedback from users as well as findings from behavioral economics research have identified that our current program cards are difficult for residents and TIs to quickly parse for important information. Users are having to click into program details to understand the program's value proposition or area focus (nutrition, transportation, etc). In order to deliver on our discoverability (and accessibility) goals, we need to remove this cognitive burden. While we will investigate multiple areas for enhancement, we'll begin with the ability to add images. 

### Key Deliverables

- There is an upload box on the program edit page. The upload supports JPEG, PNG, GIF images at a minimum. #5782 
- We have the ability to store the program images.
- The images appear on program cards on the program index  #page.  #5781 

### Documentation

PRD creation issue:  #5686 
UX mocks
TDD creation issue:   #5680

**Comment by caitlinshk** [comment]
This feature is finished and default-enabled in production. https://github.com/civiform/civiform/issues/5919 will track removing the flag eventually, but I think we can mark this as complete!
