### ISSUE TITLE
[TDD] Write TDD for adding images to program cards

### ISSUE THREAD

**Issue by melanie-exygy** [civiform/civiform#5680]
This issue is for keeping track of the work involved with writing a TDD for this epic:  #5676 

It will be considered done when:
- The design has been approved
- New issues have been created to cover the implementation work needed for this epic.

**Comment by caitlinshk** [comment]
TDD: https://docs.google.com/document/d/1HU4gtZz8e4wgsR4xZ4tAkZlZd4bAd4fM8i5Ela9NoHI/edit#heading=h.bknox3ib8wpb.

New issues for implementation: https://github.com/civiform/civiform/issues?q=label%3A%22Epic%5BProgram+Card+Images%5D%22+

The TDD hasn't been officially marked as approved, I'll chase those down in the new year.
