### ISSUE TITLE
Separate Enabling a Language for Admins and Applicants

### ISSUE THREAD

**Issue by gwendolyngoetz** [civiform/civiform#5688]
Currently the system supports multiple languages which are configured in the `application.conf` file by adding them to the `play.i18n.langs` array. 

To add support for a new language you add it to the array. At which point:

* The ability to add translations is enabled in the `programs` and `questions` manage translations pages.
* The dropdown for the user to select their language is populated to the new language.

Because the admin and applicant side are tied to the same setting you can have untranslated languages be displayed as being available for an applicant to select.

It would be useful to have a separate mechanism to determine which languages are populated in the applicant dropdown. This way we can enable the language in the system for admins to work on translating. When the newly added language has been translated for all the programs the language can then be enabled to show in the dropdown.

I have some ideas, but I'm avoiding solutioning in this issue.

**Comment by elisekalstad** [comment]
Pending OIRA's new report on Top Tier Languages. There is a chance that top languages will change this year and we will need to update the dropdowns. Will also be body of work for intern in 2024--adding tier 2 languages, that is.

**Comment by gwendolyngoetz** [comment]
@elisekalstad I have this issue already done ;) Will merge it when I'm back.

**Comment by elisekalstad** [comment]
Yes, I saw, just a little too late and had already moved the issue around a bit. You’re fast!
