### ISSUE TITLE
When editing an application, the submission time on the old version is changed to the new revision's submission time

### ISSUE THREAD

**Issue by nb1701** [civiform/civiform#5779]
**Describe the bug**
When a user edits an existing application and resubmits, the submit time for the old application is changed to the submit time of the new application revision.  This messes with metrics and we lose the ability to know when the application was originally submitted.

The reason this happens is because of this.
https://github.com/civiform/civiform/blob/f19ca54ca88ad6f5a3b381c462de8fe7674cd478/server/app/repository/ApplicationRepository.java#L125-L143

When the new revision is submitted, we look at all the old revisions, and for any that aren't marked as obsolete, we log a warning and update the submit time.  However, we have not yet obsoleted the "current" revision of the application, so that one always gets its submission time rewritten.

This was originally done to address https://github.com/civiform/civiform/pull/4179.  We should probably only update the submission time if the old application doesn't have one set.  And we should not log a warning every time there's an active application, since we haven't obsoleted it yet, or we should obsolete the "current" revision before doing this loop.

**To Reproduce**

1. Submit an application. Note the submission time in the database.
2. Edit the application and resubmit it. Note the submission time of the old application revision and the new one are now nearly the same time.

**Comment by avaleske** [comment]
From @msprenke via slack:
> I think the time is actually set to the point at which the edit button is clicked rather than the submission of the edit.
