### ISSUE TITLE
Translations Batch: 2023-10-17 (AR)

### ISSUE THREAD

**Issue by dkatzz** [civiform/civiform#5815]
Request and update CiviForm translations using [Transifex](https://app.transifex.com/civiform/civiform/dashboard/).

Follow the instructions at [go/civiform-translations](http://go/civiform-translations) to

- [x] Request a new batch of translations
- [ ] Upload translations into Transifex
- [ ] Create a ticket for the next batch of translations, and assign to the next Google.org Works SWE

**Comment by dkatzz** [comment]
Keeping track of AR translations here - https://docs.google.com/spreadsheets/d/1FMIiNeLBn2od1ipfs82_Cc9arRNZbwG3/edit?resourcekey=0-eSgTd7sGKurOS-ZYrCbmzA#gid=1940188385

**Comment by dkatzz** [comment]
Translation for spanish requested

**Comment by avaleske** [comment]
Translations are complete, and added to the sheet!
https://docs.google.com/spreadsheets/d/1FMIiNeLBn2od1ipfs82_Cc9arRNZbwG3/edit?resourcekey=0-eSgTd7sGKurOS-ZYrCbmzA#gid=1940188385

We've emailed the AR team to let them know.
