### ISSUE TITLE
Reporting submissions don't match with CSV export

### ISSUE THREAD

**Issue by elisekalstad** [civiform/civiform#5824]
**Describe the bug**
As a Program Admin, I use the Reporting Dashboard to see how many applications are submitted each month. The total number of submissions doesn't match with the CSV export of the same data.

For example:
HSD's Gold Card for the month of 9/2023

- 76 submissions per the reporting table
- 162 submissions per the CSV export

**To Reproduce**

1. Go to the Reporting Dashboard
2. Click on a program
3. See the number of submissions by month
4. Compare that number to the CSV export 
5. See that numbers aren't aligned

**Expected behavior**
I would expect the numbers to be the same

**Screenshots**
Below and CSV attached

![image](https://github.com/civiform/civiform/assets/86082659/2a717650-f3d9-41d8-9b2c-08d465495382)
[Gold Card (HSD)_Example.csv](https://github.com/civiform/civiform/files/13046696/Gold.Card.HSD._Example.csv)

**Comment by elisekalstad** [comment]
Thanks to Matt! Looks like maybe the months are just one-off. (_Data in report for August is the data in the CSV for September)._

**Comment by bion** [comment]
One thing that may be making this harder to investigate is a bug (fixed two weeks ago https://github.com/civiform/civiform/pull/5786) that incorrectly set the submit time of applications that were made obsolete by more recent submissions from the same applicant.

@elisekalstad are you sure it's just an off by one situation? it looks like the numbers are close but not the same between the CSV and the web view, even when accounting for misalignment of the months

**Comment by elisekalstad** [comment]
Thanks for taking a look! The “off by 1 month” idea is just a guess. The numbers are close but not the same. We were thinking it might have to do with the submit date changing if an application was resubmitted, which would only impact a few of the submissions. But really just a guess.

-Elise

**Comment by elisekalstad** [comment]
Can use the Fresh Bucks Community Based Org program in Testing for example.
