### ISSUE TITLE
Add administrative data fields on edit program screen.

### ISSUE THREAD

**Issue by lftaylor2023** [civiform/civiform#5838]
Add administrative and agency contact information fields. This could be used in the future for contact information shared in notification emails, in the submit confirmation popups, for alerts when there are problems with forms, etc.  It would also be used to quickly reference the point of contact for a program should we need to get in touch with them. This would be more useful than storing the contact information in a spreadsheet on the LAN or on someone's hard drive. 

Suggested Agency Fields:
•	Agency Name
•	Main Point of Contact Name
•	Contact Email (recommend a distribution list)
•	Agency Phone
•	Agency Address

**Comment by bion** [comment]
Current workaround for this: put these details in the program description

**Comment by lftaylor2023** [comment]
The agencies may not want that information to be visible to the applicants as it might result in calls to a number that was not intended to be distributed to the public. These fields are more for internal use than anything, though I was trying to be broad in the way that they can be used in the future.

Leslie F. Taylor
Business Intelligence Specialist | Data Warehouse
Transformation and Shared Services, Division of Information Systems
o. 501.682.4415
c. 501-960-3721
***@***.***
________________________________

**Comment by bion** [comment]
There are two description fields for programs, one is public-facing for the program card. The other is admin-only:

![Screenshot 2023-10-26 at 11 10 03 AM](https://github.com/civiform/civiform/assets/473671/020dc355-0bcf-496f-8df8-ab755411ba94)

**Comment by bion** [comment]
Sorry, the admin-only field is called the "admin note" rather than "description", my mistake with my original response.

**Comment by lftaylor2023** [comment]
10-4

**Comment by lftaylor2023** [comment]
Got it! Thank you!
