### ISSUE TITLE
[PRD] Disabling Programs 

### ISSUE THREAD

**Issue by isabelcshaw** [civiform/civiform#5842]
Multiple programs within the City of Seattle are seasonal and need to be enabled/disabled from CiviForm in cycles (such as school year enrollments) or as funds are available. These city programs need to be hidden from the general public. While there is currently a setting to hide the program, the ability to follow a direct link will still allow an applicant to complete an application.  A solution is needed to disable the program from being accessed completely."

Disabling Programs: https://docs.google.com/document/d/1q7WJqDNhxtAnJ1UkuqIBAnVdZEmg-VatxKKxCftvGNQ/edit?resourcekey=0-_lahZySh34RQpheoa8kKmg

**Comment by msprenke** [comment]
This is currently being worked under item 5065 https://github.com/civiform/civiform/issues/5065

**Comment by msprenke** [comment]
Closing this item as a duplicate of 5065
