### ISSUE TITLE
Determine if cache needs to be cleared by CiviForm admin in deployed instance

### ISSUE THREAD

**Issue by dkatzz** [civiform/civiform#5843]
**Description**
We have been adding caching capabilities for question, program and version data behind a feature flag. Once these flags are removed, we want to make it easy to clear the cache if needed. 

We should create an endpoint or button for admins to clear the cache, without needing to redeploy. This endpoint should check that the user is an admin and if so, allow for the cache to be cleared. 

We created a method to do this for the version cache in dev in the DevDatabaseSeedController as part of https://github.com/civiform/civiform/pull/5776.

Related to: https://github.com/civiform/civiform/issues/5844

**Comment by bion** [comment]
This gets quite a bit trickier (infeasible?) in an environment with multiple server nodes running.

Another options could be to leave the feature flag in place and make it admin-writeable, which would allow the admin to turn off caching for all nodes via the admin settings system.

**Comment by dkatzz** [comment]
Good point on this not being possible in an environment with multiple server nodes. 

In terms of this case, yes - it would only be for debug / unforeseen circumstances. 

I'm happy to keep the flag around, but in that case we may want to refactor a bit to use dependency injection (something we discussed in the eng meeting yesterday). 

Also, we can clear the cache by re-deploying, so maybe in these one-off (hopefully nonexistent) cases that is an okay approach?

**Comment by dkatzz** [comment]
There are two options for how we'll handle this:

1. Keep a "cache enabled" flag and refactor the code to use dependency injection with a cache implementation of the repository classes
2. Removing the flag and just having re-deploying as the way of clearing the cache in production

We will wait until we enable the cache by default and have it enabled for a while before deciding which approach to move forward with.

**Comment by dkatzz** [comment]
Checked with @gwendolyngoetz and there isn't a need for this. The prod cache will be re-initiated each time there is a deployment and we enable cache clearing on dev environments.
