### ISSUE TITLE
Main Page Text Revisions

### ISSUE THREAD

**Issue by lftaylor2023** [civiform/civiform#5893]
- Change From: Save time when applying for benefits
 - To: Save time finding and applying for programs and services. 
 
 - Change From: Log in to your account, or create an account, and apply for many benefits without having to enter the same information again. You can also edit applications at any time and check your application statuses.
 - To: You can continue as a guest or create an account. An account allows you to save your information, edit applications and check application statuses. 
 
 - Change From: Find services that can help you
 - To: Get Started

In general, Arkansas would like to stay away from the term "benefits" whenever possible.

**Comment by isabelcshaw** [comment]
@lftaylor2023 we haven't lost track of this one! These changes make sense to me. Programs and services are definitely more universal terms. And we have heard that folks' first impression of CiviForm is that an account is required, so clarifying that is a good short term fix. I'm going to check in with a few other folks, and we'll aim to make these changes before the end of the year.

**Comment by dkatzz** [comment]
Translations complete - https://github.com/civiform/civiform/issues/5948
