### ISSUE TITLE
"Review" Button does not save the answers on the page

### ISSUE THREAD

**Issue by paripatel07** [civiform/civiform#5939]
**Describe the bug**
When user fills in questions on a screen and selects "Review" - it does not save the responses

**To Reproduce**

1. Go to any application question screen
2. Fill out question(s)
3. Scroll down and select 'Review'
4. Responses were not saved when you see the review screen

**Expected behavior**
Filled in questions should be saved 

**Screenshots**
[Link](https://docs.google.com/document/d/1fI3dUGXR_1mAF53cg1gxOxIS0UT1SetyZHo2h7nG-gQ/edit?resourcekey=0-JidKSEZBcXLhgvBgn_UugQ)

**Additional context**
Perhaps also change the button to say "Save and Review"

**Comment by melanie-exygy** [comment]
@paripatel07 Could this be a duplicate of #5682 ?

**Comment by paripatel07** [comment]
yup, you are right - it is the same issue. Will close this one then
