### ISSUE TITLE
Ensure that applicants have profiles via a filter

### ISSUE THREAD

**Issue by yotommy** [civiform/civiform#5971]
**Is your feature request related to a problem? Please describe.**
Many, or perhaps all, of our applicant controller methods check for the presence of a user profile, as that is required to execute these methods. See this [example](https://github.com/civiform/civiform/blob/5decb99d8e5975d371e205fba40de3fb6a792bfe/server/app/controllers/applicant/ApplicantProgramReviewController.java#L89-L92). This is error-prone, since anyone writing such a method must remember to include this boilerplate code.

**Describe the solution you'd like**
Create a filter that does this for all applicant controller methods.

**Additional context**
We only want the filter to execute for routes with applicable prefixes.

Here is [another filter](https://github.com/civiform/civiform/blob/main/server/app/filters/SessionIdFilter.java) that can be used as a model. The new filter will also need to redirect in order to have the profile added to the session.

**Done when**
Done when the filter is implemented and configured to run and the boilerplate code is removed from the controller methods.

**Comment by jeffpw-goog** [comment]
#6809 added the filter, so the remaining work is to remove special handling from controller methods ([example](https://github.com/civiform/civiform/blob/5decb99d8e5975d371e205fba40de3fb6a792bfe/server/app/controllers/applicant/ApplicantProgramReviewController.java#L89-L92)).

**Comment by jeffpw-goog** [comment]
This is done! Some pages still handle the case where the profile is missing, but the remaining ones were difficult to untangle and some of them might actually be necessary with https://github.com/civiform/civiform/issues/8414.
