### ISSUE TITLE
Add "Suffix" field to Name question 

### ISSUE THREAD

**Issue by paripatel07** [civiform/civiform#5974]
**Describe the bug**
The name question type has the following fields: First Name, Middle Name, Last Name

**To Reproduce**

1. Go to Program Admin view
2. Go to Questions
3. Add a name question

**Expected behavior**
Add an optional field for "Suffix" 

**Additional context**
Since there is no Suffix option in the Name field, users are adding a new separate question to get applicants' Suffix

**Comment by azhangggggg** [comment]
duplicates of https://github.com/civiform/civiform/issues/7806
