### ISSUE TITLE
Question Bank Button Inaccessible When Long Question Title Exists

### ISSUE THREAD

**Issue by gwendolyngoetz** [civiform/civiform#5975]
If there is a question with a long link (or other unbreakable text) in the Question Bank, it causes the "Create" and "Add" buttons to be off the screen.

To repro set the question text to `https://civiformstage.seattle.gov/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa`. Additionally you can make this more pronounced if you make your browser window narrower.

Probably just need to adjust the `overflow-wrap` css for the Question Title.

### Actual
![image](https://github.com/civiform/civiform/assets/195162/1a35094b-e175-4097-bea3-422d1cf1192a)

### Expected
![image](https://github.com/civiform/civiform/assets/195162/7e283868-af35-473c-ad11-dd27ae68e6de)

**Comment by JonnyMc94** [comment]
Hi, I would like to work on this if possible!

**Comment by azhangggggg** [comment]
Is this issue fixed already? This is what I'm seeing in dev with long title questions : 
<img width="1644" alt="Screenshot 2023-12-11 at 7 19 16 PM" src="https://github.com/civiform/civiform/assets/149536150/789e6af2-158e-4ee9-a078-807a2a86e7bb">

**Comment by gwendolyngoetz** [comment]
No, it's not fixed. The text you are trying with has commas and spaces which will correctly break. Try adding this as your question text:

`https://civiformstage.seattle.gov/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa`
