### ISSUE TITLE
Update the add client workflow for TIs

### ISSUE THREAD

**Issue by isabelcshaw** [civiform/civiform#5985]
This issue covers all the work required to shift over the "add client" workflow from its current state to the experience prototyped in [the mocks. ](https://www.figma.com/file/yfhnUmE2FsonLtAqfeEfoo/TI-Edit?type=design&node-id=1%3A19&mode=design&t=ZISoVvmXCxVgUVF7-1).  Note that, as of 12/20/23, our plan for the mocks has changed.  Rather than a "New client" modal, we will have a new client page with a link to return back to the TI dashboard.  

This includes: 
1. Removing the current component 
2. Adding the "add new client" button 
3. Adding the add new client form in its own page with a return link (@Sijia mocks are TBD)
4. Adding inline field validation error messages rather than showing them in a toast notification. (all validations, including error state for the client already exists.  (This may already be completed as part of #4956 .)
5. Adding this success alert when successfully creating a client:

![Image](https://github.com/civiform/civiform/assets/134556723/b81be2c9-c10f-4507-81d9-e0b7fa96286d)

**Comment by melanie-exygy** [comment]
@sijiayam, since the client table won't have the new styles yet, where should we put the "Add new client" button?  Should it be to the right of "Clients" like this?  Please disregard my button styling.


![Image](https://github.com/civiform/civiform/assets/134556723/b38d9afa-5dfd-4d7b-bbbe-fe59906e006a)

**Comment by elisekalstad** [comment]
Review with Swathi to see if this is good "inbetween" feature to take. @swatkat1
