### ISSUE TITLE
Update header on the TI home view 

### ISSUE THREAD

**Issue by isabelcshaw** [civiform/civiform#5986]
The goal of this issue is to clean up the header section of the TI home view so that there is one prominent title that is the name of that TI organization. 

Current state: 
<img width="1329" alt="Screenshot 2023-11-20 at 9 32 19 AM" src="https://github.com/civiform/civiform/assets/12836913/8ae42fa3-a873-4d38-84f9-288333f46152">

New state: 
<img width="605" alt="Screenshot 2023-11-20 at 9 31 21 AM" src="https://github.com/civiform/civiform/assets/12836913/c14f9af6-fee3-4145-aed4-73f583b15f7c">

Design details:
- New header should use h1
- Title should state just the organizations name ex. "Central District Community Center"
- The title background should have vertical padding of 48px or '6' per[ USWDS spacing token](https://designsystem.digital.gov/design-tokens/spacing-units/#using-spacing-unit-tokens)
- Header section should have background color of gray-50

Mockups:
- Note ignore the new navigation bar designs.
https://www.figma.com/file/yfhnUmE2FsonLtAqfeEfoo/TI-Edit?type=design&node-id=1%3A27&mode=design&t=biyDzCBIdmr1bfLE-1

**Comment by isabelcshaw** [comment]
Mocks here: https://www.figma.com/file/yfhnUmE2FsonLtAqfeEfoo/TI-Edit?type=design&node-id=1-20&mode=design&t=35RyBMEoVM6W9hEV-0

**Comment by melanie-exygy** [comment]
@sijiayam, for some reason I can't access the figma file.  Could I get more specifics on what it means to make "one prominent title"?  Should it be an h1 or h2?  Do we want a bigger margin above the header?  Any other specific style changes?

**Comment by sijiayam** [comment]
@melanie-exygy I've updated the issue with some design details. Please let me know if there is more guidance and details needed.

**Comment by melanie-exygy** [comment]
> @melanie-exygy I've updated the issue with some design details. Please let me know if there is more guidance and details needed.

Thanks, @sijiayam, that's very helpful.  I don't see the gray background in the mocks.  How wide should it be?  Rectangular or rounded edges?
