### ISSUE TITLE
Enable automatic detection of changes to Sass files

### ISSUE THREAD

**Issue by melanie-exygy** [civiform/civiform#6024]
**Is your feature request related to a problem? Please describe.**
Right now, if we make a change to our to our Sass files locally (which we will likely only do to update USWDS settings), we have to delete the `civiform-1` container and run `bin/build-dev` to re-compile the Sass into CSS.  This is time-consuming when we just want to test out a change to USWDS configurations.

**Describe the solution you'd like**
Changes to `.scss` files should be detected just like changes to our TypeScript files.  A change should trigger a new bundle to be built automatically.  

**Additional context**
This is where we detect TypeScript changes, so it would be a good place to start:  [WebAssetsBundler.scala](https://github.com/civiform/civiform/blob/3d7de716deaf9f97591d3c4135e20de795bb3139/server/project/WebAssetsBundler.scala#L95C7-L95C40).  If this proves difficult,  as a stopgap we could put the `npx` commands in `bin/refresh-styles`.  We should also be able to streamline to not have to spin up a new container.  That would likely be with `docker exec --it`.

**Comment by shreyachatterjee00** [comment]
needs investigation
