### ISSUE TITLE
Add placeholders on a per-question-type basis

### ISSUE THREAD

**Issue by neel-a-mehta** [civiform/civiform#603]
Each input field should have a placeholder, which is a snippet of gray text that disappears when you start typing. Question types that only render one input (text, number, email, phone number, etc.) only need one placeholder, while question types with N input fields (name, address, etc.) need N placeholders.

It's probably easiest for these placeholders to be hardcoded, with one set of placeholders for each question type. That is, don't allow admins to customize a particular question type's placeholder, at least now for now. This means that all Name question types would share the same placeholders, as would Email Address question types, and so on. Admins can always use the question description to put more details about what types of input they expect.

This hopefully won't be too hard to implement on the applicant UI side, though it will probably require nontrivial work in i18n and the `QuestionDefinition`. 

This is a mostly cosmetic / convenience feature, since the question description lets admins specify any important details, so it's going to be low priority for launch. It'll be a good starter project down the line, though! 

[See the Slack thread for more.](https://civiform.slack.com/archives/C01R3BWAL1E/p1616541751030800)

cc @AWBaumann @natsid

**Comment by nb1701** [comment]
We removed placeholders in https://github.com/civiform/civiform/issues/2617 due to a11y.
