### ISSUE TITLE
Ability to set eligibility based on specific BETWEEN range (all date and number questions)

### ISSUE THREAD

**Issue by elisekalstad** [civiform/civiform#6109]
**Is your feature request related to a problem? Please describe.**
As a Program Admin, I want to be able to only allow people to apply to a program if their birthday falls within a specific date range. For example, the Seattle Preschool Program only accepts applications for kids with birthdays between 9/1/2018 and 8/31/2020. I currently cannot set an eligibility condition between two date ranges.

**Describe the solution you'd like**
Ability to set, "date" "is between" "mm/dd/yyyy - mm/dd/yyyy" (similar to the existing function where by you can set "age" "is between" "3-4"

**Additional context**
![image](https://github.com/civiform/civiform/assets/86082659/785b66b2-7bc0-4ed0-8791-75259f2aaa6c)

**Comment by elisekalstad** [comment]
Hi @isabelcshaw and @nb1701 -- There's a request for a small improvement to the predicate logic to be able to set eligible date ranges. Is there someone on the greater CiviForm team who has experience in the predicate code who could take this one on?

**Comment by dkatzz** [comment]
https://github.com/civiform/civiform/pull/4428/files should be helpful for this change (the original PR to create the between logic).

**Comment by msprenke** [comment]
Needing a "between" calculation isnt specific to just dates.  This applies to numbers as well.  Example, Number X is Between 60000 and 69999

I'm updating the title to reflect this need for a between eligibility calculation for all numbers AND date fields.
