### ISSUE TITLE
Store session id in user profile

### ISSUE THREAD

**Issue by yotommy** [civiform/civiform#6113]
**Is your feature request related to a problem? Please describe.**
To support OIDC logout, we introduced a session id to use as a key for a map containing id tokens. This is populated by a [Play filter](https://www.playframework.com/documentation/2.8.x/Filters) that sees all incoming requests. Since Play sessions are immutable, a redirect is required to add the id to the session ([reference](https://www.playframework.com/documentation/2.9.x/JavaSessionFlash#Working-with-Cookies)).

However, some routes are accessed by clients that do not support redirection, so we maintain a set of [excluded route prefixes](https://github.com/civiform/civiform/blob/5dde21b31807360d2ea1a2c22667647bc34e70a2/server/app/filters/SessionIdFilter.java#L20-L21). Twice, this has resulted in bugs because additional exclusions where required (`/playIndex`, `/metrics`). The current approach is fragile.

**Describe the solution you'd like**
The session id is required for authenticated users. Instead of storing the session id directly in the session, store it in the pac4j profile. This will eliminate the need for a redirect and will store the data in a relevant scope (rather than unscoped in the session).

**Comment by yotommy** [comment]
With #6736, we get the desired behavior. However I will keep this issue open to remove the migration-only code after sufficient time has passed.

**Comment by gwendolyngoetz** [comment]
Do we consider enough time to have passed?

**Comment by yotommy** [comment]
Indeed, it is time to remove migration-only code.

**Comment by yotommy** [comment]
This should no longer be necessary: https://github.com/civiform/civiform/blob/e7d16006f0050f5e7f8120388d08017611876969/server/app/auth/oidc/CiviformOidcLogoutActionBuilder.java#L114-L115

If we want to be super-safe, we could log a warning here and make sure that this code path isn't executing before we remove it.
