### ISSUE TITLE
Periodically rotate server secrets

### ISSUE THREAD

**Issue by yotommy** [civiform/civiform#6197]
The Play framework uses an [application secret](https://www.playframework.com/documentation/2.8.x/ApplicationSecret) that is used for encryption (including that of Play session cookies).

Currently, this secret is generated at deployment time and never updated. It is good practice to periodically rotate the secret in order to mitigate the risk of a leaked secret.

Since user profiles are stored in Play session cookies, we must understand the impact of changing the server secret on users with applications in progress.

**Comment by yotommy** [comment]
[Using AWS Parameter Store for Play Secret Rotation](https://github.com/guardian/play-secret-rotation/blob/main/aws-parameterstore/README.md)

This package above rotates Play server secrets using the AWS Parameter Store. It supports an `overlapDuration` during which the server will honor both the old and new secrets. (This seems like it would require support from Play itself.)

Here is an [explanation](https://github.com/guardian/play-secret-rotation/commit/01e7fa86688) of why this package uses the Parameter Store rather than the Secrets Manager.

**Comment by yotommy** [comment]
Some deployments don't use a cloud provider.

Look into how Play handles this first.

**Comment by yotommy** [comment]
The overlap period needs to be greater than or equal to session expiration time.

**Comment by yotommy** [comment]
The [`play-secret-rotation` package](https://github.com/guardian/play-secret-rotation) can be used outside the context of the AWS Parameter Store by customizing the `secretStateSupplier` parameter provided to `RotatingSecretComponents`.

Posted a question on how to do this in a Java server: [Using play-secret-rotation in a Java server](https://github.com/guardian/play-secret-rotation/issues/427)

**Comment by yotommy** [comment]
Posted another question to the Play discussion board: [Managing server secrets in a Java server](https://github.com/orgs/playframework/discussions/12341)

**Comment by mkurz** [comment]
> I presume users with an account would just need to log in again.

Yes that should be all.

> Marking this P0, because we're going to have to do this before we move to Play 2.9, and we have to do that in the next 2 months.

Even if you don't implement secret rotation until May 31st, you can still just update `play.http.secret.key` to longer random value and you can upgrade (with the need of users to log in again). You can still implement secret rotation afterwards.

**Comment by yotommy** [comment]
Thanks, @mkurz, that is encouraging.

I did some experiments:

1. A guest user has an application in progress when the secret is changed. The work is lost, but the user is able to continue to access the site (with a fresh session) with no error.
2. An admin user is logged in and has `/admin/programs` on their screen when the secret is changed. Reloading the page results in a page that displays "403 Forbidden" and nothing else. Presumably, this is due to the [admin security annotation](https://github.com/civiform/civiform/blob/ed28c495345b775d5bc186f8fcf4c37ad6ab2f22/server/app/controllers/admin/AdminProgramController.java#L81) on the corresponding method (and the fact that the new session is a guest without the admin credentials). If they return to the home page, it is displayed without error and they can log in again.
3. An application is logged in and has an application in progress when the secret is changed. Reloading the page does not display an error, though the work is lost. The user is now a guest user, though that may not be apparent. If they return to the home page, it is displayed without error and they can log in again.

**Comment by yotommy** [comment]
Re-opening this issue to track the feature request of supporting overlapping secrets during rotation.

@nb1701 added a command to the deployment system to manually rotate the server secret. This unblocks migration to Play 2.9. However, this causes in-progress applications from guest users to be lost. A more graceful solution would support an overlap period where both old and new secrets are honored.

As discussed above, there is a [library](https://github.com/guardian/play-secret-rotation) to do this for AWS and a Scala server. There has been some recent [discussion](https://github.com/orgs/playframework/discussions/12341#discussioncomment-8787169) about how to enable a similar capability for Java servers. Furthermore, there is now a [feature request](https://github.com/playframework/playframework/issues/12520) for directly supporting this in the Play framework.
