### ISSUE TITLE
Update Client information card  - UI Component

### ISSUE THREAD

**Issue by sijiayam** [civiform/civiform#6212]
**Describe the solution:** 
Update the UI of the individual client information cards, to contain more information about each client and make it easier for CBO members to parse. 

**Figma mock:** https://www.figma.com/file/yfhnUmE2FsonLtAqfeEfoo/TI-Edit?type=design&node-id=1-19&mode=design&t=uMIvhYuGGlrDyzdz-0

**Screenshots:**
![Image](https://github.com/civiform/civiform/assets/20480121/7e1b9d18-d81d-4d76-aff1-dd526c3d2396)

**Done when:** 
* CBO member is able to see each client displayed in this card format 
* Each card looks like the mock above, displaying for the client: 

> - [ ] full name
> - [ ] date of birth
> - [ ] contact information (email or phone)
> - [ ] # of programs submitted 
> - [ ] names of programs submitted (blank if no programs submitted)
> - [ ] notes about client (blank if no notes inputted by TI)

* Clicking `edit` button takes CBO member to edit screen for that client 
* Clicking `View applications` button takes CBO member to homepage for client

**Comment by shreyachatterjee00** [comment]
Possibly change `View applications` button in mock to `View applicant dashboard` for clarity?

**Comment by melanie-exygy** [comment]
> Note: we had some discussions around changing `View applications` button in mock to `View applicant dashboard` for clarity that the button takes TI to client homepage, need to finalize wording on that button

@shreyachatterjee00 @isabelcshaw @sijiayam Since I'm going to be implementing this issue now, we need to decide on the wording for this button.  I vote for 'Apply as client' or 'View applicant dashboard'.
