### ISSUE TITLE
Update search components to USWDS components

### ISSUE THREAD

**Issue by sijiayam** [civiform/civiform#6214]
### Describe the solution:
Update the input fields for search and filters on the TI dashboard top increase usability.

### Figma mock: 
https://www.figma.com/file/yfhnUmE2FsonLtAqfeEfoo/TI-Edit?type=design&node-id=816%3A494&mode=design&t=A8ppwAkGj6ALGDd0-1

### Screenshots:

![Image](https://github.com/civiform/civiform/assets/116591382/65a19b6f-357b-400b-95aa-cfa6b58d1d5b)

### Done when:
- The search inputs are laid out horizontally on desktop
- The search fields have a h4 search title
- The datepicker uses the [USWDS datepicker field](https://designsystem.digital.gov/components/date-picker/)
- The search fild used the [USWDS input field](https://designsystem.digital.gov/components/text-input/)

**Comment by melanie-exygy** [comment]
@sijiayam, could you please confirm a couple parts of the design?  

1. For the input field outlines, the corners should be square not rounded?  This would be a change from our existing input fields which look like this:
![image](https://github.com/civiform/civiform/assets/134556723/b0cf7a3e-f794-4f07-b0b1-4320a2cab40c)

2. The "Search" button should have a white background, black text and a faint outline.  I don't think we currently have any buttons with that styling and I'm concerned that the faint outline may make users think that it's disabled.

3. Are we adding the ability to search clients by email address?  I didn't notice this requirement earlier, but the design shows a label of "Name(s) or email".  If so, I'll make this new functionality part of the requirements, either on this issue or a separate one.

**Comment by melanie-exygy** [comment]
@sijiayam, I've also noticed that in the existing search, there isn't a way to clear the search.  If I search for a name, there doesn't seem to be a way to return to the full list of clients after that search.  Should we add a way to clear the search?

**Comment by sijiayam** [comment]
@melanie-exygy Some responses to your questions below:

> 1. For the input field outlines, the corners should be square not rounded?  
- My recommendation would be to begin using the USWDS input fields which do have square corners. I am okay with this being different from our current styles.

> 2. The "Search" button should have a white background, black text and a faint outline.  I don't think we currently have any buttons with that styling and I'm concerned that the faint outline may make users think that it's disabled.

- For now feel free to leave the button as is with current styles. We may do a bigger button overhaul at a later time.

> 3. Are we adding the ability to search clients by email address?  I didn't notice this requirement earlier, but the design shows a label of "Name(s) or email".  If so, I'll make this new functionality part of the requirements, either on this issue or a separate one.

- @isabelcshaw or @shreyachatterjee00 do either of you remember a request to change what users are able to search by? I added them into the mocks based off of some conversation, but am not sure if they were locked in.

> 4.  I've also noticed that in the existing search, there isn't a way to clear the search. If I search for a name, there doesn't seem to be a way to return to the full list of clients after that search. Should we add a way to clear the search?

- Yes, it would be good to add a way to clear the search with a link. Here is the mockup I have for that: https://www.figma.com/file/yfhnUmE2FsonLtAqfeEfoo/TI-Edit?type=design&node-id=843%3A5233&mode=design&t=QzhKhFbQDZhFELwU-1
