### ISSUE TITLE
Sharpen UX for Civiform admin's "All Programs" page

### ISSUE THREAD

**Issue by neel-a-mehta** [civiform/civiform#622]
@HansEngebretsen has been creating some great mocks for the Civiform admin's "All Programs" page, where Civiform admins can review the programs under their purview, make changes, publish new versions, and review old versions. [Mocks are here](https://miro.com/app/board/o9J_lXULxwE=/?moveToWidget=3074457356370295246&cot=14).

However, Hans pointed out that the "All Programs" page needs some more UX attention. Take a look at that page in Miro and create recommendations for what to change. You can either put sticky notes on Miro with suggestions, or just write suggestions here in the comments.

**Comment by nb1701** [comment]
Covered by other tasks
