### ISSUE TITLE
Markdown not formatting in non static question preview page

### ISSUE THREAD

**Issue by dkatzz** [civiform/civiform#6251]
**Describe the bug**
As an admin, when attempting to add markdown to a question (that isn't a static question), we're not seeing the changes appear in the preview page. 

This works after publishing, but not in the (non-static question) question preview

See docs: https://docs.civiform.us/user-manual/civiform-admin-guide/using-markdown#urls

**Expected behavior**
We should see the changes in markdown format in the preview.

**Screenshots**
 
![image](https://github.com/civiform/civiform/assets/86739416/26944e22-b77e-4d8f-ad7b-4b42ca5b7b2f)

![image](https://github.com/civiform/civiform/assets/86739416/4af4cc8f-e594-4e7b-af2c-f19bf61a0325)

**Comment by rockycodes** [comment]
There's an if check that checks that it's a static type question before running it through the markdown formatter. Removing this condition should apply it to all question types: https://github.com/civiform/civiform/blob/88813618cdc44338c35986a11b34c387c6f60230/server/app/assets/javascripts/preview.ts#L234
