### ISSUE TITLE
Bulleted list fearture is not displaying correctly for required questions

### ISSUE THREAD

**Issue by Miguel-314** [civiform/civiform#6349]
**Describe the bug**
I am using a list in a document upload question to indicate which documents can be uploaded to complete the question. When this question is "required" the final bullet in the list displays a red asterisks that is normally seen at the end of the question to indicate that it is required. 

![Image](https://github.com/civiform/civiform/assets/126286905/da874b11-cf9f-4541-9ffb-024cea72ccaa)

If the question is marked as "optional" the list is displayed as expected without the red asterisks. 

![Image](https://github.com/civiform/civiform/assets/126286905/a404beed-bcd5-459c-9560-8c685baf7a07)

**Expected behavior**
I do not expect to see the red asterisks in the list when questions are required. In the example above, this is a required question and cannot be marked as "optional".

**Comment by rockycodes** [comment]
@Miguel-314 I'm pretty sure I have a fix for this. I'm working on other markdown stuff for questions right now and will include this in it!

**Comment by Miguel-314** [comment]
Yay! Thank you!

**Comment by rockycodes** [comment]
@Miguel-314 is this what you imagine it should look like or should the required asterisk be after the main chunk of text (eg. after "include:")
<img width="662" alt="image" src="https://github.com/civiform/civiform/assets/24319951/004f9799-5cba-4757-8fb9-6f6f78c30f00">

**Comment by Miguel-314** [comment]
Hey Rocky! I was hoping the red asterisk would actually be at the end of the question or statement punctuation. In this image above the red asterisks would be at the end of this statement "Please upload a proof of U.S. residency for Miguel Jimenez. The document must include Miguel Jimenez's current name.*

If the red asterisks comes at the end of the final bulleted item, it may make the applicant think this option or more important/relevant/required as compared to the other bulleted items.

**Comment by rockycodes** [comment]
```
If the red asterisks comes at the end of the final bulleted item, it may make the applicant think this option or more important/relevant/required as compared to the other bulleted items.
```
That's my concern as well.

Can you share the markdown you used to create this question?

Unfortunately, there's no way to programmatically tell the difference between the sentences `The document must include Miguel Jimenez's current name.` and `Acceptable documents include:`, since they are both read as paragraph tags, but we could put the asterisk before the list of items like this:

![image](https://github.com/civiform/civiform/assets/24319951/fbac68d3-612a-4466-b244-45ae1953ffac)

**Comment by Miguel-314** [comment]
![image](https://github.com/civiform/civiform/assets/126286905/f6e624ed-f58b-442a-950d-37dc841bf378)
 
 Is this what you mean with "markdown you used to create the question?" 
 
The image above, in your last comment, is exactly what I would expect to see for required questions that also include a bulleted list.

**Comment by rockycodes** [comment]
Yep that is what I meant! And perfect, we'll go with that.

**Comment by rockycodes** [comment]
@Miguel-314 this should be fixed! Let me know if you're still seeing issues with it.
