### ISSUE TITLE
Success messages and error validation for Add/edit client workflow

### ISSUE THREAD

**Issue by sijiayam** [civiform/civiform#6386]
## Add client - success message
When a client successfully adds a client, the page should refresh with a success message that says:

- Title: New client successfully created.
- Description: Your new client [client name] has been added to your client list. You can now begin submitting applications for this client.
- With two buttons, one that takes them to a client dashboard and one back to the client list

[Mockups](https://www.figma.com/file/yfhnUmE2FsonLtAqfeEfoo/TI-Edit?type=design&node-id=1112%3A2095&mode=design&t=z5J8JKPU5WCWA3nw-1)

## Edit client - success message
When a client successfuly updates their client info, the page should refresh with an alert with a success message that says: 
- Client info has been successfully updated.
[Mockups](https://www.figma.com/file/yfhnUmE2FsonLtAqfeEfoo/TI-Edit?type=design&node-id=1112%3A1506&mode=design&t=z5J8JKPU5WCWA3nw-1)

## Delete client 
When a client tries to delete a client, a modal should pop up confirming if they want to delete the account.
[Mockups](https://www.figma.com/file/yfhnUmE2FsonLtAqfeEfoo/TI-Edit?type=design&node-id=1112%3A4963&mode=design&t=z5J8JKPU5WCWA3nw-1)

## Delete client - error message
When a client tries to delete a client and is unable to, an error message should display saying: 
- This account cannot be deleted.
[Mockups](https://www.figma.com/file/yfhnUmE2FsonLtAqfeEfoo/TI-Edit?type=design&node-id=1112%3A4964&mode=dev&t=z5J8JKPU5WCWA3nw-1)

## Delete client - success message
When a client successfully deletes a client, the page should redirect back to the client list page with a success message that says: - The client account for “Taeko Onuki” has been successfully deleted. 
[Mockups](https://www.figma.com/file/yfhnUmE2FsonLtAqfeEfoo/TI-Edit?type=design&node-id=1112%3A1506&mode=dev&t=z5J8JKPU5WCWA3nw-1)

**Comment by sijiayam** [comment]
@melanie-exygy Could you review and let me know if there are any other questions or if it is ready for development?

**Comment by melanie-exygy** [comment]
@sijiayam, here are my notes:

- These look like USWDS alerts.  It might be good to specify that in the requirements.
- Same for the delete client modals.  These are USWDS, right?
- For the Add Client message, it says "With two buttons, one that takes them to a client dashboard and one back to the client list".  What is the client dashboard?  Is that the Program Index page?  Do we take them to the Program Index page applying as the client that they just created?
- Could we specify which style-type to use for the buttons?  We could either use a USWDS button style or one of the styles from `ButtonStyles.java`.  For the latter, I could help you to see what each of those styles looks like.

**Comment by melanie-exygy** [comment]
The add and edit client workflows have already been implemented.  The delete client workflow is part of this other issue:  #5184.  Closing this issue since it is a duplicate.
