### ISSUE TITLE
[Deployment] Only create AWS resources that don't yet exist during bin/setup

### ISSUE THREAD

**Issue by dkatzz** [civiform/civiform#6418]
#### Description
When going through the AWS deployment with Charlotte, we ran `bin/setup` and then had to start over, but then when we re-ran the command, we were getting errors that resources already existed. We tried running `bin/run` `destroy`, but that didn't seem to remove everything. Also, aws-nuke removes all resources from an account, so it only would work if a civic entity has separate organizations setup for each deployment and it requires an account alias (which charlotte didn't have).

We should check whether resources exist before trying to create them and if they do, we should skip the creation step.

<img width="1488" alt="Screenshot 2024-01-19 at 4 17 16 PM" src="https://github.com/civiform/civiform/assets/86739416/ea088ab4-8776-437e-9971-b17c9c244769">

#### What priority is this?

If we do https://github.com/civiform/civiform/issues/6417, this is lower priority, but we should do one of them at least, since this is an issue that can come up during deployments

#### Associated civic entity

This came up when going through the charlotte deployment

**Comment by rockycodes** [comment]
@dkatzz do you think we still need this issue now that we're doing `bin/destroy` as a part of re-running setup?

**Comment by dkatzz** [comment]
> @dkatzz do you think we still need this issue now that we're doing `bin/destroy` as a part of re-running setup?

I think we can close it out after that update! Thank you!
