### ISSUE TITLE
[Deployment] bin/doctor doesn't work with a specified config file

### ISSUE THREAD

**Issue by dkatzz** [civiform/civiform#6419]
**Describe the bug**
When running `bin/doctor`, the command doesn't work unless you have a `civiform_config.sh` file. There are times where civic entities don't have a main config file, but instead have different files for staging, prod, etc., so we should allow this command to be run with a specified config file.

**To Reproduce**

1. Create a civiform_staging_config.sh file in civiform-deploy (and no other config file)
2. Run `bin/doctor --config civiform_staging_config.sh`
3. See error

**Expected behavior**
This should work since we're specifying a different config

**Comment by gwendolyngoetz** [comment]
@dkatzz I already do this. You just need to add an equals sign so it's `--config=civiform_staging_config.sh` 

https://github.com/civiform/civiform-staging-deploy/blob/main/bin/lib/get_cmd_args.sh

**Comment by dkatzz** [comment]
> @dkatzz I already do this. You just need to add an equals sign so it's `--config=civiform_staging_config.sh`
> 
> https://github.com/civiform/civiform-deploy/blob/main/bin/lib/get_cmd_args.sh
> 
> https://github.com/seattle-civiform/civiform-deploy-tf

Oh great thank you so much!! And just to confirm you don't have a `civiform_config.sh` file too, right? Just the environment specific files

**Comment by gwendolyngoetz** [comment]
I do not. I have the example one and three other named ones. I didn't want to accidentally forget to specify the file and run the wrong thing.

My files:
- civiform_config.example.sh
- civiform_config.prod.sh
- civiform_config.staging.sh
- civiform_config.test.sh

**Comment by dkatzz** [comment]
> I do not. I have the example one and three other named ones. I didn't want to accidentally forget to specify the file and run the wrong thing.
> 
> My files:
> 
> * civiform_config.example.sh
> * civiform_config.prod.sh
> * civiform_config.staging.sh
> * civiform_config.test.sh
> 
> I keep the example one so it's easier to update the fork.

Great, thank you!! Adding to the docs: https://github.com/civiform/docs/pull/390
