### ISSUE TITLE
PDF download of draft form

### ISSUE THREAD

**Issue by Miguel-314** [civiform/civiform#6440]
#### Is your feature request related to a problem?

 It is difficult to review a draft form without needing to click through a lot of screens. 

I need departments to be able to review their draft forms. As the forms get longer and more complicated, it can be difficult to provide documents or access that makes it easy to understand branching, answer options, ect. 

Applicants are able to download a PDF of their completed application. I would like to be able to download a PDF of the entire form before any of the answers have been selected.

A clear description of whether this is high, medium, or low priority for you and why (eg, it is majorly blocking a user group, it has been requested several times, etc).

Medium? Depends on how hard this would be. 

Is this request associated with a specific civic entity? If so, please add the associated civic entity to the label (eg, label with 'seattle' if this request is coming from Seattle admins, CBOs, or residents.

Seattle 

If this request or piece of feedback comes from a resident, add the label 'Resident feedback'.
If this request or piece of feedback comes from a CBO or TI, add the label 'TI'.
If this request or piece of feedback comes from an admin, add the label 'Program Feedback'.

#### Done when:

What conditions need to be met before this issue can be closed?

**Comment by shreyachatterjee00** [comment]
Question: can departments not go on CiviForm themselves and preview the form on there and go through it as a resident would? Why is a physical copy needed?

**Comment by Miguel-314** [comment]
This is a request from CiviForm Admins (Me). There is currently no option for seeing all questions, including visibility questions, and potential answers in a single document. We always need to preview test forms with program staff to ensure we are accurately capturing eligibility and visibility conditions, reviewing for accessibility standards, copy edits, and for plain language review to prepare for translations. Our current work around is to create a word doc that mirrors the full application by copying and pasting all questions, then going into the question bank to collect all potential answers. This workaround is time consuming and subject to error. 

If there are better workarounds that I have not considered I am all ears. Thanks!

**Comment by caitlinshk** [comment]
Hi @Miguel-314 ! This seemed like a fun project for a Friday afternoon so I took a stab at it. Attached is a PDF export of a sample program with all question types and some eligibility and visibility questions. I'd love to hear what you think, what it's missing, what's confusing, etc. I may ask to quickly sync up with you in call to hear what you think in more detail if you happen to be available :) Thanks!

[comprehensive-sample-program-2024-03-08T13_23_31.636496.pdf](https://github.com/civiform/civiform/files/14543333/comprehensive-sample-program-2024-03-08T13_23_31.636496.pdf)

**Comment by Miguel-314** [comment]
This sounds really cool but I got this window when I tried to click the link. I am down for a sync to talk through how it works! 

![image](https://github.com/civiform/civiform/assets/126286905/6c814a3d-26ab-4fcf-9764-13b2f0bd81de)

**Comment by caitlinshk** [comment]
Oh weird! I emailed the sample PDF to you instead.

**Comment by Miguel-314** [comment]
This looks amazing and is exactly what I was hoping for. 

Its easy to read. I like that it differentiates screens. I like that you can see the admin ID but its in grey. It feels easier for program staff to focus on text, help text, and answers but still gives me a reference to make edits during review. 

I like the way the enumerators are laid out. This feels clear and easy to read. 

I like that I can see the eligibility conditions clearly laid out as well. 

I was a little confused with the phrase "screen with predicate". It makes sense after I read it but we tend to use the term "visibility condition". Its a synonym so I don't feel like its a big deal to leave it the way you have it.

**Comment by caitlinshk** [comment]
Thanks for the feedback Miguel!!

"Screen with Predicate" is actually just a test name I'd chosen for that particular screen, so you wouldn't normally see "Screen with Predicate". The test program also had screens named "enumerator" and "repeated screen for enumerator", which might be why the enumerators felt clear and easy to read. It's possible the enumerators may be less clear with real program data.

I'll take another pass at laying out enumerators to make them clear with real data like "Household members" and then I'll submit this implementation as a first pass. Then you can start using it with your programs, and let me know what else you need!

**Comment by Miguel-314** [comment]
I love that. I have a few test programs that I think it would be interesting to pull from and will give me a much better idea of whats missing and whats working well. Thank you!

**Comment by caitlinshk** [comment]
@Miguel-314 this should be enabled in your release now. If you click "Edit" on a program you should see a "Download PDF preview" button. Once you try it out, let me know what else you need!

@lftaylor2023 This should be enabled on v1.56.0. I'm not sure what version Arkansas is currently on, but once you're onto v1.56.0 and give it a try you should also let me know what else you need!
