### ISSUE TITLE
Remove default value for IDCS_DISCOVERY_URI in auth.conf

### ISSUE THREAD

**Issue by rockycodes** [civiform/civiform#6442]
We are currently using Seattle's test OIDC instance for the default value for `IDCS_DISCOVERY_URI` in `auth.conf`. We should remove this. We will need to provide a different default value so the prod simulator test (defined by [prod-simulator-compose.yml](https://github.com/civiform/civiform/blob/ac5567e830c85c2ff7edd99b4e4040dd872f9586/test-support/prod-simulator-compose.yml)) still passes.

**Comment by gwendolyngoetz** [comment]
https://github.com/civiform/civiform/issues/4706
