### ISSUE TITLE
Clicking Review Without Saving Deletes all Data

### ISSUE THREAD

**Issue by lftaylor2023** [civiform/civiform#6450]
Using Arkansas' "start here" form as an example, when logged in as a guest if you complete all 11 questions but hit "Review" rather than "Save and Next," all data is deleted and you have to start over. This may be the intended functionality but I think we need to anticipate that applicants are going to do this from time to time. I haven't tried this as a logged in user yet because I'm running out of throw away email accounts. I'm assuming that the functionality will be the same as a logged in user who is using Civiform for the first time and hasn't save any data in any forms. 

Possible solutions, in no order of precedence: 

- Force the form data to always be cached in the browser when clicking "review" before "save and next."
- Add text below the row of buttons that warns users that if they choose "review" without first clicking "save and next," that their data will be lost and they will have to start over. 
- Don't show the "review" button until the form data has been saved. 

Additionally, it doesn't seem necessary to have "review, "previous" and "save and next" buttons on a form that consists of just one screen. There's no "previous" and no "next," in reality. So perhaps in scenarios when a form is only one screen, only present the user with the option to "Save and Review" their form entries.  

Leslie Taylor, State of Arkansas, ARData

**Comment by caitlinshk** [comment]
It looks like we've had this reported multiple times in the past: https://github.com/civiform/civiform/issues/3601, https://github.com/civiform/civiform/issues/2470, and https://github.com/civiform/civiform/issues/1670. I agree this is confusing and we should fix this. The simplest fix is probably a confirmation modal saying that data won't be saved? Based on [Bion's comment here](https://github.com/civiform/civiform/issues/2470#issuecomment-1138033181), also saving the data when clicking "Review" begs the question of what to do if the data they entered fails validation.

**Comment by lftaylor2023** [comment]
Can we cache everything that passes validation, flag everything that doesn't, and show those fields to the applicant as needing to be revised (red text that alludes to what the problem is)?

**Comment by caitlinshk** [comment]
So have the same experience as if you click "Save and Next" but have validation errors? Probably! We'll talk with our designers and product managers to confirm what behavior should happen but that seems reasonable to me.

**Comment by shreyachatterjee00** [comment]
Aligned that having the "Review" button having the same behavior as "Save and next" is a good fix for now. We'll also do some more thinking holistically from a UX perspective about how these buttons and navigation work overall.

**Comment by caitlinshk** [comment]
[#5682](https://github.com/civiform/civiform/issues/5682) is another duplicate (thanks @melanie-exygy  for calling this one out in Slack!)

**Comment by caitlinshk** [comment]
Charlotte also mentioned this as an issue in our last call with them.

**Comment by caitlinshk** [comment]
All the implementation work is done, but I still need to do a bug bash to find any edge cases and start enabling it in dev, staging, and prod. https://github.com/civiform/civiform/issues/6860 is the feature flag issue. Do you think we should keep both this issue and the feature flag issue open, or is closing this issue and just keeping the feature flag issue open sufficient? @nb1701

**Comment by caitlinshk** [comment]
Okay great! Marking this as complete. I hope this will be enabled in the next few weeks!
