### ISSUE TITLE
Add documentation about using AWS organizations and AWS cloudshell for CiviForm

### ISSUE THREAD

**Issue by dkatzz** [civiform/civiform#6462]
#### Description

These were some items that came up in the Charlotte staging deployment that would be helpful to add to the docs.

**Comment by rockycodes** [comment]
@dkatzz I'm working on a docs overhaul right now. I'll add this to the list.

**Comment by dkatzz** [comment]
> @dkatzz I'm working on a docs overhaul right now. I'll add this to the list.

I actually worked on adding this today, just hadn't sent the PR yet. Here it is - https://github.com/civiform/docs/pull/386. Feel free to approve and I can submit or loop it in with your changes, whatever is easiest!

Thanks for working on the docs overhaul !!

**Comment by rockycodes** [comment]
Oh great! I'm working on an overhaul for our developer docs, so I'll see what makes sense to include there. Thanks for doing this write up!
