### ISSUE TITLE
Switch out phone number question with correct universal question

### ISSUE THREAD

**Issue by elisekalstad** [civiform/civiform#6467]
We now have a phone number question type. However, programs that were set up before that feature went live still use the old phone number question. The old version is just a text field and does not correctly format into phone numbers. This makes it hard to process applications, since applicants can put in any anything as a phone number.

#### Describe the solution you'd like.

Aff Sea team needs to communicate with Program Staff the change and how it will impact them. Aff Sea team needs approval from program staff. Aff Sea team needs to swap out the old phone number question with a new one.

Need to communicate and update the following programs:

- [x] Parks scholarship
- [x] Seattle preschool
- [ ] Smoke alarm
- [x] Gold card
- [x] Flash card
- [x] SHA orca

#### What priority is this?

P1--this impacts residents and needs to be cleared up before we bring on other programs

#### Associated civic entity

Seattle

**Comment by elisekalstad** [comment]
@elisekalstad -- Reach out to William

**Comment by Miguel-314** [comment]
SFD has been completed. Race question was also added to their form. This is not flagged as universal in Prod and may need to be one of the next questions we make universal.
