### ISSUE TITLE
Default country code for phone numbers

### ISSUE THREAD

**Issue by elisekalstad** [civiform/civiform#6525]
#### Is your feature request related to a problem? Please describe.

Most of our applicants (if not all of them!) will have a U.S. phone number. Is it possible to set the "Country" on the phone number question type to default to "United States" automatically? Alternatively, could we just hide the "Country" selector? It's an extra question that doesn't impact the input of the phone number; that is, no matter what the person selects, they are still prompted to enter a 10-digit number. 

#### Describe the solution you'd like.

As an applicant, I do not want to answer the "County" question when asked for my phone number.

#### What priority is this?

P2-we'd like to switch out the phone number question that is currently in use in all program forms (currently just a text question type) with the actual phone number question type. But it would be helpful if that change doesn't add an additional question for residents to complete. So we'd like to remove the "Country" question before switching the questions in all program forms. 

We would also like to align the format of the Seattle Login phone number question with the CiviForm phone number question--both should be 10-digit phone numbers. The Seattle Login does not ask for country code, so this information is extraneous.

#### Associated civic entity

Seattle

#### User Group

Feedback is coming from the CiviForm Admins. Residents have not yet tested this feature.

#### Additional Context
Current State and Options
![image](https://github.com/civiform/civiform/assets/86082659/be7e7fe5-baed-4e0c-bb07-feeec2342728)

Seattle Login Phone Formatting:
![image](https://github.com/civiform/civiform/assets/86082659/613885d0-137b-4fa0-840a-2b9981f1571e)

#### Done when:

Applicants no longer need to select a Country.

**Comment by msprenke** [comment]
Canada country code is also +1 so its redundant

**Comment by gwendolyngoetz** [comment]
Related work #6670

**Comment by gwendolyngoetz** [comment]
Related work #6675
