### ISSUE TITLE
Program admin can customize the CSV of applicant data they download from the program admin view

### ISSUE THREAD

**Issue by neel-a-mehta** [civiform/civiform#655]
In #654, we define how a program admin can download the whole list of applications in CSV format with a single click. But some may want to customize that list, such as by specifying that they only want to download applications sent after X date, or those sent before Y date.

[See the product requirements doc](https://docs.google.com/document/d/1zhs65i5PzxfkiZXPniPAxEDD257Iz4IP1JfxHY36hR8/edit?resourcekey=0-ByzGbFZlzPNxZTxRQCbVDQ#) to see what features are needed here.

**Comment by elisekalstad** [comment]
I updated the product document to include feedback we received from program staff:

Problem: The CSV export of all columns (corresponding to all questions in the form) is more information than many program admins need.

Ideal: Program admins could specify the columns they need to export. This would also solve for the expanding number of columns, if the program form/questions were updated.


[Custom CSV Export by Fields.pdf](https://github.com/civiform/civiform/files/9457269/Custom.CSV.Export.by.Fields.pdf)
