### ISSUE TITLE
Update No Address Found error in address correction

### ISSUE THREAD

**Issue by msprenke** [civiform/civiform#6603]
**Describe the bug**
Addresses that are not in our Seattle GIS layer (such as in greater King County) throw an error for residents that is confusing. 

              No valid address found
              We could not verify the address that you provided. Please edit your address to continue.
              Address entered:
              [Edit]

 There are programs that use address correction to validate correct addresses but do not have eligibility set.  The error message needs to be changed to something that prompts the applicant to continue anyways.  Something like: 

                No valid address found
                We could not verify the address that you provided. Please edit your address to continue.  **If you believe the address to be correct, click Save and Next.**
                Address entered:
                [Edit]

**To Reproduce**

1. Go to a program with address correction enabled
2. Enter an address outside of the City of Seattle (such as in Issaquah)
3. See the error.   

**Expected behavior**
A clear and concise message that prompts the user to click save and next.  This should be find for address eligibility as well, it will be found as not eligible since it is not in the service area.

**Comment by sijiayam** [comment]
Tried to cut down the wordiness and simplify some o the language.
             
             We could not verify that address. 
             Please check and edit your address to continue.

             Address entered:

             We could not verify that address. 

             Please check and edit your address to continue.  If you believe it is correct, click Save and Next.

**Comment by msprenke** [comment]
Thank you!




Cheers;



Matt



Matt Sprenke

Business Systems Analyst | Affordable Seattle Team (CiviForm)

O: 206.615.1327 | ***@***.******@***.***>

SEATTLE INFORMATION TECHNOLOGY

Get the latest tech news & classes on the Seattle Technology Learning Hub<https://seattlegov.sharepoint.com/sites/ITD_Learning_Hub>

LinkedIn<https://www.linkedin.com/company/seattle-information-technology-department/> l Facebook<https://www.facebook.com/SeattleITDept/> l Twitter<https://twitter.com/SeattleITDept> l E-Newsletter<https://public.govdelivery.com/accounts/WASEATTLE/subscriber/topics?qsp=WASEATTLE_10>

Emails sent to and from the City of Seattle are governed by the Washington Public Records Act and may be subject to disclosure to a third-party requester. To learn more please see Chapter 42.56 RCW<https://apps.leg.wa.gov/rcw/default.aspx?cite=42.56> and the City’s Privacy Statement<http://www.seattle.gov/tech/initiatives/privacy/privacy-statement>.



________________________________

**Comment by gwendolyngoetz** [comment]
We just need to get translations to update the text now.

**Comment by msprenke** [comment]
added Elise to send translations
