### ISSUE TITLE
Program Admin search applications for a single day functionality is not clear

### ISSUE THREAD

**Issue by Miguel-314** [civiform/civiform#6629]
#### Is your feature request related to a problem? Please describe.

SHA informed us that one of the ways they prefer to look up applications is by day submitted. The date field search cannot search for a single day. You must enter a two day range and review applications within that range. 

Total applications for SHA in Test. 

![Image](https://github.com/civiform/civiform/assets/126286905/24580cb0-1110-4110-be7b-579609ce2779)

Searching for an application from 1/12/2024 produces zero results 

![Image](https://github.com/civiform/civiform/assets/126286905/08096ed3-6fe0-4476-84fb-7f8f1f4ec40c)

Searching for an application with an expanded range of 1/12/2024 - 1/13/2024 shows the desired results 

![Image](https://github.com/civiform/civiform/assets/126286905/52d9aef5-d060-404c-9d41-cf80c91095eb)

#### What priority is this?

A clear description of whether this is high, medium, or low priority for you and why (eg, it is majorly blocking a user group, it has been requested several times, etc).

#### Associated civic entity

Is this request associated with a specific civic entity? If so, please add the associated civic entity to the label (eg, label with 'seattle' if this request is coming from Seattle admins, CBOs, or residents.

#### User Group

If this request or piece of feedback comes from a resident, add the label 'Resident feedback'.
If this request or piece of feedback comes from a CBO or TI, add the label 'TI'.
If this request or piece of feedback comes from an admin, add the label 'Program Feedback'.

#### Done when:

What conditions need to be met before this issue can be closed?

**Comment by melanie-exygy** [comment]
@Miguel-314 Is this the TI search or the Program Admin search?  It doesn't seem like something that I can access when I'm logged in as a TI.

**Comment by gwendolyngoetz** [comment]
@melanie-exygy That's the program admin search page. I found that behavior a long long time ago. There may be a bug already about this.

**Comment by msprenke** [comment]
This is both a training opportunity and an opportunity to make the interface more clear.  You can search for a single day.  when you enter 1/12 and 1/13 as above you only get data from the 12th.  essentially you get from midnight 1/12 to midnight 1/13

This is not clear however so lets brainstorm a way to make this more user friendly.

**Comment by Miguel-314** [comment]
[heart]         Jimenez, Miguel reacted to your message:
________________________________

**Comment by msprenke** [comment]
@sijiayam Sijia, this would be a good item to tackle with any UI changes to the Program Admin experience.  Let me know if you have any questions.
