### ISSUE TITLE
Formatting does not apply to text in check box answers

### ISSUE THREAD

**Issue by Miguel-314** [civiform/civiform#6648]
#### Is your feature request related to a problem? Please describe.

Some check box answers can be rather large. Formatting can help break up the text and highlight key information. 

#### Describe the solution you'd like.

I would like to be able to use text formatting options in the text of checkbox or radio button answers. Is this possible?

Example: Admin ID: Decom_Options

#### What priority is this?

A clear description of whether this is high, medium, or low priority for you and why (eg, it is majorly blocking a user group, it has been requested several times, etc).

#### Associated civic entity

Seattle

#### User Group

If this request or piece of feedback comes from a resident, add the label 'Resident feedback'.
If this request or piece of feedback comes from a CBO or TI, add the label 'TI'.
If this request or piece of feedback comes from an admin, add the label 'Program Feedback'.

#### Done when:

What conditions need to be met before this issue can be closed?

**Comment by rockycodes** [comment]
@Miguel-314 can you include some screenshots of what you would like to format?

**Comment by Miguel-314** [comment]
![image](https://github.com/civiform/civiform/assets/126286905/716d0b05-5bc9-4f65-8c11-ba96db07759f)

@rockycodes here is an example of a current question on our Weatherization Application. These program requires applicants to select one of the following options to convert their oil heat to electric heat. The options need to clearly explain to the applicant the legal ramifications of each option. It would be great if we could use, page breaks, bold or italics to help applicants identify key aspects of each option. 

Here is an example of a legal statement in the same form. We are using some text formatting here but I think this is another area page breaks would be beneficial. 

![image](https://github.com/civiform/civiform/assets/126286905/9f9dd808-90f4-47a4-9862-af3427168a20)

**Comment by rockycodes** [comment]
Thank you! That makes sense. Providing page breaks should be a relatively simple change and I'll look into allowing formatting for question options as well.

**Comment by Miguel-314** [comment]
[like]  Jimenez, Miguel reacted to your message:
________________________________

**Comment by msprenke** [comment]
@rockycodes Hi Rocky, are you working this currently? Can i move it to IN PROGRESS?

**Comment by rockycodes** [comment]
Yep!

**Comment by rockycodes** [comment]
@Miguel-314 line breaks in question text should work now. I'm still working on formatting question options.

**Comment by Miguel-314** [comment]
Great! Thank you! 

Are there any special instructions on how to use page breaks or is it as simple as using the enter key to create lines where page breaks are needed? 

https://docs.civiform.us/user-manual/civiform-admin-guide/using-markdown#urls

**Comment by rockycodes** [comment]
Nope! It's just using the enter key 😄

**Comment by Miguel-314** [comment]
Perfect. Thank you!

**Comment by rockycodes** [comment]
@Miguel-314 I had to put this down for a bit, but I'm picking it back up again. Question for you -- would you like to have line breaks in the question options as well? Or just the ability to format text/add links.

**Comment by Miguel-314** [comment]
I think line breaks makes sense as well. I have a new program coming online that will benefit from links in the answers too. I have a current work around but this would make it look cleaner. Thank you!

**Comment by rockycodes** [comment]
Ok great! I'm going to open a separate issue for line breaks, since it will require a bit more work. But links will work in the fix I'm working on for this issue.

**Comment by Miguel-314** [comment]
@rockycodes I think I might have found a bug. I am working to format a question with a bullet list. Here is the result I am getting.

![image](https://github.com/civiform/civiform/assets/126286905/ab3f4830-ee7a-4baa-bded-c3eab7776524)

![image](https://github.com/civiform/civiform/assets/126286905/dd7f5de5-a66c-44ee-9929-7e83fc574ace)

**Comment by rockycodes** [comment]
@Miguel-314 that definitely seems like a bug. I'll look into it.

**Comment by rockycodes** [comment]
This issue will close with the PR I'm about to merge, so I made a new bug issue for lists: https://github.com/civiform/civiform/issues/7240
