### ISSUE TITLE
[Program Card Images] "Back" button on the "Manage translations" page doesn't WAI

### ISSUE THREAD

**Issue by sxyao33** [civiform/civiform#6657]
**Describe the bug**
The "Back" button on the "manage translations" page doesn't take the user back to the previous page.

**To Reproduce**

1. Go to the image upload screen
2. Click on "Manage translations"
3. CLick on "Back" to get back to the Image upload screen
4. Instead of Img upload, I'm taken to the program dashboard

**Expected behavior**
back to the previous screen - img upload

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

- OS: MacOS
- Browser: Chrome

**Additional context**

**Comment by caitlinshk** [comment]
After discussing with Sijia, we reailzed that we need a better overall navigation strategy for the admin dashboard overall, so we don't want to do a quick-fix for just the "Back" button on the translations page. Instead, we decided to just remove the "Back" button from the translations page for now. Admins can still use the browser back button to get back to where they came from.
