### ISSUE TITLE
Move alt-text message higher up 

### ISSUE THREAD

**Issue by shreyachatterjee00** [civiform/civiform#6662]
**Describe the bug**
Message that tells you to add the alt-text before image is lowest on the page, confusing for users who don't see it until after they try to upload an image. 

**To Reproduce**
Go to image upload page. 

**Expected behavior**
Move this message below the alt-text box. 

<img width="781" alt="image" src="https://github.com/civiform/civiform/assets/20480121/e85d75fe-5660-4057-b124-84d360ecbe7f">

**Comment by dkatzz** [comment]
@shreyachatterjee00 would you mind marking up that image with a box around what pieces should move and an arrow to where you'd like it instead to make it a bit clearer?

**Comment by caitlinshk** [comment]
I believe it should go right above the "Save image description" button (right below the text box to enter the description).

**Comment by dkatzz** [comment]
Perfect thanks! Just to confirm does this look right?

<img width="783" alt="Screenshot 2024-02-22 at 3 35 35 PM" src="https://github.com/civiform/civiform/assets/86739416/efd0a422-729a-4047-bcb3-efec17d1646d">
