### ISSUE TITLE
Environment variables not honored

### ISSUE THREAD

**Issue by inghamn** [civiform/civiform#6680]
When deploying a new release, new environment variables in the container do not affect the settings that are actually used in the app.  

In our deployment, when upgrading from v1.42 to v1.49, adding a new PROGRAM_CARD_IMAGES environment variable to the container does not enable the card images.

```bash
civiform-6b4477c6f5-rrgc4:/# env | grep IMA
CIVIFORM_IMAGE_TAG=SNAPSHOT-52485be-1706577220
SHOW_CIVIFORM_IMAGE_TAG_ON_LANDING_PAGE=true
PROGRAM_CARD_IMAGES=true
```

With the transition to editing settings in the web interface and storing them in teh database, are the environment variables in the container used anymore?
![screen](https://github.com/civiform/civiform/assets/630282/726dda64-f51b-482b-9744-f986e5df0213)

**Comment by rockycodes** [comment]
@inghamn The admin settings panel is the source of truth for all variables that are editable. Any variables that are not editable via that panel should still be set in the config file. Better documentation for this is coming soon!

**Comment by rockycodes** [comment]
Exactly. Feature flags in particular will always behave like this and shouldn't be set in your config file. Values for variables that are editable in the admin settings panel are saved in/referenced from the db after their initial setup.

**Comment by inghamn** [comment]
Sounds good, we'll start updating our deployment accordingly
