### ISSUE TITLE
Awkward spacing on file upload question if there's no help text

### ISSUE THREAD

**Issue by caitlinshk** [civiform/civiform#6742]
**To Reproduce**

1. As an admin, create a file upload question but don't provide any help text for it. Publish the program.
2. As an applicant, open the file upload question.

You can see an awkward gap where there's some reserved space for the help text.

**Screenshots**
![image](https://github.com/civiform/civiform/assets/147177873/27578cc4-647c-476a-8503-484c48923539)

**Expected behavior**
We should remove that extra spacing if there's no help text. (I don't think this is high priority because I'd expect almost all file upload questions to have help text explaining what sort of file to upload.)

**Comment by gwendolyngoetz** [comment]
Related #8537 
Fixed by #8657
