### ISSUE TITLE
Allow Question Help Text to Not Require `$this`

### ISSUE THREAD

**Issue by gwendolyngoetz** [civiform/civiform#6784]
When creating a question that is tied to an enumerator you are currently required to include the text `$this` in both the question text and the help text. 

Seattle is requesting that the help text use `$this` if provided, but only require it for the question text.

![image](https://github.com/civiform/civiform/assets/195162/e352249e-3d8d-4720-9106-6af018c6ce73)

**Comment by gwendolyngoetz** [comment]
When looking at this for Matt I had this working by removing these lines https://github.com/civiform/civiform/blob/04e199cf52dda29d79fdb1b1d2714109d183927f/server/app/services/question/types/QuestionDefinition.java#L428-L430

There likely isn't much left to do other than update tests.

**Comment by isabelcshaw** [comment]
This makes sense to me! We'll take a quick look to make sure there aren't any less obvious constraints and follow up here.
