### ISSUE TITLE
Address Eligibility to include option for "outside service area"

### ISSUE THREAD

**Issue by Miguel-314** [civiform/civiform#6800]
The Office of Housing Weatherization only available for residents who are in the Seattle City Light service area but outside the City of Seattle AND heat their home with electric heat. Customers in this category that heat their home with either Oil or Gas must use the King County Weatherization program. 

We have determined that we want to create a visibility condition that shows static text informing Oil and Gas heated homes outside the City of Seattle information about the King County program with a link. 

Here is a screen shot of the current visibility options. 

![Image](https://github.com/civiform/civiform/assets/126286905/596cb10c-2935-4ff9-968c-f7171a40ac8c)

In the second column, the images shows "in service area". This is the only option you can select in this drop down. 

Is it possible to create a second option that filters applicants who are "out of service area"?

**Comment by gwendolyngoetz** [comment]
@Miguel-314 try setting the third drop down  to this
![image](https://github.com/civiform/civiform/assets/195162/ff2f9c77-9cbc-4a19-91f3-77fd09148e8a)

**Comment by msprenke** [comment]
@gwendolyngoetz let me know if you need a design document for this.  Seems pretty straight forward.

Wondering if in the meantime it could be configured in the opposite way:  instead of shown if gas/oil Not in service area, we could do NOT show if Electric and IN the service area?

**Comment by Miguel-314** [comment]
I might be reading this wrong but I don't think that will work. Here is the full eligibility I am trying to program. 



![Image](https://github.com/civiform/civiform/assets/126286905/6fb2c3b4-9a6c-467d-a979-df871e5d9e41)

**Comment by Miguel-314** [comment]
I think this has been properly communicated but just in case, the feature being request is a visibility/eligibility condition that allows for both "in service area" and "outside service area".
