### ISSUE TITLE
Implement re-design of the Organization members table on TI dashboard

### ISSUE THREAD

**Issue by melanie-exygy** [civiform/civiform#6827]
#### Describe the solution presented in this issue.
Change table layout to reflect the new design that is in the mocks.  This includes:
- Using the USWDS Striped Table component: [USWDS table docs](https://designsystem.digital.gov/components/table/)
- Putting email in its own column
- Adding the Account Settings header
- Changing the wording for the column headers to "Name", "Email" and "Account status".

#### Link to Figma mocks: 
[Mocks](https://www.figma.com/file/yfhnUmE2FsonLtAqfeEfoo/TI-Edit?type=design&node-id=1-20&mode=design&t=35RyBMEoVM6W9hEV-0)

#### Add screenshot of relevant mocks for this issue here: 
<img width="850" alt="image" src="https://github.com/civiform/civiform/assets/116591382/f1c87cd7-a4b5-45d1-91c1-d57e18011c15">

**Comment by sijiayam** [comment]
@melanie-exygy Confirm that the the table is the striped table, and the double line is an accident! I'll update the mocks.. good catch on that one
