### ISSUE TITLE
Emphasize Image Upload Description Requirement

### ISSUE THREAD

**Issue by gwendolyngoetz** [civiform/civiform#6884]
I spent way longer than I want to admit trying to figure out why I couldn't upload an image onto the program. It would be very helpful if we emphasize the comment on having the title saved before being allowed to upload.

I like the little slim alert (with or without an icon).
https://designsystem.digital.gov/components/alert/

### Current
![image](https://github.com/civiform/civiform/assets/195162/85f09144-ce8f-4eb0-9a58-782b155f7c46)

### Suggested
![image](https://github.com/civiform/civiform/assets/195162/474c6966-fba1-4243-a2db-9befcea8135b)

**Comment by caitlinshk** [comment]
Ooh I like your suggestion, let me check with Shreya on it!

**Comment by gwendolyngoetz** [comment]
Should be quick to do. It's already build in, in the ViewUtils.java files
