### ISSUE TITLE
[North Star Applicant UI]: Add support for modal dialogs

### ISSUE THREAD

**Issue by greg-hyde** [civiform/civiform#6902]
#### Describe the solution presented in this issue.
Load any modal dialogs needed on load in applicant pages. Update the data-load-modal attribute on the body appropriately for screenshot tests

#### Done when:
What criteria need to be met for the issue to be finished? 
- [ ] All modal dialogs in the applicant UI flow are shown, and data-load-modal is removed without breaking any screenshot tests.

Individual issues will be filed for individual modal dialogs to be added

**Comment by greg-hyde** [comment]
I think that is going to be a question of scoping for product, which is still in progress. This issue in particular is just tied to including modals in the html we render, rather than the content of the modals themselves.
The modals you link to fall into 3 buckets:
1) showed in page for applicants (just the login modal)
2) modals shown in their own page for applicants
3) modals not shown to applicants.

3 will definitely be out of scope, 1 and 2 are still TBD whether they are going to be updated, but I will file issues for individual modals when the scoping is finalized

**Comment by gwendolyngoetz** [comment]
I request that we wrap the modal in the `<dialog>` element. We don't have to use the dialog api, I just want the semantic markup.

**Comment by greg-hyde** [comment]
We have support for modals now, so i'm going to close this out, and file issues for individual modals that need to be implemented
