### ISSUE TITLE
Static text screenshot doesn't match actual static text rendering

### ISSUE THREAD

**Issue by greg-hyde** [civiform/civiform#6914]
**Describe the bug**
Static text questions are bold and size XL by default, but the screenshot tests don't reflect that.

**To Reproduce**

1. Create a static text question with the markdown from static_text.test.ts
2. Compare it to the markdown-text.png browser golden

**Expected behavior**
They should match (both totally bold)

**Screenshots**
Live: 
![45gn7p76hzs2aP7](https://github.com/civiform/civiform/assets/156004543/3e734889-23f5-4f67-91b6-b61a796929f0)
Screenshot golden: https://github.com/civiform/civiform/blob/main/browser-test/image_snapshots/static_text_test/markdown-text.png

**Comment by avaleske** [comment]
let me introduce you to an old friend:
https://github.com/civiform/civiform/issues/3225

**Comment by gwendolyngoetz** [comment]
@avaleske I was just about to post that myself, lol

**Comment by gwendolyngoetz** [comment]
Should no longer be a problem
