### ISSUE TITLE
[Disabled Programs] add `disabled` to the program visibility

### ISSUE THREAD

**Issue by azhangggggg** [civiform/civiform#6995]
#### Is your feature request related to a problem? Please describe.

Per Arkansas's ask, they'd like a way to delete programs. 

#### Describe the solution you'd like.

We provided them with the solution `disable` programs. 

#### What priority is this?

It's high as in it's blocking Arkansa launch.

#### Associated civic entity

Arkansas

#### Done when:

There's a `disabled` status for program visibility options. 
Applicants won't see the disabled programs from the dashboard if they haven't started with the application yet.

**Comment by gwendolyngoetz** [comment]
@azhangggggg Can this be closed?
