### ISSUE TITLE
Display buttons and remove form on successful creation of a TI client

### ISSUE THREAD

**Issue by melanie-exygy** [civiform/civiform#6998]
#### Describe the solution presented in this issue.
Add "Start an application" and "Back to client list" buttons under the success alert that shows after a TI successfully adds a new client.  Also, hide the form.

#### Link to Figma mocks: 
[TI mocks](https://www.figma.com/file/yfhnUmE2FsonLtAqfeEfoo/TI-Edit?type=design&node-id=1%3A19&mode=design&t=QRk1Aev1YpG3M0l1-1)

![image](https://github.com/civiform/civiform/assets/134556723/400ae025-997f-4a77-b979-790ec484e121)

#### Additional Context
This is a follow-up to [this PR](https://github.com/civiform/civiform/pull/6937).

#### Done when:
- [ ] Both buttons show under the success alert
- [ ] Button text is translated
- [ ] The form is hidden
- [ ] The "Start an application" button navigates to the Program Index page so that the TI can apply on behalf of the new client.

**Comment by melanie-exygy** [comment]
@sijiayam could you please confirm that clicking the "Start an application" button should take the TI to the Program Index page so that they can apply on behalf of the new client?

Also, I noticed in the mocks that we hide the form after adding a new client, but we don't hide it after editing a client.  Is this difference intentional?
![image](https://github.com/civiform/civiform/assets/134556723/8ac0f543-dd4d-4c2c-be86-bd1e72f8947b)

**Comment by sijiayam** [comment]
@melanie-exygy Yes the difference is intentional. 

For creating a new client, the suggested next step is starting an application, and the flow supports that.

For editing a client, we are on a edit client page which should allow folks to edit and view their info.
