### ISSUE TITLE
Error when opening application from email (as Program Admin)

### ISSUE THREAD

**Issue by elisekalstad** [civiform/civiform#7107]
**Describe the bug**
As a Program Admin, I receive an email every time there is a completed application. The email contains a link to the application. When I click the link, I get a 403 error message. If I go to civiform.seattle.gov and click "admin", I am able to successfully login. Is it possible to access applications directly from the email without going to civiform and clicking admin first?

**To Reproduce**

1. See an email for a completed application
2. Click on the link within the email to the completed application
3. See the 403 error

**Expected behavior**
Able to go from the email link directly into the CiviForm Program Admin role to view the completed application

**Comment by gwendolyngoetz** [comment]
I'm pretty sure some work Tom did earlier this week will resolve this. I just updated the Test server. Can you check?

**Comment by elisekalstad** [comment]
@elisekalstad Test it out!

**Comment by msprenke** [comment]
Appears to be working now.  Marking closed.
