### ISSUE TITLE
Allow admin to specify a minimum/maximum answers for enumerator questions

### ISSUE THREAD

**Issue by gwendolyngoetz** [civiform/civiform#7136]
Example: Applicant can choose to have up to 3 trees. Each tree option has multiple fields that would be part of the enumerator.

Currently enumerators are unbounded.

We should add a setting to allow specifying the maximum number of times an enumerator can be filled out. Similarly a minimum setting may be useful.

**Comment by msprenke** [comment]
Is this being actively worked @jeffpw-goog ?  I'd like to move to in progress if it is

**Comment by jeffpw-goog** [comment]
@msprenke Yes I am actively working on it - sorry I didn't think to mark it in progress!

**Comment by jeffpw-goog** [comment]
Based on input from the Product Design Committe, I updated the title and description to include adding a setting for a minimum requirement as well.

**Comment by jeffpw-goog** [comment]
For the record, several other question types have similar min/max settings already:

- Number - min/max value
- Checkbox - min/max number of choices
- ID - min/max value length
- Text - min/max value length
- Currency - no setting (but should have a min/max value like Number?)
