### ISSUE TITLE
Create method for dumping and restoring the entire production database

### ISSUE THREAD

**Issue by nb1701** [civiform/civiform#7232]
Before we ask people to deploy a version of CiviForm that includes a PostgreSQL database migration, we need a prescribed (and preferrably automated) way for dumping the entire contents of the production database in case something goes wrong.  We then need a way to restore that dump to a running CiviForm instance.

Utilizing pgadmin for this task works, and we already have a command in our deployment system to temporarily stand up pgadmin connected to the database, and then tear it down when finished.  However, this requires manual steps to dump the database and restore it, and does not allow for automation to back up the database regularly.

We should create another command in our deployment system that opens access to the database to your particular IP (like the pgadmin command does), performs the `pg_dump` command, saves it locally, and then tears down the resources. And another command to run `pg_restore` for a given dump file.  This will probably look something like the procedure [here](https://github.com/seattle-civiform/documents/blob/main/scripts/old-scripts/pull-prod-admin-config), translated into a Terraform module to set up the temporary EC2 host, and then the deployment tooling manages SSHing in, running pg_dump, SCPing the file locally and tearing everything back down.

**Comment by dkatzz** [comment]
Closed https://github.com/civiform/cloud-deploy-infra/pull/280 as well since that was related
