### ISSUE TITLE
Question bank program list does not match program names

### ISSUE THREAD

**Issue by Miguel-314** [civiform/civiform#7293]
#### Is your feature request related to a problem? Please describe.

When reviewing questions in the question bank you can click each question to see what programs they are being used in. However this list isn’t very illustrative. 
 

![Image](https://github.com/civiform/civiform/assets/126286905/8db1c04f-a551-4666-a449-3f93c8ae4fe0)

You can see above that question Admin ID: Applicant Name is used in programs 
-	FLASH Card
-	FLASH Card (HSD) 

When you navigate to the program list, it is unclear with code applies to which program. 

![Image](https://github.com/civiform/civiform/assets/126286905/2768bba3-6b7d-4acf-9048-16508504dbd4)

 
I would suspect that I can enter each program to see the program details to find the correct code for the correct program.  But that also doesn’t show me the information I am looking for. 

 

![Image](https://github.com/civiform/civiform/assets/126286905/91111136-4c54-4e91-9b76-9a09fce85398)

I am looking for a different way to associate questions to the programs they are actively being used in. 

#### Describe the solution you'd like.

I am looking for a simple visual que in the question bank to easily see all the programs a question is currently being used in. 

#### What priority is this?

Low priority

#### Associated civic entity

Seattle 

#### User Group
CiviForm Admin

**Comment by elisekalstad** [comment]
Work-around: remove all questions from testing programs/obsolete programs.
