### ISSUE TITLE
Make the download link on the review page with a file upload question look like a link

### ISSUE THREAD

**Issue by dkatzz** [civiform/civiform#7304]
#### Description
The file download link on the review page, doesn't look like its clickable, but it is. We should give this the link styling.

You will see this on the review page if you've created a file upload question and uploaded a file.

#### Additional Context
<img width="825" alt="Screenshot 2024-04-23 at 5 41 26 PM" src="https://github.com/civiform/civiform/assets/86739416/c41b5e87-9409-4201-bf15-74e758ee92b1">

**Comment by swatkat1** [comment]
@isabelcshaw - Can this issue be closed?
