### ISSUE TITLE
Reenable file upload browser tests that were previously failing

### ISSUE THREAD

**Issue by dkatzz** [civiform/civiform#7314]
#### Description

https://github.com/civiform/civiform/pull/6738 disabled failing file upload tests because of an issue with localstack (https://github.com/localstack/localstack/issues/10351). Now that this is fixed, we should re-enable the tests from that PR.

See https://github.com/civiform/civiform/issues/6737 for more context

**Comment by ssandbekkhaug** [comment]
It looks like this was fixed in #6744. Can this issue be closed?

**Comment by dkatzz** [comment]
> It looks like this was fixed in #6744. Can this issue be closed?

Sorry about the confusion! You're right. We can go ahead and close this.
