### ISSUE TITLE
PDF Download of a form should include information about "required" or "optional" questions

### ISSUE THREAD

**Issue by Miguel-314** [civiform/civiform#7365]
#### Is your feature request related to a problem? Please describe.

 Forms can now be downloaded as PDFs for review before they are published. This gives program staff an easier tool to review a form before it is approved 3for public use. PDF downloads currently do no include information about "required" questions v "optional" questions. 

Here is an example of a required question in a test form. 

![Image](https://github.com/civiform/civiform/assets/126286905/3a0d6cb8-4be3-4725-835f-fe9580cab27e)

Here is how that question is displayed in the PDF download. 

![Image](https://github.com/civiform/civiform/assets/126286905/7bc3ff59-f8a9-4ab1-846d-ca1d970968ac)

#### Describe the solution you'd like.

Program admins need some way to review a questions status as either "required" or "optional" to confirm the accuracy of a draft form. This can be as simple as an * or red * typically used in the CiviForm admin view. Any potential alternative solution that clear differentiate question types would be acceptable. 

#### What priority is this?

P2

#### Associated civic entity

Seattle

#### User Group

 'Program Feedback'.

#### Done when:

When Civiform and program admins can see the difference between "required" questions and "optional" questions in the PDF form download.

**Comment by msprenke** [comment]
This seems pretty straight forward and the data is already available in the question.

Moving to ready for development and we can mention it in the next weekly meeting.

Either add an astrisk or add [REQUIRED QUESTION] after the question text in pdf.

**Comment by swatkat1** [comment]
It should be in the program's preview pds button- 

![Image](https://github.com/user-attachments/assets/3ce231a1-a691-4b93-8488-80280e661dcb)
