### ISSUE TITLE
Implement shared footer

### ISSUE THREAD

**Issue by devin-civi** [civiform/civiform#7377]
#### Describe the solution presented in this issue.

Implement shared header and footer, as described in the [PRD](https://docs.google.com/document/d/1VHdYTojiqRiBl4R0LbGsNuSZzOlvgjcWwNnZlLZJJHM/edit?tab=t.0).

(PRD not yet complete, issue tracking that: https://github.com/civiform/civiform/issues/7249)

Note once we have this, there is at least one test (applicant_application_test) which can be augmented to take advantage of being able to log in / log out.

#### Additional Context
Add any other context, link related issues, etc. 

#### Done when:
What criteria need to be met for the issue to be finished? 
- [ ] Clicking button A takes the user to Page B
- [ ] Criteria 2 
- [ ] Criteria 3

**Comment by greg-hyde** [comment]
Update:

The header has been implemented. We need to add the banner for "this is a government website" and the footer
