### ISSUE TITLE
"Settings not found on request when looking up value for SUPPORT_EMAIL_ADDRESS" logs error when internal server error

### ISSUE THREAD

**Issue by rockycodes** [civiform/civiform#7405]
We reference the settings value for `SUPPORT_EMAIL_ADDRESS` when we show the internal server error page here:
https://github.com/civiform/civiform/blob/02c224d105fd69424bc02a9d6bf0b21727be9062/server/app/views/errors/InternalServerError.java#L58

But the `CIVIFORM_SETTINGS_ATTRIBUTE_KEY` isn't set on the request at that point which is causing these warnings to show up in our logs:
https://github.com/civiform/civiform/blob/02c224d105fd69424bc02a9d6bf0b21727be9062/server/app/services/settings/AbstractSettingsManifest.java#L165

We should either find a way to set the `CIVIFORM_SETTINGS_ATTRIBUTE_KEY` or find another way to reference the value for `SUPPORT_EMAIL_ADDRESS` so that the warnings aren't triggered.

Note: the fallback behavior works fine so this isn't broken, just annoying.

**Comment by gwendolyngoetz** [comment]
May be related? #8373

**Comment by rockycodes** [comment]
Fixed in https://github.com/civiform/civiform/pull/8426
