### ISSUE TITLE
Help text is repeated for each value input box in predicate editor

### ISSUE THREAD

**Issue by jeffpw-goog** [civiform/civiform#7440]
**Describe the bug**
The operator help text on the eligibility and visibility condition editor is repeated for each value when there is more than one.

**To Reproduce**

1. Create a program with a date and a name question on the same screen
2. Click "Edit eligibility condition" for that screen
3. Select at least the date and name questions and click "Add condition"
4. Select "first name" and "is one of" for the name question, and "date" and "age is between" for the date question.
5. Click "Add values"

**Expected behavior**
The help text for the operator only needs to be shown once, and takes up unnecessary screen space when repeated.

**Screenshots**
<img width="559" alt="image" src="https://github.com/civiform/civiform/assets/165937506/c23f29c3-0d47-4499-8912-cb697cb5a89a">

**Comment by jeffpw-goog** [comment]
We can instead just show the help text once, below the operator and above the value inputs: 
<img width="545" alt="image" src="https://github.com/civiform/civiform/assets/165937506/c676b50d-69a2-442f-b241-5f033715aa6c">

**Comment by sijiayam** [comment]
@jeffpw-goog The solution you suggested is okay for a quick fix. Would love to look at the UX of this section when we have more time for design.

I also suggest reducing the space between the two rows of empty input fields if we are removing the helper text.

**Comment by jeffpw-goog** [comment]
Thanks @sijiayam! I agree there is plenty of room for better UX here when we have time.

**Comment by jeffpw-goog** [comment]
I found a couple of bugs with this change:
1. The spacing is wrong when there are 3 or more questions selected
2. The "enter a list of comma-separated values" help text appears for multi-select questions where the user chooses from a list of checkboxes, and it should not.

<img width="1003" alt="image" src="https://github.com/civiform/civiform/assets/165937506/e59a7357-6fca-42b7-9712-6c8af7974c4e">
