### ISSUE TITLE
[North Star Applicant UI] Get screen titles and descriptions translated by CEs

### ISSUE THREAD

**Issue by greg-hyde** [civiform/civiform#7488]
Right now, the screen titles and descriptions are not shown to applicants, so they are not translated and only showed in the admin flow. The north star prototype surfaces these in the review page, so we need to get them translated by CEs so we can show them to applicants.
![4diwZyTcTaeZVLL](https://github.com/civiform/civiform/assets/156004543/ff58b9bb-bdd5-47eb-ba85-1ec759b34aec)

**Comment by dkatzz** [comment]
Just making a note that this was replaced with https://github.com/civiform/civiform/issues/7606
