### ISSUE TITLE
[North Star Applicant UI] Update question previews in the admin page

### ISSUE THREAD

**Issue by greg-hyde** [civiform/civiform#7490]
In the admin page, we show a preview of how questions will look to applicants. We need to switch those over to render the thymeleaf implementation so it matches what the applicant will actually see

**Comment by ssandbekkhaug** [comment]
<img width="1326" alt="question_preview" src="https://github.com/civiform/civiform/assets/23390490/c432ce96-7ab8-4220-9fe5-e5ee7878465d">

**Comment by ssandbekkhaug** [comment]
Example from Greg to inspire my approach: https://github.com/civiform/civiform/pull/6531

**Comment by ssandbekkhaug** [comment]
To enable: http://localhost:9000/dev/feature/NORTH_STAR_APPLICANT_UI/enable
To disable: http://localhost:9000/dev/feature/NORTH_STAR_APPLICANT_UI/disable
