### ISSUE TITLE
"Manage translations for programs & questions" documentation is out of date

### ISSUE THREAD

**Issue by ssandbekkhaug** [civiform/civiform#7520]
**Describe the bug**
The screenshot guiding the reader to manage translations is out of date. This leads to confusion about how to access the translations page.

**To Reproduce**

1. Open https://docs.civiform.us/user-manual/civiform-admin-guide/manage-translations-for-programs-and-questions#add-or-edit-program-translations
2. In another tab, follow the documentation
3. Try to follow the second step 1

**Expected behavior**
User can find and click "Manage Translations"

**Actual behavior**
User must:
1. Click 3 dots button
2. Click "Manage translations"

**Screenshots**
<img width="777" alt="Screenshot 2024-05-21 at 9 41 45 AM" src="https://github.com/civiform/civiform/assets/23390490/9a2afd05-f36a-47e6-a22b-94daf0ae1c7b">

**Desktop (please complete the following information):**

- OS: Mac OS
- Browser: Chrome
- Version: 124.0.6367.209

**Smartphone (please complete the following information):**
n/a

**Additional context**
Also, the numbering of steps should be 1, 2, 3, 4, 5, 6 instead of 1, 2, 1, 2, 3, 4

I'd be happy to update the documentation myself.

**Comment by dkatzz** [comment]
Thank you for filing this! 

In addition to the steps mentioned in the actual behavior, the program needs to be in "draft" mode to see "Manage translations" in the 3 dots menu.

**Comment by ssandbekkhaug** [comment]
Fixed by https://github.com/civiform/docs/pull/462
