### ISSUE TITLE
[Program Migration] Handle admin name collisions in program/question import

### ISSUE THREAD

**Issue by rockycodes** [civiform/civiform#7528]
When a program or question is imported that shared an admin name with an existing program or question, programmatically rename the incoming program/question to avoid the collision.

Question admin names are auto-generated (I think) so this might be handled for questions when we add them to the db. 

Part of #7087 

Notes: 
- move helper methods to service class instead of controller
- make strings in tests into Java text blocks like in `JsonExporterServiceTest`

**Comment by melanie-exygy** [comment]
Couldn't we end up with a lot of duplicate programs?  What about replacing the existing program if the name already exists?

**Comment by rockycodes** [comment]
@melanie-exygy this is what was settled on in the PRD (see comments [here](https://docs.google.com/document/d/1mu4Nr-gsEj62NAXWoBjooVwkVUOP79I8ijAK4-jpsE0/edit?resourcekey=0-jwFNNYAH-SPW59-GolzzIg&disco=AAABKiFI0fo)). It makes sense to me, since this is a manual process, I think it's less likely that an admin would be importing an identical program and more likely they would be importing a different program that happens to have the same admin name.

**Comment by gwendolyngoetz** [comment]
I left a more detailed comment on the PRD. But I do see it being common that a program would be imported with the same name. Example 
- Make project on Test environment
- Export -> Import to prod v1
- Make changes to program on Test
- Export -> import to prod making a v2

**Comment by swatkat1** [comment]
@rockycodes  - Just letting you know we need to move the statuses data for that program from the ApplicationStatuses table too.

**Comment by rockycodes** [comment]
@swatkat1 thank you for the reminder! I talked with Isabel/product a couple of weeks ago and the recommendation was to not migrate statuses for v1 of this work, but add that in for v2. Do you see any issues with ignoring statuses from a technical perspective?

**Comment by swatkat1** [comment]
Yes, if an active status is not found for a give program, the code will throw an exception. If not importing the current status data, we should provide a way to create an empty status in the code. 

`  // Create a new row in  ApplicationStatuses table for the new program
      applicationStatusesRepository.createOrUpdateStatusDefinitions(
          adminName, new StatusDefinitions());
`
