### ISSUE TITLE
Alphabetize the list of TIs

### ISSUE THREAD

**Issue by elisekalstad** [civiform/civiform#7570]
#### Is your feature request related to a problem? Please describe.

We're getting a growing list of TIs and it can be the teenie tiniest bit challenging to find the right org since it is currently sorted chronologically by the date the organization was added.

#### Describe the solution you'd like.

Alphabetical sorting of the TI organization list, A - Z, based on the Name of the organization.

#### What priority is this?

Low, very low, but would be nice :)

#### Associated civic entity

Seattle

#### User Group

CiviForm Admin feedback

#### Additional Context

![image](https://github.com/civiform/civiform/assets/86082659/65a871e8-5ac9-4562-9584-3c49a8c9833d)
#### Done when:

What conditions need to be met before this issue can be closed?

**Comment by melanie-exygy** [comment]
@jcma-google Did you mean to close this issue as completed?  Seems like PR #7598 is only a partial step towards completing this work.

**Comment by jcma-google** [comment]
Nope! Did not mean to close.

**Comment by gwendolyngoetz** [comment]
The new sorting dropdown works, but the table is not sorted on initial page load.

**Comment by jcma-google** [comment]
Is it necessary to sort on initial page load? The original request only specifies we add functionality for sorting by A-Z. I don't think it's too much effort to sort by A-Z after the page loads, especially since people are used to the TIs being sorted by "last created date". And since we are not able to sort by "last created" or "last modified" (database does not have those modifiers), it's a neat side effect to have that be the default option on page load.

**Comment by gwendolyngoetz** [comment]
Yes. Sorting it alphabetically on page load is the primary requirement.

**Comment by avaleske** [comment]
Moving this out of Done since it looks like the underlying bug hasn't been addressed.

**Comment by elisekalstad** [comment]
@jcma-google Thanks for working on this one! Apologies that my original request wasn't clear. I'm just looking for the default sort to be alphabetical, rather than the current state that defaults to the last created date. Please let me know if I can flesh this one out further or hop on a quick call.

**Comment by jcma-google** [comment]
Cool, thanks for the clarification Elise!

**Comment by swatkat1** [comment]
@jcma-google  - Are you working on this one? If not, I can assign this work item to @jianfuchen8 ?
