### ISSUE TITLE
Set a Content-Security-Policy

### ISSUE THREAD

**Issue by gwendolyngoetz** [civiform/civiform#7574]
For increased security we should see if we can enable a [Content-Security-Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) without breaking the application.

**Comment by gwendolyngoetz** [comment]
@jeffpw-goog [here are Play's docs](https://www.playframework.com/documentation/2.9.x/CspFilter) on this if you haven't seem them yet.

**Comment by jeffpw-goog** [comment]
I [added a section](https://github.com/civiform/civiform/wiki/Frontend-Development/_compare/361836bf0f3b8550106d688f7dcc38467881769d...3bc33aade8937d0bc6835c03dd33165f8d0202b8) on CSP to the [frontend development wiki](https://github.com/civiform/civiform/wiki/Frontend-Development#content-security-policy).

**Comment by jeffpw-goog** [comment]
Per [discussion in Slack](https://civiform.slack.com/archives/C01R8SJA2HE/p1724072405469559), we will proceed with rolling out CSP despite #8143, and pursue the fix for that in parallel.

**Comment by jeffpw-goog** [comment]
CSP is now enabled by default: https://github.com/civiform/civiform/pull/8218
Also cleaned up the staging override: https://github.com/civiform/civiform-staging-deploy/pull/163

This will go out in the release on September 24.

After that the only remaining work is to submit https://github.com/civiform/civiform/pull/8661 to clean up the config variable, which we can do after a few more weeks.
