### ISSUE TITLE
Document how tasks should be assigned

### ISSUE THREAD

**Issue by ssandbekkhaug** [civiform/civiform#7588]
# Problem
Developers don't know what task to work on next. People in CiviForm are unsure how to assign and prioritize work.

# Exit criteria
The process for assigning development tasks (e.g. GitHub issues) is documented.

**Comment by ssandbekkhaug** [comment]
From Danielle: 
You could:
1. go to https://github.com/orgs/civiform/projects/1/views/68
1. look for unassigned issues in the "Ready for deveolpment" column
1. ping eng chat asking if it's OK to pick up

**Comment by melanie-exygy** [comment]
@ssandbekkhaug, I think another good step would be to ask @isabelcshaw, @shreyachatterjee00 or Nick @nb1701 for some good next-priority issues.  Isabel, Shreya or Nick, do you agree?

Don, I'm also wondering if it might be helpful to add these suggestions to the Getting Started wiki page.
