### ISSUE TITLE
[North Star Applicant UI] Application submitted page for common intake

### ISSUE THREAD

**Issue by greg-hyde** [civiform/civiform#7611]
Similar to https://github.com/civiform/civiform/issues/7487 , but the page is shown differently when the application is a common intake form

It is also controlled by the upsell controller, but handled by a different view

https://github.com/civiform/civiform/blob/6fe74efd9ee3fd1bc4f36721cc95a22d6702b8f4/server/app/views/applicant/ApplicantCommonIntakeUpsellCreateAccountView.java#L39

**Comment by ssandbekkhaug** [comment]
To enable?
http://localhost:9000/dev/feature/INTAKE_FORM_ENABLED/enable
http://localhost:9000/dev/feature/NORTH_STAR_APPLICANT_UI/enable
