### ISSUE TITLE
Create a separate section in the Admin Settings UI for flags that are for "under development" features

### ISSUE THREAD

**Issue by rockycodes** [civiform/civiform#7650]
We would like a way to differentiate between feature flags that are for production use and those that are guarding features that are under development. This will allow CEs to understand what are the flags they can enable in production and will also guard against CEs accidentally enabling features that aren't yet production ready.

This change will likely involve adding a new field to the variables in [`env-var-docs.json`](https://github.com/civiform/civiform/blob/main/server/conf/env-var-docs.json) to indicate that a flag is production ready. That field can then be used in the Admin Settings Panel to separate production flags from under development flags.

**Comment by rockycodes** [comment]
@gwendolyngoetz this is done right?

**Comment by gwendolyngoetz** [comment]
Yeah. I took the simpler approach and just moved the under development features into a new section called "Experimental" which shows up at the bottom of the screen.

**Comment by rockycodes** [comment]
Fixed by https://github.com/civiform/civiform/pull/8689
