### ISSUE TITLE
[North Star Applicant UI] Accessibility audit

### ISSUE THREAD

**Issue by greg-hyde** [civiform/civiform#7682]
Go through the app and look for a11y issues.

Right now, it's passing the Axe a11y test, but we should look in more depth to see if there are any issues

**Comment by ssandbekkhaug** [comment]
[Notes from handoff](https://docs.google.com/document/d/15-K3tUjLY_DgE8433Iz0iQ3CTPMurEqAklr4QSvHwvY/edit?resourcekey=0-lpRI_kWJjYlEVA_zjrx5aA&tab=t.0)

**Comment by ssandbekkhaug** [comment]
Filed a bug with Google Core a11y testing: https://b.corp.google.com/issues/352522787

**Comment by ssandbekkhaug** [comment]
[A11y test cases](https://docs.google.com/spreadsheets/d/1Ogf00rNevIpUO8opnYP8HYtXlY4WFFqyPrUoIFoZbF4/edit?resourcekey=0-OhkCiP9fcz_1KqWmQJAYZw&gid=1101998923#gid=1101998923). Feel free to update
