### ISSUE TITLE
[North Star Applicant UI] Add styles to address correction page

### ISSUE THREAD

**Issue by greg-hyde** [civiform/civiform#7684]
Ensure that we have proper styling on address correction page

Related story https://github.com/civiform/civiform/issues/7989 

### Versions

- Address verification - 1 address
- Multiple address verification

### Requirements by section

[Fill out with a PM]

### Address verification - 1 address
- [Desktop mockup](https://www.figma.com/design/RmhVJCLgAKWGENJLWWAtNS/CiviForm%3A-Components%2C-Styles?node-id=3913-9043&t=xU4eRWoQtP78C3tV-1)
- [Mobile mockup](https://www.figma.com/design/RmhVJCLgAKWGENJLWWAtNS/CiviForm%3A-Components%2C-Styles?node-id=3913-9483&t=xU4eRWoQtP78C3tV-1)

### Multiple address verification
- [Desktop mockup](https://www.figma.com/design/RmhVJCLgAKWGENJLWWAtNS/CiviForm%3A-Components%2C-Styles?node-id=4088-7753&t=xU4eRWoQtP78C3tV-1)
- [Mobile mockup](https://www.figma.com/design/RmhVJCLgAKWGENJLWWAtNS/CiviForm%3A-Components%2C-Styles?node-id=4721-20775&t=xU4eRWoQtP78C3tV-1)

### Spacing guidelines

- Refer to Figma devmode annotations to see the spacing guidelines
- CiviForm spacing documentation
- For more information about our spacing guidelines, see our writeup on spacing

### Layout guidelines
- [Layout guidelines](https://www.figma.com/design/RmhVJCLgAKWGENJLWWAtNS/CiviForm%3A-Components%2C-Styles?node-id=4287-23350&t=XCIBJDfrfoPaX0e8-1)

### Color guidelines

- [[USWDS theme color tokens](https://designsystem.digital.gov/design-tokens/color/theme-tokens/)](https://designsystem.digital.gov/design-tokens/color/theme-tokens/)
    - All colors used in the application should use one of the USWDS theme tokens
    - Dark text should use always use the theme token `ink`
    - View designs for more details

### Text styles

- All text should use the class `usa-prose` unless specified otherwise
- https://designsystem.digital.gov/components/prose/

### USWDS components used

- [USWDS radio button](https://designsystem.digital.gov/components/radio-buttons/)
    - Guidance on the how to use the component
    - We are using the default variant
- [USWDS button group](https://designsystem.digital.gov/components/button-group/)
    - We are using the default and `outline` variant

**Comment by ssandbekkhaug** [comment]
Mocks ready! https://www.figma.com/design/RmhVJCLgAKWGENJLWWAtNS/CiviForm%3A-Components%2C-Styles?node-id=3705-15213&m=dev

**Comment by ssandbekkhaug** [comment]
This issue is blocked on mocks for the case of "1 or more suggested addresses"

**Comment by sijiayam** [comment]
@ssandbekkhaug Could I get a screenshot of the 1 or more suggested addresses page and its current styling?

**Comment by ssandbekkhaug** [comment]
Sure, here's a screenshot in the legacy UI

<img width="1270" alt="Multiple_address" src="https://github.com/user-attachments/assets/02f587f8-6eda-47cf-ba54-db23f4994d16">

(Tip for my future self: make sure address correction is enabled for a specific question within a specific program 🤦‍♂️)

**Comment by sijiayam** [comment]
@ssandbekkhaug I was able to create a quick desktop and mobile mockup to unblock this story. I've updated the story above to reflect and linked it below too.

https://www.figma.com/design/RmhVJCLgAKWGENJLWWAtNS/CiviForm%3A-Components%2C-Styles?node-id=4088-7753&t=xU4eRWoQtP78C3tV-1

**Comment by ssandbekkhaug** [comment]
Ready for UX review before marking closed

**Comment by sijiayam** [comment]
@ssandbekkhaug could you guide me on how to test the multiple address verification?

**Comment by dkatzz** [comment]
> @ssandbekkhaug could you guide me on how to test the multiple address verification?

@sijiayam multiple file upload can be tested by turning on the MULTIPLE_FILE_UPLOAD_ENABLED flag. Once that is enabled, any file upload question will allow multiple files to be uploaded. In the admin view, a limit to how many files are allowed can be set.

**Comment by sijiayam** [comment]
@dkatzz makes sense for multiple file upload! 

I'm trying to figure out how to test the address verification where we ask a user to select from multiple addresses. Do you know the best way to set that up to test?

**Comment by dkatzz** [comment]
> @dkatzz makes sense for multiple file upload!
> 
> I'm trying to figure out how to test the address verification where we ask a user to select from multiple addresses. Do you know the best way to set that up to test?

Haha oops totally read the issue wrong :) Seems like the Seattle lookup isn't working on staging - I'll report back once I figure out the best way to test it there.

**Comment by dkatzz** [comment]
@sijiayam I was able to get this working now

If you enter `600 e 5th, Seattle, WA 98104` now on [staging](https://staging-aws.civiform.dev/) in the minimal sample program it should give you 2 addresses 

<img width="836" alt="Screenshot 2024-10-29 at 12 30 53 PM" src="https://github.com/user-attachments/assets/b6c41a89-567f-43de-8056-71847a1f0860">
<img width="1039" alt="Screenshot 2024-10-29 at 12 30 47 PM" src="https://github.com/user-attachments/assets/5d3d3369-dacb-4022-a7b0-f7eca78879f3">

**Comment by sijiayam** [comment]
Issue has been approved with visual design QA

This visual style bug has been created and added to post launch: https://github.com/civiform/civiform/issues/9411
