### ISSUE TITLE
Application ID and information of how to use it

### ISSUE THREAD

**Issue by Peggy-Liao** [civiform/civiform#7721]
Align the terms used on the application confirmation page and the application PDF. Instead of just including the application ID in parenthesis in the downable PDF, make it clear that the number is application ID. It would also be great to add information about if they can use their application ID to track status. Please see attached two images. 
![Application confirmation page](https://github.com/civiform/civiform/assets/164956206/89452dc5-5c3d-464f-8f21-0d20ba262d19)

![Image](https://github.com/civiform/civiform/assets/86082659/11aa7052-8457-45a3-b58e-400681f2a112)

#### What priority is this?

Low

#### Associated civic entity

Seattle

#### User Group

Resident feedback

#### Additional Context

This feedback is from a user testing session with a city staff who has not used CiviForm. 

#### Done when:

Applicant ID terms align on the confirmation page and PDF download.

**Comment by swatkat1** [comment]
This feels like a small work item the intern can pick up. Adding myself as the "assignee".

**Comment by elisekalstad** [comment]
@Peggy-Liao 's first submission!! Wahhhoooo!

**Comment by msprenke** [comment]
This appears to be fixed by turning on Universal Name question

**Comment by swatkat1** [comment]
Closing this issue per Matt's comment.

**Comment by swatkat1** [comment]
Closing this issue per Matt's comment.
