### ISSUE TITLE
Mocks for "Common Intake Submitted" page

### ISSUE THREAD

**Issue by ssandbekkhaug** [civiform/civiform#7736]
## Requirements
- Create North Star mocks for "Common Intake Submitted" page.
- Updated [mocks](https://www.figma.com/design/RmhVJCLgAKWGENJLWWAtNS/CiviForm%3A-Components%2C-Styles?node-id=2459-23887&t=9HOcLyzVQGIeGrQH-1)

# Old UX
In this screenshot, there are 2 programs that the user is eligible for:
* Comprehensive Sample Program
* Pet Assistance

<img width="1360" alt="Common_intake" src="https://github.com/civiform/civiform/assets/23390490/aa8f0ad5-ceef-4c63-9889-3fee6918f68c">

**Comment by sijiayam** [comment]
@isabelcshaw We need product approval on the new mocks to unblock development.

**Comment by ssandbekkhaug** [comment]
Mocks are ready for development: https://www.figma.com/design/RmhVJCLgAKWGENJLWWAtNS/CiviForm%3A-Components%2C-Styles?node-id=2459-23887&m=dev

For launch, implement version B (simple text).

After launch, implement version A (program cards, tracked in #8571)

This issue will be complete when:

- [ ] The simple text version is merged
- [ ] UX has approved the implementation

**Comment by ssandbekkhaug** [comment]
Closing this issue since mocks are done. Implementation is tracked in https://github.com/civiform/civiform/issues/7994 (copied my previous comment to there)
