### ISSUE TITLE
Let Civiform admin download list of strings that need translating, then reupload translated

### ISSUE THREAD

**Issue by neel-a-mehta** [civiform/civiform#776]
@gcapiel says: "one idea we had discussed was having an ability to download a file with all the strings that need to be translated that could be passed to a translator and then re-uploaded.  Some P1 ideas would be have be able to see all the languages for a program that were complete (all program specific and associated question translations).  If someone added a question without the required languages, then that program would no longer have a complete set of translations."

Concept mockups: https://miro.com/app/board/o9J_lXULxwE=/?moveToWidget=3074457354647675571&cot=14

Add'l details:

> The translation file should be program specific, since you probably want a program to be complete.  Obviously translations done or one program will benefit the others.
> Upon further thought, the "required set" set of translations should be based on the ones that have been completed or partially done for the program metadata. 
> So the "required set" is the union of all the languages available across program metadata fields.  For translations to be complete all program and question metadata fields need to meet that "required set" for the program

**Comment by neel-a-mehta** [comment]
@carolinedanzi fyi

**Comment by neel-a-mehta** [comment]
UPDATE: we're going to deprioritize this in favor of #778, the version of this that lets admins translate from directly within the UI. Having to manage CSV formatting (and alerting the user if they made a mistake) is very hairy.

**Comment by nb1701** [comment]
Closing since this is done in the UI, but feel free to reopen and tag me if this is still desired.
