### ISSUE TITLE
[North Star] Clicking "End Session" redirects to an error page

### ISSUE THREAD

**Issue by ssandbekkhaug** [civiform/civiform#7792]
**Describe the bug**
[North Star] Clicking "End Session" redirects to an error page

**To Reproduce**

1. Enable North Star (http://localhost:9000/dev/feature/NORTH_STAR_APPLICANT_UI/enable)
2. Click "End Session"

**Expected behavior**
Browser navigates to the homepage

**Actual behavior**
Browser navigates to error page

**Screenshots**
<img width="1435" alt="Screenshot 2024-06-14 at 1 01 38 PM" src="https://github.com/civiform/civiform/assets/23390490/78758f44-4e1d-4237-bdea-428940321dd3">

**Desktop (please complete the following information):**

- OS: Mac OS X
- Browser: Chrome
- Version: 126

**Additional context**
n/a

**Comment by greg-hyde** [comment]
looks like we're not specifying the logoutLink variable in NorthStarApplicantBaseView. Adding that should fix it
