### ISSUE TITLE
Eligibility condition on address question is not functioning

### ISSUE THREAD

**Issue by Miguel-314** [civiform/civiform#7853]
**Describe the bug**
A draft form contains an eligibility condition on an address question. The applicant should not be able to continue with the form if their address is not in the Seattle service area. However, this is not working properly. The applicant is still able to continue on to the full form after entering an address outside the City of Seattle. 

**To Reproduce**
The form is the V1 version of HomeWise Weatherization. There is a V2 version. The program admin note shows V1 or V2. 

![Image](https://github.com/civiform/civiform/assets/126286905/b80ea143-2c16-4351-9af5-c953a23748e9)

^ This image shows the eligibility programing for this question. 

Step one: When you get to the question, "how do you heat your home" select option "gas" or "oil". 

Step 2: This will take you to the following screen. The static text at the top of the screen indicates you have selected Gas or Oil as your home heating source. 

![Image](https://github.com/civiform/civiform/assets/126286905/7abc7123-bc9e-4828-8ec0-be91c337ed1a)

Step 3: Enter address that is in the SCL service area but outside the City of Seattle. In the example picture I have entered an address for a business in North Burien. 

![Image](https://github.com/civiform/civiform/assets/126286905/e8441f8d-c6cc-4270-8d84-f96343530358)

Step 4: The expected behavior is for CiviForm to let me know I am not eligible for this program. Instead, I am allowed to go to the next question. You can see in this next photo that we are now on screen 9 of 14. The previous photos shows screen 8 of 14. 

![Image](https://github.com/civiform/civiform/assets/126286905/24091ce4-32cc-4e91-8ab4-f96863863a6c)

**Expected behavior**
CiviForm should show an eligibility screen after the applicant enters an address outside the City of Seattle service area.

**Comment by gwendolyngoetz** [comment]
We have gated eligibility off on this program. Was done on purpose. We'll talk more Monday.

**Comment by gwendolyngoetz** [comment]
@Miguel-314 does our convo yesterday render this moot as a bug?

**Comment by Miguel-314** [comment]
I think this could be combined with #6800 or closed, whichever makes most sense.

**Comment by gwendolyngoetz** [comment]
We had gated eligibility off, and we enabled it. @Miguel-314 if this is still a program re-open the issue.
