### ISSUE TITLE
Visibility condition on address question no functioning

### ISSUE THREAD

**Issue by Miguel-314** [civiform/civiform#7854]
**Describe the bug**
A draft form has a visibility condition set on a previous address question. The visibility condition should hid a static text question later in the form if both conditions are met. This is not functioning properly. 

There are two drafts of the Homewise Weatherization program. The problem described in this issue is in V2 as shown in the program admin note. 

Here is an image of the visibility condition. 

![Image](https://github.com/civiform/civiform/assets/126286905/e60a3e68-9168-4a93-894a-f437627b5734)

**To Reproduce**
 Step 1: Applicant must answer a series of four questions before arriving at the address question. In this example I use the address for Seattle City Hall. 

![Image](https://github.com/civiform/civiform/assets/126286905/0a10e74c-44cf-4da4-9c76-079ebb2d72ab)

Step 2: After three more question the applicant is asked to enter their heating type. In this example, I select "gas". 

![Image](https://github.com/civiform/civiform/assets/126286905/a97ea846-6891-4eb0-9a25-caf1e9b75ef6)

The expected behavior at this point is to let the applicant continue with the application. The static text message after this series of answers should be hidden. 

However, the static text is shown incorrectly telling the applicant they are not eligible for the program. 

![Image](https://github.com/civiform/civiform/assets/126286905/8e2728e3-3097-4991-a087-a04e5d918538)

**Expected behavior**
Static text should be hidden with the current visibility condition.

**Comment by gwendolyngoetz** [comment]
We had gated eligibility off, and we enabled it. @Miguel-314 if this is still a program re-open the issue.
