### ISSUE TITLE
Can't remove entities in North Star enumerator question previews

### ISSUE THREAD

**Issue by ssandbekkhaug** [civiform/civiform#7859]
To reproduce:

1. Enable North Star
2. Preview an enumerator question
3. Click "Add Sample repeated entity type"

Expected behavior: Entity appears

Actual behavior: Nothing happens

<img width="691" alt="Screenshot 2024-06-24 at 9 56 27 AM" src="https://github.com/civiform/civiform/assets/23390490/8b2274c0-8459-4bef-a0af-52ac915a0f02">

**Comment by ssandbekkhaug** [comment]
https://github.com/civiform/civiform/pull/7890 partially fixes the issue but introduces a different bug. In the preview, removing an entity results in a console error and doesn't remove the text input box.

<img width="2126" alt="Screenshot 2024-06-27 at 9 21 53 AM" src="https://github.com/civiform/civiform/assets/23390490/7dfad783-de84-404f-a136-9997b6190816">

**Comment by dkatzz** [comment]
Validated that this works in staging after https://github.com/civiform/civiform/issues/8482
