### ISSUE TITLE
[North Star Applicant UI] Remove modal container after launch

### ISSUE THREAD

**Issue by greg-hyde** [civiform/civiform#7880]
Right now, the modals code is a little complicated because we have to have a modal container on all pages (from modal.ts).

North star doesn't use this, but we structured the modals code that way to avoid it failing.

Made a draft PR for when can do this refactoring https://github.com/civiform/civiform/pull/7879 but we have to wait until after north star launch

**Comment by ssandbekkhaug** [comment]
[More context](https://github.com/civiform/civiform/pull/7876#discussion_r1653524702)
