### ISSUE TITLE
Address Question Required Field Indicator

### ISSUE THREAD

**Issue by elisekalstad** [civiform/civiform#7993]
#### Is your feature request related to a problem? Please describe.

The Address Question type does not currently indicate which parts of the address are required. And the text "Note: Fields marked with a * are required" is small and gray, compared to the rest of the test on the page. This was flagged during user testing last week with a resident.

#### Describe the solution you'd like.

Add the required asterisks to each part of the address question type. 

Increase the size of the text: "Note: Fields marked with a * are required" to match the size of question text.

#### What priority is this?

Medium--resident feedback but not a blocker.

#### Associated civic entity

Seattle via resident user testing

#### User Group

Resident feedback

#### Additional Context

![image](https://github.com/civiform/civiform/assets/86082659/432000db-e98a-4408-bea2-0596a830f1e6)

#### Done when:

Each required address component has an asterisk and the text of "Note: fields marked with ....." is consistent with other question text.

**Comment by elisekalstad** [comment]
@sijiayam and @isabelcshaw For awareness--but seems like a small one that Jian, the new intern, could tackle.

**Comment by gwendolyngoetz** [comment]
@swatkat1 Jian do this in two separate PRs. It'll be good practice to get used to the flow.
