### ISSUE TITLE
[North Star Applicant UI] Add styling for common intake application confirmation page

### ISSUE THREAD

**Issue by ssandbekkhaug** [civiform/civiform#7994]
Need mocks from #7736

**Comment by ssandbekkhaug** [comment]
Mocks are ready for development: https://www.figma.com/design/RmhVJCLgAKWGENJLWWAtNS/CiviForm%3A-Components%2C-Styles?node-id=2459-23887&m=dev

For launch, implement version B (simple text).

After launch, implement version A (program cards, tracked in #8571)

This issue will be complete when:

- [ ] The simple text version is merged
- [ ] UX has approved the implementation

**Comment by sijiayam** [comment]
Design QA is approved
