### ISSUE TITLE
Add styles for "Ineligible" page

### ISSUE THREAD

**Issue by ssandbekkhaug** [civiform/civiform#7996]
Blocked on mocks in #7737

**Comment by ssandbekkhaug** [comment]
Blocked. See comment: https://github.com/civiform/civiform/issues/7737#issuecomment-2246240099

**Comment by ssandbekkhaug** [comment]
Sijia said we can continue with the MVP version for parity. Putting this issue back to "in progress". I'll continue it next week.

**Comment by sijiayam** [comment]
Design QA complete. 1 minor issue opened: https://github.com/civiform/civiform/issues/9036
