### ISSUE TITLE
Add styling to "form step" page

### ISSUE THREAD

**Issue by ssandbekkhaug** [civiform/civiform#8001]
https://www.figma.com/design/RmhVJCLgAKWGENJLWWAtNS/CiviForm%3A-Components%2C-Styles?node-id=2377-8313&t=tVZ2CZ74XFp8WOfP-0

**Comment by ssandbekkhaug** [comment]
How should we handle extra wide screens? @sijiayam 

e.g. Aligns the questions with the header in the center, or push the header to the left?

<img width="2490" alt="Screenshot 2024-07-11 at 12 48 44 PM" src="https://github.com/civiform/civiform/assets/23390490/6e204367-70fb-4d6d-b5f8-e07924206f21">

**Comment by ssandbekkhaug** [comment]
Sijia says: Left align header

**Comment by ssandbekkhaug** [comment]
Working on styling this page.

Open question: Should question text fill the entire center column?

<img width="2630" alt="Screenshot 2024-07-11 at 3 56 44 PM" src="https://github.com/user-attachments/assets/30cf4019-6da4-4af3-a7c2-01ed8dcc82be">

**Comment by ssandbekkhaug** [comment]
Mistakenly closed this issue. There's a bit more styling to do for mobile.

**Comment by ssandbekkhaug** [comment]
Branching another issue for the shaded circle: https://github.com/civiform/civiform/issues/8622

**Comment by sijiayam** [comment]
Design QA approved for form page styles
