### ISSUE TITLE
Clicking "Back" fails

### ISSUE THREAD

**Issue by ssandbekkhaug** [civiform/civiform#8065]
# To reproduce

1. Use CiviForm as applicant
1. Start an application with multiple questions
1. Answer exactly 1 question (at least 1 other required question must be blank)
1. Click "Back"

# Expected behavior
User returns to application review (summary) page

# Actual behavior
* User is stuck on the current page
* Page highlights required fields

<img width="599" alt="Screenshot 2024-07-16 at 11 43 59 AM" src="https://github.com/user-attachments/assets/d2517b24-9464-474f-9d0f-773e1a74c059">

**Comment by ssandbekkhaug** [comment]
I'm trying to figure out what behavior we want. I followed [the paper trail](https://github.com/civiform/civiform/pull/6992), [part 2](https://github.com/civiform/civiform/issues/6450), [part 3](https://github.com/civiform/civiform/issues/2470#issuecomment-1139068215), but I'm not sure how up-to-date everything is.

From what I understand, we want:
* Back -> Save valid fields, drop others, then navigate
* Continue -> Require user to correct invalid fields
* Save and finish later -> Save valid fields, drop others, then navigate

How do we handle edge cases?
* Field is empty -> ignore
* Field is valid -> save
* Field is invalid -> drop

Is this correct?

If so, is there a recommended way to drop invalid inputs and only save the valid ones? I'm looking at [this line  in ApplicantService.java](https://github.com/civiform/civiform/blob/b8091fc6026c937641f95f9c93d59a071cd0b7e8/server/app/services/applicant/ApplicantService.java#L410)

**Comment by ssandbekkhaug** [comment]
Guidance from Jeff and Danielle is to replicate the existing behavior instead of implementing some sort of "partial save", which might be confusing to users.

The existing behavior shows a modal.

<img width="1366" alt="Screenshot 2024-09-03 at 9 22 52 AM" src="https://github.com/user-attachments/assets/a792bc70-9820-48eb-ac90-5077a84cb41b">

**Comment by melanie-exygy** [comment]
> Guidance from Jeff and Danielle is to replicate the existing behavior instead of implementing some sort of "partial save", which might be confusing to users.
> 
> The existing behavior shows a modal.
> 
> <img alt="Screenshot 2024-09-03 at 9 22 52 AM" width="1366" src="https://private-user-images.githubusercontent.com/23390490/364022441-a792bc70-9820-48eb-ac90-5077a84cb41b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0MDEyNTIsIm5iZiI6MTcyNTQwMDk1MiwicGF0aCI6Ii8yMzM5MDQ5MC8zNjQwMjI0NDEtYTc5MmJjNzAtOTgyMC00OGViLWFjOTAtNTA3N2E4NGNiNDFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDIyMDIzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyZjdlZmRlMWViZDExNmU2ZTczODZlYzI2YWFmZjQxYjVhMGNmYjM1MmMwZWUyNjU4YWVmZDBmZTE1MWI1YzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.A8LtXC8YoM6MJ7AAB8H0OMhotji7qTLT-cYFKRz5uhM">

@ssandbekkhaug, not sure if you're aware of this, but the existing behavior only shows the modal when the user clicks "Review" or "Previous".  There is no modal when the user clicks "Save and next".

**Comment by ssandbekkhaug** [comment]
After talking with Sijia today, we realized this is 2 separate issues:

- "Previous" button -> tracked here
- "Save and finish later" -> https://github.com/civiform/civiform/issues/8523
