### ISSUE TITLE
Style North Star footer

### ISSUE THREAD

**Issue by ssandbekkhaug** [civiform/civiform#8070]
[UX Mocks](https://www.figma.com/design/RmhVJCLgAKWGENJLWWAtNS/CiviForm%3A-Components%2C-Styles?node-id=2377-8313&t=3IpvdPixSN0rFff3-0)

Notes:

- "Return to top" link
  - Align with main content in center column (class="grid-col-8") 
- Gray “admin login” + “about civiform” - [footer component documentation](https://designsystem.digital.gov/components/footer/)
  - Put links in container
  - Let the background color expand across the screen

**Comment by sijiayam** [comment]
QA issue captured in #9051
