### ISSUE TITLE
Implement Program Fast Forwarding in UX North Star

### ISSUE THREAD

**Issue by ssandbekkhaug** [civiform/civiform#8076]
We'll need to audit the program fast forwarding experience and check if there's any UI that needs to be implemented in Thymeleaf.

# Complete When

- [x] When an applicant fast-forwards an application, all the UI is implemented with UX North Star styles

**Comment by gwendolyngoetz** [comment]
Good plan on testing it. 

If it redirects to the same URLs endpoints it should be fine. The only UI differences are were the change from toasts to alerts which I added already.
