### ISSUE TITLE
Create a "My Applications" card section on the homepage

### ISSUE THREAD

**Issue by melanie-exygy** [civiform/civiform#8137]
#### Describe the solution presented in this issue.
There will be a section at the top titled “My Applications” for any programs that the user has applied to, whether they are in progress or submitted.  Cards in this section will differ from those in the other sections because they won’t include the program image or the category tags.  The current “In progress” or “Submitted” sections will be combined into one.  Note that the `Status: ` badge will have different styles as shown in the mocks.

This will be behind the PROGRAM_FILTERING_ENABLED feature flag.

Documentation and communication will be done as part of this issue:  #8138. 

#### Link to Figma mocks: 
[mocks](https://www.figma.com/file/BOES7eVIpEFIbBBShCN8AB/Program-card-discoverability?type=design&node-id=239-11037&mode=design&t=fzLPhaaMXNqOQ6yg-0)

#### Add screenshot of relevant mocks for this issue here: 
![image](https://github.com/user-attachments/assets/b467deea-a6f4-476c-b46f-e0b238128bd5)

#### Done when:
What criteria need to be met for the issue to be finished? 
- There is a "My Applications" section on the homepage.

**Comment by dkatzz** [comment]
Is this part of north star? It feels like a pretty decent change to not put behind a feature flag?

**Comment by melanie-exygy** [comment]
> Is this part of north star? It feels like a pretty decent change to not put behind a feature flag? We should also be sure to update documentation / screenshots to show this change and make sure we message it to the civic entities.

There are two separate items for this, one before the north star and one in the north star.  As part of the [Program Filtering TDD](https://docs.google.com/document/d/1hNL6r1JdauL5xjGRIw1dlDD3m81h9g0vUSiqlXOGDCs/edit?usp=sharing), we discussed whether or not to put this behind a feature flag.  @shreyachatterjee00 suggested that it might not need to be put behind a feature flag if it could be done in one PR.  @sijiayam agreed that, if it was done in a single PR, that would prevent a bad user experience.  I'm open to putting it behind a feature flag.  We can re-open that discussion.

Good idea to update documentation and message to the CEs.
