### ISSUE TITLE
Programs can be applied for despite disabled status

### ISSUE THREAD

**Issue by jhvhs-bloom** [civiform/civiform#8140]
If an applicant applies for a program and leaves the in progress application open in their browser, they can still submit their application despite the program being disabled.

This bug affected our Production instance (v2.4.2). A program we disabled on July 15, 2024 had three applications come through days after July 15, 2024. Two of the applicants are registered users and one is a guest user.

We replicated the issue in our Test instance (v2.4.2):

1. Person 1 begins applying for a program and leaves the tab open in their browser  
1. Person 2 (as admin) publishes the program with the Disabled visibility state  
1. Person 1 submits application

* OS: Ubuntu (24.04)  
* Browser: Firefox  
* Version: 128.0.2

Please let me know if you need me to clarify anything.

**Comment by sethCOB** [comment]
This PR may be discussing a similar thing, not sure:  #5043

**Comment by dkatzz** [comment]
Once an application is started, it will continue to be on the program version that it was on when the application was started. However, there's a feature flag that was just released in [2.4.3](https://github.com/civiform/civiform/releases/tag/v2.4.3) (FASTFORWARD_ENABLED) that will fast forward an in progress application to the latest program version. Let me know if that fixes the issue you're seeing.

**Comment by jhvhs-bloom** [comment]
I upgraded our test instance to 2.4.3 and enabled the FASTFORWARD_ENABLED flag. The applicant gets an error message when they try to navigate different screens. 

Overall this is good--but is it possible to change the error message?

Instead of directing folks to contact technical support, the message could let the applicant know that this program is disabled or no longer available.

![civiform-disabled-program-error](https://github.com/user-attachments/assets/8f04a7f2-ac9e-4b43-8cfd-b87bd18a5833)

**Comment by dkatzz** [comment]
This should be fixed in the latest version of CiviForm https://github.com/civiform/civiform/releases/tag/v2.8.0
