### ISSUE TITLE
TDD CSV/JSON Export Needs Significant Perf and Error Improvement

### ISSUE THREAD

**Issue by gwendolyngoetz** [civiform/civiform#8147]
Update: This TDD compiles potential performance improvements. Not all ideas in the TDD have corresponding issues:
https://docs.google.com/document/d/1gmD0hTmys7sWKUSxxKVhYpZGgiY8FWsmCClk9Jzg4ng/edit?tab=t.0

The exports (CSV / JSON) take a long time to run when programs have large amounts of data. This results in those program exports failing, typically with an HTTP 504 cause by the Fargate Load Balancer reaching it's 60 second timeout.

As a temporary stop gap, I've increased Seattle's from 60 seconds to 120 seconds. This is not ideal, nor a long term solution.

This problem has been kicked down the road for a few years now. One of [Bion's suggested approaches](https://civiform.slack.com/archives/C01QKN2UNMA/p1649906147236149) to go with an async approch. Allow admins to submit a request for an export and they'd get emailed a link to download the file upon generation.

Perhaps that approach. Perhaps we need to rewrite the code generating the export. No matter the approach we have got to do something to deal with the growing outage of the export feature.

### Non-exhaustive search of past timeout issues
- #1730
- #6573 
- #2267 

### Non-exhaustive search of past breakages of the export
- #8145 
- #6605 
- #6642 
- #8081
- #1747

### Issues to come out of this TDD and research:
- #8800
- #8805 
- #8843
- #8851
- #8852

**Comment by avaleske** [comment]
2000 is... not a lot. The other issue mentioned v2.4.2 specifically, but this is an issue with any program that has a lot of applications to export, right?

**Comment by gwendolyngoetz** [comment]
Maybe applications + many columns.

**Comment by avaleske** [comment]
Does this still happen if you use the paginated export?

There's a lot of work we're doing and then throwing away, just cause it was easier to leverage existing access methods and data structures instead of making more specific ones.

For example, in addDataToBuilder(), called by `getSummaryDataAllQuestions()`, https://github.com/civiform/civiform/blob/85c1885d6756daffae8f7dd8c8d67dfd70170276/server/app/services/applicant/ReadOnlyApplicantProgramServiceImpl.java#L332 we're creating a whole `AnswerData`, when we don't use all of it.

I have theories about what's slow, but it'd be worth doing some profiling to see where we should focus our optimization effort and if it's the same for JSON vs CSV

**Comment by gwendolyngoetz** [comment]
I think zipping them or changing them to a .txt extension will let you attach them. Unless it's a file size issue.

**Comment by avaleske** [comment]
I was able to repro this with 2000 applications to Comprehensive Sample Program:
- With a few versions, it takes ~34s to download "All applications" as JSON from the admin program applications page.
- Each new version results in it taking another ~15 seconds
- Commenting out the portion that visits every version for each application brings it down to 11s:
https://github.com/civiform/civiform/blob/469c5c397ada272ac749ed0fd361f33000add9e1/server/app/services/export/JsonExporterService.java#L135-L144

So it's likely something in `ReadOnlyApplicantProgramService.getSummaryDataAllQuestion()`, but I haven't timed it separately from the logic that builds the final JSON to export, yet.

**Comment by avaleske** [comment]
From where I was before, commenting out everything in `JsonExporterService` (see [this gist](https://gist.github.com/avaleske/d5dcfdd5c19c7a4f08857d497e3a9ad5)) cuts the time in half again to ~5-6 seconds.

Roughly, then, it takes:
- 3 seconds per 1000 applications _per version_ to prepare for export and retrieve all answers from the applicant data
- 3 seconds per 1000 applications to export

I wonder if it's a combination of the GC thrashing cause we have a lot of stuff in memory and jayway/jsonpath being slow? I noticed a lot of time in your profiler output is spent there, which makes sense but could also be a source of slowness:
![image](https://github.com/user-attachments/assets/6f49ea4b-0759-4b49-89f4-f8d9d4737a5f)


Also need to look into the synchronization stuff in that screenshot. This code isn't parallelized so I'm not sure what it's doing there.

**Comment by avaleske** [comment]
There is still performance work to do but I've created new issues to track it. Now that the TDD is done I'm closing this.
