### ISSUE TITLE
Set standard layouts for mobile/tablet/desktop/wide-desktop

### ISSUE THREAD

**Issue by ssandbekkhaug** [civiform/civiform#8155]
[Mocks](https://www.figma.com/design/RmhVJCLgAKWGENJLWWAtNS/CiviForm%3A-Components%2C-Styles?node-id=1836-7143&t=ommBYU7De1oyflsj-1)

**Comment by ssandbekkhaug** [comment]
We can move this to "Needs review" for UX after #8197 is merged.

**Comment by sijiayam** [comment]
Testing is blocked by #9035

**Comment by sijiayam** [comment]
QA approved, styles will be tested in the specific page design QA
