### ISSUE TITLE
If an applicant enters a very long string in a text field, they get a 400

### ISSUE THREAD

**Issue by natsid** [civiform/civiform#816]
We should guard against this by putting some reasonable max length on strings (10,000 characters?) and returning a helpful validation message if they enter something longer.

**Comment by natsid** [comment]
This bug blocks story acceptance of #377.

**Comment by neel-a-mehta** [comment]
Just did a quick test -- when I put in a string of 65,536 characters it was fine, but when I doubled that (to 131,072) I got this error:

![image](https://user-images.githubusercontent.com/77128518/115084221-8f578680-9ed6-11eb-905f-3461991a7259.png)

**Comment by neel-a-mehta** [comment]
So we can set a pretty high upper bound on length -- anything up to 65,536 characters is good.

**Comment by shanemc-goog** [comment]
Adding a validation.ts method for this seems straight forward enough.
