### ISSUE TITLE
Add styling for "Common intake ineligible" page

### ISSUE THREAD

**Issue by ssandbekkhaug** [civiform/civiform#8178]
Blocked on #8177

Desktop mocks: https://www.figma.com/design/RmhVJCLgAKWGENJLWWAtNS/CiviForm%3A-Components%2C-Styles?node-id=3838-9000&m=dev
Mobile mocks: https://www.figma.com/design/RmhVJCLgAKWGENJLWWAtNS/CiviForm%3A-Components%2C-Styles?node-id=3838-9089&m=dev

**Comment by ssandbekkhaug** [comment]
@sijiayam Can you add a link to the mocks?

**Comment by sijiayam** [comment]
Design QA complete
