### ISSUE TITLE
Create program preview/overview page in Thymeleaf

### ISSUE THREAD

**Issue by ssandbekkhaug** [civiform/civiform#8243]
# Notes
Functionality can be created without mocks. However, it would be better to have the mocks (issue #8242)

# Old UX

<img width="1101" alt="Program Page" src="https://github.com/user-attachments/assets/69e4f194-3d74-4e57-bcdf-f9e0ccd41e5d">

**Comment by sijiayam** [comment]
@shreyachatterjee00 This may be the same as the program preview page.

**Comment by rockycodes** [comment]
Closing as duplicate
