### ISSUE TITLE
Styling for "Program Preview/Overview" page

### ISSUE THREAD

**Issue by ssandbekkhaug** [civiform/civiform#8244]
Blocked on mocks in issue #8242

**Comment by sijiayam** [comment]
@shreyachatterjee00 Noting that this is the program preview styling issue.

**Comment by shreyachatterjee00** [comment]
@rockycodes @sijiayam do we need this issue anymore? can we close it?

**Comment by rockycodes** [comment]
We can close this! There are a couple other duplicate issues for this I think we can close. I'll find them.
