### ISSUE TITLE
[Program Filtering] Update styles of the program cards on the homepage

### ISSUE THREAD

**Issue by melanie-exygy** [civiform/civiform#8247]
#### Describe the solution presented in this issue.
UX has requested that we update the styles of the program cards on the homepage in this way:

- Remove the dark blue card outline on top
- The application status, such as “In progress”,  “Submitted 5/17/24”, “You may qualify”  will have an icon and a colored background
- Style the new category labels
- Possibly change the "Program details" link into a button labelled "View details" (this is optional if it's too much work)

#### Link to Figma mocks: 
[mocks](https://www.figma.com/file/BOES7eVIpEFIbBBShCN8AB/Program-card-discoverability?type=design&node-id=239-11037&mode=design&t=fzLPhaaMXNqOQ6yg-0)

#### Add screenshot of relevant mocks for this issue here: 
![image](https://github.com/user-attachments/assets/e55acd2b-cf79-474e-aa31-343c7343b4c0)

#### Done when:

- [ ] The style of the program cards matches the mocks.

**Comment by melanie-exygy** [comment]
> Whoever picks this up, if you can include [dealing with this](https://github.com/civiform/civiform/issues/6404) while you are at it you will have my undying thanks. Well maybe a fixed period of thanks, it is a small bug.

@gwendolyngoetz, seems like it would be more worth our time to fix it if the bug still exists in the North Star.  This particular issue is for the J2Html homepage, which won't have long to live.

**Comment by gwendolyngoetz** [comment]
Works for me
