### ISSUE TITLE
Share application via text and/or email

### ISSUE THREAD

**Issue by ssandbekkhaug** [civiform/civiform#8274]
#### Is your feature request related to a problem? Please describe.

After submitting an application, a user may want to share the confirmation via text message and/or email.

#### Describe the solution you'd like.

A button on the application confirmation page ([mocks](https://www.figma.com/design/RmhVJCLgAKWGENJLWWAtNS/CiviForm%3A-Components%2C-Styles?node-id=2459-23884&m=dev)).

#### What priority is this?

Low priority

#### Associated civic entity
n/a

#### User Group

n/a

#### Additional Context

Suggested by @sijiayam 

#### Done when:

What conditions need to be met before this issue can be closed?

- [ ] A button (or multiple buttons) are visible on the application confirmation page
- [ ] Clicking said buttons sends the application PDF via text message or email
- [ ] For text messages, the message is sent to the appropriate phone number (or, the user is prompted to input their phone number)
- [ ] For emails, the email is sent to the appropriate email address (or, the user is prompted to input their email address)

**Comment by melanie-exygy** [comment]
@ssandbekkhaug Is this a duplicate of #8262?  See @gwendolyngoetz's security concerns in that issue.

**Comment by ssandbekkhaug** [comment]
Yes, it's a duplicate. Thanks for noticing!
