### ISSUE TITLE
Update "Download PDF" button string on "Application confirmation" page

### ISSUE THREAD

**Issue by ssandbekkhaug** [civiform/civiform#8299]
# Background
While styling the "application confirmation" page in North Star, Danielle noticed the "Download PDF" button is missing. We need to:
1. Determine whether the page should have a "Download PDF" button
2. If so, get mocks that include a "Download PDF" button
3. Change the code

* Context: [comment](https://github.com/civiform/civiform/pull/8266#discussion_r1710287600)
* [Comment in Figma](https://www.figma.com/design/RmhVJCLgAKWGENJLWWAtNS?node-id=2367-6614&m=dev#905697740)

# Done when

- [ ] "Download PDF" button is visible on the application confirmation page
- [ ] Clicking the button lets the user download a PDF of their application

**Comment by dkatzz** [comment]
One thing to note is that this is controlled by the APPLICATION_EXPORTABLE setting, so similar to the current behavior, it would only appear if the admin of the instance turned that feature on.

**Comment by ssandbekkhaug** [comment]
Guidance from Sijia:
* Clicking the button downloads a PDF (same behavior as before)
* Sijia will change the text

@sijiayam What should the new button text be? ("Download PDF"?)

**Comment by sijiayam** [comment]
Copy suggestions from emily:

If this is just confirmation info:
- Download this page
- Download a copy of this page
If it is whole application:
- Download my application

**Comment by velociberry** [comment]
If it's the full application, I'd lean towards including all keyword, as those will be especially helpful for people using screenreaders, such as: 

If it's the entire application info (not just that screen with the name / confirmation #): 
- Download your application

If it's just the confirmation page (not full application): 
- Download confirmation page

**Comment by sijiayam** [comment]
We confirmed that the button downloads the full application so we can use "Download your application" as the text.
