### ISSUE TITLE
Add "Relevant Programs" section to "Application confirmation" page

### ISSUE THREAD

**Issue by ssandbekkhaug** [civiform/civiform#8306]

**Comment by ssandbekkhaug** [comment]
The section has been added. Styling the cards is tracked in #8156 (mocks) and #8157 (implementation)

![Image](https://github.com/user-attachments/assets/c3e3d0f3-a6dd-4e23-91cd-ea3595bab986)

**Comment by sijiayam** [comment]
Closing since the functionality is complete. Styling will be QA'd in #8157
