### ISSUE TITLE
Set up ESRI integration with Charlotte

### ISSUE THREAD

**Issue by dkatzz** [civiform/civiform#8310]
#### Describe the solution you'd like.

Charlotte's tree canopy program requires service area validation, so we'll need to add the ESRI configuration values to their application

#### What priority is this?

Needs to be done before the end of August

#### Associated civic entity

Charlotte

#### Additional Context

This is the map that should be used - https://charlotte.maps.arcgis.com/apps/instant/lookup/index.html?appid=4934daabeb7647eb99205a41068f737d, 
https://charlotte.maps.arcgis.com/home/item.html?id=10726c7b5aac4f39b8c14d33c680ef58 (the query filter used is on the source layer in the description)

We can plan to do this on a test instance first and then let charlotte know the configuration values they should set

#### Done when:

Service area validation works for charlotte

**Comment by megan0422** [comment]
Hi @dkatzz it sounds like the program admin want to receive all applications (even ones located outside of service areas) because there is now a possibility for a waiting list to be set up for alternative funding. So you can probably close this issue! For now, we will just link the eligibility map but allow all users to submit.

**Comment by dkatzz** [comment]
Sounds good! I'll close this issue and we can re-open it if we want to integrate ESRI in the future. Thank you!

**Comment by dkatzz** [comment]
Keeping this open to track adding address correction, but we won't be doing any service area validation for launch.

**Comment by dkatzz** [comment]
Adding `export ESRI_FIND_ADDRESS_CANDIDATES_URL="https://services.gis.nc.gov/secure/rest/services/AddressNC/AddressNC_geocoder/GeocodeServer/findAddressCandidates"` to the deployment got this working
