### ISSUE TITLE
Logging in with Auth0 will fill email in for the universal name question

### ISSUE THREAD

**Issue by dkatzz** [civiform/civiform#8344]
**Describe the bug**
When creating an account through auth0, the universal name question gets filled in with email. This is when the user creates an account with a username and password specifically because when signing in with google, a name is provided. 

**To Reproduce**

1. Go to staging or another environment with auth0
2. Click on log in and log in or create an account
3. When redirected back to civiform, click on the PAI proram (or another program with a universal name question)
4. See email in name field

**Expected behavior**
Name doesn't get filled in since there is no name coming from auth provider. Or if the email matches the name when it comes from auth provider, don't set it

**Screenshots**
See name filled in with email
![Screenshot 2024-08-15 at 3 19 37 PM](https://github.com/user-attachments/assets/d7227799-99e0-4338-b6e4-da7c02e0e88b)

**Additional context**
This was reported by charlotte as something that came up in their user studies. We'd like to fix it before launch.

**Comment by dkatzz** [comment]
Some related context / code:

https://github.com/civiform/civiform/blob/9a8f21925234632573ec03ffcc386f5bad7dcbcd/server/app/services/applicant/ApplicantData.java#L96

Set username from the OIDC profile here: https://github.com/civiform/civiform/blob/main/server/app/auth/oidc/applicant/ApplicantProfileCreator.java#L112

It gets set as first name here: https://github.com/civiform/civiform/blob/main/server/app/services/applicant/ApplicantData.java#L228-L232

**Comment by gwendolyngoetz** [comment]
It's probably specific to certain OIDC types. Seattle's works fine.
