### ISSUE TITLE
Investigate how to properly use USWDS icons

### ISSUE THREAD

**Issue by ssandbekkhaug** [civiform/civiform#8349]
# Overview

Allow CiviForm developers to easily use USWDS icons.

Today, we have some SVGs. USWDS recommends using their spritesheet, which involves adding a new dependency. We would like to avoid adding a new dependency if possible.

# Instructions from USWDS

## Prerequisite
I think we need to add a gulpfile first: https://designsystem.digital.gov/documentation/getting-started/developers/phase-two-compile/

## Adding icons

"Active icons are found in dist/img/usa-icons. The icons in this directory will be packaged into an SVG sprite. The complete set of available icons are located in two directories: dist/img/material-icons and dist/img/uswds-icons. Copy icons into a usa-icons directory within your project images directory, and rebuild the SVG sprite using [uswds-compile](https://github.com/uswds/uswds-compile/)."

Source: https://designsystem.digital.gov/components/icon/

Usage looks like this:
```
<svg class="usa-icon" aria-hidden="true" focusable="false" role="img">
        <use xlink:href="/assets/img/sprite.svg#backpack"></use>
</svg>
```

# Done when

- [ ] Decided how to best use USWDS icons
- [ ] Developers can use USWDS icons in CiviForm Thymeleaf templates

**Comment by gwendolyngoetz** [comment]
Do we need to actually compile anything if we're using the precompiled svg from the dist folder? I'd rather try to leverage the existing use of webpack and not pull in a new heavy dependency unless we have no other option.

**Comment by ssandbekkhaug** [comment]
I'm not sure. I haven't figured out a way to get SVGs from USWDS. They recommend using their spritesheet.

I think this issue is partly a "research" task to find the best way to use USWDS icons.

**Comment by melanie-exygy** [comment]
I just want to point out that we're already using a USWDS SVG for the government banner:  [lock icon](https://github.com/civiform/civiform/blob/a0a95e4ff507081253ddc085e6c9c630df1872cb/server/app/views/BaseHtmlLayout.java#L199).  What I did when working on that was add the SVG to `Icons.java`:  [here](https://github.com/civiform/civiform/blob/a0a95e4ff507081253ddc085e6c9c630df1872cb/server/app/views/components/Icons.java#L264).  It wasn't very hard to copy over, so that is one possible way of doing it.

**Comment by gwendolyngoetz** [comment]
I think we'll need to see if using the `Icons.java` class is a pain to work with in thymeleaf. I wouldn't mind seeing it go away. It's not without issues.

**Comment by ssandbekkhaug** [comment]
Ok, after a bit of trial and error, I selected a relatively simple solution. It's basically following what we already have:

1. Download a SVG and put it in `assets/Images/uswds/`
2. Add a line like this to NorthStarBaseView.java
  ```context.setVariable("fooIcon", assetsFinder.path("Images/uswds/icon-foo.svg"));```
3. Use the icon in Thymeleaf like so:
  ```
  <img th:src="${fooIcon}" ...  />
  ```

Prototype in #8444

**Comment by gwendolyngoetz** [comment]
I don't like putting the icons in as variables and there ends up being a lot of boilerplate to have to write whenever an icon img tag is used. This will end up becoming difficult to maintain.

I have a spike over at #8452 that creates a custom tag for ThymeLeaf.

You end up just having to use a single tag and we can encapsulate a lot of the repetitiveness along with throwing errors if the icon is missing. 

Example usage
`<civi:icon type="icon-https" />`

or
`<civi:icon type="icon-https" class="mb-6 h-8 w-8 custom-red-color" />`
