### ISSUE TITLE
SUPPORT_EMAIL_ADDRESS falls back to exygy email when only set in settings page

### ISSUE THREAD

**Issue by dkatzz** [civiform/civiform#8373]
**Describe the bug**
This field falls back to the backup, which is an exygy email https://github.com/civiform/civiform/blob/1a21f67dc4975e873423de4bb3e7f2381c61ed13/server/conf/application.conf#L108. 

This came up in an error message Arkansas admins were getting when they had login trouble
![exygy email issue](https://github.com/user-attachments/assets/dc3ee83d-ead7-47f5-9001-0431d0e136d2)

We have confirmed they had it in their settings page, but not their deployment config.

We should make this be set in the deployment only (and admin readable) if we can't confirm it will show the right email.

**Comment by dkatzz** [comment]
Note that attempting to set it in the config file throws the error: `'SUPPORT_EMAIL_ADDRESS' is editable via the admin settings panel and should not be set in the deploy config. Please remove it from your config file and try again. Set ALLOW_ADMIN_WRITEABLE=true in your config file to ignore this warning (use with caution).`

**Comment by sijiayam** [comment]
https://designsystem.digital.gov/templates/404-page/

Use the general guidance and styles from this USWDS page (also see what Anna has created for 404)

- Heading: An error has occurred
- Lead text: We're sorry, an internal error has occurred in our system.
- Regular text: Please contact technical support for assistance at civiform-dev@exygy.com and include this error ID [XXXXXX]
- Button: 'Visit homepage' <-- primary default button styling
- Small text: `Error code: 500`

**Comment by rockycodes** [comment]
Additional context -- the fix for this issue requires some updates to our error page. I'll be updating it to use the [USWDS error template](https://designsystem.digital.gov/templates/404-page/) with the language @sijiayam specified above.

**Comment by rockycodes** [comment]
Fixed in https://github.com/civiform/civiform/pull/8426
