### ISSUE TITLE
Help with ESRI setup for Bloomington

### ISSUE THREAD

**Issue by dkatzz** [civiform/civiform#8389]
#### Is your feature request related to a problem? Please describe.

From Jeremy in slack:

I've been setting up ESRI service areas. The Municipal Boundary service area works flawlessly.
However, I am stuck getting the Bloomington Economic Zone (BEZ) service area to correctly validate. Addresses I try to validate are ineligible despite being within the zone.
I might be missing something obvious. Any help would be appreciated!
Here's my configuration
    ESRI_FIND_ADDRESS_CANDIDATES_URLS.0: 'https://bloomington.in.gov/arcgis-server/rest/services/Locators/CityCountyAddressLocator/GeocodeServer/findAddressCandidates'
    ESRI_ADDRESS_SERVICE_AREA_VALIDATION_URLS.0: 'https://bloomington.in.gov/arcgis-server/rest/services/DataPortal/DataPortal_PoliticalBoundaries/MapServer/3/query'
    ESRI_ADDRESS_SERVICE_AREA_VALIDATION_LABELS.0: 'Municipal_Boundary'
    ESRI_ADDRESS_SERVICE_AREA_VALIDATION_ATTRIBUTES.0: 'muni_name'
    ESRI_ADDRESS_SERVICE_AREA_VALIDATION_IDS.0: 'Bloomington'
    ESRI_ADDRESS_SERVICE_AREA_VALIDATION_URLS.1: 'https://bloomington.in.gov/arcgis-server/rest/services/DataPortal/DataPortal_EconomicDevelopment/MapServer/3/query'
    ESRI_ADDRESS_SERVICE_AREA_VALIDATION_LABELS.1: 'BEZ_West'
    ESRI_ADDRESS_SERVICE_AREA_VALIDATION_ATTRIBUTES.1: 'objectid'
    ESRI_ADDRESS_SERVICE_AREA_VALIDATION_IDS.1: '5'

Using objectid or objectids did not produce any errors --but did not correctly validate addresses - always noted as ineligible.

Using zone_section does produce this error with HTTP 400: `Invalid service area ID: Downtown Expansion`

ESRI_ADDRESS_SERVICE_AREA_VALIDATION_URLS.1: 'https://bloomington.in.gov/arcgis-server/rest/services/DataPortal/DataPortal_EconomicDevelopment/MapServer/3/query'
  ESRI_ADDRESS_SERVICE_AREA_VALIDATION_LABELS.1: 'BEZ_West'
  ESRI_ADDRESS_SERVICE_AREA_VALIDATION_ATTRIBUTES.1: 'zone_section'
  ESRI_ADDRESS_SERVICE_AREA_VALIDATION_IDS.1: 'West Expansion'

#### Describe the solution you'd like.

This should correctly validate addresses - us to make sure nothing is wrong with the config

#### What priority is this?

Hoping to get this working soon, so applicants don't have to go to an outdated system to see if eligible

#### Associated civic entity

Bloomington

#### Additional Context

Eligibility:

![image (6)](https://github.com/user-attachments/assets/37e39c5f-67a6-4fdc-baba-278cd4805f01)

![image (7)](https://github.com/user-attachments/assets/f32f6344-2a77-4b63-a874-7fd682ce7a60)

#### Done when:

They can correctly validate addresses

**Comment by dkatzz** [comment]
The next thing I'd like to try is overriding the well known ID (https://docs.civiform.us/it-manual/sre-playbook/initial-deployment/configure-gis-service#overriding-the-default-wellknownid) - when making the query to [https://bloomington.in.gov/arcgis-server/rest/services/DataPortal/DataPortal_EconomicD[…]quantizationParameters=&featureEncoding=esriDefault&f=pjson](https://bloomington.in.gov/arcgis-server/rest/services/DataPortal/DataPortal_EconomicDevelopment/MapServer/3/query?where=&text=&objectIds=5&time=&timeRelation=esriTimeRelationOverlaps&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&distance=&units=esriSRUnit_Foot&relationParam=&outFields=&returnGeometry=true&returnTrueCurves=false&maxAllowableOffset=&geometryPrecision=&outSR=&havingClause=&returnIdsOnly=false&returnCountOnly=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&returnZ=false&returnM=false&gdbVersion=&historicMoment=&returnDistinctValues=false&resultOffset=&resultRecordCount=&returnExtentOnly=false&sqlFormat=none&datumTransformation=&parameterValues=&rangeValues=&quantizationParameters=&featureEncoding=esriDefault&f=pjson), I'm seeing wkid as 2245. This would mean setting export ESRI_WELLKNOWN_ID_OVERRIDE to 2245, but I'm not totally sure if that would impact the other validation

**Comment by gwendolyngoetz** [comment]
This is related to #7137 and #7944 and will be fixed by the work I'm doing to support checking for outside service area. I'm anticipating it being in the release after Labor day.

**Comment by gwendolyngoetz** [comment]
### Example Address that would not be eligible

https://bloomington.in.gov/arcgis-server/rest/services/Locators/CityCountyAddressLocator/GeocodeServer/findAddressCandidates?Address=401+N+Morton+St&City=Bloomington&Region=IN+&Postal=47404&f=pjson

https://bloomington.in.gov/arcgis-server/rest/services/DataPortal/DataPortal_EconomicDevelopment/MapServer/3/query?geometry=%7B%27%27x%27%27%3A3107700.5018695998%2C%27%27y%27%27%3A1428812.12653800473%2C%27%27spatialReference%27%27%3A2966%7D&geometryType=esriGeometryPoint&inSR=2966&outFields=*&returnGeometry=false&f=pjson


### Example Address that would be eligible

https://bloomington.in.gov/arcgis-server/rest/services/Locators/CityCountyAddressLocator/GeocodeServer/findAddressCandidates?Address=727+W+2nd+St&City=Bloomington&Region=IN+&Postal=47404&f=pjson

https://bloomington.in.gov/arcgis-server/rest/services/DataPortal/DataPortal_EconomicDevelopment/MapServer/3/query?geometry=%7B%27%27x%27%27%3A3106413.97826135764%2C%27%27y%27%27%3A1425682.16073121782%2C%27%27spatialReference%27%27%3A2966%7D&geometryType=esriGeometryPoint&inSR=2966&outFields=*&returnGeometry=false&f=pjson

**Comment by dkatzz** [comment]
Thank you, @gwendolyngoetz !!

**Comment by dkatzz** [comment]
Confirmed that Gwen's change fixed this issue!
