### ISSUE TITLE
Make landing page not require a cookie

### ISSUE THREAD

**Issue by nb1701** [civiform/civiform#8414]
Since we changed how logins work, when you land on the CiviForm index page, a guest account is automatically created and you are redirected with a session cookie for that guest account.  This creates two problems:
1) This creates a lot of unused, empty guest accounts, because everyone who just visits the page and doesn't do anything on it gets a new guest account created.
2) Search engine crawlers can not index the page because they can not store cookies while crawling, which results in an infinite redirect that creates new guest accounts over and over.

Instead, the home page should not create a new user, and a user should only be created when hitting the "apply" button on a program (if you aren't already logged in).

I believe we made it work the current way because it was easiest just to pretend a user had clicked "log in as guest" when we removed the landing page.

This is currently a problem for AR as they are unable to get Google to scrape their new CiviForm site and include it in search results.  Seattle is currently in search results, but likely from it being scraped long ago before we implemented the login changes.

**Comment by rockycodes** [comment]
related: https://github.com/civiform/civiform/issues/5542#issuecomment-1709016609
