### ISSUE TITLE
Add ability to turn off program-admin notification emails

### ISSUE THREAD

**Issue by avaleske** [civiform/civiform#8436]
#### Is your feature request related to a problem? Please describe.

Arkansas uses their own system for sending email notifications to program admins, so the ones CiviForm sends are redundant and confusing.

#### Describe the solution you'd like.

The ability to turn off new application emails at the program level.

#### What priority is this?

High, it's currently confusing their program admins

#### Associated civic entity

Arkansas

#### User Group

CiviForm Admin and Program Admin feedback

#### Additional Context

They don't want to turn off emails for the CiviForm Admins or for the entire instance, and per-program-admin settings seemed too specific.

#### Done when:

There's an option to turn off email sending for a program.

#### Eng proposed solution
- Add a setting on the program definition that controls email sending.
- Check that setting when here: https://github.com/civiform/civiform/blob/7ffc57b352d01553d5101f12856130563d69e821/server/app/services/applicant/ApplicantService.java#L600
- Store that setting as a field on the ProgramModel.
- It will default to the current behavior: sending emails to program admins.

Possible mock:
![image](https://github.com/user-attachments/assets/38acea7b-becf-46e9-b871-b57612118870)

**Comment by isabelcshaw** [comment]
I think this looks like a great solution - thank you @avaleske ! The one small behavior ask I would make here is that we default to emails being sent and allow someone to change it if needed.

**Comment by elisekalstad** [comment]
Yes please! This is an issue for City of Seattle too. We currently ask Program Admins to create a rule in their email inboxes so that they don't get inundated with alerts. It's a work-around that is a little confusing to explain. It would be great to have this as a configurable setting within CiviForm!

**Comment by avaleske** [comment]
This is in the release this week!

@sijiayam the final UI ended up being a checkbox, to allow for additional preferences in the future:
<img width="759" alt="image" src="https://github.com/user-attachments/assets/7e0f922d-baf2-4312-bbd0-f8f5d1fb73df">

**Comment by elisekalstad** [comment]
Oh my gosh! I see it!!! I used it!! THANK YOU!!!
