### ISSUE TITLE
`View details` on the main programs page just opens the /programs page again in a separate tab

### ISSUE THREAD

**Issue by ssandbekkhaug** [civiform/civiform#8478]
`View details` on the main programs page just opens the /programs page again in a separate tab

[Slack Message](https://civiform.slack.com/archives/C01QKN2UNMA/p1725468263730979?thread_ts=1725468051.919329&cid=C01QKN2UNMA)

Discovered by Danielle

**Comment by melanie-exygy** [comment]
When I test this, rather than opening the /programs page in a separate tab, it opens "https://github.com/civiform/civiform".
