### ISSUE TITLE
Add Employment and Training as Default Category Options

### ISSUE THREAD

**Issue by lftaylor2023** [civiform/civiform#8485]
#### Is your feature request related to a problem? Please describe.

Arkansas' initial focus in Civiform program development has been on workforce education and training opportunities. Because of this, we have a need to add "**Employment**" and "Training" to the default categories for Programs.

#### What priority is this?

This has a medium priority level for us. However, we'd like these categories to go live when the category feature functionality is made live in production. 

#### Associated civic entity

Arkansas State Government

**Comment by melanie-exygy** [comment]
@lftaylor2023 "Education" is already included in the default categories.  Here are the defaults so far:  Economic, Education, Childcare, Food, Healthcare, General, Housing, Transportation, Utilities, Internet.  Given that, would adding "Training" still be a medium priority?

**Comment by lftaylor2023** [comment]
My mistake. I should have requested "Employment" and not "Education." I've edited the request.

Leslie

**Comment by isabelcshaw** [comment]
@lftaylor2023 would it cover AR's needs if we 1. added "Employment" and then 2. made a change so that the category read "Education and Training"

**Comment by lftaylor2023** [comment]
I think that would be fine.

Thanks,


Leslie F. Taylor | Systems Administrator, ARData

Transformation and Shared Services

o: 501.682.4415 | 501.747.7284 | ***@***.******@***.***>

Website<http://www.transform.ar.gov/> | Facebook<http://www.facebook.com/ArkansasTSS> | Twitter<http://www.twitter.com/ArkansasTSS> | LinkedIn<https://www.linkedin.com/company/department-of-transformation-and-shared-services/> | Instagram<http://www.instagram.com/ArkansasTSS>

________________________________

**Comment by shreyachatterjee00** [comment]
@lftaylor2023 couple of questions as we try to understand the difference between these tags! cc @sijiayam 

1. What types of programs are tagged under Education vs Training (ex. are education programs referring to children's education programs like preschool?) Could you give us a couple examples? 

2. If training is related to employment (like training in a particular job field), could we tag training programs as employment? Could we just add one tag here to encompass both types of programs?

**Comment by lftaylor2023** [comment]
It is primarily adult and youth non-credit education programs, vocational and workforce training. Some of the training results in certification but not all does.

Examples:

  *   Welding
  *   Forklift operator
  *   Auto collision repair
  *   Robotics operation
  *   Machine tool technology
  *   Culinary arts

We can't label it as employment because not all education and training courses result in direct employment. It would be misleading to label it as employment.

Leslie

**Comment by shreyachatterjee00** [comment]
@lftaylor2023 Understood, thanks for the clarification! We'll add employment and training as separate new categories.

**Comment by dkatzz** [comment]
@lftaylor2023 FYI this will be included in tomorrow's release.
