### ISSUE TITLE
"Apply for programs" section seems confusing/incomplete

### ISSUE THREAD

**Issue by ssandbekkhaug** [civiform/civiform#8486]
In the current UI, we give people the option to "Apply to programs", but here showing the programs without anything actionable feels confusing

[Slack Message](https://civiform.slack.com/archives/C01QKN2UNMA/p1725468834776019?thread_ts=1725468051.919329&cid=C01QKN2UNMA)

Reported by Danielle

**Comment by melanie-exygy** [comment]
@dkatzz I think the actionable button is still there, but the wording has changed from "Apply to programs" to "Apply to another program".  @sijiayam @isabelcshaw, please note that this new wording could be confusing.  Should we keep the new wording or use the existing "Apply to programs"?  Also, if we use the new wording, we should also update the wording above to match.  "You may be able to enroll... by clicking 'Apply to another program'".

![image](https://github.com/user-attachments/assets/2782440a-ca23-412d-99c0-bc0155eb8ed3)

**Comment by ssandbekkhaug** [comment]
The [mocks](https://www.figma.com/design/RmhVJCLgAKWGENJLWWAtNS/CiviForm%3A-Components%2C-Styles?node-id=2459-23887&m=dev) show "Apply to programs" but they are not yet finalized.

**Comment by sijiayam** [comment]
@melanie-exygy @ssandbekkhaug Lets stick with "Apply for programs" for now.

**Comment by ssandbekkhaug** [comment]
The string has been changed to "Apply to programs"

<img width="1031" alt="Screenshot 2024-09-25 at 9 32 31 AM" src="https://github.com/user-attachments/assets/66819133-d7c7-4bf2-b6cb-f02a4d51319e">
