### ISSUE TITLE
Birth date is not pre-populated

### ISSUE THREAD

**Issue by ssandbekkhaug** [civiform/civiform#8489]
Filling out the comprehensive sample program:
1. On page 1, input birthday
2. On page 5, select “Spring”
3. On page 6, the user is asked for their birthday again. (Expected the birthday to be pre-populated)

[Slack Message](https://civiform.slack.com/archives/C01QKN2UNMA/p1725468912795459?thread_ts=1725468051.919329&cid=C01QKN2UNMA)

**Comment by melanie-exygy** [comment]
@ssandbekkhaug This is the existing behavior.  If we keep this bug, I propose that it not be related to the North Star.
