### ISSUE TITLE
SHOW_NOT_PRODUCTION_BANNER_ENABLED does nothing in northstar

### ISSUE THREAD

**Issue by ssandbekkhaug** [civiform/civiform#8490]
SHOW_NOT_PRODUCTION_BANNER_ENABLED does nothing in northstar - it should show a banner at the top of the page (see staging image)

[Slack Message](https://civiform.slack.com/archives/C01QKN2UNMA/p1725469012660529?thread_ts=1725468051.919329&cid=C01QKN2UNMA)

Reported by Danielle

**Comment by melanie-exygy** [comment]
@dkatzz This banner doesn't show for me locally even with the North Star flag off.  I think this is the expected behavior.  @gwendolyngoetz can you confirm?

**Comment by gwendolyngoetz** [comment]
It should work locally with NS off.

You have to enable flag `SHOW_NOT_PRODUCTION_BANNER_ENABLED`. Optionally set `CIVIC_ENTITY_PRODUCTION_URL` for the banner to include a link to a prod site.

**Comment by ssandbekkhaug** [comment]
In the legacy UI, the banner looks like a large red bar with white text.

<img width="1081" alt="Screenshot 2024-09-27 at 11 47 23 AM" src="https://github.com/user-attachments/assets/64bd02c5-264e-492b-8ee1-9516cd528166">

**Comment by gwendolyngoetz** [comment]
Yes. It's meant to be scary because people kept putting real applications in test.

**Comment by ssandbekkhaug** [comment]
How does this look, @sijiayam ? Any visual adjustments?

If this is the right direction, I'll send the PR for review.

# Home page
<img width="1408" alt="banner_homepage_link" src="https://github.com/user-attachments/assets/f2046cd3-e098-471f-aa63-1cb84ea53800">

# Generic page
<img width="1408" alt="banner_link" src="https://github.com/user-attachments/assets/d1bec422-820f-44f2-916e-c94d7ff033eb">

# Generic page without link
<img width="1408" alt="banner" src="https://github.com/user-attachments/assets/a2bce477-a9ed-4d2b-9b2d-b646753f88a1">

**Comment by gwendolyngoetz** [comment]
That box should be above everything and position sticky so it follow the user as they scroll. Otherwise people will go there, scroll down, and possibly forget they are not on the correct place.

**Comment by ssandbekkhaug** [comment]
Sijia:
What is the correct position? Top, above the government banner
Should it be sticky and float? Yes
No extra space between the “Not production” banner and gov banner

**Comment by ssandbekkhaug** [comment]
@gwendolyngoetz noticed a bug in PR #8767: This doesn't work correctly if you've set `CIVIC_ENTITY_PRODUCTION_URL` back to an empty string at some point. The settings will return isPresent=true but with an empty string. Causing the second line to show a link with no href

I'll fix this bug in #8790
