### ISSUE TITLE
On the “Application Submitted” page, the “related programs” section shows a program that I already submitted

### ISSUE THREAD

**Issue by ssandbekkhaug** [civiform/civiform#8493]
On the “Application Submitted” page, the “related programs” section shows a program that I already submitted

[Slack Message](https://civiform.slack.com/archives/C01QKN2UNMA/p1725469143948059?thread_ts=1725468051.919329&cid=C01QKN2UNMA)

**Comment by melanie-exygy** [comment]
@ssandbekkhaug I'm not able to reproduce this.  Would you mind putting repro steps here and verifying that this isn't existing pre-North Star behavior?

**Comment by ssandbekkhaug** [comment]
# To Reproduce

1. Have at least 2 programs in the instance
2. Submit application to program A
3. Submit application to program B
4. On the "Application submitted" page, observe the related programs section. Program A may appear.

## Screenshots

Notice two programs are submitted, including "Address correction program".

![Image](https://github.com/user-attachments/assets/70bf5b44-be8b-422d-b8ac-869160f9c69a)

Notice that "Address correction program" appears in the "Other programs" section.

![Image](https://github.com/user-attachments/assets/7a9b7441-3fc5-438c-9f39-307eed2043d5)

# Pre-North Star

The "Application Submitted" page does not have a "Related Programs" section pre-North Star.

![Image](https://github.com/user-attachments/assets/96b9e6f1-44ad-4429-b4b6-35de2372ee67)

**Comment by melanie-exygy** [comment]
> # To Reproduce
> 1. Have at least 2 programs in the instance
> 2. Submit application to program A
> 3. Submit application to program B
> 4. On the "Application submitted" page, observe the related programs section. Program A may appear.
> 

Thanks @ssandbekkhaug!  I'm now able to reproduce and see how it doesn't apply to pre-North Star.
