### ISSUE TITLE
Dialog says create an account or sign in but there's no option to create an account, only continue or log in.

### ISSUE THREAD

**Issue by ssandbekkhaug** [civiform/civiform#8496]
Not sure if it's a bug but when you first apply to a program the dialog says create an account or sign in but there's no option to create an account, only continue or log in. Also it says "sign in" above and "log in" below which probably should be consistent.

[Slack Message](https://civiform.slack.com/archives/C01QKN2UNMA/p1725469226634399?thread_ts=1725468051.919329&cid=C01QKN2UNMA)

Reported by Jeff

![Image](https://github.com/user-attachments/assets/d7d8ab90-353b-4856-b2f6-1b5e8fc83a3d)

**Comment by ssandbekkhaug** [comment]
Open questions:

- Should there be a button to create an account?
- Should we change the wording to be consistent? ("Sign in" vs "log in")

**Comment by dkatzz** [comment]
Just a note that once the user navigates to the authentication provider by clicking "Log in", there will be an option to "Sign up".
![Screenshot 2024-09-05 at 10 27 06 AM](https://github.com/user-attachments/assets/9a3efc6d-14d1-4f9c-85f4-d4550d45b142)

**Comment by sijiayam** [comment]
1. @isabelcshaw Would love your thoughts here on how we want to approach this popup modal for North Star launch. I know we have heard this is a sticky point for applications.
2. Is this modal shown in any other scenario other than before the start of an application?

**Comment by sijiayam** [comment]
1. This modal will be removed so there is no modal in between clicking on apply and the first page of the form application
2. This modal might be repurposed in the future for whenever there is an option to create an account on the program preview page

**Comment by ssandbekkhaug** [comment]
Does that mean the exit criteria for this issue is the following?

- [ ] When the user clicks "Apply" for their first application, a login/signup modal is *not* shown

**Comment by sijiayam** [comment]
@ssandbekkhaug Yes, it is.

**Comment by ssandbekkhaug** [comment]
In that case, it should be pretty easy to remove. I'll do this in the next sprint (or later in this sprint if I have extra time).
