### ISSUE TITLE
“Apply” button has an invalid ARIA attribute

### ISSUE THREAD

**Issue by ssandbekkhaug** [civiform/civiform#8497]
On the “Application Submitted” page, on program cards, the “Apply” button has an invalid ARIA attribute (`Invalid ARIA attribute value: aria-controls="login-dialog-6"`)

[Slack Message](https://civiform.slack.com/archives/C01QKN2UNMA/p1725469604485499?thread_ts=1725468051.919329&cid=C01QKN2UNMA)

**Comment by melanie-exygy** [comment]
I suspect the issue is that the id `login-dialog-6` doesn't exist.

**Comment by ssandbekkhaug** [comment]
I can't reproduce this. I guess it was fixed
