### ISSUE TITLE
Un-signed-in applicant is upsold to create account when they hit Save and Finish Later

### ISSUE THREAD

**Issue by neel-a-mehta** [civiform/civiform#853]
#313 describes how a guest should be prompted to create an account when they hit Submit to send in their application. We should also prompt them to create an account when they hit the "Save and Finish Later" button in the application UI.

**Comment by neel-a-mehta** [comment]
I think this'll work, but I don't think the "Save and Finish Later" button is implemented yet. I'll make an issue for it. So we can't properly test this yet, even though it appears like the login upsell should work.

**Comment by ndmckinley** [comment]
More appropriate to just unassign myself - "save and finish later" is currently *implicit* rather than *explicit* - if someone wants this later on they can add it.

**Comment by nb1701** [comment]
I believe this is being done as part of the login revamp @MichaelZetune is working on, but feel free to reopen if it isn't.
