### ISSUE TITLE
English Text elements don't render formatted in the Question translation edit page

### ISSUE THREAD

**Issue by swatkat1** [civiform/civiform#8561]
**Describe the bug**
English Text elements don't render formatted in the Question translation edit page

**To Reproduce**

1. Create any question and add some markup/line breaks
2. Click on 'edit translation' for the question 
3. The question text doesn't render with formatting 

**Expected behavior**
The English question should be formatted while rendering. 

**Screenshots**
See the below question
![image](https://github.com/user-attachments/assets/7faff096-2360-4335-bdf5-d5241281c22e)

Currently rendering as 
![image](https://github.com/user-attachments/assets/ec7cfb24-beb1-4d65-88a7-10cf17616abf)

**Comment by dkatzz** [comment]
This feels like maybe its working as intended? Even though its weird, then someone knows to add the same markdown to the translated text?

**Comment by swatkat1** [comment]
Since we added to the ability to add markdown to translated text, I think this will be useful to make sure they have parity with english text.
