### ISSUE TITLE
Add modal functionality for create an account button on application confirmation page

### ISSUE THREAD

**Issue by sijiayam** [civiform/civiform#8588]

**Comment by ssandbekkhaug** [comment]
@sijiayam Can you describe the desired behavior of each of these buttons/links? Do these buttons do the same things as "Log in" and "Create account" on the homepage?

<img width="463" alt="Screenshot 2024-09-19 at 9 16 43 AM" src="https://github.com/user-attachments/assets/a34f6a90-11c7-47f3-9910-4dfc54664982">

**Comment by ssandbekkhaug** [comment]
Sijia's answer: these buttons do the same things as "Log in" and "Create account" on the homepage

**Comment by sijiayam** [comment]
Closing this story as it is a duplicate to this issue https://github.com/civiform/civiform/issues/8480
