### ISSUE TITLE
Clicking "Print this Page" -> 403 in staging

### ISSUE THREAD

**Issue by ssandbekkhaug** [civiform/civiform#8640]
**Describe the bug**
Clicking "Print this Page" causes a 403 error in staging WHEN the "download PDF" flag is turned off 

**Expected behavior:** 
* If the "download PDF" flag is turned off, do NOT display the "print" button or the text saying that the applicant can download this application

**To Reproduce**

1. Use CiviForm staging (https://staging-aws.civiform.dev/)
2. Enable North Star
4. Apply to a program
5. Submit the application
6. On the "Application Submitted" page, click "Print this Page"
7. Actual behavior: 403 error

**Expected behavior**
User downloads a PDF

**Screenshots**
<img width="1057" alt="Screenshot 2024-09-18 at 2 43 52 PM" src="https://github.com/user-attachments/assets/cca3e781-1b87-4c72-bffc-caeea044b6bf">

**Desktop (please complete the following information):**

- OS: Mac OS X
- Browser: Chrome
- Version: 129.0.6668.58

**Additional context**
n/a

**Comment by ssandbekkhaug** [comment]
The bug only happens when the "download PDF" button is turned OFF

**Comment by lagosr-google** [comment]
is the info on how to turn off the "download PDF" button on the wiki?

**Comment by dkatzz** [comment]
> is the info on how to turn off the "download PDF" button on the wiki?

This will be through the settings section in the CiviForm Admin role
<img width="832" alt="Screenshot 2024-11-04 at 2 42 45 PM" src="https://github.com/user-attachments/assets/a1da4f19-9df8-427e-89b8-5a7fdefa36e2">
