### ISSUE TITLE
"Application confirmation" page shows "Create an account" alert when user is logged in

### ISSUE THREAD

**Issue by ssandbekkhaug** [civiform/civiform#8654]
**Describe the bug**
"Application confirmation" page shows "Create an account" alert when user is logged in

**To Reproduce**

1. Open northstar_upsell.test.ts
2. Go to the test called ['view application page while logged in'](https://github.com/civiform/civiform/blob/5b828064efb1695b2ac27b2eac56494f08bea4db/browser-test/src/applicant/northstar_upsell.test.ts#L42)
3. Read the code and notice that the test user is logged in
4. View [the screenshot](https://github.com/civiform/civiform/blob/main/browser-test/image_snapshots/northstar_upsell_test/upsell-north-star.png)
5. See "Create an account" alert

**Expected behavior**
The "Create an account" alert should NOT be visible.

**Screenshots**
https://github.com/civiform/civiform/blob/main/browser-test/image_snapshots/northstar_upsell_test/upsell-north-star.png

**Additional context**

- HTML is here: https://github.com/civiform/civiform/blob/main/server/app/views/applicant/ApplicantUpsellTemplate.html
- Make sure to run the test and update the screenshots
    - [How to run browser tests](https://github.com/civiform/civiform/wiki/Common-CLI-Commands#running-browser-tests)
    - Invoke `bin/run-browser-test-env` in one terminal in VS Code
    - In another terminal, invoke `bin/run-browser-tests northstar_upsell.test.ts`

**Done when**

- [ ] When the user is logged in in a test, the "Create an account" alert is NOT visible
- [ ] A browser test asserts that the text "Create an account" is NOT visible

**Comment by ssandbekkhaug** [comment]
@Erikang20 Another good starter issue for you

**Comment by haltmar** [comment]
@Erikang20 - will you be working on this issue?  If not, please feel free to assign to me.   Thanks.
