### ISSUE TITLE
Let program admins specify "state" for applications

### ISSUE THREAD

**Issue by neel-a-mehta** [civiform/civiform#867]
Let them specify whether or not an application is:

- Not looked at
- Ineligible
- Eligible, not reviewed yet
- In review
- Approved
- Rejected
- Need to follow up

This will help the program admin track which ones they still need to review, and which ones they're done with. 

This can feed into the filtering UI so that admins can, for instance, download a CSV containing *just* the applications they haven't looked at yet.

We can also surface this information to the applicant, so they can see the status of their application.

**Comment by neel-a-mehta** [comment]
#1008 is a clone of this. Before I close that one, here's notes from it:

> e.g. "I have reviewed this", "this one is incomplete". Let admins place these labels on people's applications directly within the program admin interface. Perhaps let admins store free-form notes about each applicant too, so they can add more information than just our labels. Would be ideal if applicants could see this status too (though probably not the free-form notes).
> Then be able to sort/filter by people's stages in the application process.
> This lets us build a lightweight CRM. We should make sure we don't go overboard and recreate Salesforce; just use this so simple information can be stored directly in CiviForm.

**Comment by baipai** [comment]
Relative to #975 and some already touched upon.

**Comment by kristinyim** [comment]
Found this old mock (not officially set in stone but just for reference). It also includes a "notes" column to each application that is invisible to the applicant but can be used for internal tracking (e.g. 'Sent to Steve for income verification').

This is also not important in the immediate term to Rochester, but P0 overall
<img width="899" alt="Screen Shot 2022-02-11 at 3 13 57 PM" src="https://user-images.githubusercontent.com/14956724/153683172-1a57a731-ba9d-46c2-99d5-0b02b4736f4a.png">

**Comment by elisekalstad** [comment]
I believe this is already done, right @shanemc-goog ?

**Comment by shanemc-goog** [comment]
Yep as part of Status Tracking!
