### ISSUE TITLE
Align Notes popup with top of page

### ISSUE THREAD

**Issue by elisekalstad** [civiform/civiform#8741]
**Describe the bug**
As a Program Admin, I need to write notes on applications. The Notes popup, however, aligns with the middle of the application so I don't see it right away and need to scroll down to it.

**To Reproduce**

1. Sign in as a Program Admin
2. View applications
3. Add a notes
4. See that the Notes popup is at the middle of the application and requires scrolling

**Expected behavior**
Align the Notes popup with the top of the application

**Screenshots**
![image](https://github.com/user-attachments/assets/5ee75f71-52f2-42d5-8925-53b131d35af9)

**Comment by avaleske** [comment]
@swatkat1 does your work on this page take care of this, or should we plan this work separately?

**Comment by swatkat1** [comment]
It's a small fix. I can take care of it today!
