### ISSUE TITLE
Handle enumerators on North Star "application review" page

### ISSUE THREAD

**Issue by ssandbekkhaug** [civiform/civiform#8795]
# Problem
The North Star "application review" page has a new way of displaying questions and answers. The page needs to handle enumerator questions.

Related issues:
* https://github.com/civiform/civiform/issues/7935
* https://github.com/civiform/civiform/issues/8792
* https://github.com/civiform/civiform/issues/8793

# Done when

- [ ] The North Star "application review" page displays enumerator questions and answers

**Comment by ssandbekkhaug** [comment]
Blocked by https://github.com/civiform/civiform/issues/7935

**Comment by sijiayam** [comment]
@ssandbekkhaug Is this issue still blocked? or can it be marked ready for dev

**Comment by ssandbekkhaug** [comment]
It's almost ready for development. It's not blocked on mocks, but https://github.com/civiform/civiform/pull/8855 needs to be merged first.
