### ISSUE TITLE
Service area validation for Charlotte

### ISSUE THREAD

**Issue by dkatzz** [civiform/civiform#8809]
#### Is your feature request related to a problem? Please describe.

Working with Charlotte on their setup of service area validation.

They specifically want to set it up for whether or not an address gives results from a particular [map](https://gis.charlottenc.gov/arcgis/rest/services/PLN/CouncilDistricts/MapServer), which will show whether or not the applicant is part of Charlotte's incorporated zone.

Here is an example of a request where someone is eligible, since results are returned: https://gis.charlottenc.gov/arcgis/rest/services/PLN/CouncilDistricts/MapServer/0/query?where=&text=&objectIds=&time=&timeRelation=esriTimeRelationOverlaps&geometry=1445904.2545321335%2C+540972.8909761285&geometryType=esriGeometryPoint&inSR=&spatialRel=esriSpatialRelIntersects&distance=&units=esriSRUnit_Foot&relationParam=&outFields=&returnGeometry=true&returnTrueCurves=false&maxAllowableOffset=&geometryPrecision=&outSR=&havingClause=&returnIdsOnly=false&returnCountOnly=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&returnZ=false&returnM=false&gdbVersion=&historicMoment=&returnDistinctValues=false&resultOffset=&resultRecordCount=&returnExtentOnly=false&sqlFormat=none&datumTransformation=&parameterValues=&rangeValues=&quantizationParameters=&featureEncoding=esriDefault&f=html

Here is an example of a request where someone is not eligible, since no results are returned: https://gis.charlottenc.gov/arcgis/rest/services/PLN/CouncilDistricts/MapServer/0/query?where=&text=&objectIds=&time=&timeRelation=esriTimeRelationOverlaps&geometry=1440324.4048117907%2C+570690.4500596193&geometryType=esriGeometryPoint&inSR=&spatialRel=esriSpatialRelIntersects&distance=&units=esriSRUnit_Foot&relationParam=&outFields=&returnGeometry=true&returnTrueCurves=false&maxAllowableOffset=&geometryPrecision=&outSR=&havingClause=&returnIdsOnly=false&returnCountOnly=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&returnZ=false&returnM=false&gdbVersion=&historicMoment=&returnDistinctValues=false&resultOffset=&resultRecordCount=&returnExtentOnly=false&sqlFormat=none&datumTransformation=&parameterValues=&rangeValues=&quantizationParameters=&featureEncoding=esriDefault&f=html

#### Describe the solution you'd like.

Charlotte can do service area validation for whether people are within the Charlotte incorporated zone

#### What priority is this?

It would be ideal for this to be added before launch

#### Associated civic entity

Charlotte

#### Additional Context

This is for one of the programs charlotte is working on.

Some example addresses:
- 1106 Euclid Avenue Charlotte NC 28203
- 1115 south mint street
- 4014 Rocky river road

#### Done when:

This works as expected

**Comment by gwendolyngoetz** [comment]
There's room for us to make this process easier, but this can be accomplished right now. 

Config settings need to be

```hocon
esri_address_correction_enabled=true
esri_find_address_candidates_urls = [
  "https://services.gis.nc.gov/secure/rest/services/AddressNC/AddressNC_geocoder/GeocodeServer/findAddressCandidates"
]

esri_external_call_tries = 3
esri_address_service_area_validation_enabled=true
esri_address_service_area_validation_urls = [
  "https://gis.charlottenc.gov/arcgis/rest/services/PLN/CouncilDistricts/MapServer/0/query",
  "https://gis.charlottenc.gov/arcgis/rest/services/PLN/CouncilDistricts/MapServer/0/query",
  "https://gis.charlottenc.gov/arcgis/rest/services/PLN/CouncilDistricts/MapServer/0/query",
  "https://gis.charlottenc.gov/arcgis/rest/services/PLN/CouncilDistricts/MapServer/0/query",
  "https://gis.charlottenc.gov/arcgis/rest/services/PLN/CouncilDistricts/MapServer/0/query",
  "https://gis.charlottenc.gov/arcgis/rest/services/PLN/CouncilDistricts/MapServer/0/query",
  "https://gis.charlottenc.gov/arcgis/rest/services/PLN/CouncilDistricts/MapServer/0/query"
]
esri_address_service_area_validation_labels = [
  "Charlotte - District 1",
  "Charlotte - District 2",
  "Charlotte - District 3",
  "Charlotte - District 4",
  "Charlotte - District 5",
  "Charlotte - District 6",
  "Charlotte - District 7"
]
esri_address_service_area_validation_ids = [
  "1",
  "2",
  "3",
  "4",
  "5",
  "6",
  "7"
]
esri_address_service_area_validation_attributes = [
  "District",
  "District",
  "District",
  "District",
  "District",
  "District",
  "District"
]
esri_wellknown_id_override = 2264
```

Configure the program like this

![image](https://github.com/user-attachments/assets/0300dc63-23d9-47ba-93c6-58ab878db4df)

**Comment by dkatzz** [comment]
That seemed to work!! Thank you so much @gwendolyngoetz 

See here for values in config file:

```
export ESRI_FIND_ADDRESS_CANDIDATES_URLS="https://services.gis.nc.gov/secure/rest/services/AddressNC/AddressNC_geocoder/GeocodeServer/findAddressCandidates"
export ESRI_ADDRESS_SERVICE_AREA_VALIDATION_URLS="https://gis.charlottenc.gov/arcgis/rest/services/PLN/CouncilDistricts/MapServer/0/query, https://gis.charlottenc.gov/arcgis/rest/services/PLN/CouncilDistricts/MapServer/0/query, https://gis.charlottenc.gov/arcgis/rest/services/PLN/CouncilDistricts/MapServer/0/query, https://gis.charlottenc.gov/arcgis/rest/services/PLN/CouncilDistricts/MapServer/0/query, https://gis.charlottenc.gov/arcgis/rest/services/PLN/CouncilDistricts/MapServer/0/query, https://gis.charlottenc.gov/arcgis/rest/services/PLN/CouncilDistricts/MapServer/0/query, https://gis.charlottenc.gov/arcgis/rest/services/PLN/CouncilDistricts/MapServer/0/query"
export ESRI_ADDRESS_SERVICE_AREA_VALIDATION_LABELS="Charlotte - District 1, Charlotte - District 2, Charlotte - District 3, Charlotte - District 4, Charlotte - District 5, Charlotte - District 6, Charlotte - District 7"
export ESRI_ADDRESS_SERVICE_AREA_VALIDATION_IDS="1, 2, 3, 4, 5, 6, 7"
export ESRI_ADDRESS_SERVICE_AREA_VALIDATION_ATTRIBUTES="District, District, District, District, District, District, District"
export ESRI_WELLKNOWN_ID_OVERRIDE=2264
```

**Comment by dkatzz** [comment]
Pushed to civiform-eng and Megan tested this and it worked as they wanted!
