### ISSUE TITLE
Support French, Russian, Arabic and Japanese program category names

### ISSUE THREAD

**Issue by melanie-exygy** [civiform/civiform#8833]
#### Describe the solution presented in this issue.
We need to include French, Russian, Arabic and Japanese translations for the default program categories.  As a bonus, we can use this issue to define an easy way to do this if we add more languages in the future.

#### Additional Context
We will need to get the translation files from Google.

#### Done when:
What criteria need to be met for the issue to be finished? 
- [ ] Program categories can be viewed in French
- [ ] Russian and Japanese translations are available
- [ ] We have defined a process for adding other translations in the future

**Comment by dkatzz** [comment]
@melanie-exygy let me know if I can help with this!

**Comment by melanie-exygy** [comment]
> @melanie-exygy let me know if I can help with this!

Thanks @dkatzz !  I've already sent the category strings to @avaleske for translation, but I'd love to either work together on this issue or hand it over to you so that I can get back to the North Star.  Let me know if that's a possibility.

**Comment by dkatzz** [comment]
> We need to include French, Russian, Arabic and Japanese translations for the default program categories. As a bonus, we can use this issue to define an easy way to do this if we add more languages in the future.

Sure, happy to take it!

**Comment by melanie-exygy** [comment]
> > We need to include French, Russian, Arabic and Japanese translations for the default program categories. As a bonus, we can use this issue to define an easy way to do this if we add more languages in the future.
> 
> Sure, happy to take it!

Yay, thanks @dkatzz!  A few thoughts:
- It might be easiest to work on this issue in tandem with #8485.
- Right now, we're using the database seed tasks ([DevDatabaseSeedTask.java](https://github.com/civiform/civiform/blob/bab09e23e64c48d2193d6e653fffb3b8e098b77a/server/app/controllers/dev/seeding/DevDatabaseSeedTask.java#L366) and [DatabaseSeedTask.java](https://github.com/civiform/civiform/blob/bab09e23e64c48d2193d6e653fffb3b8e098b77a/server/app/services/seeding/DatabaseSeedTask.java#L171), but I've been wondering if a one-time job might be better suited.  We didn't have the setup for one-time jobs when I was designing this, but now we do.  Just an idea.
