### ISSUE TITLE
[Bug] Application skips to screen created first

### ISSUE THREAD

**Issue by shreyachatterjee00** [civiform/civiform#8876]
1. Create a program with screens 1 and 2. 
2. Swap screens 1 and 2, such that screen 2 appears first.

<img width="1260" alt="image" src="https://github.com/user-attachments/assets/5f5399c4-7394-45c5-9907-02d39b72ad86">

3. As a resident, apply to the program. 
4. Program skips immediately ahead to screen 1 instead of screen 2 first. 
5. (This doesn't happen without NS flag on).

<img width="1266" alt="image" src="https://github.com/user-attachments/assets/bf051a10-0e70-4599-bf51-50985e3c5d70">

**Comment by ssandbekkhaug** [comment]
Thank you for finding this bug, Shreya!

I suspect this bug was introduced by PR #8782 in `nextBlockId`.

https://github.com/civiform/civiform/blob/083998e1d8612e11eb869bd1d80159daca113d44/server/app/views/applicant/ProgramCardsSectionParamsFactory.java#L114
