### ISSUE TITLE
Migrate static_text.test.ts to North Star

### ISSUE THREAD

**Issue by ssandbekkhaug** [civiform/civiform#8914]
# Instructions
See https://github.com/civiform/civiform/issues/8791

**Comment by haltmar** [comment]
@ssandbekkhaug - the static_text.test.ts  test file already has test cases for north star: https://github.com/civiform/civiform/blob/3c04e44626b0b59e266c2da5bc8e2efc432e8d4d/browser-test/src/applicant/questions/static_text.test.ts#L61.   Are you asking to split the North Star test cases into a separate file?

**Comment by ssandbekkhaug** [comment]
Yes. Please see the full instructions linked in #8791
