### ISSUE TITLE
[North Star] Alerts should not be in a navigation HTML element

### ISSUE THREAD

**Issue by melanie-exygy** [civiform/civiform#8942]
**Describe the bug**
In the North Star, we are misusing the navigation landmark element for alerts, which are not part of navigation.  We should be using landmarks for their intended purpose, for accessibility reasons.

**Expected behavior**
Remove the `<nav>` that is wrapping the `<section>` element for the alerts.

**Screenshots**
![image](https://github.com/user-attachments/assets/3d1ce1a9-9417-4f40-8731-4e99d647b163)

**Comment by haltmar** [comment]
in this file server/app/views/applicant/NavigationFragment.html

**Comment by haltmar** [comment]
fixed in https://github.com/civiform/civiform/pull/9267
