### ISSUE TITLE
"Create an account" button is too wide

### ISSUE THREAD

**Issue by ssandbekkhaug** [civiform/civiform#8951]
**Describe the bug**
On the "Application Submitted" page, the "Create an account" button is too wide.

It was broken by #8802. [See the diff for current and ideal pictures](https://github.com/civiform/civiform/pull/8802/files#diff-ddd7549b8edb6d9be66dc4d691fb5f41d5bbe52bcb61d7be6413fd1f68518435)

[View mocks](https://www.figma.com/design/RmhVJCLgAKWGENJLWWAtNS/CiviForm%3A-Components%2C-Styles?node-id=2367-6614&m=dev)

**To Reproduce**

1. Use CiviForm as a guest (do not be logged in)
2. Apply to a program and submit it
3. View the "Application Submitted" page

**Expected behavior**
"Create an account" button is close to the size of its text content.

**Screenshots**
[See the diff](https://github.com/civiform/civiform/pull/8802/files#diff-ddd7549b8edb6d9be66dc4d691fb5f41d5bbe52bcb61d7be6413fd1f68518435)

**Desktop (please complete the following information):**

- OS: Mac OS X
- Browser: Chrome
- Version: 129.0.6668.103

**Additional context**
n/a

**Comment by haltmar** [comment]
PR at: https://github.com/civiform/civiform/pull/9130

**Comment by haltmar** [comment]
discard previous PR.   This is the one: https://github.com/civiform/civiform/pull/9169
