### ISSUE TITLE
[Bug] North star is not responsive on mobile devices

### ISSUE THREAD

**Issue by sijiayam** [civiform/civiform#9035]
## Describe the issue:

When the North Star UI feature flag is turned on:
- Although it is responsive at smaller screen sizes, the mobile responsive experience is not viewable on a mobile device
- This is tested on chrome on a pixel device, as well as on chrome on desktop with the inspect tool set to a mobile device

![Image](https://github.com/user-attachments/assets/28111a90-b670-414e-8a95-5ac26e441e6a)
![Image](https://github.com/user-attachments/assets/48d348e9-5427-4e12-a7e5-f5ea18710e2e)
![Image](https://github.com/user-attachments/assets/cfe9cbc6-b007-4dc7-8d7d-5610bff1a14e)

**Comment by gwendolyngoetz** [comment]
I don't think the viewport meta tag is being set.

There needs to be a full audit of all meta tags because I think many are missing.
