### ISSUE TITLE
CSP error in North Star file upload tests

### ISSUE THREAD

**Issue by ssandbekkhaug** [civiform/civiform#9082]
# Problem
1. I was migrating file.test.ts for https://github.com/civiform/civiform/issues/8917.
2. I enabled North Star
3. When executing some tests, the following error occurred:

Error: Refused to execute inline event handler because it violates the following Content Security Policy directive: \"script-src 'nonce-NJJDjtsa5M/uI+odot04Lg==' 'strict-dynamic' https: 'unsafe-inline'\". Note that 'unsafe-inline' is ignored if either a hash or nonce value is present in the source list.

# Done when

- [ ] The skipped tests in northstar_file.test.ts are not skipped

**Comment by gwendolyngoetz** [comment]
[Known issue](https://github.com/civiform/civiform/issues/8143). It only prevents the preview from showing. This will be fixed when Jeff's PR to [USWDS](https://github.com/uswds/uswds/pull/5997) is merged.

**Comment by gwendolyngoetz** [comment]
The CSP issue has been fixed.

**Comment by gwendolyngoetz** [comment]
Doubled checked. No longer an issue.
