### ISSUE TITLE
Run browser tests for azure through github test action

### ISSUE THREAD

**Issue by dkatzz** [civiform/civiform#9293]
#### Is your feature request related to a problem? Please describe.

Allow for the ability to run azure tests in the tests workflow. We should probably figure out which file changes should trigger these tests, since it would add a lot of time to the tests, but we should make it possible, so all these tests don't have to be run locally each time.

https://github.com/civiform/civiform/pull/6705/files was the PR to disable these

#### Describe the solution you'd like.

Allow running azure tests in tests.yaml

**Comment by gwendolyngoetz** [comment]
Can you tell me more about what your looking for? I don't quite follow. Is there a scenario where #9223 isn't sufficient?

**Comment by dkatzz** [comment]
> Can you tell me more about what your looking for? I don't quite follow. Is there a scenario where #9223 isn't sufficient?

Yeah, good point! I guess the only thing is that the azure browser test would only run for azure is if `azure` was included in the branch name. I wonder if we should check the changed file paths and see if anything with an azure path is included or a change to something where there is a difference for azure, like file upload, but maybe that's over engineering it. Once we enable the probers for azure staging, anything that this doesn't catch should get caught there, so that may be sufficient. Let me know what you think. Happy to close this out.

**Comment by gwendolyngoetz** [comment]
Once we reach full feature parity and all the tests are passing I was planning on making aws and azure both run all the time, removing the azure branch name check. Also requiring the azure matrix of tests to all pass in order to merge to main. It takes us back to where we once were.

My concern over running it based on path/file name is that a seemly innocuous change somewhere in the code might break something azure specific and the tests wouldn't run.

**Comment by dkatzz** [comment]
> Once we reach full feature parity and all the tests are passing I was planning on making aws and azure both run all the time, removing the azure branch name check. Also requiring the azure matrix of tests to all pass in order to merge to main. It takes us back to where we once were.
> 
> My concern over running it based on path/file name is that a seemly innocuous change somewhere in the code might break something azure specific and the tests wouldn't run.

Great! So this can be just a ticket tracking the update to make it run all the time and I can mark it as blocked - how does that sound? I can update the description to make that more clear.

**Comment by lagosr-google** [comment]
All browser tests passed sans the multi-file-upload test suite.  (12/2/24)

Multi file uploads has not been implemented for azure is currently a P2 in our work-list.
