### ISSUE TITLE
Add noopener and noreferrer attributes to links

### ISSUE THREAD

**Issue by dkatzz** [civiform/civiform#9406]
**Describe the bug**
We should add noopener and noreferrer to links that open in a new tab

**Comment by avaleske** [comment]
Do we want to add any tests/presubmits to look for future additions of new tabs that don't have noopener and noreferrer attributes?

**Comment by dkatzz** [comment]
> Do we want to add any tests/presubmits to look for future additions of new tabs that don't have noopener and noreferrer attributes?

Yeah, that's a great call out - I'll create a separate bug to track that. Thanks!
