### ISSUE TITLE
Add pagination to the Civiform / Program Admin's list of programs

### ISSUE THREAD

**Issue by neel-a-mehta** [civiform/civiform#942]
This may not be a huge deal in practice, unless cities start running 50+ programs on CiviForm. If they do, though, we'll need to add paging to the list of programs so that program admins don't have to scroll so much to find the right program.

**Comment by baipai** [comment]
The 50 number may be possible but also see how we are going to scale in the future. When I was doing the research, I remembered they are one platform that can let people search the different benefits across the state.

**Comment by baipai** [comment]
Assigned for design part.

**Comment by msprenke** [comment]
Removed Seattle from label.  We are not in favor of this change.
