### ISSUE TITLE
Bulk update test failing

### ISSUE THREAD

**Issue by gwendolyngoetz** [civiform/civiform#9426]
Disabled [this test](https://github.com/civiform/civiform/pull/9425/files#diff-74ccf18fbd6cc68e57abec5db477b010549540b18ef469373469590e0fc65cb8) because it's [failing on staging](https://github.com/civiform/civiform-staging-deploy/actions/runs/12252753581).

**Comment by swatkat1** [comment]
The admin_application_statuses_bulkstatus.test.ts was failing. The PR unskips admin_predictes tests and skips the failing test.
