### ISSUE TITLE
Screenshot generation fails in North Star browser test

### ISSUE THREAD

**Issue by orwant** [civiform/civiform#9463]
**Describe the bug**

In a North Star browser test, screenshot generation fails.

**To Reproduce**

In branch https://github.com/civiform/civiform/tree/orwant/northstar_screenshot_error_file.test, 
run bin/run-browser-tests -u applicant/questions/northstar_file.test.ts:653.

Error: Timed out 5000ms waiting for expect(page).toHaveScreenshot(expected)·
      **Failed to take two consecutive stable screenshots.**
    Previous: /usr/src/civiform-browser-tests/tmp/test-output/applicant-questions-norths-52716-ploads-too-large-file-error/northstar_file_test/file-error-too-large-multiple-files-previous.png
    Received: /usr/src/civiform-browser-tests/tmp/test-output/applicant-questions-norths-52716-ploads-too-large-file-error/northstar_file_test/file-error-too-large-multiple-files-actual.png
        Diff: /usr/src/civiform-browser-tests/tmp/test-output/applicant-questions-norths-52716-ploads-too-large-file-error/northstar_file_test/file-error-too-large-multiple-files-diff.png·

Screenshot generation fails, possibly because of the time needed to render an icon.

**Additional context**

This is not important, because this test doesn't really need a screenshot, and my PR won't include one. But Danielle was curious, so here we are.

**Comment by orwant** [comment]
file.test.ts:757 has a big ol' clue!

             await applicantFileQuestion.expectFileTooLargeErrorShown()
            // Don't perform a screenshot here because it shows a spinner that doesn't become stable
            // while the file is uploading.

There's our answer.

**Comment by dkatzz** [comment]
> file.test.ts:757 has a big ol' clue!
> 
> ```
>          await applicantFileQuestion.expectFileTooLargeErrorShown()
>         // Don't perform a screenshot here because it shows a spinner that doesn't become stable
>         // while the file is uploading.
> ```
> 
> There's our answer.

Ahh makes sense - thanks for tracking that down! That was probably the small change we saw in playwright too! I'll go ahead and close the bug.
