### ISSUE TITLE
Create UI for program admins / CiviForm admins to specify eligibility rules

### ISSUE THREAD

**Issue by neel-a-mehta** [civiform/civiform#973]
This is the UI component of #970 -- create a page where CiviForm admins can build out eligibility rules, e.g. "must have annual income less than $X, _and_ must have more than Y children".

We can leverage the excellent "predicate building" UI that we use for show-hide logic. We may also need to add support for more boolean logic, i.e. `AND`s and `OR`s.

**Comment by kristinyim** [comment]
ROC requests an initial version that's based on a single input to a single field (no fancy calculations). Their idea is to add ability to "warn" applicants of an answer that would lead to disqualification (e.g. entering $1 million for income) on CiviForm. ROC admins have tried using the show/hide and its not sufficient for their needs.

Need UX work on whether a pop-up is best for this, if they should still be able to apply even after they dismiss it, if the message is generic or customizable by the admin.

**Comment by elisekalstad** [comment]
Could be related to https://github.com/seattle-uat/civiform/issues/1738

**Comment by msprenke** [comment]
User Stories:
1. Program administrator can indicate whether an applicant must live within a geographic area by program  
2. Program administrator can indicate if an applicant must meet income maximums per household size   
3. Program administrator can enter income/household size qualifiers by program

**Comment by bion** [comment]
2 and 3 are done

1 is tracked by https://github.com/civiform/civiform/issues/4028
