### ISSUE TITLE
Surface application status to applicant

### ISSUE THREAD

**Issue by neel-a-mehta** [civiform/civiform#975]
#867 lets program admins specify the status of applications -- Approved, In Review, etc. Make sure that information is shown to applicants in some way.

**Comment by baipai** [comment]
I think this maybe already done? see figma

https://www.figma.com/file/0qsODjocwTF9bKuJn5THAA/Admin-(CiviForm-Admin%2C-Program-Admin)-Screens?node-id=685%3A4024

**Comment by kristinyim** [comment]
Found this old mock. It also includes a "notes" column to each application that is invisible to the applicant but can be used for internal tracking (e.g. 'Sent to Steve for income verification')

This is also not important in the immediate term to Rochester, but P0 overall
<img width="899" alt="Screen Shot 2022-02-11 at 3 13 57 PM" src="https://user-images.githubusercontent.com/14956724/153683172-1a57a731-ba9d-46c2-99d5-0b02b4736f4a.png">
